### ISSUE TITLE
Can't run program from another directory

### ISSUE THREAD

**Issue by MaxBGreenberg** [ThioJoe/YT-Spammer-Purge#1002]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

I was trying to create a simple script in /usr/local/bin to execute the program from anywhere. I found that if I'm in the YT-Spammer-Purge directory, I can execute the program without issue. But if I try to execute it from another directory, specifying the absolute path to the program, it returns an error.
I am using Fedora Workstation 37

### Release version

2.16.10

### Steps to reproduce

Attempt to run from another directory specifying absolute path.

### What platform are you seeing this problem on?

Linux (can also be ChromeOS)

### Relevant log output

```shell
Importing Script Modules...
Traceback (most recent call last):
  File "/home/max/YT-Spammer-Purge/YTSpammerPurge.py", line 51, in <module>
    import Scripts.prepare_modes as modes
  File "/home/max/YT-Spammer-Purge/Scripts/prepare_modes.py", line 13, in <module>
    from Scripts.confusablesCustom import confusable_regex, normalize
  File "/home/max/YT-Spammer-Purge/Scripts/confusablesCustom/__init__.py", line 11, in <module>
    with open(os.path.join(os.path.dirname(__file__), CONFUSABLE_MAPPING_PATH), "r") as mappings:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/max/Scripts/confusablesCustom/assets/confusable_mapping.json'
```

### Screenshots

![Screenshot from 2023-01-10 22-31-50](https://user-images.githubusercontent.com/122072621/211711833-49d1ac14-47ed-4cd5-8cea-063308f59f76.png)

**Comment by ThioJoe** [comment]
I'm not familiar with fedora but I guess the script must be able to reference everything relatively
