### ISSUE TITLE
Filtering: Issue detecting new spammer/porn bots

### ISSUE THREAD

**Issue by Lurick73** [ThioJoe/YT-Spammer-Purge#1005]
### Filter Mode

Auto-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

![Screenshot 2023-01-21 124346](https://user-images.githubusercontent.com/62802459/213879949-ebd2e58b-69b9-4cb3-9e84-215ee5b524b7.jpg)

### (Optional) Additional Info / Context

Copy paste of comments with hundreds of votes in mere seconds from posting.

**Comment by Firecul** [comment]
Do you have `stolen_comments_check_modes` enabled? By default it's only ran in sensitive mode
![Code_●_SpamPurgeConfig ini_-_YT-Spam-Domains-List_-_Vis](https://user-images.githubusercontent.com/34950371/214721627-f73bc6a9-9b34-4da7-aba8-ed56a31ace8e.png)

**Comment by Lurick73** [comment]
> Do you have `stolen_comments_check_modes` enabled? By default it's only ran in sensitive mode ![Code_●_SpamPurgeConfig ini_-YT-Spam-Domains-List-_Vis](https://user-images.githubusercontent.com/34950371/214721627-f73bc6a9-9b34-4da7-aba8-ed56a31ace8e.png)

Good catch, I had not thought about that. I tried that though and it caught them but only under Non-Matched. Is there a way to catch them and report that I'm missing?

**Comment by Lurick73** [comment]
Works with custom .ini config file.
