### ISSUE TITLE
Filtering: (Write a short title here)

### ISSUE THREAD

**Issue by CCleanerGreg** [ThioJoe/YT-Spammer-Purge#1006]
### Filter Mode

Sensitive-Smart Mode

### Select the Problem

Some spammers not detected

### Spammer Example / Sample

![Screenshot 2023-01-22 220424](https://user-images.githubusercontent.com/38182457/213959322-cd522355-aee4-43ba-a377-1c5aca14103b.png)

### Video / Post Link

https://www.youtube.com/watch?v=HCXQzLbDrgs

### (Optional) Additional Info / Context

This 'Ella' person (or bot) was copying peoples comments and posting them as replies.  A scan for her comments on the video showed about 14 results though I couldn't report her from there (which is annoying but I understand the desire to prevent abuse).

Tried both Auto-Smart mode and Sensitive mode.

**Comment by ThioJoe** [comment]
The program can detect people who steal others' comments, but besides that and the duplicate detection, I don't think there's much to be done
