### ISSUE TITLE
There is a problem with channels having handles enabled 

### ISSUE THREAD

**Issue by zSalvoGamerX** [ThioJoe/YT-Spammer-Purge#1008]
When you try to report or delete comments it wants the ID of the channel, how do you handle the new handles format if it's for example https://youtube.com/@ThioJoe ?
maybe you could add a new feature in another beta that is going to be released

**Comment by Firecul** [comment]
![WindowsTerminal_YT-Spammer-Purge (2)](https://user-images.githubusercontent.com/34950371/215363515-a07498b6-b6b8-4d34-ba23-2e0369b8162d.png)

Using the regular scan seems to work fine. What mode are you having that issue in?

**Comment by ThioJoe** [comment]
The program reports / deletes comments based on Comment ID, so handles shouldn't make a difference
