### ISSUE TITLE
It won't create a Token.pickle file

### ISSUE THREAD

**Issue by BrandiBlitz** [ThioJoe/YT-Spammer-Purge#1011]
I tried to launch the exe file and it had me re-authenticate (once a day), although I never touched it since fixing it recently using thio's 2 methods and now it won't update nor create another pickle.token file.https://user-images.githubusercontent.com/101225938/216199877-2abd2c21-3748-43ef-afbf-a186626a2710.MOV

If anybody has a solution, then please tell me.

This happened on version 2.16.10 and v2.17.0 beta 6

**Comment by BrandiBlitz** [comment]
I managed to do some work around. Just a fair warning, if anybody has backups of YT spammer purge, re-authentication and having an older token may interfere with your main YT spammer purge root folder, regardless if it's on your internal hard drives or external USB/SSD.

Again, the beta does have trouble re-authenticating and creating tokens for some reason as of 2.17.0 beta 6 / 2.16.10 stable ver.

**Comment by KendallDoesCoding** [comment]
Please close this issue.

**Comment by KendallDoesCoding** [comment]
@BrandiBlitz @ThioJoe - Please close this issue!
