### ISSUE TITLE
Support for Headless servers for Linux

### ISSUE THREAD

**Issue by Arttast** [ThioJoe/YT-Spammer-Purge#1013]
Normally the application requires Xorg(or Wayland) for Oauth2 authentication.
Can we make it so can be used fully without a windowing system?

**Comment by Firecul** [comment]
I think this has been asked a few times but afaik no one has came up with a way of getting the oauth2 authentication without opening a url.

**Comment by ThioJoe** [comment]
The simplest way is to simply authenticate on your desktop computer and copy over the oauth token after logging in

**Comment by Arttast** [comment]
Thanks!
