### ISSUE TITLE
Converting Source Code to Exe using Pyinstaller

### ISSUE THREAD

**Issue by darsh5921** [ThioJoe/YT-Spammer-Purge#1015]
### Filter Mode

Auto-Smart Mode

### Select the Problem

Other (add details below)

### (Optional) If 'Other', Enter Very Short Description

Cannot convert python files to exe

### Spammer Example / Sample

While using pyinstaller to exe the exe generates errors of file dependencies of spamdomains list.txt not found which is not generated automatically in the folder of resources and only empty folders are generated.

![Screenshot_20230212_062909](https://user-images.githubusercontent.com/104684690/219964124-818fe87d-a0d5-479c-9ae5-9beecce01918.png)

Also after manually putting these files in resource folder there is still another error related to config file 

![Screenshot_20230218_113721](https://user-images.githubusercontent.com/104684690/219964205-a21ae021-fb4a-4279-b503-6ba2c5b8b06e.png)

@thiojoe can you give the exact "pyinstaller" command with all the add-data files you used to convert python to exe , I need to make exe for a project please reply fast if possible

**Comment by darsh5921** [comment]
I have Found the solution

**Comment by Firecul** [comment]
> I have Found the solution

Could you post your solution here so anyone that may have the same problem might be able to learn from it?
