### ISSUE TITLE
[Bug]: Docker Build failing

### ISSUE THREAD

**Issue by KendallDoesCoding** [ThioJoe/YT-Spammer-Purge#1017]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

The docker build is failing for this repo!

https://github.com/ThioJoe/YT-Spammer-Purge/actions/workflows/docker-build.yml

### Release version

Since 2.17 Beta-3

### Steps to reproduce

https://github.com/ThioJoe/YT-Spammer-Purge/actions/workflows/docker-build.yml

### What platform are you seeing this problem on?

Windows (.exe file)

**Comment by ThioJoe** [comment]
Unfortunately I really have no idea how to do docker stuff

**Comment by mbijjur** [comment]
reopen
