### ISSUE TITLE
Scanning for an invalid channel ID crashes the program

### ISSUE THREAD

**Issue by Michael-Lemons** [ThioJoe/YT-Spammer-Purge#1021]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

The account ID, UC3VNPOyub3DC5GQmF6HNquQ was terminated by YouTube. Scanning for that ID either alone or in a list causes the X-4 unknown error. This happens while either scanning a single video or recent videos on a channel.

### Release version

v2.16.10

### Steps to reproduce

1. Choose 1 for single video. Enter the video ID.
2. Choose 3 for user ID
3.  Enter the ID, UC3VNPOyub3DC5GQmF6HNquQ

### What platform are you seeing this problem on?

Windows (.py script)

### Relevant log output

```shell
File "F:\Mike\GitHub\YT-Spammer-Purge\YTSpammerPurge.py", line 1674, in <module>
    main()
  File "F:\Mike\GitHub\YT-Spammer-Purge\YTSpammerPurge.py", line 1651, in main
    continueRunning = primaryInstance(miscData)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Mike\GitHub\YT-Spammer-Purge\YTSpammerPurge.py", line 1044, in primaryInstance
    filterSettings = modes.prepare_filter_mode_ID(scanMode, config)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Mike\GitHub\YT-Spammer-Purge\Scripts\prepare_modes.py", line 188, in prepare_filter_mode_ID
    processResult = utils.process_spammer_ids(inputtedSpammerChannelID)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Mike\GitHub\YT-Spammer-Purge\Scripts\utils.py", line 124, in process_spammer_ids
    valid, IDList[i], channelTitle = validation.validate_channel_id(inputList[i])
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Mike\GitHub\YT-Spammer-Purge\Scripts\validation.py", line 169, in validate_channel_id
    if response['items']:
       ~~~~~~~~^^^^^^^^^
KeyError: 'items'
------------------------------------------------
Unknown Error - Code: X-4 occurred. This is probably my fault,
please a bug report on the GitHub issues page, and include the above error info.
Short Link: TJoe.io/bug-report
```

### Screenshots

![yt-scammer-purge bug](https://user-images.githubusercontent.com/102477612/224461725-16e52967-d413-470a-9ab2-86ccd7c48524.jpg)

**Comment by ThioJoe** [comment]
Ok yea I can reproduce it, I'll figure out the issue

**Comment by ThioJoe** [comment]
Alright the latest commit on the beta channel should fix this: https://github.com/ThioJoe/YT-Spammer-Purge/commit/e0106da898b3b90fcc0973c01546b4fb514725dd

The next release will probably move the beta channel to stable, but in the mean time you should be able to just replace the validation.py file
