### ISSUE TITLE
How to add another YouTube channel to be scanned?

### ISSUE THREAD

**Issue by Ayal1** [ThioJoe/YT-Spammer-Purge#1024]
When I sign in to my account that is a manager of 2 YouTube accounts I can only sign in to the 1 I originally was signing in to. I don't think I need to get another token but I'm not sure how to proceed now. Is there something obvious that I'm missing?

**Comment by ThioJoe** [comment]
Yea at the moment the program just supports one account token being saved. Instead of having two token files you need to rename to switch between, it might be easiest to just have two separate folders each with a copy of the whole program, one for each account.
