### ISSUE TITLE
More "Here is the full clip" and Robux scam bots

### ISSUE THREAD

**Issue by blahguy88** [ThioJoe/YT-Spammer-Purge#1026]
### Filter Mode

Auto-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

![image](https://user-images.githubusercontent.com/114196525/226143285-6340a1aa-709b-4658-8e87-f7a02bb4e852.png)
https://www.youtube.com/watch?v=lgCUhPmPjUQ&lc=UgxRyf_5zAfus6RT9zV4AaABAg.9nPm0vY6ZSv9nPsdG_S8Al
![image](https://user-images.githubusercontent.com/114196525/226143306-5f498f1c-d71d-475c-8da5-034f95d5bc87.png)
https://www.youtube.com/watch?v=lgCUhPmPjUQ&lc=Ugxui3WhACpFJRg2Let4AaABAg.9nPlV2YHwOu9nPnPBWjk3p
![image](https://user-images.githubusercontent.com/114196525/226143403-713e2e7e-6242-47b5-be76-45de32c7573e.png)

### Video / Post Link

https://www.youtube.com/watch?v=lgCUhPmPjUQ

**Comment by blahguy88** [comment]
And here's another one.
![image](https://user-images.githubusercontent.com/114196525/226299957-44f29ccd-718e-44d0-9494-78ba607da2aa.png)
https://www.youtube.com/watch?v=aQChQz5BRCQ&lc=Ugwqh6T0urAynvDGJsh4AaABAg.9nS6xXZJdXt9nS7FK9HfBT

...on this video: https://www.youtube.com/watch?v=aQChQz5BRCQ

**Comment by blahguy88** [comment]
And here are some more.

https://www.youtube.com/watch?v=qGJLTDxnMs8&lc=Ugx7vouZzbPL58OpAUd4AaABAg.9njaEyOVZIL9njnSnfThpH
![image](https://user-images.githubusercontent.com/114196525/227991809-6f66037e-f4e3-4f9b-9de4-5692df413c1d.png)
https://www.youtube.com/watch?v=qGJLTDxnMs8&lc=UgwffWeUZAgE0G5F4MF4AaABAg.9njAzfSsWSK9njCWn1vwEz
![image](https://user-images.githubusercontent.com/114196525/227992027-9bfe8306-d94e-44ca-a66c-f0be1c720264.png)
https://www.youtube.com/watch?v=qGJLTDxnMs8&lc=Ugy7cvloEbkJ2VXMNW14AaABAg.9njGmgArsVm9njJkcefACl
https://www.youtube.com/watch?v=qGJLTDxnMs8&lc=Ugy7cvloEbkJ2VXMNW14AaABAg.9njGmgArsVm9njKwsqkIOC
![image](https://user-images.githubusercontent.com/114196525/227992381-5ac132e8-9168-4fe5-9855-0f0d257181d5.png)
https://www.youtube.com/watch?v=qGJLTDxnMs8&lc=UgxyTnOh0Dh0CPH9tDt4AaABAg.9njERJWnkDf9njHHTwtx4y
![image](https://user-images.githubusercontent.com/114196525/227992998-3824096c-0521-4fbe-9e45-969172677cf5.png)
https://www.youtube.com/watch?v=qGJLTDxnMs8&lc=UgzZ77edLIYLFLPQf-54AaABAg.9njH1YIz10f9njKIMPq0W7
https://www.youtube.com/watch?v=qGJLTDxnMs8&lc=UgzZ77edLIYLFLPQf-54AaABAg.9njH1YIz10f9njKVlr4VSS
![image](https://user-images.githubusercontent.com/114196525/227993340-2e8ee8a0-d5b8-4505-b0f7-3a773220d5f9.png)
https://www.youtube.com/watch?v=qGJLTDxnMs8&lc=UgzZ77edLIYLFLPQf-54AaABAg.9njH1YIz10f9njQ4Bi7bNx
![image](https://user-images.githubusercontent.com/114196525/227993536-4ecdc365-5e95-4d9e-8ac9-8f3b34f61a31.png)
https://www.youtube.com/watch?v=qGJLTDxnMs8&lc=UgydCKhUukj_6SN7vl14AaABAg.9njUKx2aEUz9njbh_GQm7K
![image](https://user-images.githubusercontent.com/114196525/227993928-5c4752e9-030a-42fb-9f13-9b14e1766910.png)
https://www.youtube.com/watch?v=qGJLTDxnMs8&lc=UgxW-hhNbc-yi6t6uSx4AaABAg.9njJzzSynr49njNrwP6-ae
https://www.youtube.com/watch?v=qGJLTDxnMs8&lc=UgxW-hhNbc-yi6t6uSx4AaABAg.9njJzzSynr49njQ5kDa9HV
![image](https://user-images.githubusercontent.com/114196525/227994703-32dfa5c5-257b-43e6-9c9f-e962c3093357.png)

**Comment by Firecul** [comment]
@blahguy88 please use https://github.com/ThioJoe/YT-Spam-Lists, I can deal with them better there.
