### ISSUE TITLE
[Bug]: Unable to Log In

### ISSUE THREAD

**Issue by blahguy88** [ThioJoe/YT-Spammer-Purge#1033]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

I was trying to log in, but then, this happened.
![image](https://user-images.githubusercontent.com/114196525/228961434-2735ea63-c490-402b-82be-b3e2ecba1bd9.png)
![image](https://user-images.githubusercontent.com/114196525/228961489-4767df0d-c17c-42c6-876f-a7dbf55f2a46.png)

### Release version

2.18.0-Beta1

### Steps to reproduce

1. Run the program.
2. Type your password.
3. No new token page appears.

### What platform are you seeing this problem on?

Windows (.exe file)

**Comment by KendallDoesCoding** [comment]
@blahguy88 Do you have the token.pickle file in the folder?

**Comment by blahguy88** [comment]
I actually managed to resolve it by updating the token.pickle file using an older version of the Spammer Purge program. If this issue comes up again, I'll let you know.

**Comment by KendallDoesCoding** [comment]
Can you please close the issue then? @blahguy88 @ThioJoe
