### ISSUE TITLE
Filtering: Stacy keach spammer chain not detected

### ISSUE THREAD

**Issue by Michael-Lemons** [ThioJoe/YT-Spammer-Purge#1034]
### Filter Mode

Auto-Smart Mode

### Select the Problem

Some spammers not detected

### Spammer Example / Sample

![Spammer Stacy keach 1](https://user-images.githubusercontent.com/102477612/229284800-20514bb5-2e03-4cdb-9f2b-140726327701.jpg)
![Spammer Stacy keach 2](https://user-images.githubusercontent.com/102477612/229284814-eaa89e6a-d0c0-4898-9ff1-4925477c43fd.jpg)

### Video / Post Link

https://www.youtube.com/watch?v=46Fi4MWcVBM

### (Optional) Additional Info / Context

Spammer ID: https://www.youtube.com/channel/UCwhUy1n_Nn5fzGye26pXJmQ

I am using version 2.18-Beta as a script on Windows.

**Comment by Firecul** [comment]
I have added this to the lists, please submit any thread, account or video link spam to https://github.com/ThioJoe/YT-Spam-Lists/
