### ISSUE TITLE
[Bug]: YT Spammer Purge can't update the authentication token on its own

### ISSUE THREAD

**Issue by blahguy88** [ThioJoe/YT-Spammer-Purge#1040]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

I was trying to log in to the program, but once again, the token has expired. You can update the authentication token using an older version, but the current version can't do so.

### Release version

2.18.0-Beta1

### Steps to reproduce

1. Open the program.
2. Try to log in.
3. Watch it be unable to update the authentication token, and therefore fail to run.

### What platform are you seeing this problem on?

Windows (.exe file)

### Screenshots

![image](https://user-images.githubusercontent.com/114196525/230637850-1ab64ef0-5827-4199-8f14-8b2373736322.png)
![image](https://user-images.githubusercontent.com/114196525/230637882-b1d579fb-b885-485b-a9e7-745fd7903c75.png)

**Comment by Michael-Lemons** [comment]
I experienced the same problem as soon as my authentication expired for the first time after updating to version 2.18.0-Beta1. The file "token.pickle" does not exist. I was able to continue like normal after I deleted file "token.pickle.encrypted."

**Comment by blahguy88** [comment]
That worked. Now, if only it could do it automatically.

**Comment by ThioJoe** [comment]
Ah ok yea i'll have to fix that

**Comment by LunaticBFF57** [comment]
I also received this error when I upgraded to version 2.18.0-Beta1.

**Comment by lemaximedu66** [comment]
it happens too if you say no at the first question. the path is wrong too.
![image](https://user-images.githubusercontent.com/61986631/235696472-955615bb-3e63-423d-9b07-9151e90cebc1.png)

**Comment by Lightning11wins** [comment]
I'm having the same error...

![Error](https://user-images.githubusercontent.com/42805582/236348564-a731a25f-faef-479b-9fe7-8ccdd2b2fd31.png)

**Comment by ThioJoe** [comment]
Alright it was an easier fix than I anticipated. Long overdue I know. The 2.18-Beta branch should be fixed. I won't be able to make a release with an exe till around next week but the python version is fixed for now.

**Comment by ThioJoe** [comment]
Should be fixed as of 2.18.0-Beta2

**Comment by BrandiBlitz** [comment]
> Should be fixed as of 2.18.0-Beta2

I am having the same issue with 2.18.2, but i think it's a google issue. i think they changed something that is nullifying authentication for YT-Spammer-Purge
