### ISSUE TITLE
Filtering: Porno Spam Bots

### ISSUE THREAD

**Issue by blahguy88** [ThioJoe/YT-Spammer-Purge#1043]
### Filter Mode

Auto-Smart Mode

### Select the Problem

Other (add details below)

### (Optional) If 'Other', Enter Very Short Description

These porno spam bots are not detected unless filtering reposted comments is enabled. I believe that their usernames appear often enough across multiple accounts to warrant their own category.

### Spammer Example / Sample

https://www.youtube.com/watch?v=q6upgnIkbNQ&lc=UgxBuvDKLH8jDc9sBSx4AaABAg
![image](https://user-images.githubusercontent.com/114196525/232121891-21a58299-7207-44e1-ac9b-08678d06feab.png)

https://www.youtube.com/watch?v=q6upgnIkbNQ&lc=Ugwtzj9IwyHr550HVkR4AaABAg
![image](https://user-images.githubusercontent.com/114196525/232122075-25eef7d1-2081-4b4e-98a5-0407f6d3dff6.png)

https://www.youtube.com/watch?v=jpao9P_Yumw&lc=Ugx5lFkW8hFBvUo8TGJ4AaABAg
![image](https://user-images.githubusercontent.com/114196525/232122214-d51a76b0-11e5-4181-9edd-5e002c3a35c0.png)

https://www.youtube.com/watch?v=q6upgnIkbNQ&lc=UgygysQ5md-cxfd-zhB4AaABAg
![image](https://user-images.githubusercontent.com/114196525/232122526-0c216426-8a11-4b0f-b618-4df2bd066a08.png)

https://www.youtube.com/watch?v=q6upgnIkbNQ&lc=UgyQp2rqX9reGe6FAXh4AaABAg
![image](https://user-images.githubusercontent.com/114196525/232122685-79879591-d2c1-4f39-9fb0-f6b69b9bef6f.png)

https://www.youtube.com/watch?v=DfPSvvGWR64&lc=UgwWzd1F3pJr9-cU0WV4AaABAg
![image](https://user-images.githubusercontent.com/114196525/232122933-73c1b31d-8e0c-4fa7-9225-c37eab64a9c0.png)

**Comment by Legendofallpro** [comment]
Yeah, we need to add a feature that can scan the pfps of the bots to check if they are explicit, if they are explicit report, delete, ban etc, scanning pfps of the spam bots are probably not possible with the youtube api tho, need to do something else for that

**Comment by blahguy88** [comment]
This is still the only way the porno spam bots are getting caught at all.
![image](https://github.com/ThioJoe/YT-Spammer-Purge/assets/114196525/daea3f87-e945-47e3-bcf6-654b1bd2a5b1)
