### ISSUE TITLE
[Bug]: Beta version gets detected as a trojan.

### ISSUE THREAD

**Issue by KwiatekMiki** [ThioJoe/YT-Spammer-Purge#1048]
### Duplicate Issues

- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**
- [X] There are **no existing posts relating to my problem**

### What happened?

Well, I was trying to can community post but then my antivirus said that this is a trojan.

### Release version

v2.18.0-Beta1 (from GitHub because I deleted it already)

### Steps to reproduce

1. Download Kaspersky Anti-Virus
2. Run this.
3. Try to scan post comments

### What platform are you seeing this problem on?

Windows (.exe file)

### Screenshots

![image](https://github.com/ThioJoe/YT-Spammer-Purge/assets/79092746/89716578-670e-4ae0-81ff-4af5a044898c)
#### (sorry for Polish, forgot to change it)

**Comment by Firecul** [comment]
Could you verify the file hash, virustotal doesn't have an issue with the one downloaded from here when I just tried https://www.virustotal.com/gui/file/6faab36873bde13968761b8e38fa3135c7d65b8d9e776c88ca56d0e0da7bbb38?nocache=1

**Comment by KwiatekMiki** [comment]
> Could you verify the file hash

ok

**Comment by KwiatekMiki** [comment]
> Could you verify the file hash, virustotal doesn't have an issue with the one downloaded from here when I just tried https://www.virustotal.com/gui/file/6faab36873bde13968761b8e38fa3135c7d65b8d9e776c88ca56d0e0da7bbb38?nocache=1

I verified. It's the same.

**Comment by Firecul** [comment]
I would probably assume false negative then. 
If you have the ability to build it yourself to try that version, that would be more telling as you'd know exactly the code involved. I've never been able to build it myself so I can't be much help there.
