### ISSUE TITLE
'Skipping Video with no comments' when it has comments

### ISSUE THREAD

**Issue by killtheplanet** [ThioJoe/YT-Spammer-Purge#1054]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

It appears like random videos get the treatment of 'Skipping Video with no comments' when the video do have comments.

Examples: grMU2QfYd_w & jVz1DTSTU

### Release version

2.17.0

### Steps to reproduce

1. Scan recent videos for a channel
2. Select the channel
3. Select any other option
4. Notice 'Skipping' as per screenshots below.

### What platform are you seeing this problem on?

Linux (can also be ChromeOS)

### Relevant log output

```shell
No crash, relevant CLI output screenshot below.
```

### Screenshots

![image](https://github.com/ThioJoe/YT-Spammer-Purge/assets/89046743/b0315ec9-355c-431c-9883-a1c1e07eb51d)

When there are clearly comments:

![image](https://github.com/ThioJoe/YT-Spammer-Purge/assets/89046743/20ec50a3-6e9d-44bb-868b-b9f74014f3ee)

**Comment by ThioJoe** [comment]
This is likely an issue with the YouTube API returning the wrong number of comments. Notice how in your screenshot it even says "0 comments". I'm not sure what causes this but it usually sorts it self out eventually. Not really anything I can do about it though.
