### ISSUE TITLE
[Bug]: Unable to auth

### ISSUE THREAD

**Issue by conorcoder556** [ThioJoe/YT-Spammer-Purge#1058]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

It will not authurise my YT channel

### Steps to reproduce

IDK

### What platform are you seeing this problem on?

Windows (.exe file)

**Comment by ThioJoe** [comment]
There's not enough info to help with this
