### ISSUE TITLE
[Bug]: Unable to Scan Recent Community Posts

### ISSUE THREAD

**Issue by blahguy88** [ThioJoe/YT-Spammer-Purge#1082]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

The program won't retrieve any community posts when selecting the "Scan recent community posts for a channel (Experimental)" option.

### Release version

2.18.0-Beta1

### Steps to reproduce

1. Open the program
2. Select option 5
3. Note that it doesn't retrieve any community posts

### What platform are you seeing this problem on?

Windows (.exe file)

### Screenshots

![image](https://github.com/ThioJoe/YT-Spammer-Purge/assets/114196525/fbfdd18a-ccac-4dcb-b452-d2754f890136)

**Comment by ThioJoe** [comment]
Should be fixed with the latest version of `community_downloader.py` in 2.17.1. I won't be able to make a release with an .exe till like next week but the python version will work in the meantime.

**Comment by ThioJoe** [comment]
Should be fixed as of 2.17.1 and 2.18.0-Beta2
