### ISSUE TITLE
[Bug]: Premature API cutoff

### ISSUE THREAD

**Issue by blahguy88** [ThioJoe/YT-Spammer-Purge#1083]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [X] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

At some point, while I'm scanning videos, the program thinks that I've used up my API quota limit, but the API site says otherwise.

### Release version

2.18.0-Beta1

### Steps to reproduce

1. Run the program as usual.
2. Note that this problem happened at approximately 1:30 PM PST.
3. Wait for fix.

### What platform are you seeing this problem on?

Windows (.exe file)

### Screenshots

![image](https://github.com/ThioJoe/YT-Spammer-Purge/assets/114196525/79145ec0-432f-489a-b1a1-a9b4b3ccf427)

**Comment by Firecul** [comment]
That response is from Google iirc, it's not the program deciding you have exceeded your limit. 
The API page has a lag I think before it shows what you actually have it. At least from what I remember, it's been a while since I looked at it.

**Comment by blahguy88** [comment]
Odd. Google told me that it's your responsibility to manage API consumption.

**Comment by Firecul** [comment]
> Google told me that it's your responsibility to manage API consumption

It may be your responsibility to manage it but once you go over the cap they'll tell you you cannot access it any more.

**Comment by blahguy88** [comment]
That's just it. While the bug occurred, the API cap had never been reached. Oh, well.
