### ISSUE TITLE
[Bug]: Nonstop processing errors

### ISSUE THREAD

**Issue by blahguy88** [ThioJoe/YT-Spammer-Purge#1084]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

At around 1000 comments scanned, the spammer purge program bombs invariably bombs out, even when the API quota limit hasn't been exceeded.

### Release version

2.18.0-Beta1

### Steps to reproduce

1. Run the program using option 2, scanning videos on a channel
2. Watch the program bomb out
3. Restart the computer
4. Delete the token.pickle file
5. Re-authenticate the program
6. Run the program again
7. Watch the program bomb out again

### What platform are you seeing this problem on?

Windows (.exe file)

### Screenshots

![Screenshot 2023-11-21 112332](https://github.com/ThioJoe/YT-Spammer-Purge/assets/114196525/5adaa131-ff11-44c4-901e-f61e4b144244)
![Screenshot 2023-11-21 112905](https://github.com/ThioJoe/YT-Spammer-Purge/assets/114196525/fc3dd5c6-3503-468f-8edb-10c4dbb4b6e7)
![Screenshot 2023-11-21 113058](https://github.com/ThioJoe/YT-Spammer-Purge/assets/114196525/2de5c225-7a1a-402e-b334-cfe4fed5c7e2)
![Screenshot 2023-11-21 113214](https://github.com/ThioJoe/YT-Spammer-Purge/assets/114196525/a8bc38fb-2cd5-44e6-af73-8c4977fcdcd5)
![Screenshot 2023-11-21 113239](https://github.com/ThioJoe/YT-Spammer-Purge/assets/114196525/d86b2d5c-63e6-48cb-a549-b71b9b312af4)
![image](https://github.com/ThioJoe/YT-Spammer-Purge/assets/114196525/0495161d-ab32-49f2-a218-23cc4825f486)

**Comment by virophagesp** [comment]
are you still experiencing this

**Comment by blahguy88** [comment]
No.
