### ISSUE TITLE
[Bug]: No such file or directory: 'token.pickle'

### ISSUE THREAD

**Issue by cookies5219** [ThioJoe/YT-Spammer-Purge#1089]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

trying to run gives me a error after signing in

### Release version

2.17.1

### Steps to reproduce

1. get client_secrets.json
2. run program
3. sign in

### What platform are you seeing this problem on?

Windows (.exe file)

### Relevant log output

```shell
Loading YT Spammer Purge @ 2.17.1...

Please login using the browser window that opened just now.

Waiting for authorization. See message above.
[OK] Authorization Complete.


Traceback (most recent call last):
  File "Scripts\auth.py", line 82, in first_authentication
  File "Scripts\auth.py", line 73, in get_authenticated_service
FileNotFoundError: [Errno 2] No such file or directory: 'token.pickle'
----------------
[!!!] Error: [Errno 2] No such file or directory: 'token.pickle'
If you think this is a bug, you may report it on this project's GitHub page: https://github.com/ThioJoe/YT-Spammer-Purge/issues

Error Code A-1: Something went wrong during authentication. Try deleting the token.pickle file.
Press Enter to Exit...
```

**Comment by PacoBell** [comment]
Did you make sure the file is renamed "client_secrets.json", verbatim, and not whatever Google names it by default? Is it in the same directory as the binary?

**Comment by cookies5219** [comment]
i no longer use windows and forgot so im closing this
