### ISSUE TITLE
Filtering: (Write a short title here)

### ISSUE THREAD

**Issue by ImMejor35** [ThioJoe/YT-Spammer-Purge#1092]
### Filter Mode

Sensitive-Smart Mode

### Select the Problem

False Positive

### (Optional) If 'Other', Enter Very Short Description

Detected something that has no signs of a being a scam comment

### Spammer Example / Sample

https://www.youtube.com/watch?v=YLt73w6criQ&lc=Ugzfk8lCyXELhm-ddmt4AaABAg.9nW6UdWy66r9nW7M39HVP1

### Video / Post Link

https://www.youtube.com/watch?v=YLt73w6criQ

### (Optional) Additional Info / Context

I think account age should be taken into account when detecting if they are scammer comments or not

**Comment by Firecul** [comment]
Without reading through the other 532 comments in that reply thread it's very hard to tell if that is a spam or not. I lean towards it being such but that is my own opinion obviously.

**Comment by ImMejor35** [comment]
They joined 1 year ago and that's their only comment ever on that specific channel

**Comment by Firecul** [comment]
So they weren't part of a conversation then, they just jumped in to say "watch one piece"? I'd say that was spam in that case too.

**Comment by ImMejor35** [comment]
I guess I thought by spam it meant deceitful spam not regular spam
