### ISSUE TITLE
on my linux device it says the file type is not suported even though it's for linux

### ISSUE THREAD

**Issue by DeviateBacon3** [ThioJoe/YT-Spammer-Purge#110]

**Comment by ThioJoe** [comment]
Dude. You are literally providing no details. I do not use linux so I have no idea what you are even talking about unless you provide additional info like steps to produce, etc. Like is asked for in the issue template that you keep ignoring.

Did you even follow the instructions from the readme? 
https://github.com/ThioJoe/YouTube-Spammer-Purge/wiki/Linux-Installation-Instructions

Did you even look at the readme? I have no idea because you provide zero info, so I don't even know where to start to try and help.

**Comment by TechStudent11** [comment]
@DeviateBacon3 You're the same person who needed help with ChromeOS. Remember, just because ChromeOS is based on Linux, you can't just double click it and expect a result. Google thought of this. You need to

1. Enable Linux Mode (see here: https://support.google.com/chromebook/answer/9145439?hl=en)
2. Get into the terminal (you can do this by pressing the Everything button (the little circle in the corner) and searching for "Terminal".
3. Run `sudo apt install git`
5. After the command finished, run `git clone https://github.com/ThioJoe/YouTube-Spammer-Purge`
6. Then `cd YouTube-Spammer-Purge`
7. Then after that, make sure you have Python3 installed. You can check this using `python3 -v`.
8. If you get no errors, type `python3 -m venv venv` and press enter.
9. The command should be successful. If it isn't, run `python3 -m pip install virtualenv` then `python3 -m virtualenv venv`. If you get an error, you need to install `pip`. You can do this by running `sudo apt install python3-pip`.
10. Now, run `source venv/bin/activate`.
11. Now, install the dependencies by running `python3 -m pip install -r requirements.txt`.
12. Finally, you can run the Python file using the command `python3 main.py`.

That should help.

**Comment by TechStudent11** [comment]
@ThioJoe This person was asking in a Discussion to make a ChromeOS version. I said that "ChromeOS is based on Linux. No need for a `.apk` or `.AppImage`. They must have thought that they can click it and work. I just provided instructions on how to do so on ChromeOS. Maybe add that to the Linux Installation Wiki. @DeviateBacon3 if any of the steps fail, please post it here.

**Comment by DeviateBacon3** [comment]
it says  fatal: protocol 'https//' is not supported

**Comment by TechStudent11** [comment]
@DeviateBacon3 On what? You're supposed to put a colon. it should be "https://"

**Comment by DeviateBacon3** [comment]
\python3  -m venv venv
  File "<stdin>", line 1
    \python3  -m venv venv

**Comment by DeviateBacon3** [comment]
what version of python3 i need  for it to work

**Comment by TechStudent11** [comment]
3.9 should be fine. But 3.8 should work.

**Comment by TechStudent11** [comment]
Remember, if that doesn't work, skip to step 8.

**Comment by DeviateBacon3** [comment]
i get error  python3 -m pip install virtuslenv
  File "<stdin>", line 1
    python3 -m pip install virtuslenv
                 ^
SyntaxError: invalid syntax

**Comment by TechStudent11** [comment]
oh wait, you're in a python shell. Type `exit()` then continue. Do step 7 again it should work

**Comment by DeviateBacon3** [comment]
i get error python3 -m venv venv
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

**Comment by TechStudent11** [comment]
`sudo apt install python3-venv`

**Comment by DeviateBacon3** [comment]
I get error sudo apt inatall python3-pip
E: Invalid operation inatall

**Comment by TechStudent11** [comment]
`python3 -m venv venv`

**Comment by KendallDoesCoding** [comment]
@DeviateBacon3 , @TechStudent11 - Is this a program based issue or is it just that python's virtual environment, isn't setup properly. If that's the case, I suggest you watch a Youtube video tutorial, on how to do that, and consider this issue not important as the program should run properly on Linux, Windows as well as MacOS.

**Comment by KendallDoesCoding** [comment]
@DeviateBacon3, I believe other people have been facing this issue too and have created #115 for the same.

Thanks,

**Comment by TechStudent11** [comment]
@KendallDoesCoding It might be a venv (virtual environment) issue.

**Comment by KendallDoesCoding** [comment]
Ok

**Comment by KendallDoesCoding** [comment]
> Dude. You are literally providing no details. I do not use linux so I have no idea what you are even talking about unless you provide additional info like steps to produce, etc. Like is asked for in the issue template that you keep ignoring.
> 
> Did you follow the instructions from the readme? https://github.com/ThioJoe/YouTube-Spammer-Purge/wiki/Linux-Installation-Instructions
> 
> Did you even look at the readme? I have no idea because you provide zero info, so I don't even know where to start to try and help.

@TechStudent11 , @ThioJoe I think he's new to github and coding by looking at his repos, and that he didnt provide information/using issue template without filling it in.

@DeviateBacon3 If you want to resolve this you need to provide us some more information, if you don't know how to frame the sentences, please atleast provide screenshots. That's the only thing you can do for us to be able to help you...

**Comment by TechStudent11** [comment]
@KendallDoesCoding #108

**Comment by KendallDoesCoding** [comment]
@DeviateBacon3 Are you trying to run the ,exe file or are you trying to download it and then run the code in the terminal?

**Comment by KendallDoesCoding** [comment]
I would honestly suggest you just run the .exe file if you can't figure out how to run it in the terminal.

**Comment by KendallDoesCoding** [comment]
#118

**Comment by TechStudent11** [comment]
@DeviateBacon3 they're on a Chromebook. Running `.exe` files won't work under ChromeOS because it's basically Android, which is basically Linux. I am trying to say that ChromeOS is based on Linux, meaning the only option is to grab the source code and run it via Python.

**Comment by KendallDoesCoding** [comment]
> 

 Yeah, so #118 should fix that right?

**Comment by TechStudent11** [comment]
@KendallDoesCoding yep. You've now linked this issue to #118. Now, if @ThioJoe merges it, this issue closes too meaning that the issue has been fixed.

**Comment by KendallDoesCoding** [comment]
Cool, thanks!

**Comment by DeviateBacon3** [comment]
Cloning into 'youtuber-spammer-purge'...
fatal: unable to access 'https://github.cpm/thiojoe/youtuber-spammer-purge/': Could not resolve host: github.cpm
elliotgrutsch78@penguin:~$

**Comment by KendallDoesCoding** [comment]
Can you please run it on replit.com then?

**Comment by TechStudent11** [comment]
@DeviateBacon3 PLEASE READ THE ERROR. "Could not resolve host: github.cpm". The command you have to run is `git clone https://github.com/ThioJoe/YouTube-Spammer-Purge".

**Comment by TechStudent11** [comment]
@DeviateBacon3 As @KendallDoesCoding suggested, running this project on [Replit](https://replit.com) will work. Here's how.

1. Create a Replit account, if you don't already have one. Create one [here](https://replit.com/signup)
2. Next, open this link: https://replit.com/github/ThioJoe/YouTube-Spammer-Purge
3. Now, install the dependencies by opening the shell and running `python3 -m pip install -r requirements.txt`.
4. Obtain an API file. Check here: https://github.com/ThioJoe/YouTube-Spammer-Purge#instructions---obtaining-youtube-api-key. Once you got the API file, drag and drop it into the file explorer in Replit
5. Finally, you can run the Python file using the command `python3 main.py`.

**Comment by rbeer** [comment]
> @ThioJoe coded this on Windows, and Linux has a certain variation. It would help if someone fixed all the issues and gave it back to @ThioJoe and then he could make another branch called LINUX, for the Linux users who are having problems on this.

There is no changes to this repository needed. Guys, no offense, but all your Linux issues are people not knowing what they are doing. There's nothing wrong with the code, at all. I ran the program on Debian, no issues.

**Comment by TechStudent11** [comment]
@rbeer k.

**Comment by KendallDoesCoding** [comment]
> > @ThioJoe coded this on Windows, and Linux has a certain variation. It would help if someone fixed all the issues and gave it back to @ThioJoe and then he could make another branch called LINUX, for the Linux users who are having problems on this.
> 
> There is no changes to this repository needed. Guys, no offense, but all your Linux issues are people not knowing what they are doing. There's nothing wrong with the code, at all. I ran the program on Debian, no issues. Of course, you can't just start the .exe; but that's the thing. You will have to know how to run a Python program. That's literally all there is to it.
> 
> I will monitor the discussions for a while. If anyone has a specific issue, I'll be glad to help out.

Thanks, I don't have Linux, but I thought so!

**Comment by KendallDoesCoding** [comment]
@ThioJoe This issue has been open and not active from like 15 days not. Requesting you to close this.

**Comment by KendallDoesCoding** [comment]
Thanks @ThioJoe

**Comment by LinuxComptuerFixer** [comment]
Thanks @DeviateBacon3

**Comment by LinuxComptuerFixer** [comment]
hi

**Comment by LinuxComptuerFixer** [comment]
hi
