### ISSUE TITLE
[Bug]: Stuck when Scanning Comments, API Overflow

### ISSUE THREAD

**Issue by blahguy88** [ThioJoe/YT-Spammer-Purge#1118]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Well, I was trying to scan, but every time I do, it gets stuck and runs the API cost up, no matter what I try.

### Release version

2.18.0-Beta3

### Steps to reproduce

1. Run any scan mode.
2. Watch the program get stuck and never fix itself, no matter how many times you restart it.
3. Note that API consumption seems to be through the roof when this happens, even when only scanning about 2000 comments on a video.

### What platform are you seeing this problem on?

Windows (.exe file)

### Screenshots

![image](https://github.com/ThioJoe/YT-Spammer-Purge/assets/114196525/51f9cabb-b171-44d6-a3c7-0544ad1b739f)
![image](https://github.com/ThioJoe/YT-Spammer-Purge/assets/114196525/5c9d6431-7a1c-4d6f-b4ed-5e0aa281668d)
![image](https://github.com/ThioJoe/YT-Spammer-Purge/assets/114196525/4054f9b1-16c6-427d-8deb-6c73b1ad316a)
![image](https://github.com/ThioJoe/YT-Spammer-Purge/assets/114196525/e4a3c9ae-418c-4bd1-9e9e-4946f172b3b9)
![image](https://github.com/ThioJoe/YT-Spammer-Purge/assets/114196525/766813aa-2816-47da-b490-03e7d74968e6)
![image](https://github.com/ThioJoe/YT-Spammer-Purge/assets/114196525/dce82742-dc6a-4581-a843-f59cf1797942)
![image](https://github.com/ThioJoe/YT-Spammer-Purge/assets/114196525/77533a4f-d6bd-441f-9cc0-2f8c4a0339e2)
![image](https://github.com/ThioJoe/YT-Spammer-Purge/assets/114196525/1bd85e6d-e399-41da-88d6-e55d9047c302)

**Comment by blahguy88** [comment]
Now, it doesn't even start at all.
![image](https://github.com/ThioJoe/YT-Spammer-Purge/assets/114196525/bd194ec1-29f0-47bf-a68a-d1a23947ad0f)

And API consumption still runs through the roof.
![image](https://github.com/ThioJoe/YT-Spammer-Purge/assets/114196525/3d060bed-96ae-41a3-b047-7eb8e3608207)
![image](https://github.com/ThioJoe/YT-Spammer-Purge/assets/114196525/2183c063-457d-48c1-8991-b77729e16aa2)
![image](https://github.com/ThioJoe/YT-Spammer-Purge/assets/114196525/00940a5d-da5d-4109-9120-7eb05ea79076)

**Comment by virophagesp** [comment]
I think this is an issue with the library itself
since the issue is coming from any comment with more than 100 replies
and the code hasnt been changed for months

**Comment by blahguy88** [comment]
> I think this is an issue with the library itself since the issue is coming from any comment with more than 100 replies and the code hasnt been changed for months

What do you mean? Because it happened on this video too, and none of the comments had over 100 replies when I tried to scan it.
https://www.youtube.com/shorts/nfp0lmrjhxs
![image](https://github.com/ThioJoe/YT-Spammer-Purge/assets/114196525/0194df8a-988c-45b7-84fe-bdfc46393780)

**Comment by virophagesp** [comment]
I just debugged
there is definitively at least one with more than 100 replies

**Comment by blahguy88** [comment]
Yeah, happened again for me too.

**Comment by mattsblack** [comment]
bump.

also i had a bug (forgot to screenshot) where the comments scanned would increase past the total number of comments. It looked like this " Total:  Total: [107754/82888] (130%)   | Comments Scanned: (frozen) | Replies Scanned: (kept increasing) | Matches Found So Far: (frozen)" i'm on the latest beta version 2.18.0-Beta3 and used the 2nd option to scan recent videos on a channel.

**Comment by virophagesp** [comment]
now that is odd, did you alter the code, sounds like a change you made altered the way the bug works

**Comment by blahguy88** [comment]
> now that is odd, did you alter the code, sounds like a change you made altered the way the bug works

If you're talking to me, I didn't change the code.

> bump.
> 
> also i had a bug (forgot to screenshot) where the comments scanned would increase past the total number of comments. It looked like this "Total: [107754/82888] (130%) | Comments Scanned: (frozen) | Replies Scanned: (kept increasing) | Matches Found So Far: (frozen)" i'm on the latest beta version 2.18.0-Beta3 and used the 2nd option to scan recent videos on a channel.

That's not a bug. Sometimes, more comments come as the program is scanning, so it takes them into account too.

**Comment by virophagesp** [comment]
I was talking to mattsblack

**Comment by virophagesp** [comment]
hey it seems to be fixed

**Comment by virophagesp** [comment]
turns out there is another issue entirely so maybe it isnt fixed

**Comment by blahguy88** [comment]
It's fixed now.
