### ISSUE TITLE
Investment Scam from Mr Brian Nelson

### ISSUE THREAD

**Issue by thechosen-wan** [ThioJoe/YT-Spammer-Purge#1121]
### Filter Mode

Sensitive-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

![image](https://github.com/ThioJoe/YT-Spammer-Purge/assets/153333046/8d04747a-1e95-43f5-9218-3a6ff962a211)

### Video / Post Link

https://www.youtube.com/watch?v=OzWztgRGKJU

**Comment by Firecul** [comment]
Added to the lists
