### ISSUE TITLE
[Bug]: sys is not defined

### ISSUE THREAD

**Issue by airplaneboy14mc** [ThioJoe/YT-Spammer-Purge#145]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**

### What happened?

I am running this from a debian terminal without gui.
I have installed all of the requirements
I was testing the latest beta

After running the YouTubeSpammerPurge.py file it returned this error:

`A module was not found try installing the requirements using either of these:
pip3 install -r requirements.txt
pip install -r requirements.txt
Traceback (most recent call last):
  File "YouTubeSpammerPurge.py", line 2285, in <module>
    main()
  File "YouTubeSpammerPurge.py", line 1637, in main
    if sys.version_info[0] < 3 or sys.version_info[1] < 6:
NameError: name 'sys' is not defined`

before this I already ran `pip3 install -r requirements.txt`

### Release version

2.0.0-Beta1

### Steps to reproduce
1) Go to an linux debian terminal such as Google Cloud shell, a built in terminal of your operating system, or on ChromeOS
2) Clone the repository and navigate to the folder
3) Run `pip3 install -r requirements.txt`
4) Run `python3 YouTubeSpammerPurge.py`
5) Observe

### What platform are you seeing this problem on?

Linux (can also be ChromeOS)

### Relevant log output

```shell
A module was not found try installing the requirements using either of these:
pip3 install -r requirements.txt
pip install -r requirements.txt
Traceback (most recent call last):
  File "YouTubeSpammerPurge.py", line 2285, in <module>
    main()
  File "YouTubeSpammerPurge.py", line 1637, in main
    if sys.version_info[0] < 3 or sys.version_info[1] < 6:
NameError: name 'sys' is not defined
```

**Comment by KendallDoesCoding** [comment]
@airplaneboy14mc I got the same bug #138 but that was because I was trying to open the code and run it on a online application called Gitpod. But, I see your using Linux so that shouldn't be a issue.

**Comment by airplaneboy14mc** [comment]
I am running it on linux without a GUI, and the application did have support without a gui before so idk

**Comment by rbeer** [comment]
Have you tried to just run the REPL with `python3` and in that `import sys`?
`sys` is a most basic [built-in module](https://docs.python.org/3/library/sys.html) that should have been installed with python itself.

**Comment by airplaneboy14mc** [comment]
thats what I am confused about, maybe I could try updating python and see if that fixes it

**Comment by KendallDoesCoding** [comment]
@airplaneboy14mc Yeah do that, but can you send me a screenshot of the full terminal here?

**Comment by rbeer** [comment]
> Have you tried to just run the REPL with `python3` and in that `import sys`?

Is that a "no" then?

What version of Debian are you running? What do you get for `cat /etc/debian_version`?
What's the exact version of your python? `python3 --version`
Also, check whether something has set a PYTHONPATH that confuses things: `echo $PYTHONPATH`

**Comment by airplaneboy14mc** [comment]
Lemme check

**Comment by airplaneboy14mc** [comment]
I'll do it tomorrow since it is 12 am for me

**Comment by rbeer** [comment]
@ThioJoe You can move this to discussions. This is definitely not a code issue.

**Comment by KendallDoesCoding** [comment]
@airplaneboy14mc Did you sort out this issue?

If yes, please close this.

Thanks
