### ISSUE TITLE
Screenshots for reporting Bugs

### ISSUE THREAD

**Issue by TechStudent11** [ThioJoe/YT-Spammer-Purge#153]
### Discussed in https://github.com/ThioJoe/YouTube-Spammer-Purge/discussions/146

<div type='discussions-op-text'>

<sup>Originally posted by **KendallDoesCoding** December 12, 2021</sup>
Please add a screenshot field in the issue template for reporting bugs @TechStudent11 </div>

**Comment by KendallDoesCoding** [comment]
@TechStudent11 Reminder on this!

**Comment by ThioJoe** [comment]
Added in 3c951b00b0d452550261326c3996abbda4c3d448

**Comment by KendallDoesCoding** [comment]
> Added in [3c951b0](https://github.com/ThioJoe/YT-Spammer-Purge/commit/3c951b00b0d452550261326c3996abbda4c3d448)

Thanks
