### ISSUE TITLE
It doesnt detect spam comments even if it is repeated and in english.

### ISSUE THREAD

**Issue by Satyajit-2003** [ThioJoe/YT-Spammer-Purge#184]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

I was trying to report comments in one of video I was watching. I tried the program on a specific video. Video link is: [https://www.youtube.com/watch?v=nYL9_Qomh1A](url). 

As you can see it has many spam comments, but the program didnt even detected one. I dont know what the problem is, but it simply fails. And for your info, I was using Auto Smart Mode

### Release version

2.2.5

### Steps to reproduce

1. Scan for a specific video. In my case it was [https://www.youtube.com/watch?v=nYL9_Qomh1A](url)
2. Use auto smart mode
3. It finds no spam comments, even if we can see the video is full of spam and repeating comments

### What platform are you seeing this problem on?

Windows

**Comment by VixieTSQ** [comment]
I feel like this might just be impossible to improve. The comments don't have any special ascii or anything. It obviously is spam to a human but a computer can't figure out this kind of stuff. What I would suggest doing is doing something with the repeated comments from the same user. This is most of the time a red flag. At the very least a comment could have been a mistaken repost and the newest one should be deleted.

**Comment by KendallDoesCoding** [comment]
> ### Duplicate Issues
> * [x]  There are **no existing posts relating to my problem**
> * [ ]  There are **existing posts relating to my problem, but the solution given, doesn't work for me.**
> 
> ### What happened?
> I was trying to report comments in one of video I was watching. I tried the program on a specific video. Video link is: [https://www.youtube.com/watch?v=nYL9_Qomh1A](url).
> 
> As you can see it has many spam comments, but the program didnt even detected one. I dont know what the problem is, but it simply fails. And for your info, I was using Auto Smart Mode
> 
> ### Release version
> 2.2.5
> 
> ### Steps to reproduce
> 1. Scan for a specific video. In my case it was [https://www.youtube.com/watch?v=nYL9_Qomh1A](url)
> 2. Use auto smart mode
> 3. It finds no spam comments, even if we can see the video is full of spam and repeating comments
> 
> ### What platform are you seeing this problem on?
> Windows
> 
> ### Relevant log output
> _No response_

@Satyajit-2003 I understand your concern, Can you please share a screenshot of the comments that it didn't find which were in the videos?

**Comment by ThioJoe** [comment]
I added some filters that should catch more of the spammers from that video, specifically ones like "100k subscribers with no videos". For other spam comments, like ones where it's an individual person that's leaving an actually unique comment, that is just spam-like, those are nearly impossible to filter. At some point I'll look into adding a way to detect commenters who leave many identical comments.

**Comment by Satyajit-2003** [comment]
> I added some filters that should catch more of the spammers from that video, specifically ones like "100k subscribers with no videos". For other spam comments, like ones where it's an individual person that's leaving an actually unique comment, that is just spam-like, those are nearly impossible to filter. At some point I'll look into adding a way to detect commenters who leave many identical comments.

It will be good if same comments repeated more than once will be marked as spam. No way, a genunine user will comment same thing more than once for any reason. 

And, by the way, I apreciate your work a lot and it is really making a difference.

**Comment by KendallDoesCoding** [comment]
> > I added some filters that should catch more of the spammers from that video, specifically ones like "100k subscribers with no videos". For other spam comments, like ones where it's an individual person that's leaving an actually unique comment, that is just spam-like, those are nearly impossible to filter. At some point I'll look into adding a way to detect commenters who leave many identical comments.
> 
> It will be good if same comments repeated more than once will be marked as spam. No way, a genunine user will comment same thing more than once for any reason.
> 
> And, by the way, I apreciate your work a lot and it is really making a difference.

Yes, unless youtube glitches or something weird happens, there's no way, a genunine user will comment same thing more than once for any reason.

**Comment by VixieTSQ** [comment]
> Yes, unless youtube glitches or something weird happens, there's no way, a genunine user will comment same thing more than once for any reason.

exactly. That's why I think it would be irresponsible to mark all repeat comments as spam. Of course if there is like 20 of them that makes sense but just 2? I'm not sure where to draw the line here but I do think it's reasonable to draw _some_ line.

On another note
> I added some filters that should catch more of the spammers from that video, specifically ones like "100k subscribers with no videos".

Not all "100k subscribers with no videos" accounts are spam accounts. There are plenty of genuine commenters with this kind of thing. It's just a fun concept.

**Comment by KendallDoesCoding** [comment]
> > Yes, unless youtube glitches or something weird happens, there's no way, a genunine user will comment same thing more than once for any reason.
> 
> exactly. That's why I think it would be irresponsible to mark all repeat comments as spam. Of course if there is like 20 of them that makes sense but just 2? I'm not sure where to draw the line here but I do think it's reasonable to draw _some_ line.
> 
> On another note
> 
> > I added some filters that should catch more of the spammers from that video, specifically ones like "100k subscribers with no videos".
> 
> Not all "100k subscribers with no videos" accounts are spam accounts. There are plenty of genuine commenters with this kind of thing. It's just a fun concept.

Yeah, Idrk what ThioJoe implemented, but I completely agree with you, sometimes Youtube can just be glitching, I think somewhere between 10-20 is good to draw the line but 2 is pretty less.

And yes, sometimes, if youtubers want to stop uploading, they may even be verified, but they set their videos to be private/unlisted.

If ThioJoe implemented features to take down comments like this, that's okay cause people can still exculde comments though right?

**Comment by VixieTSQ** [comment]
> If ThioJoe implemented features to take down comments like this, that's okay cause people can still exculde comments though right?

I mean sure? but preferably there shouldn't be any manual interaction needed

**Comment by KendallDoesCoding** [comment]
> > If ThioJoe implemented features to take down comments like this, that's okay cause people can still exculde comments though right?
> 
> I mean sure? but preferably there shouldn't be any manual interaction needed

Yeah true.

**Comment by ThioJoe** [comment]
> Not all "100k subscribers with no videos" accounts are spam accounts. There are plenty of genuine commenters with this kind of thing. It's just a fun concept.

Actually they are against youtube's terms of service. Even the original one got banned. So they are all spam at this point

**Comment by KendallDoesCoding** [comment]
> > Not all "100k subscribers with no videos" accounts are spam accounts. There are plenty of genuine commenters with this kind of thing. It's just a fun concept.
> 
> Actually they are against youtube's terms of service. Even the original one got banned. So they are all spam at this point

Ok makes sense.

**Comment by KendallDoesCoding** [comment]
Yes, You come across a few channels with 100k subs and no videos, but mostly they are scammers.

**Comment by KendallDoesCoding** [comment]
and use Sub 4 Sub
