### ISSUE TITLE
[Bug]: tkinter library not installed with setup, and apt does not exist in my Linux distribution

### ISSUE THREAD

**Issue by lolpro11** [ThioJoe/YT-Spammer-Purge#216]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Ran the python script and it returned an error (was missing a library)

### Release version

2.2.5

### Steps to reproduce

1. Download [v2.2.5.tar.gz](https://github.com/ThioJoe/YouTube-Spammer-Purge/archive/refs/tags/v2.2.5.tar.gz)
2. Extract the files. Run: `tar -xzvf v2.2.5.tar.gz`
3. Install python. Run: `sudo pacman -S python` (I am using a non-Debian-based distribution, so I do not have apt. However, if you are using a Debian-based distribution use: `sudo apt install python3`)
4. Install pip. Run: `curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py`; and `python3 get-pip.py` (The command `sudo apt install python3-pip` didn't work for me, as I do not have apt.)
5. Install dependencies. Run: `pip install -r requirements.txt`
6. Run the python script: `python3 YouTubeSpammerPurge.py`

### What platform are you seeing this problem on?

Linux (can also be ChromeOS)

### Relevant log output

```shell
File "/home/lolpro11/Downloads/YouTube-Spammer-Purge-2.2.5/YouTubeSpammerPurge.py", line 43, in <module>
    from gui import *
  File "/home/lolpro11/Downloads/YouTube-Spammer-Purge-2.2.5/gui.py", line 13, in <module>
    from tkinter import Menu, TclError, Tk, Canvas, Entry, Text, Button, PhotoImage
  File "/usr/lib/python3.10/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: libtk8.6.so: cannot open shared object file: No such file or directory


~$ sudo apt install python3-pip
[sudo] password for lolpro11: 
sudo: apt: command not found
```

**Comment by ynsnf** [comment]
You have python installed, so you can try ```pip install tk```

**Comment by ThioJoe** [comment]
Does doing `sudo pacman -S tk` work?

Going based off: https://archived.forum.manjaro.org/t/cant-install-tkinter-for-python3/70094/10

**Comment by lolpro11** [comment]
> You have python installed, so you can try `pip install tk`

[lolpro11 YouTube-Spammer-Purge-2.2.5]$ pip install tk
Defaulting to user installation because normal site-packages is not writeable
Collecting tk
  Using cached tk-0.1.0-py3-none-any.whl (3.9 kB)
Installing collected packages: tk
Successfully installed tk-0.1.0
[lolpro11 YouTube-Spammer-Purge-2.2.5]$ python3 YouTubeSpammerPurge.py 
Traceback (most recent call last):
  File "/home/lolpro11/Downloads/YouTube-Spammer-Purge-2.2.5/YouTubeSpammerPurge.py", line 43, in <module>
    from gui import *
  File "/home/lolpro11/Downloads/YouTube-Spammer-Purge-2.2.5/gui.py", line 13, in <module>
    from tkinter import Menu, TclError, Tk, Canvas, Entry, Text, Button, PhotoImage
  File "/usr/lib/python3.10/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: libtk8.6.so: cannot open shared object file: No such file or directory

Nope, doesn't work.




> Does doing `sudo pacman -S tk` work?
> 
> Going based off: https://archived.forum.manjaro.org/t/cant-install-tkinter-for-python3/70094/10

Yes, but my database files were out of date. I did `sudo pacman -Syu` just to update database files and other packages.
