### ISSUE TITLE
[Bug]: Comments not found when trying to search Brian or memo in Windows

### ISSUE THREAD

**Issue by yoyomonem** [ThioJoe/YT-Spammer-Purge#219]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Well, I was trying to search for "Brian" and "memo" but then it said that no comments were matching these comma-separated strings. Make comment creator usernames in comments searchable in the YouTube Spammer Purge!!! 

### Release version

YouTube Spammer Purge v2.2.5

### Steps to reproduce

1. Make comment creator usernames searchable on the YouTube Spammer Purge.

### What platform are you seeing this problem on?

Windows

### Relevant log output

```shell
No matched comments or users found!

If you think this is a bug, you may report it on this project's GitHub page: https://github.com/ThioJoe/YouTube-Spammer-Purge/issues

Press Enter to exit...
```

**Comment by ThioJoe** [comment]
Username searching is working completely fine for me.  Are you searching for comments by the uploader?

Some more details would help. The exact scan mode you're using, filter mode, search terms, a screenshot perhaps.

**Comment by yoyomonem** [comment]
That wouldn't help, @ThioJoe. I need more participants here.

**Comment by yoyomonem** [comment]
And yes, it is for filtering. Put the buggy label back here.

**Comment by yoyomonem** [comment]
And no, I'm not using filtering mode.

**Comment by yoyomonem** [comment]
Anytime you want to hear from me, @ThioJoe? If yes, then follow me and I'll follow YOU.

**Comment by KendallDoesCoding** [comment]
> Anything you want to hear from me, @ThioJoe? If yes, then follow me and I'll follow YOU.

@yoyomonem Don't be so rude. He doesn't need to follow you. Your the one coming and reporting issues in his program, which we appreciate, don't get me wrong, but you can't ask him to follow you.

**Comment by KendallDoesCoding** [comment]
Also, I think this may be a troll request, so please close this in that case.

**Comment by KendallDoesCoding** [comment]
> Also, I think this may be a troll request, so please close this in that case.

@yoyomonem If this is a genuine issue, please provide the url of the video your trying to delete comments from.

**Comment by yoyomonem** [comment]
@KendallDoesCoding, I really am scanning a video of mine.

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding, I really am scanning a video of mine.

Ok, that's good that its genuine but don't tell ThioJoe to follow you. He can follow whoever he wants to follow.

**Comment by yoyomonem** [comment]
OK, @KendallDoesCoding. And the video I'm scanning was Cold Windows 7, the 14 subscriber special.

**Comment by KendallDoesCoding** [comment]
> OK, @KendallDoesCoding. And the video I'm scanning was Cold Windows 7, the YouTube 14 subscriber special.

Ok thanks for sharing that. Now, let's wait for @ThioJoe's reply. What mode are you searching for these comments again on? Did you get any log output or anything? If your running the .exe file, maybe try running the python script and see if you get any error there, .exe is still preferable but I'm just saying coz sometimes you may get some log output in the python script and not get that stuff in the .exe.

**Comment by yoyomonem** [comment]
@KendallDoesCoding, the mode I was using was a spammer's worst nightmare.

**Comment by ThioJoe** [comment]
I'm still confused. You can't choose what to search when using the auto smart mode, so what do you mean you were searching "brian" and "memo"?

**Comment by KendallDoesCoding** [comment]
> I'm still confused. You can't choose what to search when using the auto smart mode, so what do you mean you were searching "brian" and "memo"?

I didnt understand too, I thought it was a troll issue thread but it seems not?

**Comment by yoyomonem** [comment]
@KendallDoesCoding & @ThioJoe, I've double-checked the issue on another video with comments turned on and it worked! Thanks for your time. The issue is solved & closed.
