### ISSUE TITLE
Update screenshot

### ISSUE THREAD

**Issue by kiatchun** [ThioJoe/YT-Spammer-Purge#220]
Update the opening screenshot in readme.md

**Comment by KendallDoesCoding** [comment]
> Update the opening screenshot in readme.md

@kiatchun What screenshot?

**Comment by ThioJoe** [comment]
I think he means the social preview, or the first screenshot in the readme

**Comment by KendallDoesCoding** [comment]
> I think he means the social preview, or the first screenshot in the readme

I still didnt understand what he meant, but ok if you did lol

**Comment by kiatchun** [comment]
> > I think he means the social preview, or the first screenshot in the readme
> 
> I still didnt understand what he meant, but ok if you did lol

I meant 
![image](https://user-images.githubusercontent.com/93459510/147515499-297614ee-9b19-4c0d-8484-912f61e2ec93.png)

The picture is out of date in multiple ways.

**Comment by KendallDoesCoding** [comment]
> > > I think he means the social preview, or the first screenshot in the readme
> > 
> > 
> > I still didnt understand what he meant, but ok if you did lol
> 
> I meant ![image](https://user-images.githubusercontent.com/93459510/147515499-297614ee-9b19-4c0d-8484-912f61e2ec93.png)
> 
> The picture is out of date in multiple ways.

Oh ok.

**Comment by KendallDoesCoding** [comment]
@kiatchun Actually I don't think this is out of date, because this is the preview he showed in his latest video about this program at 6:21 - https://youtu.be/2tRppXW_aKo?t=381.

It's the exact same menu, so it isn't out of date.

@ThioJoe Kindly close this issue.

**Comment by kiatchun** [comment]
@KendallDoesCoding 
1. That picture is missing 2 of the modes that are available in the latest version. 
2. That picture was from 2.0.0-Beta3.
