### ISSUE TITLE
Pull request template doesn't have tags

### ISSUE THREAD

**Issue by KendallDoesCoding** [ThioJoe/YT-Spammer-Purge#227]
To make it easier for @ThioJoe to sort out Pull requests, on urgency. We need to implement a PR tag system.

**Comment by ThioJoe** [comment]
There's already labels I just haven't felt the need to use them

**Comment by KendallDoesCoding** [comment]
> There's already labels I just haven't felt the need to use them

Ok!

**Comment by KendallDoesCoding** [comment]
@ThioJoe Thanks for using my suggestion. I see you've started adding tags after this. Accordingly to me, tags just help in organizing everything and helps the contributors. Like, tomorrow lets say your prioritizing on issues with installation, and have left some PR's aside. You can always go back to them with the label and merge it accordingly, when you need it.
