### ISSUE TITLE
Add additional info field

### ISSUE THREAD

**Issue by KendallDoesCoding** [ThioJoe/YT-Spammer-Purge#234]
URGENT

YAML error: (): did not find expected '-' indicator while parsing a block collection at line 8 column 3. Learn more.

I think, 1e25470 messed this up... Sorry

@TechStudent11 Can you fix this please.

**Comment by ThioJoe** [comment]
Reverted for now

**Comment by TechStudent11** [comment]
Yep ya did.

**Comment by KendallDoesCoding** [comment]
> Reverted for now

Thanks, sorry for the issue!

**Comment by KendallDoesCoding** [comment]
> Yep ya did.

@TechStudent11 What was the issue with my commit? Can you fix it please?

**Comment by TechStudent11** [comment]
ok

**Comment by KendallDoesCoding** [comment]
thx

**Comment by KendallDoesCoding** [comment]
@TechStudent11 Will appreciate if you can tell me the issue I made, so I can sort it out. Don't want to bother you today, being New Year though, but whenever you get a chance please let me know! 

Thanks

**Comment by TechStudent11** [comment]
@KendallDoesCoding First, Happy New Year, and second: there is an extra space/indent.

**Comment by KendallDoesCoding** [comment]
Thanks. Will try to fix the issue with your feedback on this later in the
day.

**Comment by ThioJoe** [comment]
After looking at it, I think the 'what happened' box is probably sufficient. People will probably just put any necessary info in there anyway
