### ISSUE TITLE
[Bug]: Auto Smart not detecting certain spam comments

### ISSUE THREAD

**Issue by atirut-w** [ThioJoe/YT-Spammer-Purge#235]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

I used this on a Roblox video and the program does detect any spam comments despite there being a lot of them.

Examples:
![Screenshot from 2021-12-28 00-18-29](https://user-images.githubusercontent.com/25323231/147493670-ea87966f-980b-4386-ae93-70c59981a3a7.png)
![Screenshot from 2021-12-28 00-18-12](https://user-images.githubusercontent.com/25323231/147493671-db6f09d6-f822-4b0d-b389-176cb925abf0.png)
![Screenshot from 2021-12-28 00-18-06](https://user-images.githubusercontent.com/25323231/147493672-c01d0e5b-fc1f-4b86-b0e2-4ea2a0049d9c.png)

### Release version

2.2.6

### Steps to reproduce

1. Scan specific video
2. ID: _Bpx4cDEnJA
3. Use Auto Smart

### What platform are you seeing this problem on?

Linux (can also be ChromeOS)

**Comment by ThioJoe** [comment]
Ok I've added an update to the filters for these types of spammers
