### ISSUE TITLE
[Bug]: not detected spammer

### ISSUE THREAD

**Issue by congaterori** [ThioJoe/YT-Spammer-Purge#246]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

the tool not work?
![image](https://user-images.githubusercontent.com/46470547/147581737-7746a4ba-44c0-4a7d-964b-f405805b8f42.png)
![spam](https://user-images.githubusercontent.com/46470547/147581471-b76b35e8-8613-4e06-b780-e6a1708d8bbe.png)

### Release version

2.2.5

### Steps to reproduce

1. Scan a Specific video
2. (RECOMMENDED): Auto-Smart Mode: Automatically detects multiple spammer techniques
3. 

### What platform are you seeing this problem on?

Windows

**Comment by ThioJoe** [comment]
The app isn't magic, it can't detect comments like that which have no identifiable spam markers.
