### ISSUE TITLE
It keeps telling me there's a new version available but I have the newest one

### ISSUE THREAD

**Issue by WorldInCode** [ThioJoe/YT-Spammer-Purge#248]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Yeah that

### Steps to reproduce

1. Launch the program
2. Find the green text (ik very hard)

### What platform are you seeing this problem on?

Windows

**Comment by ThioJoe** [comment]
Yea I forgot to change the version number, the latest release 2.4.2 fixes it
