### ISSUE TITLE
Does Not Work On Chrome OS: Download The .exe Does Not Work On Chromebook

### ISSUE THREAD

**Issue by BlueJayCool7788** [ThioJoe/YT-Spammer-Purge#251]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Well, I was trying to Download It but then It Said Does Not Work

### Release version

2.5.2

### Steps to reproduce

1. Download
2. Run. 
3. Get Error

### What platform are you seeing this problem on?

Linux (can also be ChromeOS)

**Comment by BlueJayCool7788** [comment]
ThioJoe Can You Make This Work On Linux / Chrome OS

**Comment by kiatchun** [comment]
What error did you get?

**Comment by kiatchun** [comment]
> ### Duplicate Issues
> * [x]  There are **no existing posts relating to my problem**
> * [ ]  There are **existing posts relating to my problem, but the solution given, doesn't work for me.**
> 
> ### What happened?
> Well, I was trying to Download It but then It Said Does Not Work
> 
> ### Release version
> 2.5.2
> 
> ### Steps to reproduce
> 1. Download
> 2. Run.
> 3. Get Error
> 
> ### What platform are you seeing this problem on?
> Linux (can also be ChromeOS)
> 
> ### Relevant log output
> _No response_

There is no 2.5.2 version. The latest in 2.4.2

**Comment by ThioJoe** [comment]
An exe file is windows only, ya goof
Chrome OS isn't a supported operating system, since I don't have it so I can't test on it.
