### ISSUE TITLE
[Comment Filter Clarification] Better way of filtering comments

### ISSUE THREAD

**Issue by KendallDoesCoding** [ThioJoe/YT-Spammer-Purge#256]
In #184 you mentioned that you added a feature to catch scammers with "100k subscribers but with no videos"... I just wanted to clarify, that it will only filter SCAMMERS with 100k subscribers and no videos, which use ascii characters, share whatsapp numbers, impersonate youtubers, or if it will do that to any channel with 100k subs and no videos. Because, if that's the case, its possible that anyone can have a channel with 100k subs and no videos, for various reasons . One of the reasons, can be they quit youtube, a example of this is [Pewdiepie](https://www.youtube.com/PewDiePie)'s [wife](https://www.youtube.com/Marzia) who now has about 7M views and no videos, another example is that a channel got shouted out by a youtuber with many subscribers because they commented on their video and then got lots of subscribers from that. While, I know that the people using the program can exculde comments, I don't think these should be filtered and I just wanted to clarify.

Also, you said in #184 that, you may add a filter to automatically filter users who posted the same comment multiple times, we'll I personally if I remember correctly, have fallen into a bug in Youtube that my comment got repeated twice, with me commenting it just one time. So if you add this, I think you need a set a limit for when this starts, somewhere between 10-15 times, even from around 5 onwards should be good.

**Comment by ThioJoe** [comment]
It goes by the channel names whixh are literally "X subscribers with 0 videos" or whatever. It doesnt count subscribers and videos

**Comment by KendallDoesCoding** [comment]
But why would the channel name be "X subscribers with 0 videos"? Most of
the comment bot/spammers I see are like Hi or something else, and this rule
won't work for impersonators too right?

**Comment by ThioJoe** [comment]
> But why would the channel name be "X subscribers with 0 videos"? 

Because that's literally just the point of their account

![zero videos](https://user-images.githubusercontent.com/12518330/147686559-e3abd63f-df46-48e7-8b32-9937f2a77292.PNG)

**Comment by KendallDoesCoding** [comment]
> > But why would the channel name be "X subscribers with 0 videos"?
> 
> Because that's literally just the point of their account
> 
> ![zero videos](https://user-images.githubusercontent.com/12518330/147686559-e3abd63f-df46-48e7-8b32-9937f2a77292.PNG)

Oh ok, I've never come across channels like this myself. I've only come across a few SUB FOR SUB channels, but not with subscribers in their name...... Closing.
