### ISSUE TITLE
[Bug]: (NOT FINDING ANY SPAMMERS)

### ISSUE THREAD

**Issue by PROMAN8625** [ThioJoe/YT-Spammer-Purge#260]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

i tried every way to scan but it did'nt found any spammer or scammer
my channel link  : https://www.youtube.com/channel/UCzw1833Hhd-7QJDjivUrBJQ

### Release version

2.4.2

### Steps to reproduce

it dont find anything

### What platform are you seeing this problem on?

Windows

### Relevant log output

```shell
idk where the log file is
```

**Comment by Kurdakov** [comment]
not a bug - you have no comments.

**Comment by PROMAN8625** [comment]
i have comments
