### ISSUE TITLE
Dosent detect spammers with no special characters, should have a filter

### ISSUE THREAD

**Issue by KasliEmre6292** [ThioJoe/YT-Spammer-Purge#265]
So I just scanned a video and it has a vbucks spam and the auto-sensitive mode didn't even detect it.
and even though I understand since they don't have ant special characters it should still have filter to detect like unusual things For Example:
Sites like :  Diva.Bond
Characters like : ►
Words Like :  𝗩 𝗕𝘂𝗰𝗸𝘀 trick
If you wanna reproduce this bug here's the link to the video:
https://www.youtube.com/watch?v=4v8g8_dtNL
![tomato1](https://user-images.githubusercontent.com/96761641/147760633-721c02df-9171-4bc9-b21c-d573eed0ec21.PNG)
![tomato2](https://user-images.githubusercontent.com/96761641/147760638-ebb0f3cd-f501-4a71-a8b1-961a022f254c.PNG)
U

**Comment by KasliEmre6292** [comment]
Also , since we get to check comments one from each author I think it would be cool to see word filter in the auto smart-sensitive modes

**Comment by Firecul** [comment]
https://www.youtube.com/watch?v=4v8g8_dtNLU is the full link, I think you just missed a letter.

I could only detect them using the ► reliably

**Comment by ThioJoe** [comment]
The latest release should address these spammers. The program now checks a list of known spam domains that can be updated daily, which should catch these
