### ISSUE TITLE
Filtering: Some forms of crypto spam can't be detected currently

### ISSUE THREAD

**Issue by Firecul** [ThioJoe/YT-Spammer-Purge#274]
### Filter Mode

Sensitive-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

![chrome_EEVblog_1445_-_How_to_Simulate_an_Oscilloscope_Pro](https://user-images.githubusercontent.com/34950371/147790918-d735b92f-2d61-4a21-81f5-2624eed9abc2.png)
https://www.youtube.com/watch?v=kWSCVq7FgAE&lc=UgxxzNldmU81tI9SAqV4AaABAg

---------------------------------------------

![www youtube com_watch_v=aMeyT-_aY7M lc=Ugyh8PDoIa2cOWeQIq94AaABAg](https://user-images.githubusercontent.com/34950371/147791269-254bc7c7-c05a-4dee-af8c-3d735fb7cdd5.png)
https://www.youtube.com/watch?v=aMeyT-_aY7M&lc=Ugyh8PDoIa2cOWeQIq94AaABAg

--------------------------------------------

![www youtube com_watch_v=jrCjmUSU350 lc=UgzE93oVqoi0X7EeDE54AaABAg](https://user-images.githubusercontent.com/34950371/147797390-c19bad9b-c145-4014-997a-21e8d1cabe09.png)
https://www.youtube.com/watch?v=jrCjmUSU350&lc=UgzE93oVqoi0X7EeDE54AaABAg

--------------------------------------------

![www youtube com_watch_v=ReiL4cu1L7s lc=UgzDyXvXn71RW7c8IV94AaABAg](https://user-images.githubusercontent.com/34950371/147797404-c06eabb0-204a-4a71-9192-4f2238729648.png)
https://www.youtube.com/watch?v=ReiL4cu1L7s&lc=UgzDyXvXn71RW7c8IV94AaABAg

### Video / Post Link

Links in examples above

### (Optional) Additional Info / Context

I know they don't all have something that can easily be filtered out but more data might help you all the same.

**Comment by ThioJoe** [comment]
Yea these big threads are tricky, but I'm working on some ways to detect them reliably.

**Comment by KendallDoesCoding** [comment]
> Yea these big threads are tricky, but I'm working on some ways to detect them reliably.

That would be good! This spam bots usually either pay or do other stuff to make a thread, but its all spam mostly. Once in a while, there may be a genuine comment saying "shut up" or something like "scam" or even "fake" for that matter.

**Comment by Firecul** [comment]
Would you like me to continue putting examples here or doing a PR in the other repo?

**Comment by ThioJoe** [comment]
In the other repo would be better. I'll create submission forms for the different types of submissions, right now it's only for the spam domain type.

Going to close this because as of 164d35c7a06ecb0f131a62b2d8892a40c1b748b8 they should be addressed with the filter lists

**Comment by KendallDoesCoding** [comment]
> In the other repo would be better. I'll create submission forms for the different types of submissions, right now it's only for the spam domain type.
> 
> Going to close this because as of [164d35c](https://github.com/ThioJoe/YT-Spammer-Purge/commit/164d35c7a06ecb0f131a62b2d8892a40c1b748b8) they should be addressed with the filter lists

But their names arent added in the Spam Threads still?

**Comment by Firecul** [comment]
@KendallDoesCoding 

They are, even some I've submitted since this has been closed are added

**Comment by KendallDoesCoding** [comment]
Ok
