### ISSUE TITLE
[Bug]: Can't complete authorization ('NoneType' object has no attribute 'replace')

### ISSUE THREAD

**Issue by Xane123** [ThioJoe/YT-Spammer-Purge#275]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

This error appears very easily for me, no matter if I use the latest Windows release (2.4.2), its Python version, or a slightly older Windows release (2.4.0). All that I have to do is run the program with the client_secrets.json file in the folder, then complete the authorization. Upon doing that, an error appears about **wsgi_app.last_request_uri** not having the "replace" attribute.

I don't know if this is specific to my "secrets" file or anything, but it sounds like there's something wrong with the code, or my Python doesn't have something it needs. (Also, the "token.pickle" file isn't created.)

### Release version

2.4.2

### Steps to reproduce

1. Start the program (either Windows EXE or YouTubeSpammerPurge.py)
2. Complete authorization in browser
3. Upon clicking the final button, the page loads indefinitely, and the program displays that error message.

### What platform are you seeing this problem on?

Windows

### Relevant log output

```shell
Log in using the browser window.
Traceback (most recent call last):
  File "C:\Users\xanem\Programs\Mini Programs\YouTube Spammer Purge (by ThioJoe)\source-Python\YouTubeSpammerPurge.py", line 2060, in main
    youtube = get_authenticated_service() # Set easier name for API function
  File "C:\Users\xanem\Programs\Mini Programs\YouTube Spammer Purge (by ThioJoe)\source-Python\YouTubeSpammerPurge.py", line 122, in get_authenticated_service
    creds = flow.run_local_server(port=0, authorization_prompt_message="Log in using the browser window.")
  File "C:\Users\xanem\AppData\Local\Programs\Python\Python310\lib\site-packages\google_auth_oauthlib\flow.py", line 476, in run_local_server
    authorization_response = wsgi_app.last_request_uri.replace("http", "https")
AttributeError: 'NoneType' object has no attribute 'replace'
----------------

Error: 'NoneType' object has no attribute 'replace'
If you think this is a bug, you may report it on this project's GitHub page: https://github.com/ThioJoe/YouTube-Spammer-Purge/issues

Error Code A-1: Something went wrong during authentication. Try deleting token.pickle file. Press Enter to exit...
```

**Comment by ThioJoe** [comment]
Hm what browser do you have opening when it prompts the login?

**Comment by Xane123** [comment]
My default browser is Firefox 95 so that's what opens a new tab for authorization.

I don't have Google Chrome installed, but should I do that to see if it fixes it?

**Comment by ThioJoe** [comment]
Ok cool, closing this
