### ISSUE TITLE
help

### ISSUE THREAD

**Issue by TheGuy112** [ThioJoe/YT-Spammer-Purge#283]
when i try to scan a video it displays a message i can't even read and then closes immediantly, yesterday i reached the limit and i think its not happy that i'm trying to scan another video today, i think is some sort of a bug please help. Pop. Pop. Popcat112. Email: aeromjaime6@gmail.com

**Comment by TheGuy112** [comment]
Edit: i found out it ony dose'nt work with the channel JackSucksAtLife

**Comment by ThioJoe** [comment]
I'm going to need way more details to be able to help. Please use the bug reporting template. One thing you can try to see the error message that disappears to fast, is first open command prompt to the folder with the exe, then run it through that, then the window shouldn't close even if it crashes.
