### ISSUE TITLE
[Bug]: Lowercase "REPORT" does not work

### ISSUE THREAD

**Issue by abUwUser** [ThioJoe/YT-Spammer-Purge#284]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

I've tried to write "REPORT" with lowercase letters, and then YTSP interpreted as a invalid input.
![image](https://user-images.githubusercontent.com/27961224/147840877-b851738c-2397-479c-a051-fad338e8a3ee.png)

### Release version

2.5.1

### Steps to reproduce

1. Do a scan
2. Type "report"
3. Press enter

### What platform are you seeing this problem on?

Windows

**Comment by ThioJoe** [comment]
It is intended so people have to give a tiny extra amount of thought before executing
