### ISSUE TITLE
Filtering: Video link spam

### ISSUE THREAD

**Issue by Ganesha2282882** [ThioJoe/YT-Spammer-Purge#287]
### Filter Mode

Auto-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### (Optional) If 'Other', Enter Very Short Description

Block Comments/Replies that only have YouTube links

### Spammer Example / Sample

Spammers use these to promote a video. It also has a "rick-roll type" called "Lenning Roll'D" that uses this spam method.
The regex can go like this:
```python
(http|https)://(.*\.youtu.be|.*\.youtube.com|youtube.com|youtu.be)/.*
```
You can see a lot of these on popular short Minecraft YouTubers, such as Spectator. Also, there is some hook-up bots on the below video, but those usually get deleted. Also, the regex is for `re.match`. It's also usually one or two accounts that do the spam. The older the video is, the more spam replies it gets.

### Video / Post Link

https://www.youtube.com/watch?v=f0c-bIuhTkc

### (Optional) Additional Info / Context

It's a form of spam that usually never gets deleted.

**Comment by ThioJoe** [comment]
Hm yea I could probably add some logic to detect if a comment is literally just a video link

**Comment by ThioJoe** [comment]
These types of comments should be fixed as of release 2.5.2 and commit 2a634a90ac2569000027cf9ad2fb038f2870b833

**Comment by Ganesha2282882** [comment]
I've also seen cases where the put stuff before it so it doesn't get blocked.

**Comment by ThioJoe** [comment]
Theres only so much to be done. I think creators shoild just disable links in their comments altogether
