### ISSUE TITLE
[Bug]: Config  auto_check_update = False crash

### ISSUE THREAD

**Issue by Kurdakov** [ThioJoe/YT-Spammer-Purge#292]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

If using
auto_check_update = False
in latest version 2.5.2 I get
Traceback (most recent call last):
  File "C:\YouTube-Spammer-Purge\YouTubeSpammerPurge.py", line 3205, in <module>
    main()
  File "C:\YouTube-Spammer-Purge\YouTubeSpammerPurge.py", line 2497, in main
    if updateAvailable == True:
UnboundLocalError: local variable 'updateAvailable' referenced before assignmen

### Steps to reproduce

1. Get latest code
2. create new config
3. auto_check_update = False
4. crash

### What platform are you seeing this problem on?

Windows

**Comment by ThioJoe** [comment]
Fixed in new release 2.5.3, with commit e7a88faa74f9cc340789811058cc51ab7f7d0dfc
