### ISSUE TITLE
Disguised link as youtu.be or youtube.com

### ISSUE THREAD

**Issue by KendallDoesCoding** [ThioJoe/YT-Spammer-Purge#294]
Sometimes, users can use Unicode characters I think its called to disguise the link as youtube.com but it can lead you to a scam website. But, if its not unicode, its something you mentioned in the video mentioned below.

### Discussed in https://github.com/ThioJoe/YT-Spammer-Purge/discussions/293

<div type='discussions-op-text'>

<sup>Originally posted by **KendallDoesCoding** January  1, 2022</sup>
In #215 , it was stated that it cannot detect self promoters, which is obvious, but most of the time I see youtube.com/watch or youtu.be, But, as you stated in https://www.youtube.com/watch?v=hF1bIT1ym4g, scammers can use unicode characters to make it look like they are self promoters, but they can lead you to a scam website if you tap the link and not at all to youtube.

Also, you can't do anything about this, unless you can get all youtu.be and youtube.com links filtered out, but scammers may be using these youtu.be links and create videos that are adult content/lead you to the scam website, and for now i don't think it filters out youtu.be or youtube.com links.

</div>

**Comment by KendallDoesCoding** [comment]
Yes, I double checked and it is called unicode domains as you stated in your video on "How to Spot Any Spoofed & Fake Email (Ultimate Guide)"

**Comment by ThioJoe** [comment]
Haven't ever seen this used in practice, and I'm not sure if YouTube would allow such links to exist in comments. Nothing I can really do about it unless I see examples of it being used.

**Comment by KendallDoesCoding** [comment]
> Haven't ever seen this used in practice, and I'm not sure if YouTube would allow such links to exist in comments. Nothing I can really do about it unless I see examples of it being used.

Neither have I tbh, but I just wanted to give you a heads up.
