### ISSUE TITLE
Some install.sh fixes

### ISSUE THREAD

**Issue by KendallDoesCoding** [ThioJoe/YT-Spammer-Purge#321]
Update .sh files to new version.

It's currently using a old version it seems, as per @Kurdakov discussion with me in #319 

### Discussed in https://github.com/ThioJoe/YT-Spammer-Purge/discussions/305

<div type='discussions-op-text'>

<sup>Originally posted by **Kurdakov** January  2, 2022</sup>
@lolpro11 
Currently I'm not on linux (at home and don't want to install terminal ubuntu),
but looks like install.sh and install_full.sh need tag updates

TAG = sudo -u $USER curl https://api.github.com/repos/ThioJoe/YT-Spammer-Purge/releases/latest -s | jq .name -r
and then
sudo -u $USER curl https://codeload.github.com/ThioJoe/YouTube-Spammer-Purge/tar.gz/refs/tags/v$TAG -o yt-spammer.tar.gz
...
sudo -u $USER cd YouTube-Spammer-Purge-$TAG/

the problem is jq should be installed before hand, so in all install commands like
apt install python3 python3-tk

jq must be added

apt install python3 python3-tk jq
</div>

**Comment by ThioJoe** [comment]
Yea I updated the version. I have a script that prepares releases for me, I'll have to add a thing that updates these scripts as well to it.
