### ISSUE TITLE
Unable to detect some Robux Scam comments that use Check my channel for site

### ISSUE THREAD

**Issue by Sarah1390** [ThioJoe/YT-Spammer-Purge#327]
### Filter Mode

Auto-Smart Mode

### Select the Problem

Some spammers not detected

### Spammer Example / Sample

![Claim free robux](https://user-images.githubusercontent.com/97075311/148008407-521a286d-c1f4-4dcc-a6d8-c9fcd73d0775.PNG)
![Robux Giveaway](https://user-images.githubusercontent.com/97075311/148008409-aa9970c2-d2e1-43c2-b937-07678d24d687.PNG)

### (Optional) Additional Info / Context

I am noticing this type of scam running Rampant in these channels but these are the specific examples I watch. This is similar to the sex bots tap my channel name for website. The scam is specifically for Robux. The scam is with the channel name itself. They appear to be making varied comments. Variants are Claim Free Robux Check my channel or Robux Giveaway Check my channel. You are supposed to click on the name to be re-directed to the channel and then in the corner where they allow you to link items they post a link to a website where you can "Claim your free Robux". 

Video used for my posting example: https://www.youtube.com/watch?v=9sjD_6mQStw - I was able to scan just the usernames using the strings Robux, Free Robux and Robux Giveaway. I was able to catch 130 comments alone in this one video but if Auto Smart mode is used then only 10 are detected and can be reported. I am trying to report these scams as where I see these are on more family oriented channels with viewers.

Example channel ID's these comments are commonly seen on.
https://www.youtube.com/user/chadwildclay
https://www.youtube.com/user/VyQwaint
https://www.youtube.com/channel/UCmFzvquJYoSDFhd9W0JhZKw
https://www.youtube.com/channel/UC6Ewbj-MFWA7dXgQA9y5EEw

additional direct link to some comments. Comment link - User ID
https://www.youtube.com/watch?v=9sjD_6mQStw&lc=UgxbHONyrn8eP8_1F1V4AaABAg - UCIBYcgrUBbeasEtZ2rCBKBA
https://www.youtube.com/watch?v=9sjD_6mQStw&lc=Ugz7AbUH2LI-2iQuN014AaABAg - UCQcwIChvLcURejL71vbYBVg
https://www.youtube.com/watch?v=9sjD_6mQStw&lc=UgzOrTEbjFC0IpRT5Wp4AaABAg - UCfWCnhjoBy_EoSV74IvOxxw
https://www.youtube.com/watch?v=9sjD_6mQStw&lc=UgzLD3S7aBq16JT8bjB4AaABAg - UCbCZwi8Mi_lpUQKpoTBAdXA

**Comment by kiatchun** [comment]
To be fair, these channels where the scammers are seen on are also scams. They trick children into thinking that "project Zorgo" or whatever is real.

**Comment by Sarah1390** [comment]
All these channels belong to a brand that is trying to do Interactive Storytelling or in some ways it is closer to an Alternate Reality Game. which is one of two I follow. They have even advised people in the videos themselves not to click on these scam links.

**Comment by KendallDoesCoding** [comment]
@ThioJoe I think it should auto detect channel names like

"CLICK MY CHANNEL"
"GO TO MY CHANNEL"
"FREE ROBUX"

And there's a whole list.

**Comment by ThioJoe** [comment]
Hmm thanks for letting me know, the filter should actually have already caught these, but I think I know why they didn't.

**Comment by ThioJoe** [comment]
Now fixed as of release 2.6.2

**Comment by Sarah1390** [comment]
Thank you. Much More sensitive for the people just trying to Report. The improvements that you made were able to pick up 6000 new comments Between the 5 channels I listed as I try to scan their last 5 videos each day they release content.
