### ISSUE TITLE
[Bug]: Certain messages seem to mess with the name displayed in this tool

### ISSUE THREAD

**Issue by Firecul** [ThioJoe/YT-Spammer-Purge#331]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Scanning this creator's last 5 videos I noticed something picked up by the tool looked incorrect. 

https://www.youtube.com/watch?v=D1kqGyPGsF8&lc=Ugyf3xwilhN4U63dZjZ4AaABAg

![chrome_How_Nanotech_Can_Help_Solve_the_Fresh_Water_Crisis](https://user-images.githubusercontent.com/34950371/148136783-4202162a-0bc9-45f0-a9ff-10088ac618b7.png)
The comment looks normal enough, the name is visible as expected.

![WindowsTerminal_Windows_PowerShell (3)](https://user-images.githubusercontent.com/34950371/148136836-c47cff27-eef6-4753-8494-f99eb1fd2c16.png)
![WindowsTerminal_Windows_PowerShell (4)](https://user-images.githubusercontent.com/34950371/148136840-590e9398-b4dc-46f6-b2d7-137275e005af.png)
but in the output there is no name shown.

### Release version

v2.6.2

### Steps to reproduce

1. Scan this video https://www.youtube.com/watch?v=D1kqGyPGsF8
2. The problematic comment will be found by the tool

### What platform are you seeing this problem on?

Windows

### Screenshots

(This box appears broken btw, I can't attach images here by default)

![YTSpammerPurge 2 6 2_LDownloadsYoutube_Spam_SwatterYTSpammerPurge 2](https://user-images.githubusercontent.com/34950371/148137402-960cc44c-64fe-4493-8548-99c253dd312e.png)

**Comment by ThioJoe** [comment]
Yea i've seen this happen before on rare occasions, I'll try and look more into it

**Comment by ThioJoe** [comment]
Turns out the comment was using return carriages in the text for some bizarre reason which was clearing some lines before printing to console. Starting with 7ff7b540b247f29641baa4b0fcc9003c2695678f it will sanitize the data first, so should be fixed for the next release.
