### ISSUE TITLE
[PRERELEASE] [Bug]: Running 2.8.0 with 2.7.2 config causes crash

### ISSUE THREAD

**Issue by Firecul** [ThioJoe/YT-Spammer-Purge#337]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Running the ~~new 2.7.3~~ the most up to date code (from commit 372a509) with an old version of the config file causes it to crash (at  least in the .py) due to the missing "release_channel" key.
With this key manually added to the old v14 config it will launch and prompt to regenerate the new v15 as expected

![Screenshot_20220106_023207](https://user-images.githubusercontent.com/34950371/148318933-922ccb28-f3cc-4c25-b1fd-8d15094bf95d.png)

### Release version

Current version as of commit 372a509 (to be 2.8.0 iirc)

### Steps to reproduce

1. launch newest version with old v14 config as generated by 2.7.2
2. experience crash

### What platform are you seeing this problem on?

Linux (can also be ChromeOS)

**Comment by Firecul** [comment]
Just realised it's from the main branch not at the v2.7.3 release. So it's good to know about but not a bug in the released software yet.

**Comment by Firecul** [comment]
#338 also comes under this category of needing the ini updated or default values. I'll leave this issue up and close the other.

**Comment by ThioJoe** [comment]
Yea anything newer than the latest release is basically beta. There is a new 2.8.0-Beta release. I'll have to fix this one because the crash happens before the user gets to the menu to make a new one it looks like

**Comment by ThioJoe** [comment]
Actually I'm just going to pull the release for now, the json_encoding setting is missing, I thought I put that in the config but I guess i put it in the wrong file because it isn't there

**Comment by Firecul** [comment]
> I thought I put that in the config but I guess i put it in the wrong file because it isn't there
I have no idea how many times I've done that sort of thing.

Will the config version need changed too while you are there for 2.8.0?

**Comment by ThioJoe** [comment]
Should be fixed with b499f4044a8e0c7087664e4461dc7e5d1df0d52c , now warns the user to update the config file instead of crashing.

I didn't change the config version from 15, so you'll still have to update it even though it doesn't notify you at the beginning, but it shouldn't crash even if you're using the 'old' config.
