### ISSUE TITLE
[PRERELEASE] [Bug]: Json logs fail to write

### ISSUE THREAD

**Issue by Firecul** [ThioJoe/YT-Spammer-Purge#338]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Scanning most recent 5 videos for spam with json logs enabled I experienced a crash.

![Screenshot_20220106_024504](https://user-images.githubusercontent.com/34950371/148320188-82118100-c22c-4741-835e-8492057c7627.png)
Seems to be a missing key in the config for `json_encoding = ...` as the code expects

### Release version

Current version as of commit 372a509

### Steps to reproduce

1. Enable `json_log = True` in the config file
2. Scan https://www.youtube.com/channel/UCvn8y5Gf090ljxf9xbG5K3w for the most recent 5 videos
2. After scan completes an error is thrown
3. 

### What platform are you seeing this problem on?

Linux (can also be ChromeOS)

**Comment by Firecul** [comment]
I haven't looked at the code for this update yet to see a simple solution to this.

**Comment by Firecul** [comment]
Just realised it's from the main branch not at the v2.7.3 release. So it's good to know about but not a bug in the released software yet.

**Comment by ThioJoe** [comment]
Should be fixed with 4dfbeb01dd108af5062a3ca1d3881923612a20eb

**Comment by Firecul** [comment]
Confirmed, regen with this version will work
