### ISSUE TITLE
where is the exe file

### ISSUE THREAD

**Issue by 14paavang** [ThioJoe/YT-Spammer-Purge#340]
i went through the entire thing and I cannot find the exe file

**Comment by Firecul** [comment]
You can find the exe in the releases. If you are on the website it'll be on the right hand side from the main code page. Currently v2.7.3 is the most up to date release

**Comment by Firecul** [comment]
https://github.com/ThioJoe/YT-Spammer-Purge/releases/tag/v2.7.3
The exe is in the assets section at the bottom

**Comment by KendallDoesCoding** [comment]
@14paavang Please follow the above/Watch @ThioJoe 's videos about this, they are listed in README.md.

Requesting you to close this.

**Comment by Firecul** [comment]
I hope so
