### ISSUE TITLE
[Bug]: (The program stops and times out when searching a video OR a channels last 5 videos)

### ISSUE THREAD

**Issue by lockdot2** [ThioJoe/YT-Spammer-Purge#343]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

I was trying to check Doctor Mike's last 5 videos, and it kept timing out, on 2 different computers I tried it on. And it happens when searching a specific video too. Then I tried to search Drew Binsky and it happened again.
I dont see any other posts about this, but I may not be looking in the right spot, I never use github.
![Screenshot (6453)](https://user-images.githubusercontent.com/94180804/148497132-f2df195c-3367-4b07-a2ac-74646dc65857.png)

![Screenshot (6454)](https://user-images.githubusercontent.com/94180804/148497202-a1d946a7-b5f7-437f-bdfb-fb5e17171c4d.png)
.

### Release version

2.7.4 and 2.8.0-Beta3

### Steps to reproduce

1. Open the app
2. choose either specific video or the last 5 videos
3. use the recommended setting (1)
4. It fails after a while. In random spots.

### What platform are you seeing this problem on?

Windows

### Relevant log output

```shell
(Note: If the program appears to freeze, try right clicking within the window)

                          --- Scanning ---

Scanning 1/5: Doctor Mike Reads Thirst Tweets

Traceback (most recent call last):ents Scanned: 3395 | Replies Scanned: 650 | Matches Found So Far: 162
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YouTubeSpammerPurge.py", line 3723, in <module>
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YouTubeSpammerPurge.py", line 3357, in main
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YouTubeSpammerPurge.py", line 3348, in scan_video
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YouTubeSpammerPurge.py", line 403, in get_comments
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YouTubeSpammerPurge.py", line 432, in get_replies
  File "googleapiclient\_helpers.py", line 131, in positional_wrapper
  File "googleapiclient\http.py", line 922, in execute
  File "googleapiclient\http.py", line 221, in _retry_request
  File "googleapiclient\http.py", line 190, in _retry_request
  File "google_auth_httplib2.py", line 218, in request
  File "httplib2\__init__.py", line 1725, in request
  File "httplib2\__init__.py", line 1441, in _request
  File "httplib2\__init__.py", line 1393, in _conn_request
  File "http\client.py", line 1368, in getresponse
  File "http\client.py", line 317, in begin
  File "http\client.py", line 278, in _read_status
  File "socket.py", line 705, in readinto
  File "ssl.py", line 1273, in recv_into
  File "ssl.py", line 1129, in read
TimeoutError: The read operation timed out
------------------------------------------------
Error Message: The read operation timed out

Unknown Error - Code: Z-3 occurred. If this keeps happening, consider posting a bug report
on the GitHub issues page, and include the above error info.
Short Link: TJoe.io/bug-report

 Press Enter to Exit...
```

### Screenshots

```shell
file:///C:/Users/Optiplex/Pictures/Screenshots/Screenshot%20(6455).png
```

**Comment by KendallDoesCoding** [comment]
Hi, This seems to be a interesting bug. I don't think there are other issues with this bug too, but here's where you can search for previous closed issues, FYI https://github.com/ThioJoe/YT-Spammer-Purge/issues?q=is%3Aissue+is%3Aclosed

**Comment by lockdot2** [comment]
Hey there! Yeah, it is still happening. I recorded the whole issue so you can see it, and got a image of the problem in this video as well - https://youtu.be/AF1eIAjTdA8
I was going to send you the video directly, though its 48mb, which is larger then GitHubs 10mb limit.

**Comment by lockdot2** [comment]
Also, here is a video of it crashing when I test the 5 most recent videos on a  channel.  https://youtu.be/1Dm0mN7Hd2k

**Comment by Firecul** [comment]
Currently testing with v2.8.2 .py version and no problem so far
![Screenshot_20220108_154719](https://user-images.githubusercontent.com/34950371/148650687-c70d382b-14c4-4e8b-aa43-56ae93c2fde7.png)
I'll update when it completes or not

**Comment by Firecul** [comment]
> Also, here is a video of it crashing when I test the 5 most recent videos on a channel. https://youtu.be/1Dm0mN7Hd2k

If you try running the exe through a command line window when the app crashes you should be able to still see any errors that pop up when it crashes @lockdot2

**Comment by Firecul** [comment]
> Or is your internet connection not completely stable?

I have a feeling this is the issue, my scan is still going strong atm
![Screenshot_20220108_155846](https://user-images.githubusercontent.com/34950371/148651004-d8a2bbee-02db-4a50-a2ca-fa2cbd9ecab8.png)

**Comment by lockdot2** [comment]
My internet isnt the best, but it is quite good. It is 200mbps down and 10mbps upload. And my ping is around 10 as well. How do I see how stable it is? Also here is a screenshot of my internet, It is showing up as links for some reason. Both images are the same if you try to open one.
![Screenshot (6481)](https://user-images.githubusercontent.com/94180804/148652514-629ccfa1-bfdf-4e06-8213-b3c6af3d9dd1.png)
![Screenshot (6481)](https://user-images.githubusercontent.com/94180804/148652544-c59f7c2c-c9ba-4a56-9d5a-7a5319898f18.png)

**Comment by lockdot2** [comment]
I will try this using my phones Mobile Hot spot, which gets ~500 ping and gets a max speed of 0.5mbps, but its realistically 60kbps. But, maybe it will work better, maybe?

**Comment by lockdot2** [comment]
![image](https://user-images.githubusercontent.com/94180804/148653075-7dd42048-ed99-40db-9e02-7125c0f97e1a.png)
It is working so far it seems.

**Comment by lockdot2** [comment]
![image](https://user-images.githubusercontent.com/94180804/148653353-6936ba1a-67a5-4f42-9460-b84e45066bdb.png)
It finished! Nice! Thanks for saying it may be my internet. It worked on the slow mobile hot spot.

**Comment by KendallDoesCoding** [comment]
@lockdot2 Ok, It may've been a bug which is since fixed in a new update, Request you to close this.

**Comment by Firecul** [comment]
![Screenshot_20220108_174600](https://user-images.githubusercontent.com/34950371/148654239-5006e599-0535-456a-91c5-690d915c51fb.png)
Mine eventually did crash, I'm not too sure why but I'm not too interested atm. if it happens again then I'll look into it and report it.
