### ISSUE TITLE
[BUG] token.pickle error

### ISSUE THREAD

**Issue by hackershrimp1** [ThioJoe/YT-Spammer-Purge#344]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Well, I was trying to log in with my google account with the API set up but then I got this error.
![image](https://user-images.githubusercontent.com/97303509/148573619-5cd83ff0-31af-4b82-8e20-b305d630b5e8.png)

### Release version

2.8.0

### Steps to reproduce

1. https://www.youtube.com/watch?v=c6ebWvay8dE&t=0s
2. Log in
3. Get login error
4. Press Enter to retry
5. Retry fails
6. Press Enter to Exit
7. Big Bruh Moment

### What platform are you seeing this problem on?

Windows

### Relevant log output

```shell
Traceback (most recent call last):
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YouTubeSpammerPurge.py", line 1043, in get_current_user
KeyError: 'items'

Error: Still unable to get channel info. Big Bruh Moment. Try deleting token.pickle. The info above might help if you want to report a bug.
```

**Comment by ThioJoe** [comment]
Do any of the "known possible causes" apply to you?

**Comment by hackershrimp1** [comment]
Oh I am really sorry I didn't make it a channel.

**Comment by hackershrimp1** [comment]
Im gonna close this issue
