### ISSUE TITLE
[Bug]: in json files escaped utf strings are printed

### ISSUE THREAD

**Issue by Kurdakov** [ThioJoe/YT-Spammer-Purge#345]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

in 2.9 beta output to json log contains utf escaped strings like
"\ud83d\udc98\ud83c\udf39\ud83c\udf39\ud83c\udf39\ud83c\udf37\ud83c\udf37\ud83c\udf37\ud83d\udc8b\u2764\ud83d\udc4d\ud83d\udc4d\ud83d\udc4d\ud83d\udc4d"

to output utf-8 symbols use ensure_ascii=False
file.write(json.dumps(dictionaryToWrite, indent=4, ensure_ascii=False))

### Steps to reproduce

1. run beta 2.9 output to json
2. view json file

### What platform are you seeing this problem on?

Windows

**Comment by Kurdakov** [comment]
another thing - rtf file is saved too, but there is a problem with rtf file see https://github.com/ThioJoe/YT-Spammer-Purge/discussions/257 - in case of flag emoji or any other multi character utf symbol there will be crash, while with json there will not be crashes.
also - as youtube is utf-8 encoded - what is the need for utf-16 utf-32?

**Comment by ThioJoe** [comment]
Hm I'll have a look at the ascii setting mentioned. The reason for they're also many more options the python method will accept as the encoding method, so I figured may as well mention them as a possibility, utf-16 and 32 were just the ones i knew off the top of my head to add into the description. I'll probably replace it with a link to this table which apparently has all the possibilities: https://docs.python.org/3/library/codecs.html#standard-encodings

**Comment by ThioJoe** [comment]
Should be fixed with aded9dfa90b2f1d13eae3b2feacd31694149d89c
