### ISSUE TITLE
Filtering: Misses a Spam comment

### ISSUE THREAD

**Issue by along02** [ThioJoe/YT-Spammer-Purge#350]
### Filter Mode

Auto-Smart Mode

### Select the Problem

Some spammers not detected

### Spammer Example / Sample

![image](https://user-images.githubusercontent.com/21041802/148620368-429de2c9-c101-44f1-a25e-1671b1aad7e5.png)

### Video / Post Link

https://www.youtube.com/watch?v=ACJlB7mRYdk

**Comment by Firecul** [comment]
You could add `dating.link` to the spam domains, that would do it.

**Comment by Firecul** [comment]
https://github.com/ThioJoe/YT-Spam-Lists/issues/new?assignees=&labels=scam-domain&template=report_spam_domains.yaml&title=Spam+Domain+Submission

![Screenshot_20220107_234440](https://user-images.githubusercontent.com/34950371/148620972-eebbdc15-0ad0-420f-8622-4dab3d6a5f61.png)
![Screenshot_20220107_234450](https://user-images.githubusercontent.com/34950371/148620979-e4f18f26-7f4f-4b60-a211-07aa2a66edad.png)

Just fill in the details as appropriate here.

**Comment by Firecul** [comment]
Yip that looks fine, you can prob close this if you want unless you would like to wait for ThioJoe's opinion
