### ISSUE TITLE
[Bug]: Window resizing issue causing display to bug out while scanning videos

### ISSUE THREAD

**Issue by Sarah1390** [ThioJoe/YT-Spammer-Purge#351]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

I was just doing a channel scan of 5 videos, replicated multiple times on different channels, when I went to move the window to the side, the window snapped to half size the screen. When half size the screen starts scrolling with each scan output on an individual line. Return the window to opening size or fullscreen and you will get the results with looks like text wrapping until the last line.

### Release version

YTSpammerPurge.2.8.2

### Steps to reproduce

1. Perform a scan on any video and channel
2.  While scanning snap window to half screen
3. After snapping window to half screen for a few seconds return window to fullscreen or startup screen size

Some additional information, I have in my windows setup my display scale set to 250% under System>Display>Scale and Layout
I have my text scale set to 125% under Ease of Access>Display>Make Text Bigger.
I am using a large screen tv and I have trouble seeing words at a distance of greater than an arms length so I need to increase my scaling on everything.

### What platform are you seeing this problem on?

Windows

### Relevant log output

```shell
N/A
```

### Screenshots

```shell


![Display issue half screen](https://user-images.githubusercontent.com/97075311/148631616-5f1267d7-5c3e-47c4-931a-af14e983fff5.png)

**Comment by Sarah1390** [comment]
sorry, screenshots weren't working trying again
![Display issue half screen](https://user-images.githubusercontent.com/97075311/148631778-48b65ec3-df7b-4403-81c0-e8bc020d7abe.png)
![display iss
![Display issue regular size](https://user-images.githubusercontent.com/97075311/148631811-9d9f687c-2ea6-40a4-b757-a3792a2cc0ad.png)
ue](https://user-images.githubusercontent.com/97075311/148631803-302fbcdd-306b-48a7-ac1e-b84ca2c76675.png)

**Comment by ThioJoe** [comment]
Yea i'm pretty sure that's just how the console window works. I think the script gets the console window size at the beginning in the background and uses that to display everything, so if the size changes it's going to wrap at different parts

**Comment by Firecul** [comment]
I've had this before when I was in windows but I wasn't able to replicate it. Never had it in Manjaro at all.
I'll have a try later to have it happen again on windows when I have the chance.

**Comment by Sarah1390** [comment]
I'll give it a try. I'm pretty familiar with running into this type of bug with programs provided by my work. I can easily live with it
