### ISSUE TITLE
Filtering: (Write a short title here)

### ISSUE THREAD

**Issue by gnuhead-chieb** [ThioJoe/YT-Spammer-Purge#352]
### Filter Mode

String search

### Select the Problem

Some spammers not detected

### Spammer Example / Sample

![Screenshot_20220109_060919](https://user-images.githubusercontent.com/41156994/148660063-0bcbb7f1-58e8-458f-8e45-892fc92d5341.png)

### Video / Post Link

https://www.youtube.com/watch?v=SpUJkyCP8AI&lc=UgxbrT9P43nMxztvKWl4AaABAg.9WwGYGV2osv9Ww_naqcxaf

### (Optional) Additional Info / Context

the string "#垃圾" should be detected.
Many of the recent spam comments contain this string.

**Comment by ThioJoe** [comment]
The trouble is it's just a normal word in Chinese, so would catch many false positives on certain channels, especially like the one linked where all the comments are also in Chinese. Though I do have another repository where you can submit domain names seen being used in comments like this to be added to the spam domains list: https://github.com/ThioJoe/YT-Spam-Lists

I'll add this one in the mean time.

**Comment by gnuhead-chieb** [comment]
> The trouble is it's just a normal word in Chinese, so would catch many false positives on certain channels, especially like the one linked where all the comments are also in Chinese.

okay.then how about detect by combination of other spamming evidence?
Many spam comments use multiple laungauge in the comment.it may can be detected by unicode mapping.
https://unicodemap.org/

Example:
プ(Katakana)/ñ(Latin Extended)[Multiple charset detected]
+
NewDebut-Av.Monster[URL Contained]
+
#垃圾[Specious string]
+
:[Specious symbol]
=
Shit comment
