### ISSUE TITLE
[Bug]: Missing parameter for community post in 2.9.0-Beta1

### ISSUE THREAD

**Issue by Kurdakov** [ThioJoe/YT-Spammer-Purge#355]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

tried to check community post in beta version got

Traceback (most recent call last):

  File "c:\YouTube-Spammer-Purge\YouTubeSpammerPurge.py", line 3937, in <module>
    main()
  File "c:\YouTube-Spammer-Purge\YouTubeSpammerPurge.py", line 3506, in main
    scan_community_post(communityPostID, maxScanNumber)
  File "c:\YouTube-Spammer-Purge\YouTubeSpammerPurge.py", line 3505, in scan_community_post
    check_against_filter(currentUser, miscData, filterMode=filterMode, filterSubMode=filterSubMode, commentID=commentID, videoID=communityPostID, authorChannelID=authorChannelID, parentAuthorChannelID=None, inputtedSpammerChannelID=inputtedSpammerChannelID, inputtedUsernameFilter=inputtedUsernameFilter, inputtedCommentTextFilter=inputtedCommentTextFilter, authorChannelName=authorChannelName, commentText=commentText, regexPattern=regexPattern)
TypeError: check_against_filter() missing 1 required positional argument: 'config'

------------------------------------------------

Error Message: check_against_filter() missing 1 required positional argument: 'config'

config parameter is missing in function call

### Steps to reproduce

1. start beta version
2. check community post
3. cras

### What platform are you seeing this problem on?

Windows

**Comment by ThioJoe** [comment]
Ah yup, should be fixed with 48e00bda235d86f0595e74d829bcd6771fe414cd
