### ISSUE TITLE
Filtering: Missing Dream imposter spam and a few less than 10 cmt entry spam

### ISSUE THREAD

**Issue by Devtorious** [ThioJoe/YT-Spammer-Purge#358]
### Filter Mode

Auto-Smart Mode

### Select the Problem

Some spammers not detected

### Spammer Example / Sample

![image](https://user-images.githubusercontent.com/62132131/148672920-63a83ae8-fe1e-4636-8119-4e78fbb9f733.png)
![image](https://user-images.githubusercontent.com/62132131/148672935-cbfed22c-5e82-44e9-9710-c4aaf233958a.png)
![image](https://user-images.githubusercontent.com/62132131/148672993-7b391f1c-5559-4868-9050-4c2fde530c30.png)
seemingly bots channel links:
https://www.youtube.com/channel/UCQ7g4L1WfbbYmR9W__iuk7Q
https://www.youtube.com/channel/UCUf3UGvCo0PVCRB9_x_3ItA
https://www.youtube.com/channel/UCVpLXQoj18Mq2UMgMrdwCZA
https://www.youtube.com/channel/UCYd-w7Zi1v_NtGmzox0vWkw

### Video / Post Link

https://www.youtube.com/watch?v=Yz_mfPbWEHY

### (Optional) Additional Info / Context

I'm 80% sure all of the comment img I sent were spam sorry I don't know what kind of format you wanted so I send the images and channel link (unsure how to get specific cmt link)

**Comment by TechStudent11** [comment]
It's called YouTube Spammer Purge. It only deletes users who spam I guess. This should be solved.

**Comment by TechStudent11** [comment]
@Devtorious you should keep it open so that ThioJoe can take a look at this.

**Comment by Devtorious** [comment]
well I thought you mentioned that this should be solved, or maybe i got that sentence wrong some how lol

**Comment by TechStudent11** [comment]
@Devtorious I meant that someone should fix it. I could, but maybe not now.

**Comment by ThioJoe** [comment]
Yea unfortunately for the ones like the 'dream' and 'Atom', there's not much that can be done. The best thing would be for the creator to disable hyperlinks in their comments section.

**Comment by TechStudent11** [comment]
@ThioJoe How? I've never seen that on my channel.

**Comment by Firecul** [comment]
> ThioJoe How? I've never seen that on my channel.

![chrome_Video_comments_-_YouTube_Studio_-_Google_Chrome](https://user-images.githubusercontent.com/34950371/148710003-e6465d0f-3f5e-44d6-b132-d868aa9c58ad.png)

I found it by going to YT Studio > Settings (On the bottom left for me) > Community > Automated filters, then you'll see it right down at the bottom.

**Comment by TechStudent11** [comment]
@Firecul thanks.
