### ISSUE TITLE
there is no token.pickle file

### ISSUE THREAD

**Issue by 14paavang** [ThioJoe/YT-Spammer-Purge#360]
there is no token . pickle file after I log it and it is telling me to delete it
<img width="675" alt="image" src="https://user-images.githubusercontent.com/81815334/148691566-83ea667f-91a5-41f6-b192-d91c64fb58f8.png">

**Comment by Kurdakov** [comment]
searched for similar problems: solutions include
https://giters.com/xyou365/AutoRclone/issues/57 - moving program to some other user accessible folder (maybe a whitespace in name of folder is a reason?)
changing operating port of auth? https://github.com/googleapis/google-api-python-client/issues/622

so try to move program to another user accessible folder, preferably without whitespaces - would  it help?

**Comment by ThioJoe** [comment]
Yea I think this means the program does not have permissions to write to that directory

**Comment by 14paavang** [comment]
Let me check

**Comment by KendallDoesCoding** [comment]
@14paavang Has this issue been fixed?

**Comment by 14paavang** [comment]
Yes

**Comment by KendallDoesCoding** [comment]
Good to hear that. Thanks for closing the issue.
