### ISSUE TITLE
[Bug]: Renaming main file causes error within gui.py

### ISSUE THREAD

**Issue by compsup** [ThioJoe/YT-Spammer-Purge#362]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

When attempting to rename YouTubeSpammerPurge.py to something else and run it, gui.py comes back with an import error.

### Release version

2.8.2

### Steps to reproduce

1. Use the raw version, not the .exe
2. Rename YouTubeSpammerPurge.py
3. Run YouTubeSpammerPurgeRenamed.py
4. Observe traceback with an import error from gui.py

### What platform are you seeing this problem on?

Linux (can also be ChromeOS)

### Relevant log output

```shell
python3 YouTubeSpammerPurge1.py 
Traceback (most recent call last):
  File "/home/username/Documents/Python-projects/YT-Spammer-Purge/YouTubeSpammerPurge1.py", line 44, in <module>
    from gui import *
  File "/home/username/Documents/Python-projects/YT-Spammer-Purge/gui.py", line 5, in <module>
    import YouTubeSpammerPurge as myFunctions
ModuleNotFoundError: No module named 'YouTubeSpammerPurge'
```

### Screenshots

```shell
Not needed, just exactly what is posted above.
```

**Comment by compsup** [comment]
Normally I would have ignored this however all over the documentation it says you can rename the file which will cause this error.

**Comment by ThioJoe** [comment]
Oh, yea I meant rename the exe. The gui script accesses some functions in the main script, so if you change it's name it won't know how to go back and access them. I'm not sure if there's anyway around that

**Comment by compsup** [comment]
Honestly, I would just remove all references to renaming the file in the linux and macos install instructions.

**Comment by Firecul** [comment]
Pass through the main script name as an option when launching the gui?

**Comment by ThioJoe** [comment]
> Pass through the main script name as an option when launching the gui?

I just tried. I'm able to get the current path of the main script and pass it into the function as a variable, but it won't let the variable be imported, it doesn't like it. 

There might be a way to do it but I think the simplest thing to do would be go into the gui.py script and change where it says "import YouTubeSpammerPurge" to import whatever your file name is

**Comment by compsup** [comment]
I feel since this project is so large and splitting the main file up is a foreseeable thing to happen what about implementing a main `start` file. Something like `start.py` or `start.sh`. This will solve the issue of people wanting to make the file they run to be shorter/called something different and will possibly solve future problems.

**Comment by mysistersbrother** [comment]
From what I can see the GUI file only uses one function from the main file, `make_char_set`. This function and some others could be moved to a separate `utils.py` file which then the GUI and main file import from. That would solve the renaming of the main file issue.

**Comment by compsup** [comment]
> From what I can see the GUI file only uses one function from the main file, `make_char_set`. This function and some others could be moved to a separate `utils.py` file which then the GUI and main file import from. That would solve the renaming of the main file issue.

This sounds like the best solution as not only will it solve the issue at hand but also eliminate the bad practice of two files importing each other (it can get real confusing very quickly).

**Comment by TechStudent11** [comment]
> > From what I can see the GUI file only uses one function from the main file, `make_char_set`. This function and some others could be moved to a separate `utils.py` file which then the GUI and main file import from. That would solve the renaming of the main file issue.
> 
> This sounds like the best solution as not only will it solve the issue at hand but also eliminate the bad practice of two files importing each other (it can get real confusing very quickly).

You could separate that even farther like functions that help with authentication can go into a file called `auth.py` and files that help with comments can go into a file called `comments.py` and so on and so forth.

**Comment by ThioJoe** [comment]
This should be fixed with the latest beta branch, which separates out the files
