### ISSUE TITLE
Version number mis-match

### ISSUE THREAD

**Issue by compsup** [ThioJoe/YT-Spammer-Purge#364]
When pulling from `https://codeload.github.com/ThioJoe/YT-Spammer-Purge/tar.gz/refs/tags/v{latestVersion}` the version that the code is tagged at, lets say 2.10.0, the version number in the code is still at 2.9.0. I believe this is caused by the commit for changing the version number in the code happening after you created the version tag.

**Comment by ThioJoe** [comment]
Yea for the 2.10 beta i realized after i made the release tag that i haven't been setting the beta releases to the beta branch. So the beta release tags have been linking to the latest main commit. I'll fix it going forward

**Comment by ThioJoe** [comment]
Actually I was able to change the commit associated with the tag. So now it should be correct.
