### ISSUE TITLE
Filtering: Missed a spammer

### ISSUE THREAD

**Issue by KevinZ147** [ThioJoe/YT-Spammer-Purge#366]
### Filter Mode

Auto-Smart Mode

### Select the Problem

Some spammers not detected

### Spammer Example / Sample

https://www.youtube.com/watch?v=SK0ZbCFuBZE&lc=UgwpwH_zSg1FI2qnS854AaABAg.9X-W0LK2yTs9X-Wik4IolR

### Video / Post Link

https://www.youtube.com/watch?v=SK0ZbCFuBZE

**Comment by ThioJoe** [comment]
Yea that type of spam is more or less impossible to distinguish. If they are leaving many identical comments I'm eventually going to add a feature to detect that sort of thing. The best thing for a creator to do in that case is disable hyperlinks in comments.
