### ISSUE TITLE
[Bug]: Use config file = true not being honoured.

### ISSUE THREAD

**Issue by Firecul** [ThioJoe/YT-Spammer-Purge#368]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

With `use_this_config = True` in the config file for the newest beta .exe I am still being asked whether the program should use it or not.
![Code_SpamPurgeConfig ini_-_Visual_Studio_Code](https://user-images.githubusercontent.com/34950371/148845326-60129189-498a-4d2d-aa28-dee2d0a25f9b.png)
![WindowsTerminal_Windows_PowerShell (8)](https://user-images.githubusercontent.com/34950371/148845341-5998d8bb-7b78-47d6-8a80-54ae1290b19b.png)

### Release version

v2.10.0-Beta2

### Steps to reproduce

1. Generated new config
2. Set `use_this_config = True`
3. Start exe

### What platform are you seeing this problem on?

Windows

**Comment by ThioJoe** [comment]
Ah ok I see the problem

**Comment by ThioJoe** [comment]
Now fixed with latest commit, so will be included in next release

**Comment by Firecul** [comment]
Working in .py in Windows 100%, I'm sure the .exe will too.
