### ISSUE TITLE
[Bug]: JSON profile picture settings error

### ISSUE THREAD

**Issue by Firecul** [ThioJoe/YT-Spammer-Purge#369]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

When testing out the `json_profile_picture` setting I tried both `high` and `medium` with both failing. `False` and `default` work as expected.

![WindowsTerminal_Windows_PowerShell (7)](https://user-images.githubusercontent.com/34950371/148845745-b074fb75-5478-4ffa-899a-b7a9fb0906a8.png)

![WindowsTerminal_Windows_PowerShell (9)](https://user-images.githubusercontent.com/34950371/148845751-7651e779-9941-4f4d-a825-71767f38d641.png)

### Release version

v2.10.0-Beta2

### Steps to reproduce

1. Generate new config
2. Set `json_profile_picture` to `high` or `medium`
3. Perform a scan, I used 6 most recent videos of a channel.
4. The error occurs at the end of the comment readout

### What platform are you seeing this problem on?

Windows

**Comment by ThioJoe** [comment]
Ok should be fixed in the latest commit

**Comment by Firecul** [comment]
Working in .py in Windows 100%, I'm sure the .exe will too.
