### ISSUE TITLE
Filtering: Insensitive spam

### ISSUE THREAD

**Issue by TwoPercentSkill** [ThioJoe/YT-Spammer-Purge#372]
### Filter Mode

Sensitive-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

![image](https://user-images.githubusercontent.com/43811420/149000361-e679f775-486c-4d4d-b0c5-996fa9e6a37b.png)
![image](https://user-images.githubusercontent.com/43811420/149005364-7ceadd1e-ec6d-4fba-b75e-37e610eb71ff.png)

https://www.youtube.com/channel/UCpe4MY5NjgSF2HYgjWmThmQ

### Video / Post Link

https://www.youtube.com/watch?v=QPBBLdI_tlY

### (Optional) Additional Info / Context

There are many other similar comments on made by similar users. The spam involves first making a comment like this on their alt. Normal users who are upset go to their alt's page, click on the featured video, and get transfered to their main channel where they gain a view.

**Comment by ThioJoe** [comment]
Spam this specific is better suited as a custom search using one of the other modes
