### ISSUE TITLE
error upon running in Ubuntu

### ISSUE THREAD

**Issue by Dfmaaa** [ThioJoe/YT-Spammer-Purge#378]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

When I tried to run 2.10.0 on Ubuntu 20.04.3 LTS, I got this error
import YouTubeSpammerPurge as myFunctions
  File "/home/dfmaaa1/YT-Spammer-Purge-2.10.0/YouTubeSpammerPurge.py", line 1027, in <module>
    def get_current_user(config:dict) -> tuple[str, str, bool]:
TypeError: 'type' object is not subscriptable

### Release version

2.10.0

### Steps to reproduce

1. python3 YoutubeSpammerPurge.py

### What platform are you seeing this problem on?

Linux (can also be ChromeOS)

### Relevant log output

```shell
import YouTubeSpammerPurge as myFunctions
  File "/home/dfmaaa1/YT-Spammer-Purge-2.10.0/YouTubeSpammerPurge.py", line 1027, in <module>
    def get_current_user(config:dict) -> tuple[str, str, bool]:
TypeError: 'type' object is not subscriptable
```

**Comment by ThioJoe** [comment]
Hmm what version of python are you using?

**Comment by Dfmaaa** [comment]
3.8.10

**Comment by Dfmaaa** [comment]
Also, great project!

**Comment by ThioJoe** [comment]
For some reason it doesn't seem to like the typehint. I think it might actually require 3.9 for that. Might have to just take it out.

**Comment by TechStudent11** [comment]
@ThioJoe Is type-hinting nesessary?

**Comment by TechStudent11** [comment]
> > @ThioJoe Is type-hinting nesessary?
> 
> Nah, I was just experimenting with it

Okay so maybe remove of something? Maybe make a branch for development code and when it's ready push to the main branch.

**Comment by ThioJoe** [comment]
Ok should be fixed with the latest commit on the beta branch
