### ISSUE TITLE
["Bug"]: When no spam comments found tool exits instead of returning to menu

### ISSUE THREAD

**Issue by Firecul** [ThioJoe/YT-Spammer-Purge#386]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

It's not a bug per se but just an annoyance, at the end of most scans there is the option to return to the main menu. However, when no spam is found the tool exits completely.

![WindowsTerminal_Windows_PowerShell (12)](https://user-images.githubusercontent.com/34950371/149604364-14ff9e64-9ca5-4958-b6cf-25c3a93e610a.png)

### Release version

v2.11.0-Beta

### Steps to reproduce

1. Scan a "clean" video or a channel's most recent videos. I used https://www.youtube.com/watch?v=Um-rXWv_-iY as a video and https://www.youtube.com/channel/UCr_GXW2Y56hOpGchXYNqZOQ as a channel (5 most recent)
2. Use Auto mode
3. No results were found and the tool exits in 5 seconds.

### What platform are you seeing this problem on?

Windows (.py script)

**Comment by ThioJoe** [comment]
Looks like this happens when the config's log setting is not 'Ask'. I'll have to change it.

**Comment by Firecul** [comment]
> Looks like this happens when the config's log setting is not 'Ask'.

I wouldn't have even thought to test that. I need to look at this code properly at some point.

**Comment by ThioJoe** [comment]
Should be fixed with the latest commits on both branches, I'll put up a new release soon.

**Comment by Firecul** [comment]
Yip that looks good.
