### ISSUE TITLE
German comments might not be properly filtered.

### ISSUE THREAD

**Issue by Uma410** [ThioJoe/YT-Spammer-Purge#388]
### Filter Mode

Auto-Smart Mode

### Select the Problem

False Positive

### Spammer Example / Sample

https://www.youtube.com/watch?v=jXb-zSPjhPI&lc=Ugxv_nicRg4GOIKTtBh4AaABAg

### (Optional) Additional Info / Context

The comment in the sample was flagged as spam, however it is just a normal comment on a german video. The detection seems to not work so well on non-english videos.

**Comment by ThioJoe** [comment]
Hm yea I don't see why it would have even flagged that message, I'll have to investigate. I have a couple theories off the top of my head

**Comment by ThioJoe** [comment]
Ok should be fixed with the latest commit, so it will be in the next release. It actually had nothing to do with the comment being in german, just the way one of the words was being checked.
