### ISSUE TITLE
All-Unicode name got flagged

### ISSUE THREAD

**Issue by Uma410** [ThioJoe/YT-Spammer-Purge#389]
### Filter Mode

Auto-Smart Mode

### Select the Problem

False Positive

### Spammer Example / Sample

https://www.youtube.com/watch?v=FFbPN7kBOHQ&lc=Ugy7Tlxk4XhJXT9ceAB4AaABAg

**Comment by ThioJoe** [comment]
Hm yea I know why it got caught, I'll probably adjust the sensitivities for some of the checks

**Comment by ThioJoe** [comment]
Ok should be fixed with the latest commits and will be in the next release
