### ISSUE TITLE
Error code Z-3 occurs when trying to update from 2.11.0-beta2 to 2.11.0-beta3

### ISSUE THREAD

**Issue by prettybadatcoding** [ThioJoe/YT-Spammer-Purge#390]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

The title says it all.

### Release version

YOUTUBE SPAMMER PURGE VERSION 2.11.0-BETA2

### Steps to reproduce

1. Use version 2.11.0-beta2
2. Check for updates
3. Program throws the error Z-3

### What platform are you seeing this problem on?

Windows (.exe file)

### Relevant log output

```shell
File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1349, in <module>
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1306, in main
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 798, in primaryInstance
AttributeError: module 'Scripts.prepare_modes' has no attribute 'prepare_modes'
------------------------------------------------
Error Message: module 'Scripts.prepare_modes' has no attribute 'prepare_modes'

Unknown Error - Code: Z-3 occurred.
```

### Screenshots

```shell
Screenshot doesn't appear :(
```

**Comment by ThioJoe** [comment]
ah yup i know what the issue is

**Comment by ThioJoe** [comment]
The latest releases are out so this should be fixed

**Comment by prettybadatcoding** [comment]
thx!
