### ISSUE TITLE
A few possible false positives from "Steven Van Metre"

### ISSUE THREAD

**Issue by alextiming** [ThioJoe/YT-Spammer-Purge#392]
### Filter Mode

Auto-Smart Mode

### Select the Problem

False Positive

### Spammer Example / Sample

Here's a screen grab
![example](https://user-images.githubusercontent.com/1020664/149680430-4afd9045-ab6c-472d-8e71-6109e6d7b653.png)
.

### Video / Post Link

https://www.youtube.com/channel/UCRIQM-CUkxVazVPv980YZsw

### (Optional) Additional Info / Context

I scanned his last 10 videos.

**Comment by Firecul** [comment]
13, 18 and 59 are the only ones I'd consider false positives there, and that's without following their links.

I caught a few more that you did on the latest beta but most of them are prob spam too tbh
![WindowsTerminal_Windows_PowerShell (13)](https://user-images.githubusercontent.com/34950371/149680751-4d036f74-8ebc-424d-8ee3-23d6891c72ea.png)

**Comment by ThioJoe** [comment]
The program specifically looks for people who post nothing but a youtube link and no other text. Idk how people don't consider that spam

**Comment by Firecul** [comment]
> The program specifically looks for people who post nothing but a youtube link and no other text. Idk how people don't consider that spam.

Sometimes it's not, it could be a reply to someone asking for a referenced video by the creator for example. Generally, I'd look at the comment (or comment train) first before declaring it spam, I just couldn't be bothered doing so in this case. If it's a channel link or link to a short then normally it's spam from my experience.

**Comment by ThioJoe** [comment]
Alright I've decided to make it optional via config, and false by default, because that's not the first time I've seen people consider them false positives. ( a47e4b843bbab4816594bdc6f084d99740859cf5 )
