### ISSUE TITLE
MacOS Instructions OUTDATED

### ISSUE THREAD

**Issue by karolchilinski** [ThioJoe/YT-Spammer-Purge#394]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

this Instruction: python3 YouTubeSpammerPurge.py needs to replace to: python3 YTSpammerPurge.py

### Release version

2.11.0

### Steps to reproduce

1. not working 8. Now you can run the program by running: python3 YouTubeSpammerPurge.py
2. change to: 8. Now you can run the program by running: python3 YTSpammerPurge.py

### What platform are you seeing this problem on?

MacOS

**Comment by ThioJoe** [comment]
Ah yup, I've gone and updated it
