### ISSUE TITLE
Filtering: "My content is better" and other spam comments

### ISSUE THREAD

**Issue by QuentinMcCarthy** [ThioJoe/YT-Spammer-Purge#395]
### Filter Mode

Auto-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

![image](https://user-images.githubusercontent.com/36647653/149837512-a8220ac5-f054-45f5-a1d2-a9de985b8f0f.png)
![image](https://user-images.githubusercontent.com/36647653/149837523-1fc94e01-fc4d-4c2e-ad46-d84e65693e35.png)
![image](https://user-images.githubusercontent.com/36647653/149837594-84e0e58b-657f-4b00-ae9a-eebb8dc43626.png)
![image](https://user-images.githubusercontent.com/36647653/149837617-6f5a9555-3c02-4c3f-a6db-6fe0487d7462.png)

Comment chain:
https://www.youtube.com/watch?v=vs4lcY4w3lY&lc=Ugzg0Pt44rDx8bUG7Cp4AaABAg

### Video / Post Link

https://www.youtube.com/watch?v=WS3Lkc6Gzlk

### (Optional) Additional Info / Context

All the comments on the linked video that relate to "my content is better" were not detected. Any comments that used different techniques in order to get subs by "sub to me I sub to you" tactics like the upside-down text one screenshotted were also missed.
The "skip video ads" comment I am unsure if whether or not it is a spam comment, but shared it just in case.

All these comments were found in the replies of the linked comment.

**Comment by ThioJoe** [comment]
Hm I'll see about adding something for these

**Comment by ThioJoe** [comment]
Alright in the new 2.14.0-Beta1 release I've added some checks for these types of spammers
