### ISSUE TITLE
Path on ThioJoe's computer is shown in errors 

### ISSUE THREAD

**Issue by TechStudent11** [ThioJoe/YT-Spammer-Purge#404]
Before I get into this, this is version 2.10.0-Beta2. This shouldn't effect anything though.

I was using the program to report some spam on a video, and when I was done I pressed Control + C. In Python, pressing Control + C will always output a KeyboardInterrupt (aka an error). I did this and got really interesting results. When pressing the key combination, I expected to get the normal `File "C:\Users\<username>\what\ever\YouTubeSpammerPurge.py", line <some number>, in <module>`. I got that, but with a path on ThioJoe's computer?

```python
File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YouTubeSpammerPurge.py", line 4124, in <module>
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YouTubeSpammerPurge.py", line 4106, in main
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YouTubeSpammerPurge.py", line 3134, in primaryInstan
ce
```

![image](https://user-images.githubusercontent.com/76978184/150403456-6873ed11-d4ac-4436-8c74-d591fc5d00cc.png)

I'm sorry, **WHAT**

Is this a PyInstaller issue or what?

**Comment by ThioJoe** [comment]
Lol yea that's bizarre. I think it has to do with the pyinstaller spec file which it uses to build the exe. One of the fields is 'pathex' which is the absolute directory, and apparently that's not necessary so I can try taking it out. Not sure why it would show during an exception though.

**Comment by TechStudent11** [comment]
It appears part of this has been fixed (https://github.com/ThioJoe/YT-Spammer-Purge/commit/93413a54a493a494af8f59be63518f4bdebc6bcf), but that doesn't change the path issue.

**Comment by ThioJoe** [comment]
Actually I did update the pyinstaller spec file for the latest release, so it should be good now

**Comment by TechStudent11** [comment]
alright
