### ISSUE TITLE
Filtering: Harassment spam for certain YouTubers

### ISSUE THREAD

**Issue by QuentinMcCarthy** [ThioJoe/YT-Spammer-Purge#410]
### Filter Mode

Auto-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

HIS DAD IS IN H3LL BECAUSE MY CONTENT IS BETTER!
JACKSEPTICEYE'S DAD IS IN H3LL LMAO 🤣🤣🤣

Comment chain, spam found in replies:
https://www.youtube.com/watch?v=rNfFbUW4ZEM&lc=UgwBO9wBWf1vBBu_S0Z4AaABAg

### Video / Post Link

https://www.youtube.com/watch?v=rNfFbUW4ZEM

### (Optional) Additional Info / Context

These are only examples of ones that attack Jacksepticeye, but I have previously seen ones that have attacked Markiplier (over his grandfather) and other "big" YouTubers. Regardless of the attacks and their contents, the messages are still spam and should be reported for multiple reasons.

The ones listed are from only one account, but I have seen the spam being posted by numerous different accounts. I can't at this time find any of the other bot accounts or any of the other messages on Markiplier's videos or anything.

**Comment by ThioJoe** [comment]
Spammers this specific to a channel are better dealt with using the 'string search' filter mode. Though it looks like a good amount of them are actually those "my content is better" type bots, which I'm gonna be adding filters for soon.
