### ISSUE TITLE
Filtering: phone number & Message scam not detected

### ISSUE THREAD

**Issue by Oondanomala** [ThioJoe/YT-Spammer-Purge#418]
### Filter Mode

Auto-Smart Mode

### Select the Problem

Some spammers not detected

### Spammer Example / Sample

![scam](https://user-images.githubusercontent.com/87101222/151244159-eea39ce6-2e28-41a4-8001-f11d600b3976.png)

### Video / Post Link

https://www.youtube.com/channel/UCXuqSBlHAE6Xw-yeJA0Tunw/community?lc=Ugx8urOjepPyiYSDZ_94AaABAg.9RTZRk9tmEC9RVVCtbKaa7&lb=Ugxwc80uNwL727rGu194AaABCQ

### (Optional) Additional Info / Context

Scammers are still detected with duplicate checking

**Comment by ThioJoe** [comment]
Hmm yea i'll have to adjust the filters

**Comment by Rairye** [comment]
Is there a PR or something for this? I have worked on something similar and was wondering if I could take a peak.

**Comment by KendallDoesCoding** [comment]
> Is there a PR or something for this? I have worked on something similar and was wondering if I could take a peak.

I don't think there is any PR on this, but @ThioJoe is working on fixing this on localhost.

**Comment by vedurk** [comment]
I noticed something quite similar, so I guess no need for a new issue?

It was "non-matched" but detected only because of the duplicates.

![image](https://user-images.githubusercontent.com/51442956/154848294-407e1abf-ead8-4804-a6f6-812ca61166a4.png)
https://www.youtube.com/watch?v=ih_a8wmgq20&lc=Ugxpdtu7mMeOCtP2kbp4AaABAg.9YMWQIzhyYR9YN1oHe32Nf

**Comment by ThioJoe** [comment]
> I noticed something quite similar, so I guess no need for a new issue?
> 
> It was "non-matched" but detected only because of the duplicates.
> 
> ![image](https://user-images.githubusercontent.com/51442956/154848294-407e1abf-ead8-4804-a6f6-812ca61166a4.png) https://www.youtube.com/watch?v=ih_a8wmgq20&lc=Ugxpdtu7mMeOCtP2kbp4AaABAg.9YMWQIzhyYR9YN1oHe32Nf
> 
> "Sensitive smart" of course finds them

Hmm it should have caught that but now I see why it didn't. Definitely gonna have to fix that.

**Comment by ThioJoe** [comment]
Alright I finally got around to addressing this in 2.16.3. Should be much more effective at detecting whatsapp numbers
