### ISSUE TITLE
Filtering: Spammers taking a popular comment and reposting it

### ISSUE THREAD

**Issue by nick-potts** [ThioJoe/YT-Spammer-Purge#419]
### Filter Mode

Sensitive-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

![image](https://user-images.githubusercontent.com/1109914/151302478-dec4b36d-527b-47e8-a267-8177aa973b04.png)

As you can see, one popular comment is taking by bots and repeated without detection. I'd love for a simple check that takes a message with length > x and similarity > x and checking who has the earliest comment before marking all proceeding messages as spam.

### Video / Post Link

https://www.youtube.com/watch?v=ejIdvwkKInc

**Comment by nick-potts** [comment]
I'd like to add this has become an increasingly popular method used by spam commenters in the recent weeks. I believe some of them are even botting likes on their messages to get some initial traction, and then they end up receiving the most likes on said videos.

**Comment by BrandonDoesDev** [comment]
What if I were to make a filtering method that removes comments by certain text?

**Comment by DarkrDev** [comment]
What if I were to add a method that deletes comments by text? In this case, it would delete all comments with "You guys have the best bro relationship..."

**Comment by rcmaehl** [comment]
Just saw one of these today as well

![image](https://user-images.githubusercontent.com/716581/151854355-2d52fa92-3dac-481c-8509-218d2543e129.png)

**Comment by NoOverflow** [comment]
Guess you could mostly counter this by running a specific filter on the account name and not only the text comment (If that's not the current behaviour)

**Comment by StealthHydra179** [comment]
> Guess you could mostly counter this by running a specific filter on the account name and not only the text comment (If that's not the current behaviour)

https://developers.google.com/youtube/v3/docs/comments author's names can be collected with comment information and it is currently used:
https://github.com/ThioJoe/YT-Spammer-Purge/blob/cac3f8076c04e9057750c48a240c6025591bed12/Scripts/operations.py#L30

It is also passed into the filter, in which it is used:
https://github.com/ThioJoe/YT-Spammer-Purge/blob/cac3f8076c04e9057750c48a240c6025591bed12/Scripts/operations.py#L375-L384

**Comment by nick-potts** [comment]
This screenshot is a poor example. 

A lot of these comments are replicated by verified commenters with single word names, often with a mr beast logo.

**Comment by NoOverflow** [comment]
Could it be done like this then ? 
- Check if a message has been posted >1 time 
- Get the original comment (Oldest comment)
- Delete the rest ?

**Comment by nick-potts** [comment]
That's exactly how my pull request functions, except it looks for similar messages not exact duplicates

**Comment by ThioJoe** [comment]
I actually don't think it's necessary at this time to check for this. Because if a spammer copies another comment's text, that means they will have to put everything up in the username, which actually could make them easier to detect because they're more limited. I'll consider this a possibility in the future though.
