### ISSUE TITLE
[Bug]: Short link doesn't work

### ISSUE THREAD

**Issue by tretron** [ThioJoe/YT-Spammer-Purge#426]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

The shortened link (https://www.TJoe.io/api-setup) does not work to open the required page on the wiki. 

Note: I have to manually type the link since on windows 10 the CMD terminal does not allow me to copy and paste the link.

relevant software:
- Windows 10 build 19043.1466
- firefox 64 bits, 96.0.3

### Steps to reproduce

1. open the app
2. manually type the shortened website

### What platform are you seeing this problem on?

Windows (.exe file)

### Relevant log output

```shell
Hmm. We kunnen die website niet vinden.

We kunnen geen verbinding maken met de server op www.tjoe.io.

Als het adres juist is, kunt u drie andere dingen proberen:

    Probeer het later opnieuw.
    Controleer uw netwerkverbinding.
    Als u verbinding hebt maar zich achter een firewall bevindt, controleer dan of Firefox toegang heeft tot het web.
```

### Screenshots

![afbeelding](https://user-images.githubusercontent.com/15999930/152027971-f48b104c-2aa9-44ab-b62e-4ee027837125.png)

**Comment by ThioJoe** [comment]
Ah crap it's because the www. It works if you just do "TJoe.io". I probably have a DNS record wrong, I'll see what I can do

**Comment by ThioJoe** [comment]
Ok it should be fixed now, though it still might not work for a bit on your computer if your browser cached the DNS, so until it refreshes that.

**Comment by tretron** [comment]
that was fast, I also works on my end.

Keep on the good work
