### ISSUE TITLE
Filtering: (Write a short title here)

### ISSUE THREAD

**Issue by EzioPR** [ThioJoe/YT-Spammer-Purge#438]
### Filter Mode

Auto-Smart Mode

### Select the Problem

Some spammers not detected

### (Optional) If 'Other', Enter Very Short Description

Spammer named Jasmine not detected

### Spammer Example / Sample

The comment spam is the following:
"The whole truth about the coronavirus. Watch the video you will be shocked EVERYDAY.CF                                                                                                                                                                                  Let`s take the moment to appreciate how much effort he puts into the content for us..."

The EVERYDAY.CF is a link, reading the replies the following is said on said replies:
"scam scam scam DO NOT CLICK THESE LINKS JASMINE IS A SCAMMER NEVER CLICK HIS LINK"
"Political virus."

### Video / Post Link

https://www.youtube.com/watch?v=XUv6IO-9LRs

### (Optional) Additional Info / Context

This Jasmine user has been spamming multiple videos on this channel (Forbes Breaking News) and I've seen this same comment for about over a week now.

**Comment by ThioJoe** [comment]
ok I've added the domain to the filter list over on https://github.com/ThioJoe/YT-Spam-Lists

So should start getting picked up the next time everyone's filter lists download
