### ISSUE TITLE
[Bug]: OPENSSL_Uplink(00007FFE32A1CD30,08): no OPENSSL_Applink

### ISSUE THREAD

**Issue by LEx66** [ThioJoe/YT-Spammer-Purge#442]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Well, I was trying to authorize the program but, after authenticating the app through the browser I get an error `OPENSSL_Uplink(00007FFE32A1CD30,08): no OPENSSL_Applink` in the console, and the program exits

![image](https://user-images.githubusercontent.com/56795858/152044306-4c8f7cb5-c552-4161-9572-c5e0227b2880.png)

### Release version

2.14.0, 2.13.1 and 2.8.2

### Steps to reproduce

1. Setup program (client_secrets.json and login through browser)
2. read error in console

### What platform are you seeing this problem on?

Windows (.exe file)

### Relevant log output

```shell
Loading YT Spammer Purge @ 2.14.0...

Please login using the browser window that opened just now.

Waiting for authorization. See message above.
OPENSSL_Uplink(00007FFE32A1CD30,08): no OPENSSL_Applink
```

### Screenshots

![image](https://user-images.githubusercontent.com/56795858/152044306-4c8f7cb5-c552-4161-9572-c5e0227b2880.png)

**Comment by ThioJoe** [comment]
Hm are you on windows 11 by any chance? Someone else had this problem at one point: https://github.com/ThioJoe/YT-Spammer-Purge/issues/245

They basically ended up using the python version instead of the exe. It could be because of Pyinstaller which is used to package the script, apparently having a different openSSL library

**Comment by LEx66** [comment]
@ThioJoe I am on Windows 10 2004. I will try the Pyinstaller
