### ISSUE TITLE
Typo error in "Linux Installation Instructions"

### ISSUE THREAD

**Issue by mikedebian** [ThioJoe/YT-Spammer-Purge#444]
https://github.com/ThioJoe/YT-Spammer-Purge/wiki/Linux-Installation-Instructions

It is in step 3.

Finally, execute the script. Run:

    ./install.sh

---

It should say
   ./install_full.sh

**Comment by ThioJoe** [comment]
Ah yea good catch, just fixed it

**Comment by mikedebian** [comment]
So I don't create a new issue,

Under the how to run the app on linux using the command

"python3 YTSpammerPurge.py" as it states, it should perhaps be noted on that same page that when running the installation program, a new directory is created from where the script was ran (in my case ~/YT-Spammer-Purge-2.14.0) and the user should change in to that directory.

I know it is trivial as the saying goes that if a user runs Linux, these things should be self explanatory, but just in case there are less technical advanced users, this should maybe be added?
