### ISSUE TITLE
Error Code A-1

### ISSUE THREAD

**Issue by sealthedoor** [ThioJoe/YT-Spammer-Purge#453]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

first time boot up for me, i followed the istructions on the github and then suddnly `Error Code A-1: Something went wrong during authentication. Try deleting the token.pickle file.` has appeard
i have no clue how to fix this as the `token.pickle` dosent exist
am using win 11 64bit
(note: am not fully sure if this is new or not)

### Steps to reproduce

1. download the file 
2. get `client_secrets.json`
3. run

### What platform are you seeing this problem on?

Windows (.exe file)

### Relevant log output

```shell
Loading YT Spammer Purge @ 2.14.0...

Please login using the browser window that opened just now.



Traceback (most recent call last):
  File "Scripts\auth.py", line 81, in first_authentication
  File "Scripts\auth.py", line 68, in get_authenticated_service
  File "google_auth_oauthlib\flow.py", line 202, in from_client_secrets_file
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 340, in decode
json.decoder.JSONDecodeError: Extra data: line 1 column 13 (char 12)
----------------
[!!!] Error: Extra data: line 1 column 13 (char 12)
If you think this is a bug, you may report it on this project's GitHub page: https://github.com/ThioJoe/YT-Spammer-Purge/issues

Error Code A-1: Something went wrong during authentication. Try deleting the token.pickle file.
Press Enter to exit...
```

### Screenshots

![image](https://user-images.githubusercontent.com/52865223/152063115-99eac3d1-e915-465e-979f-075c86c94664.png)
![image](https://user-images.githubusercontent.com/52865223/152063182-e90f4552-a99a-4684-bd2b-21a944286b6f.png)

**Comment by ThioJoe** [comment]
Hm it's having trouble loading your json file. 

Did you by any chance make the client_secrets.json file yourself by copying and pasting into it, instead of downloading it?

**Comment by sealthedoor** [comment]
yes
thats what i did

**Comment by sealthedoor** [comment]
but now i downloaded it works
(sorry for bothering you, i made a mistake in while reading the instructions)
