### ISSUE TITLE
False positives on religious/atheists video comments

### ISSUE THREAD

**Issue by jra78** [ThioJoe/YT-Spammer-Purge#454]
### Filter Mode

Auto-Smart Mode

### Select the Problem

False Positive

### Spammer Example / Sample

All Matched Comments:

1. Chris Cortez:  1. I was not putting words in your mouth. Perhaps if you wrote your rants more specifically and coherently, I would’ve understood what you were referring to.  2. And yet the crusades, sexual abuse coverups, treatment of women & children as property, the violent eradication of all non compliant religious groups, persecution based on little to no evidence, terrorizing Jews & Muslims, burning a man for printing bibles for the masses, HEAVILY sexist views, witch hunts, “pardoning” sins for payment, imprisoning Galileo, slave owning missionaries, Indian residential schools, anti intellectualism & stagnation were all part of the Catholic Church. They didn’t exactly agree with human rights don’t you think?  3. I already know what people you believe shouldn’t “exist”. And to help enlighten you from a bigot world view: No, a gay relationship is not like pedophilia or zoophilia. A healthy relationship is based on CONSENT. In the case of a child, well, it’s a child. They’re neither physically nor mentally developed enough to have a relationship like that and if you can’t trust them to vote or drive why would you trust them to be in a sexual relationship? In the case of an animal you literally have no way of knowing what the animal is thinking or how to ask it for consent for a relationship. If you can even call it a “relationship” and not just an abuse of power dynamics. Gay people on the other hand, CAN have a relationship based on consent. They’re just regular people like us who were [Comment Truncated by YT SPammer Purge]
—————————————————————————————————————————————————————————————————————————————————————————————
     > Direct Link: https://www.youtube.com/watch?v=P_7I8CNZkiY&lc=UgzARROHiLE2hL7kgxN4AaABAg.9XcxKgk0e0w9XdE3-UUY5e
     > Author Channel ID: UC5lYhvAkGCT3PEbMMVfAcaQ
=============================================================================================

2. Chris Cortez:  1. What do you mean it’s “self evident” that the guy wasn’t a real Christian? People can genuinely believe in something all their life and deconstruct after finding something wrong with it. Perhaps if you told me what you think a “real Christian” is I could have a better understanding of what you’re saying. 2. Exactly what rights existed in the 13th century? The idea of human rights didn’t really take off until the enlightenment period which was roughly in the 1700s.  3. What do you mean that liberalism makes rights “pre eminent over all things, even truth.” Are you implying that some people don’t deserve rights?
—————————————————————————————————————————————————————————————————————————————————————————————
     > Direct Link: https://www.youtube.com/watch?v=P_7I8CNZkiY&lc=UgzARROHiLE2hL7kgxN4AaABAg.9XcxKgk0e0w9Xd7HiF7rUe
     > Author Channel ID: UC5lYhvAkGCT3PEbMMVfAcaQ
=============================================================================================

3. Chris Cortez:  So he admits that he’s against religious freedom, something that is not only a basic human right but something that the American founders SPECIFICALLY put in the constitution because they realized how inflexible, corrupt, and inefficient state mandated religions are. Even Christians back then accept it because they didn’t want to end up like England at the time. It’s actually interesting watching these Christian Nationalists ignore and rewriting entire history in their own heads in order to justify their prejudices and supremacist views.
—————————————————————————————————————————————————————————————————————————————————————————————
     > Direct Link: https://www.youtube.com/watch?v=P_7I8CNZkiY&lc=UgzKUHW3q_FyE_x6nCF4AaABAg
     > Author Channel ID: UC5lYhvAkGCT3PEbMMVfAcaQ
=============================================================================================

4. Chris Cortez:  @The Pale Galilean Are you listening to yourself? You are literally advocating a supremacist mindset and despite what you claim, your ideas sound very fitting for a Christian theocracy. You’re also ignoring all the atrocities I listed above and those are just the ones that came off my tongue. Prejudice, arrogance, brutality, racism, pride and supremacism will continue to exist so long as people like you are there to excuse and justify it. We need to learn from the mistakes of the past and build a better world through compassion, learning, patience, justice and acceptance, not regressing back to ignorant tribalism. Anyway I’m tired of arguing with you. Try not to be bigot and please treat other people with respect. Bye.
—————————————————————————————————————————————————————————————————————————————————————————————
     > Direct Link: https://www.youtube.com/watch?v=P_7I8CNZkiY&lc=UgwG929dSIXW734BRNZ4AaABAg.9XcvB1DX__z9XdMtMj5FcF
     > Author Channel ID: UC5lYhvAkGCT3PEbMMVfAcaQ
=============================================================================================

5. Chris Cortez:  @The Pale Galilean   “Sacred cow?” Wow very creative wording. What really makes you a bigot are your views on homosexuality and your belief that if everyone simply abandoned their own cultures to convert to (your version of) Christianity, it would somehow make the world a better place. Also, I don’t need “qualifications” to speak my mind, especially to someone who values regressive self- destructive dogma over actual human wellbeing. The fact that you think people need “qualifications” to think or speak on a subject kinda exposes how narrow minded your views are.
—————————————————————————————————————————————————————————————————————————————————————————————
     > Direct Link: https://www.youtube.com/watch?v=P_7I8CNZkiY&lc=UgwG929dSIXW734BRNZ4AaABAg.9XcvB1DX__z9XdIn9O5H8J
     > Author Channel ID: UC5lYhvAkGCT3PEbMMVfAcaQ
=============================================================================================

6. Chris Cortez:  @Andrew Dickson Considering his bigoted comments, rejection of “liberalism”, certainty of his “Truth” *tm, and the fact that he’s in agreement with the pastor in the video, I think it’s safe to say he wants an authoritarian Christian supremacist theocracy.
—————————————————————————————————————————————————————————————————————————————————————————————
     > Direct Link: https://www.youtube.com/watch?v=P_7I8CNZkiY&lc=UgwG929dSIXW734BRNZ4AaABAg.9XcvB1DX__z9XdFE-PNAEj
     > Author Channel ID: UC5lYhvAkGCT3PEbMMVfAcaQ
=============================================================================================

7. Chris Cortez:  @The Pale Galilean  1. I was not putting words in your mouth. Perhaps if you wrote your rants more specifically and coherently, I would’ve understood what you were referring to.  2. And yet the crusades, sexual abuse coverups, treatment of women & children as property, the violent eradication of all non compliant religious groups, persecution based on little to no evidence, terrorizing Jews & Muslims, burning a man for printing bibles for the masses, HEAVILY sexist views, witch hunts, “pardoning” sins for payment, imprisoning Galileo, slave owning missionaries, Indian residential schools, anti intellectualism & stagnation were all part of the Catholic Church. They didn’t exactly agree with human rights don’t you think?  3. I already know what people you believe shouldn’t “exist”. And to help enlighten you from a bigot world view: No, a gay relationship is not like pedophilia or zoophilia. A healthy relationship is based on CONSENT. In the case of a child, well, it’s a child. They’re neither physically nor mentally developed enough to have a relationship like that and if you can’t trust them to vote or drive why would you trust them to be in a sexual relationship? In the case of an animal you literally have no way of knowing what the animal is thinking or how to ask it for consent for a relationship. If you can even call it a “relationship” and not just an abuse of power dynamics. Gay people on the other hand, CAN have a relationship based on consent. They’re just regular peop[Comment Truncated by YT SPammer Purge]
—————————————————————————————————————————————————————————————————————————————————————————————
     > Direct Link: https://www.youtube.com/watch?v=P_7I8CNZkiY&lc=UgwG929dSIXW734BRNZ4AaABAg.9XcvB1DX__z9XdDZ1Hft3s
     > Author Channel ID: UC5lYhvAkGCT3PEbMMVfAcaQ
=============================================================================================

8. Chris Cortez:  @The Pale Galilean 1. What do you mean it’s “self evident” that the guy wasn’t a real Christian? People can genuinely believe in something all their life and deconstruct after finding something wrong with it. Perhaps if you told me what you think a “real Christian” is I could have a better understanding of what you’re saying. 2. Exactly what rights existed in the 13th century? The idea of human rights didn’t really take off until the enlightenment period which was roughly in the 1700s.  3. What do you mean that liberalism makes rights “pre eminent over all things, even truth.” Are you implying that some people don’t deserve rights?
—————————————————————————————————————————————————————————————————————————————————————————————
     > Direct Link: https://www.youtube.com/watch?v=P_7I8CNZkiY&lc=UgwG929dSIXW734BRNZ4AaABAg.9XcvB1DX__z9Xd76VNzBh9
     > Author Channel ID: UC5lYhvAkGCT3PEbMMVfAcaQ
=============================================================================================

9. Chris Cortez:  @The Pale Galilean Seriously? The generic “yOu WeReN’t A REAL ChRiStIaN” argument? (And that depends entirely on your definition of “True” Christian which other denominations would disagree with) Also could you be more specific on “liberalism”? Liberalism is the philosophy of individual rights, civil liberties, democracy, and consent of the governed. By saying you’ve rejected liberalism in general, you are quite literally saying you have rejected all of the above. Liberalism also makes up the foundational ideal of democracies and founded nations like the US. Additionally, I really hope you don’t actually mean to support his idea of a Christian supremacist theocracy. I don’t think I should need to explain why that’s a bad thing.
—————————————————————————————————————————————————————————————————————————————————————————————
     > Direct Link: https://www.youtube.com/watch?v=P_7I8CNZkiY&lc=UgwG929dSIXW734BRNZ4AaABAg.9XcvB1DX__z9XczqVdpE1z
     > Author Channel ID: UC5lYhvAkGCT3PEbMMVfAcaQ
=============================================================================================

10. Chris Cortez:  It’s Orwellian doublethink and cognitive dissonance. War is peace, slavery is freedom, genocide is love, faith is fact, fear is hope, etc. And let’s not forget demonizing pride while claiming that they’re morally and culturally superior to every other religious group and culture. Additionally thinking every non Christian on Earth is either “rejecting the truth”, being manipulated by Satan, or is just pure evil 😑 because apparently it’s impossible to be a decent person without being Christian.
—————————————————————————————————————————————————————————————————————————————————————————————
     > Direct Link: https://www.youtube.com/watch?v=P_7I8CNZkiY&lc=UgwKIPDWCYXIuYh4DUZ4AaABAg.9Xcu0dnnojx9XcwVB5nPFm
     > Author Channel ID: UC5lYhvAkGCT3PEbMMVfAcaQ
=============================================================================================

11. Chris Cortez:  So he admits that he’s against religious freedom, something that is not only a basic human right but something that the American founders SPECIFICALLY put in the constitution because they realized how inflexible, corrupt, and inefficient state mandated religions are. Even Christians back then accept it because they didn’t want to end up like England at the time. It’s actually interesting watching these Christian Nationalists ignore and rewriting entire history in their own heads in order to justify their prejudices and supremacist views.
—————————————————————————————————————————————————————————————————————————————————————————————
     > Direct Link: https://www.youtube.com/watch?v=P_7I8CNZkiY&lc=UgzbRah7QBwFu2HleLZ4AaABAg.9Xctx-m_03T9XcyNIsKb_g
     > Author Channel ID: UC5lYhvAkGCT3PEbMMVfAcaQ
=============================================================================================

### Video / Post Link

https://www.youtube.com/watch?v=P_7I8CNZkiY

**Comment by TechStudent11** [comment]
I think it tagged them because they either weren't related to the video or they spammed it.

**Comment by jra78** [comment]
There is duplicate text so probably that why it is detected. I was little bit too fast to put this here, but oh well...

**Comment by TechStudent11** [comment]
It was also spammed by the same person (Chris Cortez, UC5lYhvAkGCT3PEbMMVfAcaQ), so it makes sense that they were all flagged.

**Comment by KendallDoesCoding** [comment]
It could have also tagged them because they couldve copied another comment from the the video, which was genuine and this is a spammer? It's weird that all the comments you stated were from (Chris Cortez, UC5lYhvAkGCT3PEbMMVfAcaQ)

**Comment by ThioJoe** [comment]
Yea I don't really consider duplicate matches to be false positives, since it's basically working as intended.

In the 2.15 beta it will distinguish the duplicates from the matches better. For some reason the current 2.15 beta doesn't actually detect this guy as being duplicate for some reason, so that might be a bug I'll have to work out though.
