### ISSUE TITLE
[Bug]: Choosing "Hold For Review" on comments older than 60 days effectively removes them

### ISSUE THREAD

**Issue by JTHicks26** [ThioJoe/YT-Spammer-Purge#457]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

I scanned a 1 year old video on my channel, and chose the "Hold For Review" option so that I could view the users' accounts before deciding whether or not to remove the comments. However, because the comments were all older than 60 days they never showed up in the "Held for review" section in YT Studio, effectively removing them.

This isn't really a bug with the program logic, but it might be helpful for the program (if it detects comments older than 60 days) to prompt the user that those won't show up as expected in the "Held for review" section in YT Studio and ask if the user is sure they want to continue.

Side note: I'm here from the LTT video and this is an awesome tool, thank you for making it! :)

![image](https://user-images.githubusercontent.com/37845757/152069476-faf90455-b0b8-4047-8124-9c5ed24df32f.png)

### Release version

2.14.0

### Steps to reproduce

1. Scan a video with spam comments older than 60 days.
2. Choose "Hold For Review"
3. Check the "Held for review" section in YT Studio, any of the comments older than 60 days will not appear.

### What platform are you seeing this problem on?

Windows (.exe file)

### Relevant log output

```shell
IDs of the comments on my video which were "Held for review" but never appeared in YT Studio:

IDs of Matched Comments: [ UgwirZ5QVp8VNvJxB6V4AaABAg.9HYO7Fsi_vV9HYZrzAxEsB, Ugyb0fheZsjhq072dSV4AaABAg.9HYNIrgBAhu9HYZttyHPrC, UgzuwRTaeEWreoqaUGB4AaABAg.9HYCisN8kmA9HYZwdVEce8, UgyKMyE2jwzRa9jqc6N4AaABAg.9HYCUZZXfWD9HYZyBHhbJG, Ugw-LGAyss5sEsakYFZ4AaABAg.9HYBEPU64pt9HYZzJLpQqS, UgyHj4nb2s6mmzPtB4d4AaABAg.9HS56dzhziZ9HSjXkCc6Cc, UgwRAFKJbN7IljB2N554AaABAg.9HRi1wK3Fbx9HSjhhpcs2A, UgyB7W3Y-R4XmwnHub14AaABAg.9HRH3uD0jr59HSjruk4DCu, UgwTvKQg6OkzmxleJUh4AaABAg.9HRAJxBuT7-9HSkWgh1ARt, UgxCDdPyAIM2XUcUH0h4AaABAg.9HOv2orjl9H9HSllpUjBGM, UgxCDdPyAIM2XUcUH0h4AaABAg.9HOv2orjl9H9HSkO8j2upG, UgxU6Ch9MzflQUMY3FB4AaABAg.9HAyU2yyAeF9HSlInSRdad, Ugz7qICFzgip8vbf3rF4AaABAg.9H8Kye9a6im9HSkr7kuO93, Ugx9rs5MOMPRAOFLmwZ4AaABAg.9H7M7kuxzcE9HSjc6q6dn2, UgxZmZ9d3Pi0lVuNUMN4AaABAg.9GfgbFt6GCF9HSjEtlAuwQ, UgxgCMysBekNmaKEcXt4AaABAg.9HNk6o42hb79HOBB7lU_bt, UgxgCMysBekNmaKEcXt4AaABAg.9HNk6o42hb79HNvaUVVqSo, Ugw_9hTIy-eOzr3WMfd4AaABAg.9HNb1R8sjEU9HNvYDOn598, Ugx2Kc0-Wwndby1k_Sx4AaABAg.9HNBVstzciR9HNviDtvKK8, Ugz3cfQ3g9rSB3RH7Cp4AaABAg.9HMCqwEDCoV9HNvTc-hV0e, Ugww5Ei2i3aQgF9fgWZ4AaABAg.9HKh19vg2gV9HNvLemTGhj, Ugxy8akjP_7sFglfjpN4AaABAg.9H8niqoSIbp9HNvluH0TTd ]
```

### Screenshots

![image](https://user-images.githubusercontent.com/37845757/152069722-403c1fe9-7611-4038-a4e7-3d49e5cd9b86.png)

**Comment by ThioJoe** [comment]
Hm that's definitely something I hadn't considered. I'll have to add a message or something.

**Comment by ThioJoe** [comment]
So after some experimenting, the threshold must be longer than 60 days, because I held some comments that were 3 months (90+ days) old and they still showed up in held for review

<img width="424" alt="3 months" src="https://user-images.githubusercontent.com/12518330/152272036-938f2363-36f8-43ea-be91-2d366b4c37f0.png">

**Comment by KendallDoesCoding** [comment]
@JTHicks26 How old was the scam comment? 60 days old?

**Comment by JTHicks26** [comment]
They were all just over a year old, from December 2020. It could be something else entirely that kept them from appearing, from the message in YouTube Studio I just assumed it was because of their age. Here's the log file from the run, although obviously none of the comments are visible on YouTube anymore.

[Spam_Log_2022-02-01_17-18-52.rtf.txt](https://github.com/ThioJoe/YT-Spammer-Purge/files/7996946/Spam_Log_2022-02-01_17-18-52.rtf.txt)

**Comment by KendallDoesCoding** [comment]
> They were all just over a year old, from December 2020. It could be something else entirely that kept them from appearing, from the message in YouTube Studio I just assumed it was because of their age. Here's the log file from the run, although obviously none of the comments are visible on YouTube anymore.
(Very NSFW language in the comments in this log file, be warned) [Spam_Log_2022-02-01_17-18-52.rtf.txt](https://github.com/ThioJoe/YT-Spammer-Purge/files/7996946/Spam_Log_2022-02-01_17-18-52.rtf.txt)

Yeah, it couldve been something else, as there are no other issues about this, glad you managed to delete the comments from the video! Requesting you to close this issue.

**Comment by Firecul** [comment]
> Very NSFW language in the comments in this log file

Well, you weren't wrong. 

At least the option to restore the comments is there, **if** you wanted to of course.
