### ISSUE TITLE
[Bug]: X-5 after mass-report

### ISSUE THREAD

**Issue by BenDundon** [ThioJoe/YT-Spammer-Purge#458]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Ran Auto-Smart on a popular youtuber's channel. Came up with a few _thousand_ hits. When I tried to mass-report, it got most of the way through before giving this error

```
Comments Reported! If no error messages were displayed, then everything was successful.
Traceback (most recent call last):
  File "/home/ben/.local/bin/YT-Spammer-Purge/YTSpammerPurge.py", line 1507, in <module>
    main()
  File "/home/ben/.local/bin/YT-Spammer-Purge/YTSpammerPurge.py", line 1484, in main
    continueRunning = primaryInstance(miscData)
  File "/home/ben/.local/bin/YT-Spammer-Purge/YTSpammerPurge.py", line 1441, in primaryInstance
    logging.write_log_completion_summary(current, exclude, logMode, banChoice, deletionModeFriendlyName, rtfExclude, plaintextExclude)
TypeError: write_log_completion_summary() takes 4 positional arguments but 7 were given
------------------------------------------------
Unknown Error - Code: X-5 occurred. This is probably my fault,
please a bug report on the GitHub issues page, and include the above error info.
```

Which seems to suggest a successful report, but gave an error anyway.

### Release version

2.14.1

### Steps to reproduce

1. Run auto-smart against Mr Beast Gaming (I figured this would be a great place to find some spam), using the last 3 videos
2. Try to report all found comments 
3. Succeed(?) with an error

### What platform are you seeing this problem on?

Linux (can also be ChromeOS)

**Comment by ThioJoe** [comment]
Ah yea, I'm still working on 14.1, it's not actually a release yet.
I'd recommend downloading the script and stuff from the actual release page
