### ISSUE TITLE
[Bug]: After daily quota is over the app gives unknow error

### ISSUE THREAD

**Issue by sreejen** [ThioJoe/YT-Spammer-Purge#461]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Well, I was trying to scan any channel but my quota is already reached 10K the app have traceback

### Release version

2.14.0

### Steps to reproduce

1. Finish up the quota for the day
2. Scan a channel
3. There will be a trace back.

### What platform are you seeing this problem on?

Windows (.exe file)

### Relevant log output

```shell
Enter a channel ID or Link to scan recent videos from
   > If scanning your own channel, just hit Enter

Enter Here: UC1WXDjMBw6m439JAcdzX9kQ
Traceback (most recent call last):
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1478, in <module>
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1455, in main
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 578, in primaryInstance
  File "Scripts\validation.py", line 158, in validate_channel_id
    response = auth.YOUTUBE.channels().list(part="snippet", id=isolatedChannelID).execute()
  File "googleapiclient\_helpers.py", line 131, in positional_wrapper
  File "googleapiclient\http.py", line 922, in execute
  File "googleapiclient\http.py", line 221, in _retry_request
  File "googleapiclient\http.py", line 190, in _retry_request
  File "google_auth_httplib2.py", line 218, in request
  File "httplib2\__init__.py", line 1725, in request
  File "httplib2\__init__.py", line 1441, in _request
  File "httplib2\__init__.py", line 1364, in _conn_request
  File "http\client.py", line 1276, in request
  File "http\client.py", line 1322, in _send_request
  File "http\client.py", line 1271, in endheaders
  File "http\client.py", line 1031, in _send_output
  File "http\client.py", line 992, in send
  File "ssl.py", line 1236, in sendall
  File "ssl.py", line 1205, in send
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2384)
------------------------------------------------
Error Message: EOF occurred in violation of protocol (_ssl.c:2384)

Unknown Error - Code: Z-3 occurred. If this keeps happening, consider posting a bug report
on the GitHub issues page, and include the above error info.
Short Link: TJoe.io/bug-report
```

**Comment by ThioJoe** [comment]
Kinda weird, usually if the quota is up it will just say that. I'll have to look more into it

**Comment by hvn2k** [comment]
> > Kinda weird, usually if the quota is up it will just say that. I'll have to look more into it
> 
> Yes, for @Brayman30, it gave this when the quota was up (it wasnt up but youtube api thought it was) #466
> 
> ```
> ===================== YOUTUBE SPAMMER PURGE v2.14.2 =====================
> =========== https://github.com/ThioJoe/YT-Spammer-Purge ===========
> ================= Author: ThioJoe - YouTube.com/ThioJoe ================
> 
> Purpose: Lets you scan for spam comments and mass-delete them all at once
> 
> NOTE: It's probably better to scan individual videos, because you can scan all those comments,
>       but scanning your entire channel must be limited and might miss older spam comments.
> You will be shown the comments to confirm before they are deleted.
> Traceback (most recent call last):
>   File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1513, in <module>
>   File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 290, in main
>   File "Scripts\auth.py", line 113, in get_current_user
>   File "Scripts\auth.py", line 111, in fetch_user
>   File "googleapiclient\_helpers.py", line 131, in positional_wrapper
>   File "googleapiclient\http.py", line 937, in execute
> googleapiclient.errors.HttpError: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/channels?part=snippet&mine=true&fields=items%2Fid%2Citems%2Fsnippet%2Ftitle&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">
> ------------------------------------------------
> Error Message: <HttpError 403 when requesting https://youtube.googleapis.com/youtube/v3/channels?part=snippet&mine=true&fields=items%2Fid%2Citems%2Fsnippet%2Ftitle&alt=json returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "[{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]">
> Status Code: 403
>     Reason: quotaExceeded
> 
> Error: You have exceeded the YouTube API quota. To do more scanning you must wait until the quota resets.
>  > There is a daily limit of 10,000 units/day, which works out to around reporting 10,000 comments/day.
>  > You can check your quota by searching 'quota' in the google cloud console.
> Solutions: Either wait until tomorrow, or create additional projects in the cloud console.
>   > Read more about the quota limits for this app here: TJoe.io/api-limit-info
> 
> An 'HttpError' was raised. This is sometimes caused by a remote server error. See the error info above.
> If this keeps happening, consider posting a bug report on the GitHub issues page, and include the above error info.
> Short Link: TJoe.io/bug-report
> 
> Press Enter to Exit...
> ```

I saw a video where someone used multiple instances of the Google API, this was the [Tutorial](https://youtu.be/SxOgJKg-eZg?t=239)

**Comment by somecoderithink** [comment]
The same issue is also on #466

**Comment by KendallDoesCoding** [comment]
> The same issue is also on #466

ig this issue should be closed in that case.

**Comment by ThioJoe** [comment]
Looking back I think the original error is related to SSL and not the quota, and might have just been coincidental
