### ISSUE TITLE
Filtering: Investment spam

### ISSUE THREAD

**Issue by ddesborough** [ThioJoe/YT-Spammer-Purge#468]
### Filter Mode

Auto-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

direct link to one comment in the thread that was caught: https://www.youtube.com/watch?v=KKorSeSCTNc&lc=Ugz82kzHlntz3BES4b14AaABAg.9Xsz3XJdOb39XtDuYehU3K 

The whole comment thread is spam with lots of spam bots. I had this same sort of thread show up on one of my own videos a while back. 
![filter-suggestion](https://user-images.githubusercontent.com/58405537/152084713-3c6fea30-5e62-439e-8d9e-fff09272d2e1.png)

### Video / Post Link

https://youtu.be/KKorSeSCTNc

**Comment by ThioJoe** [comment]
Yea for these types of spam threads I need to still add functionality to detect them. In the mean time, you can report the names they use in the threads in this repository: https://github.com/ThioJoe/YT-Spam-Lists

So for example 'Mr Lawrence Tom' will go onto the list to be detected from now on.

**Comment by ddesborough** [comment]
Will do. Great work and thank you for this! I immediately downloaded it after seeing the Linus video.

**Comment by KendallDoesCoding** [comment]
Created a issue to report these spam commenters names there: https://github.com/ThioJoe/YT-Spam-Lists/issues/78

**Comment by KendallDoesCoding** [comment]
@ddesborough This should be fixed by commit 991916926150a1a50084819d0ae0619c80f0c277 in https://github.com/ThioJoe/YT-Spam-Lists/issues/78, requesting you to close this issue thread.

**Comment by ddesborough** [comment]
Closing!
