### ISSUE TITLE
WinError 10060

### ISSUE THREAD

**Issue by gerthubr** [ThioJoe/YT-Spammer-Purge#471]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [X] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

I was trying to boot up the program after jumping through countless hoops, but when it's finally time to boot up, the thing keeps reporting ''WinError 10060'' along with some other stuff, it recommended me to delete token.pickle, but that did nothing. Can anyone please help me? Thank you in advance.

### Release version

2.14.2

### Steps to reproduce

1.Open the program
2. Wait for it to load
3.Tasa, there it is

### What platform are you seeing this problem on?

Windows (.exe file)

### Relevant log output

```shell
File "Scripts\auth.py", line 81, in first_authentication
  File "Scripts\auth.py", line 74, in get_authenticated_service
  File "googleapiclient\_helpers.py", line 131, in positional_wrapper
  File "googleapiclient\discovery.py", line 287, in build
  File "googleapiclient\discovery.py", line 420, in _retrieve_discovery_doc
  File "googleapiclient\_helpers.py", line 131, in positional_wrapper
  File "googleapiclient\http.py", line 922, in execute
  File "googleapiclient\http.py", line 221, in _retry_request
  File "googleapiclient\http.py", line 190, in _retry_request
  File "httplib2\__init__.py", line 1725, in request
  File "httplib2\__init__.py", line 1441, in _request
  File "httplib2\__init__.py", line 1363, in _conn_request
  File "httplib2\__init__.py", line 1153, in connect
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
```

**Comment by ThioJoe** [comment]
Do you have something that might be blocking it?

**Comment by KendallDoesCoding** [comment]
> Do you have something that might be blocking it?

Yeah, do you use a antivirus or something for example @gerthubr

**Comment by KendallDoesCoding** [comment]
@gerthubr Once you paste the client_secrets.json file, I dont remember but I think it opens a link in your browser to authenticate, so if you have something blocking the link from opening those errors just mean the link cant open.

**Comment by gerthubr** [comment]
I don't think anything was blocking it, i was able to authenticate it. the problem starts when everything is set up and when i try to run the program

**Comment by KendallDoesCoding** [comment]
> ```shell
> authentication
> ```

That's weird coz it seems to be a authentication problem with Google/Youtube API.

**Comment by ThioJoe** [comment]
This is most likely an issue related to your network environment or computer configuration, I'd recommend just looking up that error message, such as: https://stackoverflow.com/questions/15820739/python-urlerror-urlopen-error-errno-10060

**Comment by Firecul** [comment]
Complete guess => Did you definitely install the python requirements?

**Comment by gerthubr** [comment]
i use the exe, does it need anything else?

**Comment by Firecul** [comment]
> i use the exe, does it need anything else?

No, it shouldn't. I must not have read that part sorry

**Comment by kingbrucelee** [comment]
I have the exact same problem and did the same things. Anyone had luck to deal with that? My internet seems to work fine. And my computer does not have any extraordinary things.
