### ISSUE TITLE
[Bug]: (When app is checking for updates it gives me an error)

### ISSUE THREAD

**Issue by superoloyt** [ThioJoe/YT-Spammer-Purge#480]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

When app was checking for updates it gave me this error:
![image](https://user-images.githubusercontent.com/69038702/152121871-65cd3ce1-d6d9-46b0-b27d-82343e656f91.png)
It should just open and ask me for my channel id

### Release version

2.14.2

### Steps to reproduce

1. Just open the program idk

### What platform are you seeing this problem on?

Windows (.exe file)

### Relevant log output

```shell
Traceback (most recent call last):
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1513, in <module>
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 168, in main
  File "Scripts\files.py", line 617, in copy_asset_file
  File "shutil.py", line 256, in copyfile
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\PC\\Desktop\\scammercommentsdelete\\SpamPurge_Resources\\Spam_Lists\\SpamDomainsList.txt'
------------------------------------------------
Error Message: [Errno 13] Permission denied: 'C:\\Users\\PC\\Desktop\\scammercommentsdelete\\SpamPurge_Resources\\Spam_Lists\\SpamDomainsList.txt'

Unknown Error - Code: Z-3 occurred. If this keeps happening, consider posting a bug report
on the GitHub issues page, and include the above error info.
Short Link: TJoe.io/bug-report

 Press Enter to Exit...
```

### Screenshots

![image](https://user-images.githubusercontent.com/69038702/152122295-96183d69-72c2-4fab-85be-cc7d67af19d9.png)

**Comment by ThioJoe** [comment]
This means the program does not have the file permissions to copy the file for whatever reason. Maybe try putting everything in the 'My Documents' (or just called 'Documents' these days) folder, instead of the Desktop.

**Comment by superoloyt** [comment]
> This means the program does not have the file permissions to copy the file for whatever reason. Maybe try putting everything in the 'My Documents' (or just called 'Documents' these days) folder, instead of the Desktop.

Unfortunately it doesn't work either. The same error

**Comment by superoloyt** [comment]
oh I have two disks on my computer C and D and when I put it on the D drive it worked fine so I will close this issue with this comment. Thank you for help :)
