### ISSUE TITLE
client_secrets.json file not found Error at startup

### ISSUE THREAD

**Issue by KendallDoesCoding** [ThioJoe/YT-Spammer-Purge#481]
### Discussed in https://github.com/ThioJoe/YT-Spammer-Purge/discussions/440

<div type='discussions-op-text'>

<sup>Originally posted by **wuser200** February  2, 2022</sup>
I had a json file named client_secrets.json and made a Google Cloud Platform Project and it's showing me this:

                  ----- [!] Error: client_secrets.json file not found -----
         ----- Did you create a Google Cloud Platform Project to access the API? -----
         > For instructions on how to get an API key, visit: www.TJoe.io/api-setup

         > (Non-shortened Link: https://github.com/ThioJoe/YT-Spammer-Purge/wiki/Instructions:-Obtaining-an-API-Key)

         Press Enter to Exit...

Please tell me how to fix this</div>

**Comment by UnknownCrafts** [comment]
did you put the json file in the same folder as the exe?

**Comment by wuser200** [comment]
yes

**Comment by wuser200** [comment]
i did

**Comment by ThioJoe** [comment]
Do you have viewing file extensions enabled? If not, if you named the file "client_secrets.json" for example, it may actually be called "client_secrets.json.json" behind the scenes. Try just calling it "client_secrets". 

Or, enable file extensions in explorer to see: https://www.howtogeek.com/205086/beginner-how-to-make-windows-show-file-extensions/

**Comment by KendallDoesCoding** [comment]
@wuser200 Please share a screenshot of the file selected and properties opened, and we will be able to see the file extension there, if you want too.

**Comment by ThioJoe** [comment]
@wuser200 To be clear, DO NOT screenshot the contents of the JSON file. 

Also if you are able to solve the problem with what I suggested, there's no need to post a screenshot or anything, just say that it worked.

**Comment by UnknownCrafts** [comment]
File pickers should help in these situations. please look at my pull request and let me know if it is a good way of addressing these types of issues.

**Comment by ThioJoe** [comment]
This should be fixed with release 2.14.3 and https://github.com/ThioJoe/YT-Spammer-Purge/commit/e16ebb9d520e65f12952cfc27c69272233b8bd65
Unless we hear back that the problem was something different than I described.

**Comment by KendallDoesCoding** [comment]
> @wuser200 To be clear, DO NOT screenshot the contents / inside of the JSON file.
> 
> Also if you are able to solve the problem with what I suggested, there's no need to post a screenshot or anything, just say that it worked.

Yes, I meant to say just share a screenshot of the file properties for us to see the extension, if the above mentioned by you didnt work but thanks for this disclaimer!

**Comment by KendallDoesCoding** [comment]
@wuser200 Please let me know if this issue has been resolved, and will close the issue thread accordingly.

**Comment by ThioJoe** [comment]
Gonna assume it's fixed

**Comment by wuser200** [comment]
> Do you have viewing file extensions enabled? If not, if you named the file "client_secrets.json" for example, it may actually be called "client_secrets.json.json" behind the scenes. Try just calling it "client_secrets".
> 
> Or, enable file extensions in explorer to see: https://www.howtogeek.com/205086/beginner-how-to-make-windows-show-file-extensions/

It worked
