### ISSUE TITLE
Filtering: HL2 Project Beta channel scan shows all false positives

### ISSUE THREAD

**Issue by UAVXP** [ThioJoe/YT-Spammer-Purge#482]
### Filter Mode

Auto-Smart Mode

### Select the Problem

False Positive

### Spammer Example / Sample

The channel I've scanned is https://www.youtube.com/channel/UCSmeXFiBOxnhIHXN-aS2TTQ

None of these 16 "spam" comments found at this channel's videos are actually spam:
https://www.youtube.com/watch?v=hiVpY2MwVac&lc=UgyXvHt72cyFIfvoZ6B4AaABAg.9HBEdJdCnws9Q33z9g30Pu
https://www.youtube.com/watch?v=hiVpY2MwVac&lc=UgwnjoT0mODDp6Ss3vx4AaABAg.9CdIis7UHLP9Q341DwdaUa
https://www.youtube.com/watch?v=hiVpY2MwVac&lc=Ugw8_HAc24OpRMCYbKF4AaABAg.9AGWDO-zxwk9Q33pO2lhEK
https://www.youtube.com/watch?v=hiVpY2MwVac&lc=UgySGwJwprCrZ_OsJpl4AaABAg.96vzF2cqng29Q33vMybFRM
https://www.youtube.com/watch?v=hiVpY2MwVac&lc=UgwKPphnkPwNPHEdUFN4AaABAg.96vvZvv9JLM9QAhpsv9QUI
https://www.youtube.com/watch?v=hiVpY2MwVac&lc=UgwKPphnkPwNPHEdUFN4AaABAg.96vvZvv9JLM9QAEKDvKeeF
https://www.youtube.com/watch?v=hiVpY2MwVac&lc=UgwKPphnkPwNPHEdUFN4AaABAg.96vvZvv9JLM9QA1KHSJEmX
https://www.youtube.com/watch?v=hiVpY2MwVac&lc=UgwKPphnkPwNPHEdUFN4AaABAg.96vvZvv9JLM9Q9mWvuePPW
https://www.youtube.com/watch?v=hiVpY2MwVac&lc=UgwKPphnkPwNPHEdUFN4AaABAg.96vvZvv9JLM9Q9_ApPF0fk
https://www.youtube.com/watch?v=hiVpY2MwVac&lc=UgwKPphnkPwNPHEdUFN4AaABAg.96vvZvv9JLM9Q9WqmKlBr9
https://www.youtube.com/watch?v=hiVpY2MwVac&lc=UgwKPphnkPwNPHEdUFN4AaABAg.96vvZvv9JLM9Q9BXH4y5fJ
https://www.youtube.com/watch?v=hiVpY2MwVac&lc=UgwKPphnkPwNPHEdUFN4AaABAg.96vvZvv9JLM9Q8KiwL4S2a
https://www.youtube.com/watch?v=hiVpY2MwVac&lc=UgwKPphnkPwNPHEdUFN4AaABAg.96vvZvv9JLM9Q33tHdT_Vq
https://www.youtube.com/watch?v=p_mTNjXdStY&lc=Ugz6WejXu4QEjMjqtp14AaABAg
https://www.youtube.com/watch?v=KWT9EWOZUms&lc=UgxOI6TgwOdGVpiuvHN4AaABAg
https://www.youtube.com/watch?v=KWT9EWOZUms&lc=Ugh2YU3iWxz4G3gCoAEC.8V3D8vrOX_199uDESpwEL8

### (Optional) Additional Info / Context

Spam log here: [Spam_Log_2022-02-02_12-36-02.zip](https://github.com/ThioJoe/YT-Spammer-Purge/files/7985691/Spam_Log_2022-02-02_12-36-02.zip)

**Comment by EthanHindmarsh** [comment]
"41K subs with no videos at all" seems like a spam username to me, I don't know
"sipeB" is spamming a bunch of links, I'm not sure how I'd feel about calling it a false positive

**Comment by UAVXP** [comment]
I mean, the comments themselves are pretty harmless and just leading to Wikipedia

**Comment by EthanHindmarsh** [comment]
> I mean, the comments themselves are pretty harmless and just leading to Wikipedia

Yeah, definitely not botted comments (maybe 41K subs is, not 100% sure), but this is a 'spammer purge' tool, so I'm not sure if I'd call this error

**Comment by ThioJoe** [comment]
Those were all flagged because they were caught by the duplicate detection settings, which I consider separate from the actual auto-smart mode filter.  I should probably add some clarifying words about reporting false positives with that. 

If you find you're getting a lot of false positives with that you can just use the config file to increase the threshold for minimum duplicates, and just be sure to check the duplicates list extra carefully.
