### ISSUE TITLE
Error: 'utf-8' codec can't decode byte 0xc4 in position 0: invalid continuation byte

### ISSUE THREAD

**Issue by SoNickRND** [ThioJoe/YT-Spammer-Purge#502]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

My system is 
Russian 
Win7 max
ver 6.1 (build 7601: SP1)

Downloaded code, got API key, got requirements, run.
Got that error, in log part.
First idea was it 'cause my Cyrillic names for network adapters, renamed all to latin, not helped. 
Tried in Python IDLE IDE, same.

PS: I cut out all "colourings" 'cause it was looking like `[0m[0m`

### Release version

version = "2.14.2"

### Steps to reproduce

1. run YTSpammerPurge.py on my PC
2. get error

### What platform are you seeing this problem on?

Windows (.py script)

### Relevant log output

```shell
Loading YT Spammer Purge @ 2.14.2...

Please login using the browser window that opened just now.



Traceback (most recent call last):
  File "C:\Users\DvaKota\Downloads\YT-Spammer-Purge-main\Scripts\auth.py", line 81, in first_authentication
    YOUTUBE = get_authenticated_service() # Create authentication object
  File "C:\Users\DvaKota\Downloads\YT-Spammer-Purge-main\Scripts\auth.py", line 69, in get_authenticated_service
    creds = flow.run_local_server(port=0, authorization_prompt_message="Waiting for authorization. See message above.")
  File "C:\Users\DvaKota\AppData\Local\Programs\Python\Python38\lib\site-packages\google_auth_oauthlib\flow.py", line 457, in run_local_server
    local_server = wsgiref.simple_server.make_server(
  File "C:\Users\DvaKota\AppData\Local\Programs\Python\Python38\lib\wsgiref\simple_server.py", line 154, in make_server
    server = server_class((host, port), handler_class)
  File "C:\Users\DvaKota\AppData\Local\Programs\Python\Python38\lib\socketserver.py", line 452, in __init__
    self.server_bind()
  File "C:\Users\DvaKota\AppData\Local\Programs\Python\Python38\lib\wsgiref\simple_server.py", line 50, in server_bind
    HTTPServer.server_bind(self)
  File "C:\Users\DvaKota\AppData\Local\Programs\Python\Python38\lib\http\server.py", line 140, in server_bind
    self.server_name = socket.getfqdn(host)
  File "C:\Users\DvaKota\AppData\Local\Programs\Python\Python38\lib\socket.py", line 756, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 0: invalid continuation byte
----------------
[!!!] Error: 'utf-8' codec can't decode byte 0xc4 in position 0: invalid continuation byte
If you think this is a bug, you may report it on this project's GitHub page: https://github.com/ThioJoe/YT-Spammer-Purge/issues

Error Code A-1: Something went wrong during authentication.  Try deleting the token.pickle file. 
Press Enter to exit...
```
```


### Screenshots

_No response_

**Comment by Kurdakov** [comment]
Non English  system might have that problem see
https://stackoverflow.com/questions/29423734/unicodedecodeerror-utf-8-codec-cant-decode-byte-0xc4-in-position-0-invalid
so it's not only ports, but likely computer name

**Comment by SoNickRND** [comment]
@Kurdakov 
Yep, you're right, exactly windows network name, change it to latin only and script started.
Can it be fixed in script?

**Comment by Kurdakov** [comment]
>Can it be fixed in script?

it looks like script does not directly provide host name, so there is need to fix underlying code (google auth etc)
which does not seem as likely feature

**Comment by ThioJoe** [comment]
I can maybe see if there is some way to temporarily set the host name, like if it's an environment variable, and just encode the characters somehow

**Comment by Kurdakov** [comment]
@ThioJoe good idea, but seems while in linux it's possible to change hostname without reboot 
https://trendoceans.com/how-to-set-or-change-the-temporary-hostname-in-linux/ 
windows requires reboot
 https://stackoverflow.com/questions/54989/change-windows-hostname-from-command-line

**Comment by F1r3w477** [comment]
> @ThioJoe good idea, but seems while in linux it's possible to change hostname without reboot https://trendoceans.com/how-to-set-or-change-the-temporary-hostname-in-linux/ windows requires reboot https://stackoverflow.com/questions/54989/change-windows-hostname-from-command-line

I believe @ThioJoe is only talking about changing the hostname the python session would run off of, not changing the actual computer hostname temporarily. 

ie: 

Currently:
PC Hostname: THISPC
>Run script
PC Hostname: THISPC
Python session Hostname: THISPC

With change:

PC Hostname: THISPC
>Run script
PC Hostname: THISPC
Python session Hostname: YT-Spammer

**Comment by KendallDoesCoding** [comment]
Are you running the .exe file or the script @SoNickRND ?

**Comment by Kurdakov** [comment]
the solution is in fact - to update python. the problem should be fixed since this patch: 
https://github.com/python/cpython/commit/d8576b1d15155688a67baac24c15254700bdd3b7 
(I checked, latest 3.8 python has this patch applied)

**Comment by KendallDoesCoding** [comment]
> the solution is in fact - to update python. the problem should be fixed since this patch: [python/cpython@d8576b1](https://github.com/python/cpython/commit/d8576b1d15155688a67baac24c15254700bdd3b7) (I checked, latest 3.8 python has this patch applied)

This should work, requesting you to close this issue @SoNickRND , @ThioJoe

**Comment by SoNickRND** [comment]
@KendallDoesCoding python script

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding python script

Why not run it on the .exe?

**Comment by KendallDoesCoding** [comment]
Your on windows right?

**Comment by SoNickRND** [comment]
> 

EXE crushes with  dll api ms bla-bla not found. I left it for next time ticket)))

**Comment by KendallDoesCoding** [comment]
I suggest you create a issue thread then, and then ThioJoe may fix that?

**Comment by SoNickRND** [comment]
@KendallDoesCoding done
https://github.com/ThioJoe/YT-Spammer-Purge/issues/519

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding done #519

Thanks a lot! And you opened my email too lol 
![image](https://user-images.githubusercontent.com/84712013/152340024-42be7b61-a976-4ac6-90ec-fd1cc7d39762.png)

**Comment by SoNickRND** [comment]
> 

I updated to 3.8, now have to rename it back, restart, and check again. Maybe later, in my evening, 20-22 UTC+3

**Comment by KendallDoesCoding** [comment]
> ```shell
> Please login using the browser window that opened just now.
> ```

@SoNickRND btw, it says

> Please login using the browser window that opened just now.

Did any link open in the browser? If not, it can also be that there's something blocking it and that error is only showing up coz the link cant open in the browser. Do you have a antivirus software?

**Comment by SoNickRND** [comment]
> > ```shell
> > Please login using the browser window that opened just now.
> > ```
> 
> @SoNickRND btw, it says
> 
> > Please login using the browser window that opened just now.
> 
> Did any link open in the browser? If not, it can also be that there's something blocking it and that error is only showing up coz the link cant open in the browser. Do you have a antivirus software?

Nope, it crashed before browser started, and looks like it just can't hande cyrillic symbols in username.
After I change pc name to latin only it starts just fine.

**Comment by KendallDoesCoding** [comment]
> > > ```shell
> > > Please login using the browser window that opened just now.
> > > ```
> > 
> > 
> > @SoNickRND btw, it says
> > > Please login using the browser window that opened just now.
> > 
> > 
> > Did any link open in the browser? If not, it can also be that there's something blocking it and that error is only showing up coz the link cant open in the browser. Do you have a antivirus software?
> 
> Nope, it crashed before browser started, and looks like it just can't hande cyrillic symbols in username. After I change pc name to latin only it starts just fine.

Oh ok, So, do you need to language to Russian or can you make it English?

**Comment by SoNickRND** [comment]
> 

I want to check it with Russian (Cyrillic) name, but I'll do it later, can't reboot now, working.
 
If updating to 3.8 fixes that issue, all we need to do is to mention this in some FAQ\manual, as "if you have older Python, non-latin PC name, and got this error update your Python"

**Comment by ThioJoe** [comment]
As for the colors, are you by any chance running the console / cmd in [legacy mode](https://docs.microsoft.com/en-us/windows/console/legacymode)? You can check by right clicking the cmd window and going to defaults, then look at the bottom and see if 'use legacy console' is checked.

**Comment by SoNickRND** [comment]
Sorry for delay.
Now I renamed my win7 Russian PC back to Russian (network) name.
Rebooted.
Also I updated Python to 3.8.10 like two days before.
(it is last version that have win64 installer and not noted as " cannot be used on Windows7". There is  3.8.11 and 3.8.12 but packed as "tar.gz" archive,  dunno how to install it on my system, if possible at all)

Did run script, have .... a similar error, with another error message now....

`Loading YT Spammer Purge @ 2.14.2...


Traceback (most recent call last):
  File "C:\Users\DvaKota\Downloads\YT-Spammer-Purge-main\Scripts\auth.py", line 81, in first_authentication
    YOUTUBE = get_authenticated_service() # Create authentication object
  File "C:\Users\DvaKota\Downloads\YT-Spammer-Purge-main\Scripts\auth.py", line 65, in get_authenticated_service
    creds.refresh(Request())
  File "C:\Users\DvaKota\AppData\Local\Programs\Python\Python38\lib\site-packages\google\oauth2\credentials.py", line 30
2, in refresh
    ) = reauth.refresh_grant(
  File "C:\Users\DvaKota\AppData\Local\Programs\Python\Python38\lib\site-packages\google\oauth2\reauth.py", line 322, in
 refresh_grant
    response_status_ok, response_data = _client._token_endpoint_request_no_throw(
  File "C:\Users\DvaKota\AppData\Local\Programs\Python\Python38\lib\site-packages\google\oauth2\_client.py", line 115, i
n _token_endpoint_request_no_throw
    response = request(method="POST", url=token_uri, headers=headers, body=body)
  File "C:\Users\DvaKota\AppData\Local\Programs\Python\Python38\lib\site-packages\google\auth\transport\requests.py", li
ne 183, in __call__
    response = self.session.request(
  File "C:\Users\DvaKota\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 542, in re
quest
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\DvaKota\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 655, in se
nd
    r = adapter.send(request, **kwargs)
  File "C:\Users\DvaKota\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 439, in se
nd
    resp = conn.urlopen(
  File "C:\Users\DvaKota\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 696,
in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\DvaKota\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 964,
in _prepare_proxy
    conn.connect()
  File "C:\Users\DvaKota\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 359, in c
onnect
    conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\DvaKota\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 500, in _
connect_tls_proxy
    return ssl_wrap_socket(
  File "C:\Users\DvaKota\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\ssl_.py", line 453, in ss
l_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\DvaKota\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\ssl_.py", line 495, in _s
sl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\DvaKota\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\DvaKota\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 997, in _create
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname
----------------
[!!!] Error: check_hostname requires server_hostname
If you think this is a bug, you may report it on this project's GitHub page: https://github.com/ThioJoe/YT-Spammer-Purge
/issues

Error Code A-1: ←[31mSomething went wrong during authentication.←[0m ←[33mTry deleting the token.pickle file.←[0m
Press Enter to exit...`

Did not cleared "colors" now. sorry.

Yep, with name in Latin chars all worked just fine, tried yesterday.

**Comment by SoNickRND** [comment]
> 

Checked both PS and CMD, no such option
![image](https://user-images.githubusercontent.com/125238/152656615-164d8528-3572-42e9-9dad-2ba8390e07e0.png)
Only "Cursor size" group, "Command buffer' and "Editing" (like allowing copy\paste features).
It seems to me, that "legacy mode" is for win10 only.

> 

I can keep PC name in Latin chars now, but, let's say, maybe add some check for non-Latin with some valid error message, like: "Sorry, computer name must be in ASCII for this script to work" :)

**Comment by ThioJoe** [comment]
Hm that's odd, mine looks like this 
![image](https://user-images.githubusercontent.com/12518330/152660976-cdaefd2b-9c6c-4aac-b7c3-ba4bbe3421c1.png)

**Comment by Kurdakov** [comment]
while there are no official binaries for python 3.8.12 there are unofficial https://github.com/adang1345/PythonWindows/tree/master/3.8.12

**Comment by SoNickRND** [comment]
> Hm that's odd, mine looks like this ![image](https://user-images.githubusercontent.com/12518330/152660976-cdaefd2b-9c6c-4aac-b7c3-ba4bbe3421c1.png)

Well, you not on win7. :)

**Comment by TechStudent11** [comment]
> > Hm that's odd, mine looks like this ![image](https://user-images.githubusercontent.com/12518330/152660976-cdaefd2b-9c6c-4aac-b7c3-ba4bbe3421c1.png)
> 
> Well, you not on win7. :)

@SoNickRND I think it might be time to upgrade, given that MS has stopped updating Windows 7 (😥), and that Windows 8.1 (not a viable upgrade), Windows 10 (would recommend ✔️) and Windows 11 (still buggy) are all options.

**Comment by KendallDoesCoding** [comment]
Isn't it paid though to update Windows 7 or 8 to Windows 10, I may be
mistaken.

**Comment by TechStudent11** [comment]
No you can upgrade Windows 7 directly to Windows 10 without going through Windows 8.1 first.

**Comment by ThioJoe** [comment]
Has it been determined what the root problem is?

**Comment by TechStudent11** [comment]
@SoNickRND So uh it's been a week. Has your issue been solved?

**Comment by SoNickRND** [comment]
> @SoNickRND So uh it's been a week. Has your issue been solved?

Well, if someone added note about "if you fail here -- maybe you need to rename your pc\update windows" then, yes. Can anybody confirm it?

**Comment by ThioJoe** [comment]
Been a while in this issue, so the solution at this point is to rename the OS to not include special foreign characters?

**Comment by SoNickRND** [comment]
Not OS, PC network name.

**Comment by ThioJoe** [comment]
> Not OS, PC network name.

Ah ok that's what I meant

**Comment by TechStudent11** [comment]
Yeah, unless you can change the non-ASCII letters to ASCII letters, or just get rid of them entirely.
