### ISSUE TITLE
Filtering: Username false positive

### ISSUE THREAD

**Issue by nutter308** [ThioJoe/YT-Spammer-Purge#505]
### Filter Mode

Auto-Smart Mode

### Select the Problem

False Positive

### Spammer Example / Sample

<img width="678" alt="Screenshot 2022-02-02 233503" src="https://user-images.githubusercontent.com/8521778/152255667-2e2f58a6-edf7-4510-8d8f-0ec63f19d89f.png">
https://www.youtube.com/watch?v=omeDomW0Oy8&lc=Ugzjz61LTWiMTCaoCHd4AaABAg

### Video / Post Link

https://www.youtube.com/watch?v=omeDomW0Oy8&lc=Ugzjz61LTWiMTCaoCHd4AaABAg

### (Optional) Additional Info / Context

false positive on a random channel I watched after seeing Linus recommend the community to help. hope this helps a little ;)

**Comment by ThioJoe** [comment]
Yea that's odd, i'll have to see why it caught that

**Comment by flexagoon** [comment]
@ThioJoe it caught it because the username has "on IG" in it lol

**Comment by ThioJoe** [comment]
> @ThioJoe it caught it because the username has "on IG" in it lol

I think you're right 😂, I'll have to fix that

**Comment by HitomiTenshi** [comment]
Not sure how phrases are detected but on this one it would make sense to also check for word boundries before `on` and after `IG`.

For example with regex:
![firefox_2022-02-05_00-07-43](https://user-images.githubusercontent.com/7304212/152615564-4e46feb4-a8bc-47b7-8ade-4fdec529546c.png)

Same goes for "on my IG" / "in my IG" / "on this IG" and other variations.

**Comment by ThioJoe** [comment]
Yea probably something like that

**Comment by ThioJoe** [comment]
Ok I've addressed this in the latest release, 2.16.0
