### ISSUE TITLE
Add certificate and update assets for releases before you bought the certificate

### ISSUE THREAD

**Issue by KendallDoesCoding** [ThioJoe/YT-Spammer-Purge#514]
I just downloaded the first version of this project, and theres no certificate identified, I was just wondering if you could add the certificate to all the previous releases and update the assets for them too, not that anyone else will download the previous releases, but if possivle this would be great, but if its going to be time consuming then forgot about this.

I mean, its also fair that if the user wants to download the first version they can do a few extra clicks.

**Comment by bolshoytoster** [comment]
@KendallDoesCoding I don’t think it will be possible, at least not without a lot of `git reset`ing since the releases in this repo aren’t in their own branches like in other repos.

I’m also not sure if you can overwrite an existing release. It’s probably best to just put a warning somewhere.

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding I don’t think it will be possible, at least not without a lot of `git reset`ing since the releases in this repo aren’t in their own branches like in other repos.
> 
> I’m also not sure if you can overwrite an existing release. It’s probably best to just put a warning somewhere.

I think you can update the assets of each release but I dont know a way to automate it, you can do it manually, I believe. But as mentioned, it would take a lot of time for ThioJoe, Closing for now and ig we can put a warning in README?
