### ISSUE TITLE
Filtering: Crypto Thread Spam

### ISSUE THREAD

**Issue by BlackMambaViper** [ThioJoe/YT-Spammer-Purge#518]
### Filter Mode

Auto-Smart Mode

### Select the Problem

Some spammers not detected

### (Optional) If 'Other', Enter Very Short Description

Initial comments about crypto not being picked up but replies are 

### Spammer Example / Sample

[Spam_Log_2022-02-03_13-58-37.txt](https://github.com/ThioJoe/YT-Spammer-Purge/files/7994289/Spam_Log_2022-02-03_13-58-37.txt)

### Video / Post Link

https://www.youtube.com/watch?v=_28FnZUo6So&lc=UgzATfRQAxxqSCCEFrp4AaABAg.9XRSQmUjVrO9XRkz8c76MO%5Cline&ab_channel=AntonPetrov

### (Optional) Additional Info / Context

Often I have found comments in the first category that are replies to crypto comments on completely unrelated educational videos and the replies are picked up first before the initial comment but unusually the original comment is not picked up only the replies with sometimes phone numbers and contacts 

I suggest that there be a crypto filter to pick these up since it has been hard to pick up in general

**Comment by ThioJoe** [comment]
Yea these are a type of spammer I really need to get on. I think I'll do that today actually. Gonna keep this open

**Comment by ThioJoe** [comment]
This scanning for these threads has been added in the latest release, 2.15.0-Beta1
