### ISSUE TITLE
Large comments threads not being deleted

### ISSUE THREAD

**Issue by DGBAntho** [ThioJoe/YT-Spammer-Purge#520]
### Filter Mode

Sensitive-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

![A6191C03-3C0D-49CE-8548-B4550C1DBED5](https://user-images.githubusercontent.com/95594811/152341624-ddb13f5f-9bd3-468e-9abb-7ecf95656186.png)
![8759EC46-DA24-41BD-908E-518D7DDBF9D3](https://user-images.githubusercontent.com/95594811/152341641-e574aee8-7630-4b06-8a93-1120d3705bc7.png)
![07D49011-E7CC-4A1B-B725-CDEBBA0958B7](https://user-images.githubusercontent.com/95594811/152341646-c424e9ad-7a68-4dea-9ea6-7a07d819ae9d.png)

### Video / Post Link

https://youtu.be/ao1nONgJ_sY

**Comment by KendallDoesCoding** [comment]
Why did you close this?

**Comment by Firecul** [comment]
I'm hoping, to make a request with the spammer names on the spam list repo @KendallDoesCoding

**Comment by KendallDoesCoding** [comment]
> I'm hoping, to make a request with the spammer names on the spam list repo @KendallDoesCoding

Yes, this is a great idea. Please drop that request here: https://github.com/ThioJoe/YT-Spam-Lists/discussions
