### ISSUE TITLE
Filtering: (Write a short title here)

### ISSUE THREAD

**Issue by snabbott** [ThioJoe/YT-Spammer-Purge#528]
### Filter Mode

Auto-Smart Mode

### Select the Problem

Some spammers not detected

### Spammer Example / Sample

![image](https://user-images.githubusercontent.com/74937333/152422273-54701ac7-cadd-4d6f-84da-610f935a9353.png)
![image](https://user-images.githubusercontent.com/74937333/152422536-8c3a3595-55d8-4765-81f5-69a386aaedf8.png)

### Video / Post Link

https://www.youtube.com/watch?v=ItxIvVH3T6o&t=612s&ab_channel=TheFoodTheorists

**Comment by ThioJoe** [comment]
The ones pictures do actually get caught when I ran it, but a couple didn't. So I've updated the filters in the latest commit, they'll be in the next beta release.
