### ISSUE TITLE
Spanish/spammers in other languages

### ISSUE THREAD

**Issue by CyanoTex** [ThioJoe/YT-Spammer-Purge#529]
### Filter Mode

Auto-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

![Screenshot_20220203-215326_YouTube](https://user-images.githubusercontent.com/62466866/152427773-fdf0dae6-a2af-4e2b-b90d-40d328ce0eeb.png)

### Video / Post Link

https://youtu.be/pqZFcrQTZ_E

### (Optional) Additional Info / Context

It's spam, but in Spanish. I believe YouTube allows you to click "Translate into English" to get a translation, but that's on mobile, not sure if it's on Desktop.

**Comment by EthanHindmarsh** [comment]
@ThioJoe Heres a "actual specific example" of spam in another language 👍

It's interesting that 'OnLine' is capitalized like that 😅

Text:
`
**MOMOKIMI*(A.:,:)* • há 1 h 
Eres la mejor Bigbooty.OnLine Las elecciones cinematográficas y artísticas son brillantes. Referencias culturales europeas realmente interesantes. Ojalá la cultura europea se representara más a menudo tan bellamente. No puedo dejar de decir "oh, esto es hermoso" a lo largo del video. Luz, en serio... el que se encargue de la iluminación, genial. 
`

**Comment by KendallDoesCoding** [comment]
#477 #496 

@ThioJoe 's comments:
it's not really feasible for me to create filters for every single language. You'd be better off using entering your own search terms using one of the other filtering modes.

If there is a pattern of a certain type of spammer in another language I'll take a look and see what I can do. But I'd need actual specific examples



This is a spam comment purger, mainly for english, as it will be hard to code stuff to filter out other languages, and there will have to be some api with some kind of transalation running behind searching for all comments in other languages and translating text, so I doubt it will be efficient even if he does it.

**Comment by KendallDoesCoding** [comment]
Although, we will mark that domain as a scam domain.

**Comment by ThioJoe** [comment]
> Although, we will mark that domain as a scam domain.

Who's "we" 🤔

**Comment by KendallDoesCoding** [comment]
> > Although, we will mark that domain as a scam domain.
> 
> Who's "we" 🤔

lol, its a habit, to say we. Anyways, I meant, I will make a request to mark that as a scam domain.

**Comment by KendallDoesCoding** [comment]
@ThioJoe Please close this issue
