### ISSUE TITLE
Authorization Issue

### ISSUE THREAD

**Issue by Lfranca111** [ThioJoe/YT-Spammer-Purge#532]
So I tried to set up the API but every time I try I get a authorization page even though I did everything the same as youll see in pictures. Help pl
![Capture](https://user-images.githubusercontent.com/98989860/152441677-fca3c508-5932-41bb-a7a3-d436434f595b.PNG)
![Capture1](https://user-images.githubusercontent.com/98989860/152441680-9998e11d-8711-4962-b586-a181b8a64f20.PNG)
![Capture2](https://user-images.githubusercontent.com/98989860/152441681-432354f1-378d-47a2-a134-e484ac5c4282.PNG)
![Capture3](https://user-images.githubusercontent.com/98989860/152441683-118fbda9-0512-4e4b-b3db-dc4cdfc9ece0.PNG)
![Capture4](https://user-images.githubusercontent.com/98989860/152441684-6baff71e-511c-4b40-9603-46ebdd51d6ff.png)

**Comment by TechStudent11** [comment]
You need to add yourself as a tester

**Comment by ThioJoe** [comment]
Were you sure to also do the last step / step 14? 

As shown in this instructions page: https://github.com/ThioJoe/YT-Spammer-Purge/wiki/Instructions:-Obtaining-an-API-Key

**Comment by Lfranca111** [comment]
That was it thx you
