### ISSUE TITLE
[Bug]: Sensitive-Smart Mode identifies itself as Auto-Smart Mode

### ISSUE THREAD

**Issue by bejelentkezni** [ThioJoe/YT-Spammer-Purge#533]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Selecting Sensitive-Smart mode for the first time was very confusing as it prints out all the same output as Auto-Smart mode except for the very last line warning about false positives. I think this should be changed, at least to display the correct mode at the top of the output.

### Release version

git-224bb22

### Steps to reproduce

1. Choose scan option 1, 2, or 3.
2. Enter needed data and confirm.
3. Choose identify method number 2.
4. Observe confusing output (below).

### What platform are you seeing this problem on?

Windows (.py script)

### Relevant log output

```shell
-------------------------------------------------------
~~~~~~~~~~~ Choose how to identify spammers ~~~~~~~~~~~
-------------------------------------------------------
 1. (RECOMMENDED): Auto-Smart Mode: Automatically detects multiple spammer techniques
 2. Sensitive-Smart Mode: Much more likely to catch all spammers, but with significantly more false positives
 3. Enter Spammer's channel ID(s) or link(s)
 4. Scan usernames for criteria you choose
 5. Scan comment text for criteria you choose
 6. Scan both usernames and comment text for criteria you choose
 7. ASCII Mode: Scan usernames for ANY non-ASCII special characters (May cause collateral damage!)
 Note: With 'Not Your Channel Mode' enabled, you can only report matched comments while using 'Auto-Smart Mode'.

Choice (1-7): 2

----------------------------------------------- Auto-Smart Mode -----------------------------------------------
~~~ This mode is a spammer's worst nightmare. It automatically scans for multiple spammer techniques ~~~

 > Extremely low (near 0%) false positives
 > Detects whatsapp scammers and '18+ spam' bots
 > Easily cuts through look-alike characters and obfuscations, including impersonating usernames
 > NOTE: In sensitive mode, expect more false positives. Recommended to run this AFTER regular Auto Smart Mode.

Press Enter to Begin Scanning...
```

### Screenshots

![Untitled](https://user-images.githubusercontent.com/67395204/152458888-2ebabaf7-6515-480d-9d3e-ed3cea7323f4.png)

**Comment by EthanHindmarsh** [comment]
See #535 -- Should be fixed if changes approved 👍
