### ISSUE TITLE
[Feature Request]: Unable to scan channels in which user is Editor

### ISSUE THREAD

**Issue by Grommish** [ThioJoe/YT-Spammer-Purge#538]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

When attempting to run the Purge (Windows) executable against a channel in which user is an Editor (not Manager or Owner, but still will Comment-control rights), Applications uses SSO to authenticate.  Changing the Channel ID in the Config returns

```
Error: The channel ID in the config file appears to be valid, but does not match the channel ID of the currently logged in user.
```

Since multiple channels can be under a single Login, I was unable to see a way in which to scan something other than the "main" channel outside of "Not My Channel" mode which doesn't delete the items.

### Release version

2.14.3

### Steps to reproduce

1.  Download .exe
2.  Set separate config option and credential .json
3. Change general.your_channel_id to the Channel_ID for the channel in which user is Editor

### What platform are you seeing this problem on?

Windows (.exe file)

### Screenshots

![image](https://user-images.githubusercontent.com/4427558/152488237-fd1bdc61-4d65-413a-b427-9f084dbefa3a.png)

**Comment by Kurdakov** [comment]
you should enable moderator mode in settings file. So - start the program, save config, edit it moderatorMode = True

**Comment by Grommish** [comment]
Enabled, still an issue. 

![image](https://user-images.githubusercontent.com/4427558/152518569-e2586c06-9a67-4669-83a5-23c7f3946c4b.png)

**Comment by Kurdakov** [comment]
I think you should not set your_channel_id

**Comment by Grommish** [comment]
Actually, I just figured it out :)

I figured it was something silly :)  Appreciate it!

**Comment by Grommish** [comment]
Is there a way to actually DELETE the found reports in Moderator mode?

**Comment by Kurdakov** [comment]
Held for review sends to review pane of owner and hides from channel (the same as pressing delete comment manually by moderators), actual delete (without sending to review pane) is not allowed by API for moderators, so held for review just does the task, even if fills review paneof owner. you might request https://issuetracker.google.com/ feature here to add delete to moderators.

**Comment by Kurdakov** [comment]
Just one question. Is a channel you moderate is company channel? Maybe it's possible to add Editor mode for program. So in this case reopen request with description of your particular setup ( company channel, Editor role etc ), then you'd be able to set your channel id and not have a problem

**Comment by Grommish** [comment]
> Just one question. Is a channel you moderate is company channel? Maybe it's possible to add Editor mode for program. So in this case reopen request with description of your particular setup ( company channel, Editor role etc ), then you'd be able to set your channel id and not have a problem

Yes, it is a branded company channel.

In this case, "Limited Editor/Editor" have Comment Administration abilities, including Delete/Flag/Report/Mute and the ability to respond/heart/moderator Held comments that are separate from Chat Moderation.

**Comment by Kurdakov** [comment]
for videos it's probably better to scrape them with something like https://github.com/banhao/scrape-youtube-channel-videos-url,
then just list links in ini file
also I think for business channel it's possible to request an upped api limit (until possibly scrape mode to videos will be added (youtube could maybe block such use though) , using api only for actual removal of spammers)

**Comment by Kurdakov** [comment]
I think in Editor/Manager roles for business accounts  it is the same as owner mode, but without setting your_channel_id (or instead the same as moderator mode, but allowing delete), probably you might just edit script to allow to 'delete' in moderator mode and confirm that delete works in this case.

**Comment by Grommish** [comment]
I will test and try it.. It's easy enough to comment out 

```
userNotChannelOwner = True
```

a few times.. I'm out of API hits for the day though :) I will test it tomorrow and let you know.

**Comment by ThioJoe** [comment]
Yea in that case it's probably better to just modify the script

**Comment by Grommish** [comment]
No problem.. I can keep a local commit for any changes and rebase to keep it updated.. I appreciate all the help and the script!
