### ISSUE TITLE
Filtering: Not detected this spam link

### ISSUE THREAD

**Issue by stJL** [ThioJoe/YT-Spammer-Purge#545]
### Filter Mode

Auto-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

![Screenshot 2022-02-04 204454](https://user-images.githubusercontent.com/25957971/152531331-34a8f05c-d615-4773-8cc2-4d30cad4fe2a.png)

### Video / Post Link

https://www.youtube.com/watch?v=W3Okalqe9KQ

**Comment by ThioJoe** [comment]
Did you enable spam link detection in config

**Comment by stJL** [comment]
Yes, I enable "detect_link_spam" in config and use auto-smart mode but cannot found this spammer.

Here is a log I created with this function "Channel IDs of spammer searched"，here's what I found and add here
[Uploading Spam_Log_2022-02-04_20-43-01.txt…]()

**Comment by ThioJoe** [comment]
Ah I just noticed that's not actually a youtube link, just a domain made to look like one

**Comment by ThioJoe** [comment]
Ok I added the domain to the spam list in the other repository: https://github.com/ThioJoe/YT-Spam-Lists
