### ISSUE TITLE
[Bug]: Error when the value after comma for "only" is blank (Code Z-3)

### ISSUE THREAD

**Issue by lloyddunamis** [ThioJoe/YT-Spammer-Purge#549]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

I derped.
I just pressed Enter key when I thought to do `only 1-4`, but forgot that I had `,` included. So basically I had the next value after the comma blank. That "expecting value after that comma" might've caused the error.

Bug might appear on `exclude` too, but I ran out of quota today to test.

### Release version

2.15.0-Beta1

### Steps to reproduce

1. Get to the "(Not Case Sensitive) Input:" part _(after spam scanning is done)_.
2. Input only `1-4,` or as long as there's no value after a comma. (ex: `only 1-4,8,`)
3. Enter the command.

### What platform are you seeing this problem on?

Windows (.exe file)

### Relevant log output

```shell
(Not Case Sensitive) Input: only 1-4,
Traceback (most recent call last):
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1573, in <module>
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1550, in main
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1387, in primaryInstance
  File "Scripts\operations.py", line 873, in exclude_authors
ValueError: invalid literal for int() with base 10: ''
------------------------------------------------
Error Message: invalid literal for int() with base 10: ''

Unknown Error - Code: Z-3 occurred.
```

### Screenshots

A "reproduce" instance, so the input is different.
![image](https://user-images.githubusercontent.com/6012867/152551639-62ea18bb-aac7-4f0c-833f-8b58fa729c4c.png)

**Comment by Kurdakov** [comment]
it is fixed in main branch, so either git pull or wait for next release

**Comment by ThioJoe** [comment]
Yea I'll just close it since it's already fixed in the next release
