### ISSUE TITLE
Filtering: (Write a short title here)

### ISSUE THREAD

**Issue by Manodragon** [ThioJoe/YT-Spammer-Purge#553]
### Filter Mode

Auto-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### (Optional) If 'Other', Enter Very Short Description

Spammer not detected

### Spammer Example / Sample

https://www.youtube.com/watch?v=An0TbF0zGt
<img width="578" alt="Screenshot 2022-02-04 221137" src="https://user-images.githubusercontent.com/6142132/152596867-f079a001-3a4d-4072-91da-359143d4281e.png">
<img width="326" alt="Screenshot 2022-02-04 221045" src="https://user-images.githubusercontent.com/6142132/152596869-486c5f97-4377-44fb-b139-23b6a8cdb0aa.png">
<img width="536" alt="Screenshot 2022-02-04 221234" src="https://user-images.githubusercontent.com/6142132/152596872-9fa6c93e-1774-4fcd-b272-0c62472ff317.png">
<img width="300" alt="Screenshot 2022-02-04 221203" src="https://user-images.githubusercontent.com/6142132/152596874-63038b57-14cb-4c55-bdd5-a1d091c5a6c4.png">
0

### Video / Post Link

https://www.youtube.com/watch?v=An0TbF0zGt0

**Comment by ThioJoe** [comment]
A real person just leaving a bunch of unique comments is not really what this program is for
