### ISSUE TITLE
[Bug]: Scanning more than 10 recent videos non-interactively 

### ISSUE THREAD

**Issue by djsv23** [ThioJoe/YT-Spammer-Purge#554]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

There are some prompts in the way of allowing the docker container to run non-interactively. The first one I've gotten caught on is the one asking if I want to see the rest of the recent video titles before scanning when mounting a config file that asks for more than 10 recent videos to be scanned, which throws an error and ends the script.

### Steps to reproduce

1. Authorize through the initial run of the script to generate client_secret.json and token.pickle
2. Build the docker image
2. Mount the client secret and token, and config file set up so that no questions should be asked and >10 recent videos to be scanned
3. docker-compose up

### What platform are you seeing this problem on?

Linux (can also be ChromeOS)

### Screenshots

![image](https://user-images.githubusercontent.com/35004431/152606345-b8fce11a-2ddf-4f7d-8e6e-8c6b86827efb.png)

**Comment by djsv23** [comment]
@ThioJoe I'm happy to take a crack at fixing all the places this could happen so that the script can always run without requiring user input, but that could either be done by adding a new config item for each prompt that's missing one right now, or introducing some sort of an "Auto Mode" config option that would be a one-line option to support this use case that sets all the prompt responses to defaults

**Comment by ThioJoe** [comment]
Ah yea. There actually is a setting in config `skip_confirm_video` but I forgot to apply it to that particular prompt. Let me know if you come across any more like that.

Should be fixed in the next beta release with: https://github.com/ThioJoe/YT-Spammer-Purge/commit/2fa4f14fa4b07faf97c2d6b6ab96e86d92fdee16
