### ISSUE TITLE
Filtering: FREE [INSERT VALUABLE THING HERE] ON MY CHANNEL

### ISSUE THREAD

**Issue by HitomiTenshi** [ThioJoe/YT-Spammer-Purge#556]
### Filter Mode

Auto-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Comment:
```
❤️FREE GIFT CARDS ON MY CHANNEL❤️
I love how he makes all videos, I love to watch them and I can't wait for future videos jyY
```

### Channel:
https://www.youtube.com/channel/UCyg0nP0opqSXHeLiu8pYnoA

### Screenshots:
The comment:
![firefox_2022-02-04_23-39-14](https://user-images.githubusercontent.com/7304212/152612959-fa180087-3972-4735-a787-004173569699.png)

The profile:
![firefox_2022-02-04_23-41-54](https://user-images.githubusercontent.com/7304212/152612968-533389fe-172b-4496-ad14-ebfd5e05d5bd.png)

### Video / Post Link

https://www.youtube.com/watch?v=Ufoj1H5JTDE

### (Optional) Additional Info / Context

This spammer does not actually spam the video but has a bunch of accounts upvoting the comment. People see the title and are tempted to click on their profile. The profile has a huge banner leading you to a scam / malicious website.

**Comment by KendallDoesCoding** [comment]
> ### Filter Mode
> Auto-Smart Mode
> 
> ### Select the Problem
> A type of spammer is not detected at all
> 
> ### (Optional) If 'Other', Enter Very Short Description
> _No response_
> 
> ### Spammer Example / Sample
> ### Comment:
> ```
> ❤️FREE GIFT CARDS ON MY CHANNEL❤️
> I love how he makes all videos, I love to watch them and I can't wait for future videos jyY
> ```
> 
> ### Channel:
> https://www.youtube.com/channel/UCyg0nP0opqSXHeLiu8pYnoA
> 
> ### Screenshots:
> The comment: ![firefox_2022-02-04_23-39-14](https://user-images.githubusercontent.com/7304212/152612959-fa180087-3972-4735-a787-004173569699.png)
> 
> The profile: ![firefox_2022-02-04_23-41-54](https://user-images.githubusercontent.com/7304212/152612968-533389fe-172b-4496-ad14-ebfd5e05d5bd.png)
> 
> ### Video / Post Link
> https://www.youtube.com/watch?v=Ufoj1H5JTDE
> 
> ### (Optional) Additional Info / Context
> This spammer does not actually spam the video but has a bunch of accounts upvoting the comment. People see the title and are tempted to click on their profile. The profile has a huge banner leading you to a scam / malicious website.

Other people use this malicious site and actually comment with it, but that domain is already on the domain list for scam sites.

**Comment by KendallDoesCoding** [comment]
I put it somewhere a idea of a list of scam words so if @ThioJoe does that, it can filter names like FREE/free gifts/ free giftcards, etc

**Comment by KendallDoesCoding** [comment]
> I put it somewhere a idea of a list of scam words so if @ThioJoe does that, it can filter names like FREE/free gifts/ free giftcards, etc

https://github.com/ThioJoe/YT-Spam-Lists/discussions/63

**Comment by ThioJoe** [comment]
Updated the filters a bit in 2.15.0-Beta3, we can keep an eye on other patterns that show up
