### ISSUE TITLE
[Bug]: Not adhering to config file limits.

### ISSUE THREAD

**Issue by divinewind420** [ThioJoe/YT-Spammer-Purge#557]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

I ran with config file and instead of adhearing to max_comments, it appears to read more than that.
settings:
scan_mode = RecentVideos
max_comments = 1000
videos_to_scan = Ask
channel_to_scan = https://www.youtube.com/c/MrBeast6000
recent_videos_amount = 1

### Release version

2.14.2

### Steps to reproduce

1. Setup config file as noted.
2. Run program.
3. It will run, and appears to scan more comments than requested and dies on REPORT due to reported quota over run. I checked and quota usage appears to be about 7-7.5k not 10k but that issue was already reported.

### What platform are you seeing this problem on?

Windows (.exe file)

**Comment by djsv23** [comment]
This is more of a feature request than a bug. The comments in the config file state that the max_comments is only checked when scanning a whole channel or a community post, so I expect this is intended behavior.

**Comment by divinewind420** [comment]
I changed scan_mode = EntireChannel but then it appeared to scan no comments.

**Comment by ThioJoe** [comment]
Yea the max comments only applies to scanning your entire channel, because otherwise there would be no end. 

As for the issue with it scanning no comments, I'd need some more details about that to investigate

**Comment by ThioJoe** [comment]
Haven't heard back so marking this as closed
