### ISSUE TITLE
hello! so basically on the channel id  UC5c9VlYTSvBSCaoMu_GI6gQ the spammers dont mean any harm but for getting people to sub them , they just spam a same quote over and over again and the others spammers will copy that quote and start scamming the funny part is that they don't even know how to spell "congratulations" and Another thing could u add some sort of feature so for eg if a vid has over 10k+ spam then the other account takes over automatically ?(I meant MrBeast's vid)

### ISSUE THREAD

**Issue by Thenewbiehacker** [ThioJoe/YT-Spammer-Purge#564]
### Filter Mode

Auto-Smart Mode

### Select the Problem

Some spammers not detected

### Spammer Example / Sample

![image](https://user-images.githubusercontent.com/98798019/152644247-28d6203e-ad57-45a4-b426-0b142e77a70a.png)
![image](https://user-images.githubusercontent.com/98798019/152644267-31720eaa-f633-458a-b746-3d6c1ae9e06e.png)
![image](https://user-images.githubusercontent.com/98798019/152644282-ff6940f2-206b-4d87-86f7-c66123801b3b.png)
u get the point lol

### Video / Post Link

https://www.youtube.com/watch?v=dV7c1W6IOxI

### (Optional) Additional Info / Context

The fliter picks up some of them but shows them in the bottom section (The ones where a viewer gave the same comment multiple times)

**Comment by Firecul** [comment]
Holy titles Batman. Maybe put that in the short description instead?

**Comment by Firecul** [comment]
> The fliter picks up some of them but shows them in the bottom section (The ones where a viewer gave the same comment multiple times)

That probably is the only way to detect them. There is nothing outright spammy in those messages IMO that can be easily filtered. the use of `"""` and emoji maybe but that second one is up for debate. The fact of them posting it multiple times is the easiest to detect and thankfully as you said the tool does this already.

**Comment by ThioJoe** [comment]
This is the equivalent of putting the entire email in the subject line

**Comment by Firecul** [comment]
> This is the equivalent of putting the entire email in the subject line

💯

**Comment by KendallDoesCoding** [comment]
I loaded 181 comments, and 156 were genuine, meaning 25 comments were duplicate on the latest video of channel id UC5c9VlYTSvBSCaoMu_GI6gQ using the tool @Gustavo Rodrigues showed in #218, and you can see those scam comments, they arent malicious, but their still duplicate comments which is spam, and some people, they duplicate the comment, pay for likes by bots and their comment ranks higher than the original

![image](https://user-images.githubusercontent.com/84712013/152651665-263978d5-e473-42a0-8cc5-70db3a859852.png)

**Comment by KendallDoesCoding** [comment]
> Another thing could u add some sort of feature so for eg if a vid has over 10k+ spam then the other account takes over automatically ?(I meant MrBeast's vid)

I didnt understand this but for idea and feature requests, you need to post them here not within a issue: https://github.com/ThioJoe/YT-Spammer-Purge/discussions

**Comment by ThioJoe** [comment]
I'm not sure if there's anything actionable unfortunately. They get caught by the duplicate detection already, and they're undoubtedly spam, so you can just choose to exclude them if you want. So I guess I'll just close this.
