### ISSUE TITLE
Filtering: Typical spam

### ISSUE THREAD

**Issue by OfficialEsco** [ThioJoe/YT-Spammer-Purge#565]
### Filter Mode

Auto-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### (Optional) If 'Other', Enter Very Short Description

The weird thing is these does get caught, but just some? (All of these are from Similar Comments)

### Spammer Example / Sample

* Look at my profile picture or name
  - WOWW YOU DON'T READ MY PROFILE PICTURE 😶😶❌❌
  - D.nnt lo ok my name
  - Don't read my name
* My content is better
  - `<Creator> IS FUUU!!* *MY CONTENT IS WAY BETTER`
  - `<Creator> is lit, but my ABOUT page sucks 😉😉`
  - `<Creator> is GARBAGE!! MY content is Better!!! I will replace him soon!!`
  - Don't look at my playlist666
  - `I'm better than <Creator> I got heat on my paige`
  - `<Creator> is <Creator>trash, My content is better!`
  - `*<Creator> IS NOTHING WITHOUT ME* *I AM WAY BETTER THAN THEM*`
  - `<Creator> ɪꜱ ɢᴀʀʙᴀɢᴇ, ᴍʏ ᴄᴏɴᴛᴇɴᴛ ɪꜱ ʙᴇᴛᴛᴇʀ!!`
  - `<Creator> is garbage!! I MAKE WAY BETTER CONTENT!!`
  - `*<Creator> SUCKS LMAO!!* *IM 100% WAY BETTER LOL*`
  - `*<Creator> EXPOSED: **https://youtu.be/yTol2txaPjc** CAUGHT IN 26K ULTRA HD!*`
  - `*I created delicious not RickRoII video 😂* *Never gonna give you up*`
  - I hope you guys like my ling mobile legends gameplay☺️💙
* Subs from comment
  - how many subs can I get from this comment? Current: 55K
  - How many years your mother live ??   1 SUBSCRIBE -150  years  Ignore - instantl
  - MY SUBS TARGET 700
  - Let's see how many subs I get from this comment
  - Let’s see how many subs I can get from this comment.
  - 100K With 0 video challenge. 8 min ago One best thing about dude is that whenev
  - Please sub
  - it says 789 on the profile can it be 800 please
  - SUBSCRIBE IF YOU SEE THIS YOU MIGHT GET A  COOKIE 🍪 🤫😋
  - How Many years our mother lives??😁😄  1 SUBSCRIBED - 120 years 😇😇 Ignored - Inst
  - JUST GIVE ME HATE COMMENTS ON MY VIDEO I SAID GIVE ME HATE COMMENTS ON MY VIDEO
  - JUST GIVE ME HATE ALREADY MY WORLD RECORD IS TO BE THE MOST HATED YOUTUBER ON Y
  - `<Creator> is my inspiration, my parents said if I get 50k subscribers they defi`
  - TO TELL THE TRUTH I MAKE GOOD VIDEOS BUT PEOPLE DON'T WATCH 😞😭😭
  - It says 74 on my profile can you be 80 my friend greetings
  - help mee 200 subscribers
  - subscribe or i will comment more
  - I just love it when the notification pops up “someone liked your comment” or
  - hi, I made my first video on youtube on a top 5 of phones to play, if you like
  - My subs TARGET 7⁰⁰
  - hey im on the road o 4k can you help?
* "Credit"
  - 💋💝💞❤️One of the best thing about dude is that be never takes credit of himself
  - One of the best things about dude is that he never takes credit for himself whe
  - One of the best thing about dude is that he never takes credit for himself when he achieves something. He always respect us, the audience and his team, and he is polite in all his videos.We congratulate ourselves on this achievement. More to com❤️❤️
  - The most hardworking person who is dedicated towards his work to bring smile
  - I'm just here to appreciate the amount of time and research done by Arun to pro
* Have a great day | If you are reading this comment
  - Congrats to everyone who is early and found this comment! Have a great day, and
  - me: ive been wating for u so pls read dis
  - <Reply to OP> Thank you for your nice comment 😍 My friends, there is nothin
  - ᴛᴏ ᴛʜᴇ ᴘᴇʀꜱᴏɴ ʀᴇᴀᴅɪɴɢ ᴛʜɪꜱ ᴄᴏᴍᴍᴇɴᴛ  ʏᴏᴜ ᴀʀᴇ ᴀᴡᴇꜱᴏᴍᴇ & ʜᴏᴘᴇ ʏᴏᴜ ᴀʀᴇ ʜᴀᴠɪɴɢ ᴀ ɢʀᴇ
  - Congrats to everyone who is early and found this comment 🥇
* Claim Price
  - 🆙Thanks for watching 🔝🔝message right away I have something for you 🆙🆙🆙
  - ⬆️⬆️ thanks for watching ⬆️⬆️ inbox to claim your price 🎁🎁 available to choose
  - 🆙 Happy New Year Thanks for watching🔝🔝 message right away I have something for
  - Congratulations ☝ You've been selected among the shortlisted winners for the on
  - Thanks for watching and commenting🤗🤗 Send a direct message right away,to the nu
  - Thanks for watching,  you are among our lucky winners. Contact to claim prizd t
  - You won ^^^ WhatsApp Only
  - Claim your ''here within an hour'' ticket here!!❤️❤️❤️
* Random
  - It's not a mistake✨, it's a master piece ✨
  - "RushGarcia" does great Orchestra Videos on YT. He is probably great for your project as he made a lot of Anime and Game Music before.
* New
  - UNCENSORED S*X specialdate.my.id/Loo Loo is a beautiful girl. He's the person I
  - MOANING SOUNDS beautyzone.cam/Loo Loo is a beautiful girl. He's the person I lo
  - SPECIAL FOR YOU beautyzone.cam/Anna Anna is a beautiful girl.   He's the person
  - SPECIAL DATING FOR YOU beautyzone.cam/Anna  Anna is a beautiful girl.   He's th
* Special
  - `----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 💜 http://nude.snapgirls.uno/alexakey/?[PRIVATE-S*X]    #ライブ配信の再編ありがとうです！#この日のライブ配信は、#かならりやばかったですね！１#万人を超える人が見ていたもんね（笑）#やっぱり人参最高！#まさかのカメラ切り忘れでやら1かしたのもドキドキでした！#今後は気を付けないとね5). .   !💖🖤❤#今後は気をライブ配信の再編ありがとうです！#この日のライブ配信は、#１万人を超える人が見ていたも ん（#笑）#やっぱり人参最高！#まさかのカメラ切り忘れでやら1かしたのもドキドキでした #今後は気をライブ配信の再編ありがとうです！（ #笑）#垃圾`
  - `------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 💜 special-nudegirls.site 💜    #ライブ配信の再編ありがとうです！#この日のライブ配信は、#かならりやばかったですね！１#万人を超える人が見ていたもんね（笑）#やっぱり人参最高！#まさかのカメラ切り忘れでやら1かしたのもドキドキでした！#今後は気を付けないとね5). .   !💖🖤❤#今後は気をライブ配信の再編ありがとうです！#この日のライブ配信は、#１万人を超える人が見ていたも ん（#笑）#やっぱり人参最高！#まさかのカメラ切り忘れでやら1かしたのもドキドキでした #今後は気をライブ配信の再編ありがとうです！（ #笑）#垃圾`
(the spam text appears to be the same)
* Godly bs
  - ♥️🌺 May God be our friend and open the way of light to our hearts, amen. When we look in the mirror, we see that we are made of flesh and blood. This power that created us will resurrect us. Let's be friends of God so that we will not be in a difficult situation on the day of reckoning. Because God loves us very much, God is a friend to everyone, and he expects us to be friends with him, amen.♥️🌺

### Video / Post Link

https://www.youtube.com/watch?v=V-hwrOcuXOM, https://www.youtube.com/watch?v=puZ3poLO9GA, https://www.youtube.com/watch?v=zkw9aI1-feM, https://www.youtube.com/watch?v=LsWwhmy8wf0, https://www.youtube.com/watch?v=aIqAHYuFdSw

**Comment by Firecul** [comment]
Quite a few of these already get caught

![WindowsTerminal_Windows_PowerShell (14)](https://user-images.githubusercontent.com/34950371/152645194-eff61d0a-a70d-48cd-8dee-268a6ce512da.png)

Some of them may just be slight variations that just miss the filter but I'll be honest I'm not going to look through the 4600 comments the tool found to compare against your list. Those examples might be worth adding if they are not in the filters currently though.

**Comment by OfficialEsco** [comment]
> Quite a few of these already get caught
> 
> ![WindowsTerminal_Windows_PowerShell (14)](https://user-images.githubusercontent.com/34950371/152645194-eff61d0a-a70d-48cd-8dee-268a6ce512da.png)
> 
> Some of them may just be slight variations that just miss the filter but I'll be honest I'm not going to look through the 4600 comments the tool found to compare against your list. Those examples might be worth adding if they are not in the filters currently though.

I checked the marked as clear spam section after i went trough the Similar Comments section and created the issue, and you are correct a lot of these are detected, but when my Similar Comments section is flooded with these then the detection needs to be improved/tweaked :)

**Comment by ThioJoe** [comment]
Hm yea there are some new variations they're using, so I'll have to account for them

**Comment by OfficialEsco** [comment]
Closing the issue since its from [v2.14.3](https://github.com/ThioJoe/YT-Spammer-Purge/releases/tag/v2.14.3) and there have been way too many improvements since then

**Comment by ikkysleepy** [comment]
This is Gold. Thanks for the list. I am making something similar and found this repo after I made my sentiment analysis tool. Great Work!!
