### ISSUE TITLE
[Bug]: module

### ISSUE THREAD

**Issue by alphaleadership** [ThioJoe/YT-Spammer-Purge#566]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Traceback (most recent call last):
  File "D:\YT-Spammer-Purge\YTSpammerPurge.py", line 45, in <module>
    import Scripts.auth as auth
  File "D:\YT-Spammer-Purge\Scripts\auth.py", line 7, in <module>
    from googleapiclient.errors import HttpError
ModuleNotFoundError: No module named 'googleapiclient'

### Release version

latest commit 

### Steps to reproduce

1. 
2. 
3. 
try to import module 
python ytspammerpurge

### What platform are you seeing this problem on?

Windows (.py script)

### Relevant log output

```shell
Traceback (most recent call last):
  File "D:\YT-Spammer-Purge\YTSpammerPurge.py", line 45, in <module>
    import Scripts.auth as auth
  File "D:\YT-Spammer-Purge\Scripts\auth.py", line 7, in <module>
    from googleapiclient.errors import HttpError
ModuleNotFoundError: No module named 'googleapiclient'
```

**Comment by rachmadaniHaryono** [comment]
you have to install required package

https://github.com/ThioJoe/YT-Spammer-Purge/blob/main/requirements.txt

**Comment by Firecul** [comment]
Yeah I think you forgot to run `pip3 install -r requirements.txt`

**Comment by ThioJoe** [comment]
Yea basically you gotta install the requirements
