### ISSUE TITLE
2.15.0-Beta2 ascii codec can't encode character

### ISSUE THREAD

**Issue by hessel-a** [ThioJoe/YT-Spammer-Purge#568]
### Filter Mode

Auto-Smart Mode

### Select the Problem

Other (add details below)

### (Optional) If 'Other', Enter Very Short Description

UnicodeEncoderError ascii codec can't encode character

### Spammer Example / Sample

![TJoe codec bug](https://user-images.githubusercontent.com/61541459/152649348-d10fe3a1-2063-4949-b316-3218d1c3c18b.JPG)

### Video / Post Link

https://www.youtube.com/channel/UCqGONXW1ORgz5Y4qK-0JdkQ

### (Optional) Additional Info / Context

Just scan the last 10 videos.
2.15.0-Beta2

**Comment by ThioJoe** [comment]
Hm i'll have to investigate to see which character specifically is causing the issue and maybe add an exception handler for it

**Comment by Kurdakov** [comment]
also there was discussion here https://github.com/ThioJoe/YT-Spammer-Purge/discussions/257

**Comment by ThioJoe** [comment]
Ok new release is out with the fix, 2.15.0-Beta3
