### ISSUE TITLE
Filtering: (Write a short title here)

### ISSUE THREAD

**Issue by VinLAURiA** [ThioJoe/YT-Spammer-Purge#572]
### Filter Mode

String search

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

![image](https://user-images.githubusercontent.com/3753353/152659326-639db0ed-5e5c-453d-8d39-dc70e67106dc.png)

The bottom two are mimicking the top one with added spam text.

### Video / Post Link

https://www.youtube.com/watch?v=GoVMsD97iZY

**Comment by ThioJoe** [comment]
Ok I've added the domain to the spam domains list with the latest release
