### ISSUE TITLE
[Bug]: X-2 variable 'spamThreadSamplesContent' referenced before assignment

### ISSUE THREAD

**Issue by NatNgs** [ThioJoe/YT-Spammer-Purge#579]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

May be related to #576. Error message is not exactly the same, so there is a new bug report

Scanning for **another channel** (https://www.youtube.com/channel/UC7dF9qfBMXrSlaaFFDvV_Yg, last **25 videos**, **~228k comments**)

At the end of the scan, YTSP listed all suspected comments, printed summary, and then crashed before asking for user input (exclude, report...).

### Release version

2.15.0-Beta2

### Steps to reproduce

1. Open the app, using stored settings, continue as same user
2. Scan mode `2. Scan recent videos for a channel`
3. Channel ID: `https://www.youtube.com/channel/UC7dF9qfBMXrSlaaFFDvV_Yg`
4. Videos to scan: `25`
5. Wait for the scan (~1h)
6. Crash occurs at the very end of the scan

### What platform are you seeing this problem on?

Windows (.exe file)

### Relevant log output

```shell
Traceback (most recent call last):
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1591, in <module>
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1568, in main
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1202, in primaryInstance
  File "Scripts\logging.py", line 134, in print_comments
UnboundLocalError: local variable 'spamThreadSamplesContent' referenced before assignment
------------------------------------------------
Error Message: local variable 'spamThreadSamplesContent' referenced before assignment

Error - Code: X-2 occurred. This is almost definitely my fault and requires patching (big bruh moment)
```

### Screenshots

![image](https://user-images.githubusercontent.com/10955538/152690620-bdd4d5f7-ccbf-4aa6-bde2-5eb94989eba0.png)

**Comment by ThioJoe** [comment]
Should be already fixed in the new beta, you're using an old version
