### ISSUE TITLE
[Errno 13] Permission Denied | Error Code: Z-3

### ISSUE THREAD

**Issue by Algenhirn67** [ThioJoe/YT-Spammer-Purge#580]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

When starting the script it gives me this error message. I tried starting it as an admin but it still gives me this error.

### Release version

2.14.3

### What platform are you seeing this problem on?

Windows (.exe file)

### Screenshots

![Unbenannt](https://user-images.githubusercontent.com/99136364/152691950-6fb6a241-6f95-4d0f-b8db-38a59d61dd8a.PNG)

**Comment by ThioJoe** [comment]
Hm that means the program is unable to write to the file for some reason. Is the file open or something? Maybe try moving everything to a different folder, such as the documents directory, not the desktop

**Comment by Algenhirn67** [comment]
I moved it to the Downloads folder and now it works.
Thank you.
