### ISSUE TITLE
Filtering: missing filter for spam account

### ISSUE THREAD

**Issue by Engstory** [ThioJoe/YT-Spammer-Purge#582]
### Filter Mode

Auto-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

![image](https://user-images.githubusercontent.com/99150304/152706505-9b73986c-f611-438a-98b6-5c3c3725ab02.png)

**Comment by Firecul** [comment]
Huh, that has been suggested before, I thought ThioJoe added it already, I guess not

**Comment by Firecul** [comment]
@Engstory do you have a link to a video with that comment on it? Or a link to the comment would be even better.

**Comment by Engstory** [comment]
Hey, yes I do have the link to the video. Here it is: https://youtu.be/minxwFqinpw 
And here is the spammer's channel link: https://www.youtube.com/channel/UCFRi7Mrj-Eg4QWDo4hklyNQ

**Comment by ThioJoe** [comment]
I've addressed this in the latest release, 2.16.0
