### ISSUE TITLE
Program takes long to fire up

### ISSUE THREAD

**Issue by KendallDoesCoding** [ThioJoe/YT-Spammer-Purge#586]
I downloaded the program and loaded up client_secrets.json, then I ran the program, nothing showed up on the screen, I had to press space 5-10 times and enter 5-10 times then only it started running.

**Comment by Firecul** [comment]
.exe or .py?
What version of the tool?

**Comment by Firecul** [comment]
.py v2.15.0 works fine for me.

https://user-images.githubusercontent.com/34950371/152817487-2a9a244f-2244-48a0-a5ff-fa31905a7eab.mp4

**Comment by KendallDoesCoding** [comment]
.exe

**Comment by KendallDoesCoding** [comment]
> .py v2.15.0 works fine for me.
> 
>  2022-02-07.15-22-27.mp4

Yes, I'm sure python will work fast, I've been having some issues with Python on my computer though, so I use the .exe, and think most of the people use .exe.

**Comment by Firecul** [comment]
> .exe

https://user-images.githubusercontent.com/34950371/152899170-fc4305f5-ecd8-4ac2-b096-b168b1df31c4.mp4

Not great, not terrible.

**Comment by biswasmoheshwar** [comment]
> > .exe
> 
>  2022-02-08.01-11-41.mp4 
> Not great, not terrible. (And I'm running a game on my other monitor at the same time.)

Same. But I am not running a game.

**Comment by KendallDoesCoding** [comment]
> > .exe
> 
>  2022-02-08.01-11-41.mp4 
> Not great, not terrible. (And I'm running a game on my other monitor at the same time.)

its longer for me

**Comment by Firecul** [comment]
> its longer for me

I'm afraid I can't help you diagnose why it's slow only on your pc then

**Comment by ThioJoe** [comment]
> > .exe
> 
> 
> 
> https://user-images.githubusercontent.com/34950371/152899170-fc4305f5-ecd8-4ac2-b096-b168b1df31c4.mp4
> 
> 
> 
> Not great, not terrible. 
> 
> (And I'm running a game on my other monitor at the same time.)

That's a helluva taskbar

**Comment by ThioJoe** [comment]
But yea not sure there's anything to be done here, pretty sure it's an isolated issue

**Comment by Firecul** [comment]
> That's a helluva taskbar

It doesn't look as bad on my 3440*1440 screen I swear.

**Comment by Firecul** [comment]
> Your using windows right? You dont have any shortcuts on the home screen, so that's all in the tasbar?

I have a few on the desktop but they are turned off to take this video, I have a few things on there both work and personal I don't need public.
Everything on the taskbar I use at least once a week and I'd rather have them easy to access than search through the start menu, or even the PowerToys Run (which is pretty good.)
