### ISSUE TITLE
[Bug]: (Can't report comments from log file)

### ISSUE THREAD

**Issue by KendallDoesCoding** [ThioJoe/YT-Spammer-Purge#588]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

I fetched lots and lots of comments and closed the program accidently, not I can't report them using the log file?

### Release version

Newest Version

### Steps to reproduce

1. Open program
2. Fetch comments
3.  Make a log
4. Close program
5. Re-open
Error

### What platform are you seeing this problem on?

Windows (.exe file)

**Comment by KendallDoesCoding** [comment]
I think this is because there's no mode in the program to do so, there should be one though @ThioJoe

**Comment by Firecul** [comment]
ThioJoe had a good reason why not in #569 
Basically it opens up for abuse

**Comment by KendallDoesCoding** [comment]
> ThioJoe had a good reason why not in #569 Basically it opens up for abuse

Yeah, bad that's sad, my quotas got used up and I wasted them by closing the program mistakly
