### ISSUE TITLE
Weird hybrid spam comment

### ISSUE THREAD

**Issue by CyanoTex** [ThioJoe/YT-Spammer-Purge#594]
### Filter Mode

Auto-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

![Screenshot_20220207-210607_YouTube](https://user-images.githubusercontent.com/62466866/152863787-fd00c30e-2538-4eec-bb33-fa75a4ae8037.png)

### Video / Post Link

https://youtu.be/_UB9XoPlJ0U

### (Optional) Additional Info / Context

Seems to use special characters, other languages, emojis, tags... Frankly, it's weird as hell.

**Comment by ThioJoe** [comment]
Yea these are actually pretty common, they're very strange.
 
They do indeed seem to be caught though, are there some that weren't?

<img width="949" alt="image" src="https://user-images.githubusercontent.com/12518330/152870593-908ed2ce-494c-42ad-9d20-12d0b01f65cd.png">
