### ISSUE TITLE
Need Clarification - Comment REPORT

### ISSUE THREAD

**Issue by KendallDoesCoding** [ThioJoe/YT-Spammer-Purge#601]
When, a user, report comments in the program, which catergory does it get reported to YouTube?

![image](https://user-images.githubusercontent.com/84712013/153011560-2efb2dac-0e31-4e1c-9989-0296f4facc9a.png)

The first one right?

**Comment by Tc-001** [comment]
I believe so.

Here is the relevant code:

https://github.com/ThioJoe/YT-Spammer-Purge/blob/ef070af10a65c05d8c62549941a90210167f6b6b/Scripts/operations.py#L889-L890

**Comment by KendallDoesCoding** [comment]
> I believe so.
> 
> Here is the relevant code:
> 
> https://github.com/ThioJoe/YT-Spammer-Purge/blob/ef070af10a65c05d8c62549941a90210167f6b6b/Scripts/operations.py#L889-L890
> 
> Seems to be this action: https://developers.google.com/youtube/v3/docs/comments/markAsSpam

Ok thanks. Closing...
