### ISSUE TITLE
[Bug]: Update failed and deleted all files in current directory

### ISSUE THREAD

**Issue by Steltek** [ThioJoe/YT-Spammer-Purge#604]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

I was trying to perform the self-update from 2.15.0 to 2.15.1 on Linux, but the update failed and apparently performed a self-destruct (the entire current directory was emptied out, including client secrets, config, and the software itself).

Might have been a one-off. I haven't had time to re-install and re-test it.

### Release version

2.15.0

### Steps to reproduce

1. Start ./YTSpammerPurge.py
2. Use option 9 to trigger a self-update and confirm with 'Yes'.

Result: All files in the current directory are deleted.

### What platform are you seeing this problem on?

Linux (can also be ChromeOS)

### Relevant log output

```shell
`Getting info about latest updates...
------------------------------------------------------------------------------------------
 A new version is available! Visit TJoe.io/latest to see what's new.
   > Current Version: 2.15.0
   > Latest Version: 2.15.1
------------------------------------------------------------------------------------------

Update Now? (y/n): 
> Downloading version: 2.15.1

> Extracting...
> Installing...
Traceback (most recent call last):
  File "/home/steltek/YT-Spammer-Purge-2.15.0/./YTSpammerPurge.py", line 1612, in <module>
  File "/home/steltek/YT-Spammer-Purge-2.15.0/./YTSpammerPurge.py", line 1589, in main
  File "/home/steltek/YT-Spammer-Purge-2.15.0/./YTSpammerPurge.py", line 875, in primaryInstance
  File "/home/steltek/YT-Spammer-Purge-2.15.0/Scripts/files.py", line 356, in check_for_update
FileNotFoundError: [Errno 2] No such file or directory: '/home/steltek/YT-Spammer-Purge-2.15.0/temp/YT-Spammer-Purge-2.15.1'
------------------------------------------------
Error Message: [Errno 2] No such file or directory: '/home/steltek/YT-Spammer-Purge-2.15.0/temp/YT-Spammer-Purge-2.15.1'

Unknown Error - Code: Z-3 occurred. If this keeps happening, consider posting a bug report
on the GitHub issues page, and include the above error info.
Short Link: TJoe.io/bug-report

 Press Enter to Exit...
steltek@shodan:~/YT-Spammer-Purge-2.15.0$ ./YTSpammerPurge.py 
bash: ./YTSpammerPurge.py: No such file or directory
steltek@shodan:~/YT-Spammer-Purge-2.15.0$ ls -l
total 4
drwxr-xr-x 2 steltek steltek 4096 Feb  8 11:35 temp
steltek@shodan:~/YT-Spammer-Purge-2.15.0$ `
```

**Comment by ThioJoe** [comment]
Hm i'll have to look into this. I didn't write the linux auto update part myself but I'll try and test it out

**Comment by Firecul** [comment]
> Hm i'll have to look into this. I didn't write the linux auto update part myself but I'll try and test it out

Calling @compsup

**Comment by Firecul** [comment]
@Steltek just to get info what OS are you running?

**Comment by Steltek** [comment]
Running Debian Linux (bullseye).

Tried to reproduce the issue and I got this first this time:

`Getting info about latest updates...
------------------------------------------------------------------------------------------
 A new version is available! Visit TJoe.io/latest to see what's new.
   > Current Version: 2.15.0
   > Latest Version: 2.15.1
------------------------------------------------------------------------------------------

Update Now? (y/n): y

> Downloading version: 2.15.1

> Extracting...
> Installing...
Traceback (most recent call last):
  File "/usr/lib/python3.9/shutil.py", line 815, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: './config' -> '/home/steltek/swdownloads/ytspamscanner/YT-Spammer-Purge-2.15.0/temp/YT-Spammer-Purge-2.15.1/config'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/steltek/swdownloads/ytspamscanner/YT-Spammer-Purge-2.15.0/./YTSpammerPurge.py", line 1612, in <module>
    main()
  File "/home/steltek/swdownloads/ytspamscanner/YT-Spammer-Purge-2.15.0/./YTSpammerPurge.py", line 1589, in main
    continueRunning = primaryInstance(miscData)
  File "/home/steltek/swdownloads/ytspamscanner/YT-Spammer-Purge-2.15.0/./YTSpammerPurge.py", line 875, in primaryInstance
    files.check_for_update(version, updateReleaseChannel)
  File "/home/steltek/swdownloads/ytspamscanner/YT-Spammer-Purge-2.15.0/Scripts/files.py", line 350, in check_for_update
    move("./config", extraFolderPath)
  File "/usr/lib/python3.9/shutil.py", line 835, in move
    copy_function(src, real_dst)
  File "/usr/lib/python3.9/shutil.py", line 444, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: './config'
------------------------------------------------
Error Message: [Errno 2] No such file or directory: './config'

Unknown Error - Code: Z-3 occurred. If this keeps happening, consider posting a bug report
on the GitHub issues page, and include the above error info.
Short Link: TJoe.io/bug-report

 Press Enter to Exit...`

After creating a directory called 'config', the previous behaviour returned and the directory content was wiped out.

**Comment by Firecul** [comment]
> Running Debian Linux (bullseye).

I'll try and reproduce this tomorrow when I have time then.

**Comment by compsup** [comment]
It seems like ThioJoe merged without doing the refactor that was needed. All config files need to be put into ./config

**Comment by compsup** [comment]
I found the issue, I will today create a PR fixing this issue.
