### ISSUE TITLE
Only count videos, dont count livestreams

### ISSUE THREAD

**Issue by Tyler887** [ThioJoe/YT-Spammer-Purge#605]
#600 was out of scope for discussions, opened an issue from it.

### Discussed in https://github.com/ThioJoe/YT-Spammer-Purge/discussions/600

<div type='discussions-op-text'>

<sup>Originally posted by **KendallDoesCoding** February  8, 2022</sup>
This youtuber is currently streaming, so when I scanned the last 2 videos from his channel I think it counted the live-stream as a video too, make it so that it only counts YT videos as a **VIDEO**

![image](https://user-images.githubusercontent.com/84712013/153009389-61712c05-7fbc-42fa-ab44-6c957301e802.png)
</div>

**Comment by ThioJoe** [comment]
Also a feature request so belongs in discussion
