### ISSUE TITLE
IMPORTANT: Message prior to filtering

### ISSUE THREAD

**Issue by Tyler887** [ThioJoe/YT-Spammer-Purge#606]
<sup>Originally posted by **KendallDoesCoding** in #602 February  8, 2022</sup>
I filtered ASCII characters, I think under nuke mode, it filtered everything and in the end I got a comment "You can not report comments even in mod mode. To prevent abuse, etc", but it already used my quotas right? So, if the messege is on top before filtering, which will take from 1minute-1-2 hours depending the size of the comments, to filter out (if filtering a bunch of videos from a channel) I think its better to show that messege prior.

**Comment by ThioJoe** [comment]
This is a feature request so the discussions tab is the right place for it

**Comment by Tyler887** [comment]
> This is a feature request so the discussions tab is the right place for it

Thanks!
