### ISSUE TITLE
Auto-Smart Mode not detecting the Bot Comments and detecting legit Comments and not the biggest part of Scam/Spam/Bot comments

### ISSUE THREAD

**Issue by tfinn345** [ThioJoe/YT-Spammer-Purge#609]
### Filter Mode

Auto-Smart Mode

### Select the Problem

Some spammers not detected

### Spammer Example / Sample

Picture of a Scam/Bot comment (wich is just posted from other accounts with the exact same text):
![image](https://user-images.githubusercontent.com/66796737/153087649-38caeb81-9af7-46a9-9a08-6322326ed585.png)

Some of the Comments detected:
https://www.youtube.com/watch?v=UGz8cee_bno&lc=UgyLO-v3mf1842ttsex4AaABAg
https://www.youtube.com/watch?v=UGz8cee_bno&lc=UgwsyOjFCQcBX98eYnl4AaABAg.9L-DDllrdUm9LNWzbOSkbn
https://www.youtube.com/watch?v=UGz8cee_bno&lc=UgxU1trO3b6P1IirnUB4AaABA

[Spam_Log_2022-02-08_23-28-57.txt](https://github.com/ThioJoe/YT-Spammer-Purge/files/8028082/Spam_Log_2022-02-08_23-28-57.txt)

### Video / Post Link

https://www.youtube.com/watch?v=UGz8cee_bno

### (Optional) Additional Info / Context

Yeah so, the Video is just a scam on itself and I just wanted to try out the detection where I noticed that it did not detect a big part of the scam/bot comments.

**Comment by ThioJoe** [comment]
The new 2.16.0-Beta should address this, by detecting if someone reposted / stole a previous comment

**Comment by Firecul** [comment]
> The new 2.16.0-Beta should address this, by detecting if someone reposted / stole a previous comment

Oh it caught them alright

![image](https://user-images.githubusercontent.com/34950371/153978479-316302c7-1d25-4128-9695-96f548a8a47a.png)
