### ISSUE TITLE
Real users with many comments sometimes get flagged as duplicates

### ISSUE THREAD

**Issue by michaelts1** [ThioJoe/YT-Spammer-Purge#618]
### Filter Mode

Auto-Smart Mode

### Select the Problem

False Positive

### Spammer Example / Sample

This user actually has 29 comments on that video, but I will only link 2 of them here:

https://www.youtube.com/watch?v=HjZ4POvk14c&lc=UgzCslQD6X9GjzVDotd4AaABAg.9Y9_iln9E239Y9dEzX4kF-
![Screenshot_1](https://user-images.githubusercontent.com/41857330/153155073-5cb9347b-0868-4480-9bcf-dc947c551fc0.png)
https://www.youtube.com/watch?v=HjZ4POvk14c&lc=Ugz96SVaexXdenuG45l4AaABAg.9Y9aoiZ_-k59Y9begLnxAp
![Screenshot_2](https://user-images.githubusercontent.com/41857330/153155079-9e514a3e-3efc-4731-b0d0-45570632ccf4.png)

You can find the rest of this user's comments based on the ids in this screenshot from the log:
![Screenshot_1](https://user-images.githubusercontent.com/41857330/153155721-084525ca-3957-4527-b0f4-ad53d2d20442.png)

### Video / Post Link

https://www.youtube.com/watch?v=HjZ4POvk14c

### (Optional) Additional Info / Context

It seems like leaving too many comments (especially short ones?) on the same video might result in YouTube Spammer Purge accidentally flagging your comments as spam.

**Comment by Firecul** [comment]
I guess it was his single word comments of `why` and `yes` that got caught

**Comment by michaelts1** [comment]
Thanks, this makes sense.

But still, I think `Auto-Smart Mode` should prefer false negatives over false positives. Maybe `Auto-Smart Mode` should be tweaked to not flag one-word duplicates, and users who do want to catch these comments will have to use `Sensitive-Smart Mode`.

**Comment by ThioJoe** [comment]
Hm might be worth it to add a minimum length, or maybe under a certain length it has to be exactly the same

**Comment by dingyuchen** [comment]
@ThioJoe I would like to take this issue, if possible

**Comment by ThioJoe** [comment]
Ok I've addressed this in the latest release, 2.16.0
