### ISSUE TITLE
will not execute in linux ( kubuntu 20.04 )

### ISSUE THREAD

**Issue by folfgirl** [ThioJoe/YT-Spammer-Purge#621]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

I try to execute YTSpammerPurge.py using the command "python3 YTSpammerPurge.py" and it give me this " Traceback (most recent call last):
  File "/home/folfgirl/YT-Spammer-Purge/YTSpammerPurge.py", line 44, in <module>
    from Scripts.shared_imports import *
  File "/home/folfgirl/YT-Spammer-Purge/Scripts/shared_imports.py", line 6, in <module>
    from colorama import init, Fore as F, Back as B, Style as S
ModuleNotFoundError: No module named 'colorama' " I don't know what I did wrong if I did. I installed all of the prerequisites

### Release version

2.15.1

### Steps to reproduce

1. python3 YTSpammerPurge.py
2. " Traceback (most recent call last):
  File "/home/folfgirl/YT-Spammer-Purge/YTSpammerPurge.py", line 44, in <module>
    from Scripts.shared_imports import *
  File "/home/folfgirl/YT-Spammer-Purge/Scripts/shared_imports.py", line 6, in <module>
    from colorama import init, Fore as F, Back as B, Style as S
ModuleNotFoundError: No module named 'colorama' " 

I ran  pip3 install colorama and got 
Requirement already satisfied: colorama in /home/folfgirl/.local/lib/python3.8/site-packages (0.4.4)

### What platform are you seeing this problem on?

Linux (can also be ChromeOS)

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/folfgirl/YT-Spammer-Purge/YTSpammerPurge.py", line 44, in <module>
    from Scripts.shared_imports import *
  File "/home/folfgirl/YT-Spammer-Purge/Scripts/shared_imports.py", line 6, in <module>
    from colorama import init, Fore as F, Back as B, Style as S
ModuleNotFoundError: No module named 'colorama' "
```

### Screenshots

![Screenshot_20220212_152451](https://user-images.githubusercontent.com/79891947/153729092-ed6469c6-1b50-49b5-a9d7-542d689efda8.png)

**Comment by Kurdakov** [comment]
try
pip3 install colorama

the most probable reason the module was added to code, but not to requirements.txt

**Comment by ThioJoe** [comment]
Did you install the required modules via `pip3 install -r requirements.txt`? (Might also be just `pip`)

**Comment by Firecul** [comment]
> the most probable reason the module was added to code, but not to requirements.txt

tbh colorama has been in the requirements.txt and working for about 3 months (#86 )

**Comment by compsup** [comment]
This issue seems to have gone stale, it also does not apply to the program but instead too python dependencies.

@folfgirl This should fix it, however if it does not, do `pip3 list | grep -F colorama` and make sure it comes up with colorama.

**Comment by compsup** [comment]
@folfgirl Could you try this and then re-run the program. Run `pip3 install --upgrade --force-reinstall colorama` in your terminal.

**Comment by folfgirl** [comment]
I know why it was not working, I compiled python3.10.2 but when I was using pip3 it when to python3.8.
