### ISSUE TITLE
[Bug]: might want to completely delete the obfuscation pr and issue

### ISSUE THREAD

**Issue by Masamune3210** [ThioJoe/YT-Spammer-Purge#623]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

You might want to delete that deobfuscation pr and issue if possible since it leaks the filters out

### Release version

N/a

### Steps to reproduce

1. 
2. 
3. 

### What platform are you seeing this problem on?

Windows (.exe file)

### Relevant log output

```shell
Sorry for the (kinda) abuse of the issue system, didn't know how else to let you know
```

**Comment by ThioJoe** [comment]
Not possible unfortunately. GitHub has a hardon for not "messing with history" or however you want to put it. It's not the biggest deal, not like it's a secret. The point is just to make it not obvious to the dumbest scammers when looking through the code. The smart ones will already know how to see it anyway.

**Comment by Masamune3210** [comment]
Ok, just wanted to make sure, sorry for bothering you
