### ISSUE TITLE
[Bug]: Can't identify unique channel ID's on its own without entering the full URL

### ISSUE THREAD

**Issue by teduniq** [ThioJoe/YT-Spammer-Purge#624]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

On the entering a channel ID or link part, when entering a unique channel ID by itself, the app displays an error "Invalid Channel link or ID!".

Now you may say that the user should just enter the full URL, and to that I suggest to make the prompt more specific, like "Enter a channel ID (not unique) or link...".

### Release version

2.16.0-Beta1

### Steps to reproduce

1. Enter "2" for the scanning options
2. Enter a unique channel ID on its own ("mkbhd", "NASA", etc.)

### What platform are you seeing this problem on?

Windows (.exe file)

### Screenshots

![00bug](https://user-images.githubusercontent.com/81689588/153387029-f78c874e-6dca-45ec-878b-48570f7726c7.PNG)
![00bug1](https://user-images.githubusercontent.com/81689588/153387036-40ad7af0-4f44-4979-8f63-9d540858ccc0.PNG)

**Comment by ThioJoe** [comment]
Technically those are not channel IDs. Might be able to have it check though

**Comment by ThioJoe** [comment]
A couple things to add though. The YouTube API offers absolutely zero way to do a direct query to retrieve the channel ID if the /c/ channel URL is given, for some reason. It does however, offer a way to directly get the channel ID if the legacy username, so for "youtube.com/whatever", you can query for just "whatever". (Except apparently not always? See example below)

The problem with that is, sometimes the /c/ name is different from the legacy name. So if I were to add a thing way to query the username "mkbhd" for example, it actually returns this channel id: UCmf_VrB73I-eJ3fq0adaOkg, which is not MKBHD's main channel: https://www.youtube.com/channel/UCmf_VrB73I-eJ3fq0adaOkg

In fact, it's not even the same channel that comes up if you type in youtube.com/mkbhd . So there's not really any perfect solution.

**Comment by ThioJoe** [comment]
Gonna close this because it's probably not feasible based on the reasoning I gave above
