### ISSUE TITLE
Filtering: (Decode the base64 strings)

### ISSUE THREAD

**Issue by DasDirt** [ThioJoe/YT-Spammer-Purge#632]
### Filter Mode

Auto-Smart Mode

### Select the Problem

Other (add details below)

### (Optional) If 'Other', Enter Very Short Description

Decode the unnecessary base64 encoded arrays

### Spammer Example / Sample

[Decoded.txt]

I have added a file in which almost all the arrays are decoded.
Why are they encoded at all?
And the line utf_16 = "utf-8" is a bit confusing and should be renamed

**Comment by Firecul** [comment]
https://github.com/ThioJoe/YT-Spammer-Purge/pull/622#issuecomment-1034288838
> no, it's there for a specific reason for the foreseeable future

- ThioJoe

**Comment by Firecul** [comment]
> it might not be what you were hoping 
 
 ### 🤔
