### ISSUE TITLE
[Bug]: X-2 error on exclude comment

### ISSUE THREAD

**Issue by Firecul** [ThioJoe/YT-Spammer-Purge#633]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

I scanned the url from #528 just for kicks and found (in my opinion) a false positive, I tried to exclude it and got an X-2 crash.
This seems to be due to my config having the `whitelist_excluded = False` set, when I returned this to `Ask` and did the same again the program performed as expected.

### Release version

v2.15.1

### Steps to reproduce

1. Set `whitelist_excluded = False` in your config
2. Scan https://www.youtube.com/watch?v=ItxIvVH3T6o
3. Try to exclude a comment, I excluded Mike # 35
4. Crash on pressing enter.

### What platform are you seeing this problem on?

Windows (.py script)

### Screenshots

![Code_SpamPurgeConfig ini_-_Visual_Studio_Code (2)](https://user-images.githubusercontent.com/34950371/153691019-1d4c9c67-c00c-4b24-905d-ac9999b414bc.png)

![WindowsTerminal_Windows_PowerShell (22)](https://user-images.githubusercontent.com/34950371/153691000-aec6c039-a215-47a2-a568-bfcf95f0de07.png)

**Comment by rachmadaniHaryono** [comment]
related to #536 

this is one of several variable that pyright marked as possibly unbound

**Comment by Firecul** [comment]
> related to #536
> 
> this is one of several variable that pyright marked as `possibly unbound`

I did not even remember that PR I'm embarrassed to say.

**Comment by ThioJoe** [comment]
Ah doh, I had it checking for the config value of 'True' and 'False' as strings instead of booleans...

Should be fixed with https://github.com/ThioJoe/YT-Spammer-Purge/commit/dedb10728f6f653324db521126c9fdf5d6305908 , I'll make a release soon

**Comment by rachmadaniHaryono** [comment]
as far as i can tell you get config directly from ini file and there is no conversion around `whitelist_excluded` config

so you get string and you check it directly with bool on https://github.com/ThioJoe/YT-Spammer-Purge/commit/dedb10728f6f653324db521126c9fdf5d6305908

this bug may also be caused because `whitelist_excluded` is default to `Ask` but you check for `ask`

**Comment by Firecul** [comment]
> this bug may also be caused because whitelist_excluded is default to `Ask` but you check for `ask`

That also wouldn't help.

**Comment by rachmadaniHaryono** [comment]
recommendation

- use https://docs.python.org/3/library/enum.html#enum.unique for value because multi state value
- check config for valid value

quick google search give me this discussion https://news.ycombinator.com/item?id=22964910, which have multiple way/tool to validate the config

**Comment by ThioJoe** [comment]
> > this bug may also be caused because whitelist_excluded is default to `Ask` but you check for `ask`
> 
> That also wouldn't help.

Nah the program converts all the config setting strings to lower case so that's why it checks for 'ask' instead of 'Ask'. Except for some settings where I've specified to not change the case, like here: https://github.com/ThioJoe/YT-Spammer-Purge/blob/main/Scripts/files.py#L446

Also for config values that are True/False it converts them to bools

**Comment by ThioJoe** [comment]
> as far as i can tell you get config directly from ini file and there is no conversion around `whitelist_excluded` config

actually it does: https://github.com/ThioJoe/YT-Spammer-Purge/blob/153a30ce13aa9eeaec16e6e795ffe59e9b0292c7/Scripts/files.py#L456

**Comment by rachmadaniHaryono** [comment]
i am wrong then. 

can you refactor it? maybe i can add unittest for that
