### ISSUE TITLE
[Bug]: Timeout Error once we're Ready to Report (Z-3)

### ISSUE THREAD

**Issue by lloyddunamis** [ThioJoe/YT-Spammer-Purge#635]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [X] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Resuming from #567.
Scanning options Involved: `1` `2`
Unaffected: `4` `5`
Partially Tested: `3`

What changed from bug567?
From my testing, it seems it's affecting only the reporting part now. It's no longer timing out on any other YT-querying part, like I was able to back there and in [#567 Comment 2-3](https://github.com/ThioJoe/YT-Spammer-Purge/issues/567#issuecomment-1030638601).
Scan methods 4 & 5 are unaffected. For method 3, my channel doesn't have spam to test further to the point of reporting; the pre-reporting steps seem unaffected.

1. **Scan**  _(commonly others' videos/channels)_
2. **Review**  _(opening the log file on the side on one's favorite text/word processor to make use of search & move around the log from bottom to the referenced spam above)_
3. **Report**
...except it's unable to report; because it's taken us time to review the filtered spam, YT may have decided to timeout the connection and thus unable to issue the report commands...in my observation.

Has happened too many times to be ignored. As a result/workaround, we have to open the script/program again and do the same scanning to be able to report it.
Requesting for a "load from logfile as a savepoint" feature (#391) is not viable for loading from logs involving videos we don't own (#569); understandably so.

<s>Is there a way that the script could automatically reset the timeout every 5 minutes or so? Like some kind of separate thread counting down to 5mins to query a YT API or something.</s> ...but this is a script so it can't be doing two things at a time.
Another, maybe easier, option would be to refresh the timeout when it receives this timeout error _(like previously suggested)_.
This is so that we won't have to start the scan & repeat the review process all over again, for any possible changes that renders "the previous scan's number range/s to report" useless.

_(painfully rewritten after a BSOD forcibly cleared the forms, form saver add-on not entirely saving it)_

### Release version

2.16.0-Beta1

### Steps to reproduce

1. Scan any channel that isn't yours w/ known spam.
2. Idle for 8 minutes or so, on the review spam/before typing "report" part.
3. Enter. Wait for 1 minute, then error should appear.

### What platform are you seeing this problem on?

Windows (.exe file)

### Relevant log output

```shell
Traceback (most recent call last):[0 / 2220] (In Groups of 50)
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1650, in <module>
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1627, in main
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1576, in primaryInstance
  File "Scripts\operations.py", line 942, in delete_found_comments
  File "Scripts\operations.py", line 907, in setStatus
  File "googleapiclient\_helpers.py", line 131, in positional_wrapper
  File "googleapiclient\http.py", line 922, in execute
  File "googleapiclient\http.py", line 221, in _retry_request
  File "googleapiclient\http.py", line 190, in _retry_request
  File "google_auth_httplib2.py", line 218, in request
  File "httplib2\__init__.py", line 1725, in request
  File "httplib2\__init__.py", line 1441, in _request
  File "httplib2\__init__.py", line 1393, in _conn_request
  File "http\client.py", line 1368, in getresponse
  File "http\client.py", line 317, in begin
  File "http\client.py", line 278, in _read_status
  File "socket.py", line 705, in readinto
  File "ssl.py", line 1273, in recv_into
  File "ssl.py", line 1129, in read
TimeoutError: The read operation timed out
------------------------------------------------
Error Message: The read operation timed out

Unknown Error - Code: Z-3 occurred. If this keeps happening, consider posting a bug report
```

### Screenshots

After idling (12m this instance), scan
![image](https://user-images.githubusercontent.com/6012867/153709730-4f318dd7-400a-46ad-a1a3-db308cd18aa4.png)
1min after
![image](https://user-images.githubusercontent.com/6012867/153709768-2a4279a5-12ca-434f-805b-efad2ab2b80e.png)

**Comment by Firecul** [comment]
I cannot reproduce with the py version, I left it for 20 minutes (my laptop even went to sleep.)
I'll try the exe when I can in a few hours.

**Comment by ThioJoe** [comment]
Hm that seems odd. I'm not familiar with how the connection handling happens in the background, but the program itself doesn't really do anything to keep a connection open. Each query and response to the API is a separate thing, so I wouldn't think it would make any difference how long it takes to review the results

**Comment by Firecul** [comment]
Unable to reproduce with the .exe (v2.15.2)
Launched the scan, left it for 17 minutes, typed `report` hit enter and it worked as expected.


![YTSpammerPurge 2 15 2_CUsersfirecDocumentsGitHubYT-Spammer-PurgeY](https://user-images.githubusercontent.com/34950371/153732489-38c3fbca-4592-42c6-912d-2875fa90f0b9.png)


I'll try a few more things, see if I can figure out how to do it.

**Comment by ThioJoe** [comment]
I've found in some cases recently, deleting comments does take a decent amount of time for the API to respond with success for each 50-block. But it's only like 10 seconds tops each. And when reporting it usually goes through them extremely fast with no delay.

So maybe the reporting / deleting calls are just more prone to being delayed? I'll have to look up if maybe there's a way to increase the time before it considers it a timeout

**Comment by ThioJoe** [comment]
Gonna assume this is solved

**Comment by ThioJoe** [comment]
Hm ok

**Comment by ThioJoe** [comment]
Is this issue still happening?
