### ISSUE TITLE
[Bug]: Odd error traceback

### ISSUE THREAD

**Issue by Firecul** [ThioJoe/YT-Spammer-Purge#637]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Trying to replicate the error in #635 by disconnecting my network between scanning and reporting I found an interesting error message. 
The first type of error was expected (it couldn't connect to google API) 

![YTSpammerPurge 2 15 2_CUsersfirecDocumentsGitHubYT-Spammer-PurgeY (2)](https://user-images.githubusercontent.com/34950371/153733026-b3df0e08-12fc-408e-98f0-baf0d106c27c.png)

The second error though, refers to a location I don't have and I suspect most don't. 

![YTSpammerPurge 2 15 2_CUsersfirecDocumentsGitHubYT-Spammer-PurgeY (3)](https://user-images.githubusercontent.com/34950371/153733131-c287832a-414b-436c-8f97-f73d3f3a4989.png)

I don't see where this is hard-coded in so I imagine this is from the building process.

### Release version

v2.15.2

### Steps to reproduce

1. Scan a video using the exe version
2. disconnect your network
3. try to report

### What platform are you seeing this problem on?

Windows (.exe file)

**Comment by guywhoreportsissues** [comment]
I don't think you can report without internet. You need internet to access youtube. Google, GoogleAPI etc

**Comment by ThioJoe** [comment]
> I don't think you can report without internet. You need internet to access youtube. Google, GoogleAPI etc

Indeed, in this issue though I think he just mentioned that as context, and the main point is the traceback mentioning the path `D:\Users\Joe` ...

There was another issue where a similar thing was happening, I thought I fixed it by changing the path in the pyinstaller spec file that builds it, maybe it's somewhere else too

**Comment by Firecul** [comment]
> I also believe this is just cosmetic and shouldn't affect anything, considering the traceback shows the rest of the functions after that worked fine.

I think you are right, just bringing it to your attention for something that could be improved/fixed.

**Comment by guywhoreportsissues** [comment]
It might have been fixed now. I closed my issue since mine got fixed. Api-problem is fixed. Please try Version 2.15.4

**Comment by Firecul** [comment]
> It might have been fixed now. I closed my issue since mine got fixed. Api-problem is fixed. Please try Version 2.15.4

Your issue isn't related to this one. I barely call mine an issue tbh but there isn't a less formal way of bringing this up for ThioJoe to look at.

**Comment by EthanHindmarsh** [comment]
This is not an error, 
Its purpose is to assist the developer in debugging, not the user.

> I also believe this is just cosmetic and shouldn't affect anything, considering the traceback shows the rest of the functions after that worked fine. So it might just be a variable name for the file, but might not be used for calling? idk

It tells you the locations and names of the functions that were *imported from the build computer* during the build, so the user does not have to install anything to run the .exe
The .exe does not check if the user has any of the dependencies installed, as it does not `import` any files from the user's computer.

This is not an issue, and this is not a cosmetic error👍
