### ISSUE TITLE
[Bug]: NOT ABLE TO RUN

### ISSUE THREAD

**Issue by guywhoreportsissues** [ThioJoe/YT-Spammer-Purge#643]
### Duplicate Issues

- [x] There are **no existing posts relating to my problem**
- [x] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

I opened the app as I do usually worked well. Recently did a update to Windows Terminal using winget. The next day Its not able to authorize itself. Token.pickle file is deleted did not work. Created a whole new project and followed your instructions did not work. The app simply isn't working anymore. 

### Release version

2.15.2

### Steps to reproduce

1. Open the app
2. Verify (OAuth consent screen)

### What platform are you seeing this problem on?

Windows (.exe file)

### Screenshots

![2](https://user-images.githubusercontent.com/86945563/153766967-752bc6d8-0172-4348-99bd-4ffe8692a6fa.png)
![1](https://user-images.githubusercontent.com/86945563/153766970-1e918c02-3bfd-47da-8444-8545fbf3302a.png)

**Comment by TechStudent11** [comment]
Looks like an internet or API issue

**Comment by TechStudent11** [comment]
Have you changed accounts or disconnected the project recently? Have you done **EVERY** step in the wiki?

**Comment by ThioJoe** [comment]
Hmm, considering it worked before it's kind of odd. Does it work if you run it without the new terminal, and just by clicking the .exe / with the old cmd window?

**Comment by Kurdakov** [comment]
in forum other user complains for oauth timeout, so likely it's not related to terminal update, rather some problems on google side

**Comment by ThioJoe** [comment]
Yea possibly related to #635 as well

**Comment by guywhoreportsissues** [comment]
I recently updated windows terminal. I don't think I can roll it back.

**Comment by guywhoreportsissues** [comment]
sorry for the late reply everyone

**Comment by guywhoreportsissues** [comment]
related to issue #637 and #651

**Comment by guywhoreportsissues** [comment]
> Hmm, considering it worked before it's kind of odd. Does it work if you run it without the new terminal, and just by clicking the .exe / with the old cmd window?

Can you elaborate on that sir?

**Comment by guywhoreportsissues** [comment]
I changed the settings to automatically go windows terminal instead of windows console host.

**Comment by guywhoreportsissues** [comment]
the first few times I used windows terminal that is

**Comment by guywhoreportsissues** [comment]
> Looks like an internet or API issue

I think its api

**Comment by guywhoreportsissues** [comment]
> Have you changed accounts or disconnected the project recently? Have you done **EVERY** step in the [wiki](https://github.com/ThioJoe/YT-Spammer-Purge/wiki)?

no. I haven't disconnected the project or account. Created a whole new project and tried again but it didn't work. I followed the new video that Thio Joe created. https://www.youtube.com/watch?v=2tRppXW_aKo&t=319s

**Comment by guywhoreportsissues** [comment]
Yes every step in the wiki has been followed.

**Comment by guywhoreportsissues** [comment]
Fixed in 2.15.4

**Comment by guywhoreportsissues** [comment]
Fixed by Google actually. Working in older versions too.

**Comment by DinhHuy2010** [comment]
the program still work on the Windows Terminal (Windows 10)
