### ISSUE TITLE
Cannot delete comments

### ISSUE THREAD

**Issue by LapizMsI0Tech** [ThioJoe/YT-Spammer-Purge#650]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Well, I was trying to delete but then failed.

### Release version

2.15.3

### Steps to reproduce

1. Open YTSpammerPurge.2.15.3.exe, wait for it to load and type 7.
2. Use a random log file with .txt format.
3. Try to delete them by typing 1 in the program.
4. Don't ban the commenters by typing "n"

### What platform are you seeing this problem on?

Windows (.exe file)

### Screenshots

![image](https://user-images.githubusercontent.com/99629154/153795667-ca3ad851-abe5-4a23-ae57-b585983d9880.png)

**Comment by ThioJoe** [comment]
Yep that's an oops. Should be fixed with the latest new release, 2.15.4

Fixed via https://github.com/ThioJoe/YT-Spammer-Purge/commit/d5d943a3f9752c00dd190536453db04d0200ff7e
