### ISSUE TITLE
[Bug]: Original Comment IDs displaying after report entered

### ISSUE THREAD

**Issue by Firecul** [ThioJoe/YT-Spammer-Purge#656]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

I was verifying #654 was fixed and after typing `report` on the comments I had not excluded It proceeded to list some comment IDs  for me from the stolen comments. 

### Release version

v2.16.0-Beta3

### Steps to reproduce

1. `stolen_comments_check_modes = AutoSmart, SensitiveSmart` in config file
2. I scanned `https://www.youtube.com/watch?v=E1zLaK1TH54` with auto-smart
3. excluded a couple of comments
4. `report` the rest

### What platform are you seeing this problem on?

Windows (.py script)

### Screenshots

![WindowsTerminal_Windows_PowerShell (30)](https://user-images.githubusercontent.com/34950371/153976042-f3deb6b6-5e05-4672-b203-b138209a6343.png)

**Comment by ThioJoe** [comment]
oops, looks like I put that one indentation too far left

**Comment by Firecul** [comment]
Indentation will get you in Python 😉

**Comment by ThioJoe** [comment]
Should be fixed now

**Comment by Firecul** [comment]
> Should be fixed now

It is, I was using the .py version with your fix for this since I saw it.
