### ISSUE TITLE
[Bug]: Loading log file of other channels comments only gives you options related to your channel

### ISSUE THREAD

**Issue by RooRay** [ThioJoe/YT-Spammer-Purge#661]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

**What happened**:
I disconnected my internet to do something while scanning comments on another youtubers account (and the program failed to connect to the YouTube APIs as expected) and was prompted to make a log file so when I did and loaded the log file to report the malicious comments after I reconnected my internet I did not get the option to, only to delete them which gave me an error as I didn't own the channel the comments were related to. 

**What should've happened**:
Should have had the option to report the comments and the other not-your-channel features.

### Release version

2.15.0

### Steps to reproduce

1.  Scan for comments on someone elses channel and disconnect your internet
2.  When given the option to, save them as a log file
3.  Reconnect your internet and load the log file
4. Note how the software assumes it is your channel and only gives you the options to delete the comments (which would result in an error)

### What platform are you seeing this problem on?

Windows (.exe file)

### Screenshots

![image](https://user-images.githubusercontent.com/86845749/154137863-12e50ad9-b25c-4ac9-a07a-5b9859bd3246.png)

**Comment by Firecul** [comment]
As in #588 and #569, Basically, it opens up for abuse by potentially using the more in-depth tools to log your keyword of choice then using that log to mass report.
