### ISSUE TITLE
Filtering: "ratio", "L", and others are detected as spam comments

### ISSUE THREAD

**Issue by justkamiii** [ThioJoe/YT-Spammer-Purge#663]
### Filter Mode

Auto-Smart Mode

### Select the Problem

False Positive

### Spammer Example / Sample

![image](https://user-images.githubusercontent.com/84019509/154176982-e1251913-4464-4905-bae5-8f4438d51f5f.png)

### Video / Post Link

https://www.youtube.com/watch?v=bSSUg00RIeE

### (Optional) Additional Info / Context

~~Just the normal vocabulary of a Twitter user~~

**Comment by justkamiii** [comment]
While it is kind of spammy to send L's and some "offensive" comments, I don't think this is supposed to be on the margin of YT-Spammer-Purge

**Comment by justkamiii** [comment]
Alright. Should I close this and move my findings into 618?

**Comment by ThioJoe** [comment]
Ok I've addressed this in the latest release, 2.16.0
