### ISSUE TITLE
Filtering: Missed Spammers

### ISSUE THREAD

**Issue by Mous3kteer** [ThioJoe/YT-Spammer-Purge#670]
### Filter Mode

Auto-Smart Mode

### Select the Problem

Some spammers not detected

### Spammer Example / Sample

![image](https://user-images.githubusercontent.com/52615946/154539722-817e6103-4da2-464b-b14d-51c7a02ac7b2.png)
![image](https://user-images.githubusercontent.com/52615946/154539825-afe0e0a2-0fef-4bf4-ab7d-1ccee00f48ff.png)

### Video / Post Link

https://www.youtube.com/watch?v=U9KnNktuZnM

### (Optional) Additional Info / Context

Didn't see too many of them, but Auto-Smart didn't pick them up and I figured it probably should.

**Comment by Firecul** [comment]
I've already made an [issue](https://github.com/ThioJoe/YT-Spam-Lists/issues/87) to update the lists to include that one.

**Comment by ThioJoe** [comment]
I've also added some filtering in 2.16.3 for these
