### ISSUE TITLE
Filtering: Missing a type of youtube link spammers

### ISSUE THREAD

**Issue by tillepprecht** [ThioJoe/YT-Spammer-Purge#680]
### Filter Mode

Sensitive-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

![grafik](https://user-images.githubusercontent.com/31342983/154655997-8a27860e-f1c3-42d1-b4e9-92b37801365e.png)

![grafik](https://user-images.githubusercontent.com/31342983/154656064-029e8be2-86a1-4d20-aaad-4fe11e2d0822.png)

![grafik](https://user-images.githubusercontent.com/31342983/154656137-9b2b9df4-f532-485b-b84f-710fd6169849.png)

![grafik](https://user-images.githubusercontent.com/31342983/154656488-49847a57-1868-4b62-bbed-6ab2a18e45e2.png)

### Video / Post Link

https://www.youtube.com/watch?v=EnQE-QY42ek

### (Optional) Additional Info / Context

I'm guessing these are gonna be quite hard to detect without generating false positives with their plain names (except for Dream 🅥 i guess) and short messages that could also just be people providing a link for a video someone asked for 🤔

**Comment by ThioJoe** [comment]
Yea, honestly the best way for creators to avoid this type of spam is to disable hyperlinks in their comments section

**Comment by KendallDoesCoding** [comment]
@tillepprecht Is this on  your video?

**Comment by Firecul** [comment]
As the links above should be caught in the main lists now (https://github.com/ThioJoe/YT-Spam-Lists) this issue can probably be closed, if you have more URLs to submit please do that in the other repo.

**Comment by ThioJoe** [comment]
The new filtering method should be able to detect these going forward, but I'll have to add the phrases as they show up. The other spam list will also help
