### ISSUE TITLE
[Suggestion] better feedback with comment list and more...

### ISSUE THREAD

**Issue by AlecMcCutcheon** [ThioJoe/YT-Spammer-Purge#682]
### Filter Mode

Auto-Smart Mode

### Select the Problem

Other (add details below)

### (Optional) If 'Other', Enter Very Short Description

Not actually just for this mode but this is the most used and most polished.

### Spammer Example / Sample

... just suggestions ... Don't have any comments in question, I can provide those at some point down the line though

### (Optional) Additional Info / Context

My first suggestion would be that whenever you exclude comments, that it shows you an updated list after the executing of the comments instead of just asking you what you want to do with the comments that are left. This would make it easier to exclude in the first place, it would make stuff easier to ingest because you could easily just pick out ranges, clear them out, see an updated list and continue. Also, I think there should be more options with deleting and or reporting, it would be great if there was a reverse of the exclude option for deleting and reporting so that you could actually pick out all of the comments that you want to report instead of just reporting whatever is left after excluding. It also be great if there was an option to completely ignore x1 comments as I was running this a lot lately on the recommended mode, and I will say I saw a lot more than nearly 0% false positives, and almost 90% of the false positives I saw were in the x1 category. Obviously, that means you're going to miss some scammers but it would reduce the casualties. Maybe we could even make another report option that would allow you to report all except x1 and then you can choose to either go back through that list of x1manually or just ignore them. also this might be a hard ask but I've had instances where my API maxed out while I was in the middle of reporting comments and it would be great to be able to save the list of what's left to report for later when the API renews and or allow transfer of the rest to another instance of the bot, and it would also be cool to see a number of how many comments you were able to report before it was maxed out. Also I'm not sure if this is doable cause I'm not very familiar with the API but you should have the option to choose whether you want to run it in Reporting mode or personal mode and not have to have an account with a channel attached to it to be able to report, I would think that you wouldn't have to actually have a channel to be able to still report comments, so for people like me that only are using it to help others out, I don't see why making a channel for my account or my dummy accounts is necessary . Apologies if there's any mistyping errors, I'm using voice to text and I'm dyslexic so My proofreading skills are not great. also just wanted to say you guys are awesome, and I hope I can do my part to help out the cause, going to be hosting events pretty regularly to stream the program on my discord and also take suggestions from my community on who could use some help. I'm super impressed with how much you can send and receive in just a single API request, great job guys!

**Comment by AlecMcCutcheon** [comment]
> Yea some of the suggestions are ones I've thought about. I could probably add a thing to update the sample list after excluding, it would just be a bit more work than it seems.
> 
> > it would be great if there was a reverse of the exclude option for deleting and reporting so that you could actually pick out all of the comments that you want to report instead of just reporting whatever is left after excluding
> 
> You can actually already do that, with the "only" command instead of exclude <img alt="image" width="807" src="https://user-images.githubusercontent.com/12518330/154745310-a8e6ef0e-923f-465b-b147-12e09c624961.png">


Oh sweet, I totally missed that, and I'm sure it definitely takes a lot of work, I write code on a daily basis but it's usually PowerShell, Java, or (HTML, JavaScript, CSS), for patching or other similar purposes, not Python And the few times I've used/coded in Python it was definitely an adventure lol.

**Comment by Firecul** [comment]
> I saw a lot more than nearly 0% false positives, and almost 90% of the false positives I saw were in the x1 category

Can you show us a log of examples of that with the false positives?

**Comment by AlecMcCutcheon** [comment]
> Can you show us a log of examples of that with the false positives?

Do you want the entire log files or just a specific part of it? I don't have the log files currently of the original scans that I noticed The false positives on. But while I was running a scan last night, there were a few that I was noticing, mainly I think the question/issue with all of it is that. It seems to flag user names that are not appropriate or suspicious, but in that particular video, the comments left by those particular people do not seem to be scams, just general reaction to the video. So it kind of becomes a question of is it acceptable for people with those kind of usernames to leave harmless comments/ reactions and. Interact with Youtubers in general. Or because they have a bad user name, should they just be reported Anyway? Which is morally the correct answer?  IDK

**Comment by jingofett** [comment]
> Yea some of the suggestions are ones I've thought about. I could probably add a thing to update the sample list after excluding, it would just be a bit more work than it seems.
> 
> > it would be great if there was a reverse of the exclude option for deleting and reporting so that you could actually pick out all of the comments that you want to report instead of just reporting whatever is left after excluding
> 
> You can actually already do that, with the "only" command instead of exclude <img alt="image" width="807" src="https://user-images.githubusercontent.com/12518330/154745310-a8e6ef0e-923f-465b-b147-12e09c624961.png">

Is it possible to exclude when running from a saved list (option 7. Remove comments using a pre-existing list or log file)? i reported all comments first (after excluding 3 entries), and I have the saved list to delete and ban the reported comments, but I'm not sure if it will give me the option to exclude after I enter in yes. Also is there a way to report, delete, and then ban without having to use the list/re-scanning?

**Comment by ThioJoe** [comment]
Old thread but probably not going to update this functionality for the time being
