### ISSUE TITLE
Filtering: fase positive 

### ISSUE THREAD

**Issue by menzo2003** [ThioJoe/YT-Spammer-Purge#686]
### Filter Mode

Auto-Smart Mode

### Select the Problem

False Positive

### Spammer Example / Sample

Yeah, both my brother and I are waiting for them to put in co-op before we play the campaign. The first play through has always been co-op on legendary since the OG (except Halo 5 because neither of us touched that garbage).

### Video / Post Link

https://www.youtube.com/watch?v=2QduDV8h7Ts&lc=Ugzf1OANVaiB9JsynPx4AaABAg

**Comment by ThioJoe** [comment]
Ah ok I figured out the issue, just added a new commit so it will be fixed in the next release

**Comment by ThioJoe** [comment]
Alright the new release 2.16.3 has this fixed
