### ISSUE TITLE
Filtering: Some Porn Bots not caught in main detection(though duplicate still hits them)

### ISSUE THREAD

**Issue by gregovin** [ThioJoe/YT-Spammer-Purge#694]
### Filter Mode

Auto-Smart Mode

### Select the Problem

Some spammers not detected

### Spammer Example / Sample

https://www.youtube.com/watch?v=VM1CbIbCdHE&lc=Ugys7EqDov4i6ADV1X54AaABAg.9YbqxzBXNoY9Ybr8x58c7X

### Video / Post Link

https://youtu.be/VM1CbIbCdHE

**Comment by ThioJoe** [comment]
Ok added via spam lists
