### ISSUE TITLE
Filtering: A kind of "subscribe" spam is not found

### ISSUE THREAD

**Issue by vedurk** [ThioJoe/YT-Spammer-Purge#695]
### Filter Mode

Sensitive-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

It is in the form of:

> I really love it when the notification says "someone liked your comment" and "someone subscribed to your channel",.

..or with some variation of that:

> I really love it when the notification says "**_somone_** liked your comment" and "**_somone_** subscribed to your channel"

..or (from Google search):

> I really love it when the notification shows up someone liked your comment and you have a new subscriber

It is a rather subtle one and not entirely sure of its purpose, as not all of these channels seem to have content.

Usually I would have dismissed it as a one-off thing but googling _"I really love it when the notification"_ apparently gave apparently 332 000 results, although only 4 pages were shown.

![Spam_Log_2022-02-24_00-53-19 pic](https://user-images.githubusercontent.com/51442956/155431539-01e85655-e94f-4ac8-bfc0-7af0728b0a8d.PNG)

### Video / Post Link

https://www.youtube.com/watch?v=t-BZJbGqLGg&lc=Ugz-ywFVoglDabxWyq54AaABAg

### (Optional) Additional Info / Context

Version 2.16.4

**Comment by ThioJoe** [comment]
These types of comments are really hard to detect because they don't really have any distinguishing features

**Comment by vedurk** [comment]
Fair enough. Seems to a bit more in the grey area anyway.

**Comment by Firecul** [comment]
> Fair enough. Seems to a bit more in the grey area anyway.

I wouldn't personally call that in the grey area, it's 100% spam in my eyes
