### ISSUE TITLE
Update config file on linux. 

### ISSUE THREAD

**Issue by YuvanMichael** [ThioJoe/YT-Spammer-Purge#700]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

I was trying to update the program on linux. But after updating it didn't tell me about an old config file like it usually does in windows. 

### Release version

 2.15.4 and above

### Steps to reproduce

1. Install the program on linux an older version.  
2. Try to update. 
3. After updating, exit the terminal. And start the program again. 
4. It doesn't tell you about an old config file. 

### What platform are you seeing this problem on?

Linux (can also be ChromeOS)

**Comment by EthanHindmarsh** [comment]
Can you describe the issue in more detail?
I'm not sure what the bug is here

**Comment by YuvanMichael** [comment]
In windows, When you update the program it tells you that the config file is out of date. And update it after we say yes. Also, I have use this config set to True in my config file.

**Comment by YuvanMichael** [comment]
So why is this this not happening in linux? This is more of a bug and a question at the same time.

**Comment by YuvanMichael** [comment]
Also, now I have another problem issue #739

**Comment by YuvanMichael** [comment]
issue #739 fixed.

**Comment by YuvanMichael** [comment]
> So why is this this config file update not happening in linux? This is more of a bug and a question at the same time.

This is my problem

**Comment by YuvanMichael** [comment]
Also, how is using ./install.sh different than using number 9 as update option.

**Comment by EthanHindmarsh** [comment]
Install.sh is really meant for installation only, but updating through
install.sh should cause no issues as long as the script was also installed
through install.sh (or was `git clone`d)
The updating functionality of install.sh is done through a `git checkout`
of the latest release version, and may not work if you made local changes
to the code (changes may need to be `git stash`ed before checking out
latest)

RE: Yuvan
I'm not sure how updating in the python script is implemented
I will check out the python script 👍

RE: Compsup
install.sh will not overwrite config files, but it may fail if they exist
I will check again to make sure of this, and submit a PR if it actually
does overwrite config files 😁

**Comment by EthanHindmarsh** [comment]
In Scripts/files.py: 
https://github.com/ThioJoe/YT-Spammer-Purge/blob/a2093a3102946c60d78d052936a16b162e56007e/Scripts/files.py#L121-L122

Here is the prompt I believe you are talking about:
https://github.com/ThioJoe/YT-Spammer-Purge/blob/a2093a3102946c60d78d052936a16b162e56007e/Scripts/files.py#L174-L178

The only times I see check_for_update called are the update option:
https://github.com/ThioJoe/YT-Spammer-Purge/blob/3d92b7a353d54c54fb2ca19a606982645631e2c6/YTSpammerPurge.py#L894-L898
And as part of the config:
https://github.com/ThioJoe/YT-Spammer-Purge/blob/3d92b7a353d54c54fb2ca19a606982645631e2c6/YTSpammerPurge.py#L221-L223



In `check_for_update`, the script checks if the platform is windows:
https://github.com/ThioJoe/YT-Spammer-Purge/blob/a2093a3102946c60d78d052936a16b162e56007e/Scripts/files.py#L180

If not, fail:
https://github.com/ThioJoe/YT-Spammer-Purge/blob/a2093a3102946c60d78d052936a16b162e56007e/Scripts/files.py#L284-L287


So, this is not a bug, but more documentation could be helpful to make it clearer that updating inside the python script is windows-only, and that unsupported systems (linux, MacOS) should use `install.sh` or update manually

**Comment by YuvanMichael** [comment]
> In Scripts/files.py:
> 
> https://github.com/ThioJoe/YT-Spammer-Purge/blob/a2093a3102946c60d78d052936a16b162e56007e/Scripts/files.py#L121-L122
> 
> https://github.com/ThioJoe/YT-Spammer-Purge/blob/a2093a3102946c60d78d052936a16b162e56007e/Scripts/files.py#L174-L178
> 
> Is this the prompt you are talking about?
> 
> There is also a check for the config.ini being out of date, do you mean this one?
> 
> https://github.com/ThioJoe/YT-Spammer-Purge/blob/f7fc6b351a8deb2ab30730c9b0ea8fd6e8b1282e/Scripts/files.py#L492
> 
> 
> https://github.com/ThioJoe/YT-Spammer-Purge/blob/f7fc6b351a8deb2ab30730c9b0ea8fd6e8b1282e/Scripts/files.py#L504-L506

The second one.

**Comment by YuvanMichael** [comment]
check for config.ini being out of date

**Comment by YuvanMichael** [comment]
Where I have to hit enter to update config file.

**Comment by YuvanMichael** [comment]
yeah so, point is. Is there a reason for why this is not happening on linux? Or is it a bug? I think that since its python. It should work on all operating systems. As long as you have python installed.

**Comment by YuvanMichael** [comment]
This is interesting... 
The code in your comment is not there in the .py file I got. 
screenshots taken from YTSpammerPurge.py The main python executable. 

![Screenshot from 2022-03-16 13-10-47](https://user-images.githubusercontent.com/86945563/158541232-61555fd2-c9b8-4f5f-9020-febc820256c9.png)
![Screenshot from 2022-03-16 13-12-17](https://user-images.githubusercontent.com/86945563/158541237-fad6cd72-0e57-430a-8b6e-c44e083ef814.png)
![Screenshot from 2022-03-16 13-14-19](https://user-images.githubusercontent.com/86945563/158541244-c4458189-22c8-46ab-be1a-ea92387c697c.png)
![Screenshot from 2022-03-16 13-15-13](https://user-images.githubusercontent.com/86945563/158541257-16122458-9214-4b61-91dc-71b844595324.png)

**Comment by YuvanMichael** [comment]
Here's the whole .py file.
[YTSpammerPurge.zip](https://github.com/ThioJoe/YT-Spammer-Purge/files/8259931/YTSpammerPurge.zip)

Extract it.

**Comment by EthanHindmarsh** [comment]
As for why it is not happening on Linux, I'm not completely sure at the
moment. I'm not sure why the config version check would not be called

**Comment by EthanHindmarsh** [comment]
The code would not be in YTSpammerPurge.py, it is `import`ed from the
`Scripts/files.py`:
Line 48 in your YTSpammerPurge.py
"import Scripts.files as files"

**Comment by YuvanMichael** [comment]
Here it is
![Screenshot from 2022-03-17 16-45-50](https://user-images.githubusercontent.com/86945563/158797733-ca1a7ebf-e65c-4707-b2e7-36b54d5a59ce.png)

**Comment by YuvanMichael** [comment]
I do have use this config enabled to true. But it should still update the config right?

**Comment by compsup** [comment]
Question is does the config file need to be updated? Not every version has a config file update.

**Comment by Firecul** [comment]
> Question is does the config file need to be updated? Not every version has a config file update.

That is a very good point that didn't even pop into my head.
It would depend on which version you were moving from and what version you were moving to, if the config version for both is the same then you wouldn't get a prompt.

**Comment by EthanHindmarsh** [comment]
> Question is does the config file need to be updated? Not every version has a config file update.

Yes, good catch
@YuvanMichael Could you upload the config file? Are you 100% sure the config version is out-of-date?

**Comment by Firecul** [comment]
`v2.15.4` he mentions above which would have been config version 26, but at the time of posting this issue, `v2.16.4` was the up to date version with the config version being 31 by then. 
I think we just need more info, what he is/was moving from and too.

**Comment by YuvanMichael** [comment]
> > Question is does the config file need to be updated? Not every version has a config file update.
> 
> Yes, good catch @YuvanMichael Could you upload the config file? Are you 100% sure the config version is out-of-date?

Ok. But, I'm not 100% sure about the config version. My config version is 31.

**Comment by YuvanMichael** [comment]
I always get config updates on windows. If I remeber correctly, it should update the config file at least if there is a new version. Example: 2.16 to 2.17

**Comment by YuvanMichael** [comment]
[SpamPurgeConfig.zip](https://github.com/ThioJoe/YT-Spammer-Purge/files/8313499/SpamPurgeConfig.zip)
Here you go. :)

**Comment by YuvanMichael** [comment]
> `v2.15.4` he mentions above which would have been config version 26, but at the time of posting this issue, `v2.16.4` was the up to date version with the config version of that being 31 by then. I think we just need more info, on what he is/was moving from and too.

Sorry guys, bit of a blunder here. When I said version 2.15.4 I meant that I started using it on linux but, I didn't get a conifg update. On windows I did.

**Comment by YuvanMichael** [comment]
yeah, maybe it kind of updated it silently without asking me that is. 🤔

**Comment by YuvanMichael** [comment]
I guess we could just put a config update that says something like config_updated_report = True. I guess it would be cool to add it and see if it updates the config file. Without asking me. If that's the problem we can just put a confirmation prompt up.

**Comment by YuvanMichael** [comment]
Also, I think it would be cool to add a gui. Although, the command line is pretty good. If not perfect.

**Comment by YuvanMichael** [comment]
Hello?

**Comment by EthanHindmarsh** [comment]
Re: Yuvan

Hello,

Is there any other issue?

If you're requesting a feature it would be better to open a discussion 👍

I agree that it should be clearer about when the config file is updated /
up to date, but I'm not sure that is not a bug, since it did somehow at
some point get you the latest config version without error.

It is definitely weird that you were never prompted, I'm not sure why it
did not prompt you 🤔

**Comment by YuvanMichael** [comment]
yeah, also umm. I guess you saw my pull request for adding a new package to fedora right? #744 I would like to get python3-devel and other required packages on debian. (Linux mint). Since, uh. not able to get it here as well.

**Comment by YuvanMichael** [comment]
I'll give you the terminal output if you want.

**Comment by YuvanMichael** [comment]
> Re: Yuvan Hello, Is there any other issue? If you're requesting a feature it would be better to open a discussion +1 I agree that it should be clearer about when the config file is updated / up to date, but I'm not sure that is not a bug, since it did somehow at some point get you the latest config version without error. It is definitely weird that you were never prompted, I'm not sure why it did not prompt you thinking

Actually this is the reason for why I opened an issue. Update config file on linux. Maybe it should've been Forced config updates or something. Sorry the title was not clear enough. 

> I guess we could just put a config update that says something like config_updated_report = True. I guess it would be cool to add it and see if it updates the config file. Without asking me. If that's the problem we can just put a confirmation prompt up.

As I said, we could try this.

**Comment by YuvanMichael** [comment]
I do find this project helpful. Makes me happy to help my youtube friends. :)

**Comment by YuvanMichael** [comment]
yeah it is weird.
