### ISSUE TITLE
[Bug]: documentation update

### ISSUE THREAD

**Issue by luismsousa** [ThioJoe/YT-Spammer-Purge#706]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Well, I was trying to run the [Linux Installation Instructions](https://github.com/ThioJoe/YT-Spammer-Purge/wiki/Linux-Installation-Instructions) but the URL is incorrect.

This issue is for me to open a PR to fix it.

### Steps to reproduce

1. just attempt to run the steps in this wiki page.

### What platform are you seeing this problem on?

Linux (can also be ChromeOS)

**Comment by TechStudent11** [comment]
It's working for me

**Comment by TechStudent11** [comment]
Or are you talking about this line?

![image](https://user-images.githubusercontent.com/76978184/155889249-7883a8c9-1891-46b3-a641-2a3faab54b97.png)

**Comment by ThioJoe** [comment]
Ok just updated it, should be good now
