### ISSUE TITLE
Badges in README

### ISSUE THREAD

**Issue by KendallDoesCoding** [ThioJoe/YT-Spammer-Purge#713]
On top, you can see the issues open and pr's open, so I'm not a big fan of duplicate info on the page, so maybe it can be changes to closed issues, closed pr's? But, that's just my opinion :)

**Comment by EthanHindmarsh** [comment]
Why would closed PRs / Closed issues be important info?

**Comment by TechStudent11** [comment]
> But, that's just my opinion :)

Exactly. It's **your** opinion. I don't really see any benefit. You said that you yourself aren't a fan, but what about others.

> Why would closed PRs / Closed issues be important info?

Also another reason.

---

Not being mean, just saying.

**Comment by KendallDoesCoding** [comment]
> But, that's just my opinion :)

> Exactly. It's your opinion. I don't really see any benefit. You said that you yourself aren't a fan, but what about others.

Tbh, I created a PR with issue and pr's open in another repo, and other people said that to me to, I don't think duplicate info is useful

> Why would closed PRs / Closed issues be important info?

> Also another reason.

Yeah true.

> Not being mean, just saying.

Yep, I don't want to ague or fight here so let ThioJoe decide on this :)

**Comment by EthanHindmarsh** [comment]
I'm not against it, but why would it be an improvement? I'm not sure what
you think the benefit is

**Comment by Retraces** [comment]
While I understand that the amount of issues/pull requests is displayed above, the nature of shields.io allows you to condense your repo's information into a few images that take up a single line. I don't think it's a huge issue, it looks fine as it is.

**Comment by KendallDoesCoding** [comment]
> While I understand that the amount of issues/pull requests is displayed above, the nature of shields.io allows you to condense your repo's information into a few images that take up a single line. I don't think it's a huge issue, it looks fine as it is.

True, will keep this open though, let ThioJoe make a decision but most likely, it's a no.

**Comment by ThioJoe** [comment]
Eh i'll just keep it as is for now
