### ISSUE TITLE
Filtering: False positive report

### ISSUE THREAD

**Issue by silviucc** [ThioJoe/YT-Spammer-Purge#716]
### Filter Mode

Auto-Smart Mode

### Select the Problem

False Positive

### Spammer Example / Sample

`-----------------------------------------------------------------------------------------------------------------

1. Nemecyst:  https://www.youtube.com/watch?v=-2WVE9tsD1k
—————————————————————————————————————————————————————————————————————————————————————————————
     > Reason: Filter Match
     > Direct Link: https://www.youtube.com/watch?v=6Ke2PSvOO5Y&lc=UgzsVSGz-F3RqcvhyTx4AaABAg.9Yq5ec25OM-9Ysf5W2DxN5
     > Author Channel ID: UCkf9-VKiL_CmFzUaEQyFbqA
=============================================================================================

2. TheBigEtrain:  Holy shit Barney this was worth the fucking wait, I’ve never had a YouTube video series (let alone one about a game I don’t play) make me feel this way my guy, thanks for all the laughs, the tears, and the headaches, here’s to MORE BARNY CONTENT WOOOO
—————————————————————————————————————————————————————————————————————————————————————————————
     > Reason: Filter Match
     > Direct Link: https://www.youtube.com/watch?v=6Ke2PSvOO5Y&lc=UgxiJsV3ndIng3gsuc14AaABAg
     > Author Channel ID: UCuatberh3ZE68wSHdn3PTdg
=============================================================================================

3. Donnie Carney:  Damn, I must be in the afterlife, TWO BARNY VIDEOS IN TWO DAYS?!
—————————————————————————————————————————————————————————————————————————————————————————————
     > Reason: Filter Match
     > Direct Link: https://www.youtube.com/watch?v=6Ke2PSvOO5Y&lc=Ugza40ESgwxjkhD7cMt4AaABAg
     > Author Channel ID: UCu0YH43q5EiBiy8IvIAN4Ag
=============================================================================================

4. n0xx:  The sad part is we won't get to see more Barny content for a year....
—————————————————————————————————————————————————————————————————————————————————————————————
     > Reason: Filter Match
     > Direct Link: https://www.youtube.com/watch?v=6Ke2PSvOO5Y&lc=UgwSs5DfVp52HKlw8V94AaABAg
     > Author Channel ID: UC8Os6hjHmDpPlsIP2WWG4nQ
=============================================================================================

5. ben chadwick:  Can never get enough of barny content!
—————————————————————————————————————————————————————————————————————————————————————————————
     > Reason: Filter Match
     > Direct Link: https://www.youtube.com/watch?v=6Ke2PSvOO5Y&lc=UgxTwN0x-SBSpcUjr6l4AaABAg
     > Author Channel ID: UCdpCgXAONaXrYjDwYx-ILAA
=============================================================================================

6. SonyEricSon:  TWO Barny videos back to back?!
—————————————————————————————————————————————————————————————————————————————————————————————
     > Reason: Filter Match
     > Direct Link: https://www.youtube.com/watch?v=6Ke2PSvOO5Y&lc=UgxXLasfwZ35iJIe7Pt4AaABAg
     > Author Channel ID: UCjL2NkFPEdDoPCBM7wX6OWA
=============================================================================================

                                             
============================ Match Samples: One comment per matched-comment author ============================
 1.  [x1]   SonyEricSon         : TWO Barny videos back to back?!                                                   
 2.  [x1]   ben chadwick        : Can never get enough of barny content!                                            
 3.  [x1]   n0xx                : The sad part is we won't get to see more Barny content for a year....             
 4.  [x1]   Donnie Carney       : Damn, I must be in the afterlife, TWO BARNY VIDEOS IN TWO DAYS?!                  
 5.  [x1]   TheBigEtrain        : Holy shit Barney this was worth the fucking wait, I’ve never had a YouTube vide...
 6.  [x1]   Nemecyst            : https://www.youtube.com/watch?v=-2WVE9tsD1k       `

### Video / Post Link

https://www.youtube.com/watch?v=6Ke2PSvOO5Y

### (Optional) Additional Info / Context

None  of the above comments are spam.

**Comment by ThioJoe** [comment]
Hm odd, I'll figure it out

**Comment by ThioJoe** [comment]
Forgot to mark this as solved but it is. There was some text that was getting flagged so I updated the filters to be a bit less sensitive to those words.
