### ISSUE TITLE
Filtering: copy spambot not detected

### ISSUE THREAD

**Issue by agardip** [ThioJoe/YT-Spammer-Purge#717]
### Filter Mode

Auto-Smart Mode

### Select the Problem

Some spammers not detected

### Spammer Example / Sample

In video (https://www.youtube.com/watch?v=3yl3TIhJ2Hs) there is a "copy someone's comment" bot with explicit content.
link of bot: https://www.youtube.com/channel/UCriCPYAPHnPao5JuxSkfCng/featured

### Video / Post Link

https://www.youtube.com/watch?v=3yl3TIhJ2Hs

**Comment by Firecul** [comment]
![WindowsTerminal_Windows_PowerShell (38)](https://user-images.githubusercontent.com/34950371/156903158-c1de0a72-fa1d-415a-aba7-3fd7f29cd02b.png)
It *is* detected for me, I'm running v2.16.4
https://www.youtube.com/watch?v=3yl3TIhJ2Hs&lc=UgyYuOnMn-4ABVeapBh4AaABAg

**Comment by ThioJoe** [comment]
Yea besides the 'stolen comment' function, there's not really any way to otherwise distinguish a spam comment like this
