### ISSUE TITLE
Filtering: Missed Comments

### ISSUE THREAD

**Issue by Tevyy** [ThioJoe/YT-Spammer-Purge#719]
### Filter Mode

Auto-Smart Mode

### Select the Problem

False Positive

### (Optional) If 'Other', Enter Very Short Description

i found some comments that where spam but not bad spam

### Spammer Example / Sample

![spam bot](https://user-images.githubusercontent.com/91659571/156934396-ebe6ff95-904f-4c86-b608-8919b015dd98.png)

### Video / Post Link

i dont know what video it was sorry i just sent the photo of the comments

### (Optional) Additional Info / Context

hope this helps

**Comment by Firecul** [comment]
It's in the section "Commenters, But Who Wrote Many Similar Comments" So probably a lot of the comments they wrote were spam (or could be considered such.) 
128-131 + 133-137 are 100% spam in my eyes.
132 **might** not be but I'd have to see his other comments to be sure. Basically, I think there are 0 false positives here.

**Comment by ThioJoe** [comment]
I probably am not going to consider the duplicate comment results false positives at this point. I did increase the threshold a bit before but if someone leaves 10 of the same comment that's on them in my opinion
