### ISSUE TITLE
Stopped working on project?

### ISSUE THREAD

**Issue by KendallDoesCoding** [ThioJoe/YT-Spammer-Purge#724]
The last commit was 9 days ago, have you stopped working on this project @ThioJoe?

**Comment by ThioJoe** [comment]
I've been busy building a new computer this past week. Also the program is pretty much feature complete at this point so development will definitely be slower going forward, as it will be features I see as 'nice to haves'

**Comment by KendallDoesCoding** [comment]
> 9 Days is far from abandonment, besides he has plenty of other things to worry about too. Chill lol

Yeah ik he's a busy guy, was just wondering if the project stopped being mantained.

**Comment by KendallDoesCoding** [comment]
> I've been busy building a new computer this past week. Also the program is pretty much feature complete at this point so development will definitely be slower going forward, as it will be features I see as 'nice to haves'

Ok cool. Yeah, true, makes sense!
