### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable in Nuke Mode while scanning recent community posts

### ISSUE THREAD

**Issue by DinhHuy2010** [ThioJoe/YT-Spammer-Purge#725]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Well, I was trying to scanning recent community posts but then got error: TypeError: 'NoneType' object is not subscriptable

### Release version

YTSpammerPurge 2.15.1 (modifed)

### Steps to reproduce

1. Use recent community posts mode
2. Choose a channel (Channel ID: UCTFBrIlufYVR80kMyIj-XUw)
3. Use Nuke Mode
4. Got error

### What platform are you seeing this problem on?

Windows (.py script)

### Relevant log output

```shell
Traceback (most recent call last):lyzing Comments For Spam
  File "C:\python\spam_base\YT-Spammer-Purge-2.15.1_modfied\YTSpammerPurge.py", line 1611, in <module>
    main()
  File "C:\python\spam_base\YT-Spammer-Purge-2.15.1_modfied\YTSpammerPurge.py", line 1588, in main
    continueRunning = primaryInstance(miscData)
  File "C:\python\spam_base\YT-Spammer-Purge-2.15.1_modfied\YTSpammerPurge.py", line 1106, in primaryInstance
    scan_community_post(current, config, id, maxScanNumber, postScanProgressDict=postScanProgressDict, postText=postText)
  File "C:\python\spam_base\YT-Spammer-Purge-2.15.1_modfied\YTSpammerPurge.py", line 1080, in scan_community_post
    current = operations.check_spam_threads(current, filtersDict, miscData, config, parentCommentDict, threadDict)
  File "C:\python\spam_base\YT-Spammer-Purge-2.15.1_modfied\Scripts\operations.py", line 255, in check_spam_threads
    threadWords = filtersDict['CustomCommentTextFilter']['threadFiltersDict']['threadWords']
TypeError: 'NoneType' object is not subscriptable
------------------------------------------------
Unknown Error - Code: X-5 occurred. This is probably my fault,
please a bug report on the GitHub issues page, and include the above error info.
Short Link: TJoe.io/bug-report

 Press Enter to Exit...
```

### Screenshots

![Screenshot 2022-03-08 094207](https://user-images.githubusercontent.com/95196459/157155811-0cbdf9b2-1479-4d96-9618-f07fe877fab9.png)

**Comment by Firecul** [comment]
Can you define `(modifed)` in your version?
Have you tried v2.16.4 which is the newest version?

**Comment by ThioJoe** [comment]
Yea you'll need to try the latest version. The program uses a different filtering method for the 'threadwords' variable now, so I can't really even see if this would still apply.

**Comment by ThioJoe** [comment]
Gonna close this from inactivity

**Comment by DinhHuy2010** [comment]
nice
