### ISSUE TITLE
[Bug:] YT config duplication bug

### ISSUE THREAD

**Issue by BrandiBlitz** [ThioJoe/YT-Spammer-Purge#731]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [X] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Hey Thio, I got an error with “YT Spammer Purge” saying that the “Config Settings for ‘Channel_to_scan’ appears invalid: True” message. I’m not sure if this is a bug, b/c I had noticed my config file(s) were outside of the YT spammer purge folder, so I put it back in, but it asked me if I wanna replace some of the files. I didn’t know I had duplicates, so I deleted the duplicates that were outside of the folder. That’s how I got the message. 

### Release version

2.16.4

### Steps to reproduce

1. Config file was outside of the YT spammer purge folder
2. Trying to put it back in, I was prompted ro replace the file
3. Instead of actually replacing it, I deleted the duplicate config file

### What platform are you seeing this problem on?

Windows (.exe file)

### Relevant log output

```shell
Error: Invalid Channel link or ID!

ERROR! Config setting for ‘channel_to_scan’ appears invalid: True
Make sure it is either a single channel ID or Channel link. If it’s a link, try using the channel ID instead.

If you think it is a bug or can’t figure it out, report it on GitHub page: TJoe.io/bug-report

Press Enter to exit . . .
```

### Screenshots

![C9C3079A-5560-4AFD-B1C3-D808BA08B954](https://user-images.githubusercontent.com/101225938/157342697-df105819-aeb5-4ab8-933a-619eb75035c1.jpeg)

**Comment by ThioJoe** [comment]
What exactly do you mean by "outside of the folder"?

**Comment by EthanHindmarsh** [comment]
lol'd at the screenshot, nice

In your config, make sure 'channel_to_scan' looks something like `UCx123-BlahBlahExampleID` (or the words `Ask` or `Mine`)

Better yet, if you could upload your config.ini so we could check it that would be great 👍

**Comment by BrandiBlitz** [comment]
> What exactly do you mean by "outside of the folder"?
> 
> And is Channel_to_scan not actually set to true? That's not a valid value

It is set to true. I had noticed the config.ini file was outside of the dedicated YT Spammer purge folder. I tried to put it back in, then it says that the file already exists inside. So I was confused and thought I had made 2 of the same configuration files. I thought I didn't need the extra one, so I had deleted it. Then, the errors started popping up.

**Comment by BrandiBlitz** [comment]
> lol'd at the screenshot, nice
> 
> 
> 
> In your config, make sure 'channel_to_scan' looks something like `UCx123-BlahBlahExampleID` (or the words `Ask` or `Mine`)
> 
> 
> 
> Better yet, if you could upload your config.ini so we could check it that would be great 👍

I will do what I can in the morning~

**Comment by Firecul** [comment]
> It is set to true.

`True` is **not** a valid value for that parameter.
![Code_SpamPurgeConfig ini_-_YT-Spammer-Purge_-_Visual_St (2)](https://user-images.githubusercontent.com/34950371/157900129-68b56294-2b5c-45d3-8194-f89c1016021d.png)

**Comment by ThioJoe** [comment]
Yep, the error is because of the reason it says

**Comment by Firecul** [comment]
Or you could have changed the word `True` to any of the above suggestions. But yes that works.

**Comment by BrandiBlitz** [comment]
> Or you could have changed the word `True` to any of the above suggestions. But yes that works.

I did a clean install. That fixed it
