### ISSUE TITLE
Filtering: Undetected Usernames

### ISSUE THREAD

**Issue by Firecul** [ThioJoe/YT-Spammer-Purge#734]
### Filter Mode

Auto-Smart Mode

### Select the Problem

Some spammers not detected

### Spammer Example / Sample

![chrome_Don't_Trust_Desert_Sand,_Toyota_Rolls_Hard_Off_The](https://user-images.githubusercontent.com/34950371/157760248-5c5e5b43-30df-4655-bc73-2686b31b8dd0.png)
https://www.youtube.com/watch?v=xek1HTYnlog&lc=UgyVKhjgAlbsxrJYSyN4AaABAg

![chrome_This_Tacoma_Needs_More_Than_A_Rescue _-_YouTube_-_](https://user-images.githubusercontent.com/34950371/157760259-f2d87443-3a3d-4113-8dce-ad4cdb831894.png)
https://www.youtube.com/watch?v=ad1oLRgWDHQ&lc=UgwNWLOpv15RkEipmW54AaABAg.9ZNLNUmI7Ek9ZNLRJX8gcL

### Video / Post Link

See above

### (Optional) Additional Info / Context

v2.16.5

**Comment by Firecul** [comment]
Actually, you might have just fixed N°2 with 1c23ba0cf42d27e43d0e9d4dd97751aa16907f62, I'll check

**Comment by ThioJoe** [comment]
Yea I have an idea on how to handle these but it will take adding an additional bit of logic, whenever I get around to 2.17 I'll be adding a function that will be able to handle stuff like this more universally

**Comment by ThioJoe** [comment]
Latest beta should catch these
