### ISSUE TITLE
Filtering: Repeated "finally it's here" in replies from multiple accounts with an irrelevant video link

### ISSUE THREAD

**Issue by mungodude** [ThioJoe/YT-Spammer-Purge#736]
### Filter Mode

Auto-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

![Screenshot_2022-03-11_22-14-23](https://user-images.githubusercontent.com/32443386/157837878-77ecc8af-7621-43fe-a5fb-83a30cdd5359.png)

### Video / Post Link

https://www.youtube.com/watch?v=sxxflxyteoU

### (Optional) Additional Info / Context

Repeated replies to comments from multiple accounts with an irrelevant video link and the text "finally it's here :]"

**Comment by ikkysleepy** [comment]
Does the tool not have duplicate / copy detection option?

**Comment by Firecul** [comment]
> Does the tool not have duplicate / copy detection option?

It does, I assume mungodude is aware of it and was asking if this particular spam could be caught by the main filters.

![image](https://user-images.githubusercontent.com/34950371/157983038-3de3ba47-6a29-4e4e-acd5-8278a72789dd.png)

**Comment by Firecul** [comment]
I suppose a filter could look for `<YT Link> finally it's here` that does seem to be a very common message

**Comment by ThioJoe** [comment]
I might be able to add something, but I've always said when it comes to link spam, it's mainly up to creators to just disable hyperlinks in their comments, it's just a checkbox in settings

**Comment by LunaticBFF57** [comment]
> > I might be able to add something, but I've always said when it comes to link spam, it's mainly up to creators to just disable hyperlinks in their comments, it's just a checkbox in settings
> 
> A question I've just thought of, then why do we submit spam domains?

Maybe some YouTubers just want to do it at the same time as deleting the other scam comments? (I know it's very counter-intuitive, some users might have their own reasoning to do this).

**Comment by Firecul** [comment]
As the links above should be caught in the main lists now (https://github.com/ThioJoe/YT-Spam-Lists) this issue can probably be closed, if you have more URLs to submit please do that in the other repo.
