### ISSUE TITLE
Hi my name is [NAME] if you don't mind check out my vido

### ISSUE THREAD

**Issue by Kiaan-Wijayasekara** [ThioJoe/YT-Spammer-Purge#745]
### Filter Mode

Sensitive-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

![15-03-](https://user-images.githubusercontent.com/88933260/158319035-96414657-2ac6-4308-9f01-6c02e028bc3f.png)
![image](https://user-images.githubusercontent.com/88933260/158319151-2fa6dce3-fd0f-41be-bc24-a552b01567db.png)

Alice - https://www.youtube.com/channel/UC1_Wl6-KC6CFT37J92fbMHg
Lisa - https://www.youtube.com/channel/UCOv7I2exoqJ_Xvl46yhCpaA

### Video / Post Link

https://www.youtube.com/watch?v=ALAWx3pEAuI

**Comment by YuvanMichael** [comment]
Does autosmart catch it?

**Comment by YuvanMichael** [comment]
sensitive smart catches more false positives. Autosmart identifies various scamming methods. Occasionally misses some spammers.

**Comment by YuvanMichael** [comment]
I can see how this is not caught since, spam comments usually contain links, offensive content, swearing etc. The channel username (commenter's username) doesn't contain a whole lot of that. Plus the comments are just one word comments showing regular words like out.

**Comment by ThioJoe** [comment]
Yea it's a constant cat and mouse game, I'll have to add some stuff to catch these in particular

**Comment by ThioJoe** [comment]
Should be fixed as of the latest commit and in the next release
