### ISSUE TITLE
Filtering: Extra characters for blackwords filter

### ISSUE THREAD

**Issue by Firecul** [ThioJoe/YT-Spammer-Purge#748]
### Filter Mode

Auto-Smart Mode

### Select the Problem

Some spammers not detected

### (Optional) If 'Other', Enter Very Short Description

Scammers are using different characters to bypass the telegram blacklist

### Spammer Example / Sample

![chrome_The_fireworks_in_Bahrain_are_getting_a_bit_EXTREME](https://user-images.githubusercontent.com/34950371/158893130-296e537e-cf7f-485b-af30-6abf5c5b2a27.png)

### Video / Post Link

https://www.youtube.com/watch?v=qZKRnKRAKRw&lc=UgyomlmvN16oBRsrGSZ4AaABAg

### (Optional) Additional Info / Context

`ͲeIєɠɾαm`
So you can add them to the Filter_Variables

**Comment by ThioJoe** [comment]
Ok finally got around to adding those characters
