### ISSUE TITLE
logInfo referenced before assignment

### ISSUE THREAD

**Issue by killtheplanet** [ThioJoe/YT-Spammer-Purge#757]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Running in Moderator mode in any of the 3 modes produces this just after parsing all the results...

```
How do you want to  ALL  the listed comments above? (Including Non-Matched Duplicates)
~~ Moderator Mode: Reporting and Holding for Review is possible ~~
 > To exclude certain authors: Type 'exclude' followed by a list of the numbers (or ranges of #'s) from the sample list
      > Example:  exclude 1, 3-5, 7, 12-15
 > To only process certain authors: Type 'only' followed by a list of the numbers (or ranges of #s) from the sample list
      > Example:  only 1, 3-5, 7, 12-15  --  (Will effectively exclude the 'inverse' of the 'only' selected authors)
 > To move ALL comments above to 'Held For Review' in YT Studio: Type 'HOLD', then hit Enter.
 > To report the comments for spam, type 'REPORT'.
 > To do nothing and only log, type 'NONE'

 (Not Case Sensitive) Input: hold

Also remove all other comments from the selected authors, even if their other comments weren't matched?

Choose: (y/n): y
                                                       

Traceback (most recent call last):
  File "./YTSpammerPurge.py", line 1670, in <module>
    main()
  File "./YTSpammerPurge.py", line 1647, in main
    continueRunning = primaryInstance(miscData)
  File "./YTSpammerPurge.py", line 1564, in primaryInstance
    logInfo['logFileContents'] = logFileContents
UnboundLocalError: local variable 'logInfo' referenced before assignment
------------------------------------------------
Error Message: local variable 'logInfo' referenced before assignment

Error - Code: X-2 occurred. This is almost definitely my fault and requires patching (big bruh moment)
Please post a bug report on the GitHub issues page, and include the above error info.
Short Link: TJoe.io/bug-report
    (In the mean time, try using a previous release of the program.)

 Press Enter to Exit...

```

### Release version

9349f25668e766d1269207de8df585e484ca4260

### Steps to reproduce

1.  2 - Scan recent videos of a channel
2.  Enter Channel
3.  Number of recent videos: 10
4. Is everything correct - Y
5. 1 - auto-smart mode
6. Y - save log file
7. enter - display comments
8. hold - what to do with comments
9. y - remove all other comments from the selected authors

### What platform are you seeing this problem on?

Linux (can also be ChromeOS)

### Relevant log output

```shell
Shown above
```

**Comment by killtheplanet** [comment]
Note - appears to break as soon as 'Also remove all other comments from the selected authors, even if their other comments weren't matched?' is true

**Comment by ThioJoe** [comment]
Hmm i'll look at it

**Comment by killtheplanet** [comment]
> Hmm i'll look at it

Thanks, FWIW just to confirm that it is still happening in v2.16.7, only particular videos appear to trigger it.
Scan mode do not appear to matter, had it happen at least on Auto Smart|Sensitive Smart | username&comments -> string

![image](https://user-images.githubusercontent.com/89046743/161234548-d7c14bfd-f000-4da6-80f2-bab509b41ed5.png)

**Comment by ThioJoe** [comment]
Ok should be fixed with the latest commit
