### ISSUE TITLE
[Bug]: Typo in script action text

### ISSUE THREAD

**Issue by Mous3kteer** [ThioJoe/YT-Spammer-Purge#758]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

In Auto-Smart mode (at least, since that's the only one I use), after scanning for comments, the script asks "How do you want to  ALL  the listed comments above? (Including Non-Matched Duplicates)". That's not a full sentence; it's missing a verb. It should say something along the lines of "How do you want to /handle/ ALL  the listed comments above?"

It's definitely not a huge issue, but I think it's worth an edit.

### Release version

2.16.6

### Steps to reproduce

1. Scan any video with spam comments in Auto-Smart mode.
2. Read the text shown in the screenshot provided.

### What platform are you seeing this problem on?

Windows (.exe file)

### Screenshots

![image](https://user-images.githubusercontent.com/52615946/159971748-b43038b0-99fd-4749-8f64-fe284d7ea54a.png)

**Comment by Firecul** [comment]
How have I never noticed that before?
