### ISSUE TITLE
500 recent videos description fix in default config file

### ISSUE THREAD

**Issue by DinhHuy2010** [ThioJoe/YT-Spammer-Purge#767]
The default config file (settings key 'recent_videos_amount') description say 500 videos instead of 5000 videos. @ThioJoe, fix description the default config file.

Screenshot:
![Screenshot 2022-04-01 094926](https://user-images.githubusercontent.com/95196459/161185624-2adff44f-cdd0-4887-8cc0-3e0ea9217f34.png)

**Comment by Firecul** [comment]
Maybe next time it's better to just point out the issue, it sounds like an order the way you wrote it. I'm sure it's not the way you intended but that's the way it looks.
