### ISSUE TITLE
[Bug]: "Something went wrong" on oauth consent screen

### ISSUE THREAD

**Issue by OldWorldOrdr** [ThioJoe/YT-Spammer-Purge#776]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

After selecting continue on the "this app is not verified by google" part, I got a "something went wrong" error

### Release version

2.16.7

### Steps to reproduce

1. open exe
2. go through oauth consent
3. get error

### What platform are you seeing this problem on?

Windows (.exe file)

### Screenshots

![Screenshot 2022-04-02 115907](https://user-images.githubusercontent.com/57970114/161391159-bb8cfec0-031c-4224-9c19-ba3f4d0fc485.png)

**Comment by ThioJoe** [comment]
Hm not even really sure about this one, seems like something on Google's side, but it doesn't even give a proper error message

**Comment by OldWorldOrdr** [comment]
@ThioJoe just tried again, still doesn't work.  I'll try again tomorrow.

**Comment by 0x556c79** [comment]
I have the same problem. 

https://accounts.google.com/info/unknownerror

![image](https://user-images.githubusercontent.com/19878020/161426616-6f32a003-d525-4aef-9d89-70d5e815144f.png)

**Comment by 0x556c79** [comment]
I have now tried it with Microsoft Edge instead of Brave as a browser and now it has worked

**Comment by raghunandhanvr** [comment]
The one reason for this would be That the mail ID you're trying to log in should have been logged-in already. Might be your browser mistake or remove the distributed cache and try again?

- try with a different Mail ID or only one mail id logged in the browser
- try changing the default browser gateway
- try doing the process from the beginning again

**Comment by OldWorldOrdr** [comment]
i tried with a different email and it didnt work.  i tried getting a new api key and it didnt work.  i tried updating to 2.16.8 and it didnt work.  i tried clicking next on the error screen and got this
![Screenshot 2022-04-04 114057](https://user-images.githubusercontent.com/57970114/161580860-9749d76f-e3ea-4952-ab3d-ddb7dbbecd7e.png)

**Comment by KendallDoesCoding** [comment]
> I have now tried it with Microsoft Edge instead of Brave as a browser and now it has worked

Maybe coz Brave has some setting and it things this is not safe, privacy issue?

**Comment by ThioJoe** [comment]
> i tried with a different email and it didnt work. i tried getting a new api key and it didnt work. i tried updating to 2.16.8 and it didnt work. i tried clicking next on the error screen and got this

Have you tried a different browser?

**Comment by OldWorldOrdr** [comment]
@ThioJoe I tried firefox and that did it.  I feel really stupid for not trying before.

**Comment by KendallDoesCoding** [comment]
> @ThioJoe I tried firefox and that did it. I feel really stupid for not trying before.

> Maybe coz Brave has some setting and it things this is not safe, privacy issue?

Yeah, then Brave is blocking it coz of some privacy thing, ig... Please close the issue.

**Comment by tmbottegal** [comment]
I had this issue, I just opened the login in a private tab of the same browser (Firefox), and it worked flawlessly.
