### ISSUE TITLE
Filtering: (youtube video link filtering regex not identifying some links as youtube links)

### ISSUE THREAD

**Issue by Andre-4949** [ThioJoe/YT-Spammer-Purge#792]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

I was trying to find a loophole in the code to then report it and found out that some links are not identified as youtube links by the regex. This regex to be presice : https://github.com/ThioJoe/YT-Spammer-Purge/blob/b885dc4f047f7eb56d2e076fb191a48a8642c293/Scripts/validation.py#L15

I would suggest to change it to:
```python
youtube_video_link_regex = r"^\s*(?P<video_url>(?:(?:https?:)?\/\/)?(?:(?:www|m)\.)?(?:youtube\.com|youtu.be)(?:\/[\w\-]+\?(app=desktop&)*(?:v=|embed\/|v\/)?))?(?P<video_id>[\w\-]{11})(?:(?(video_url)\S+|$))?\s*$" #this is far from perfect but it works
```
The video id group still contains the same data, so i think it'll work.

### Release version

2.16.8

### Steps to reproduce

You have to be on a PC (I am using Windows 10 Pro (Version: 21H2) and Google Chrome (Version: 100.0.4896.75 64-Bit)):
1. Click on a youtube video
2. Go to the url
3. change the "www" to "m"
4. press enter
5. wait until you get redirected
6. look at the url and find out "app=desktop&" has appeard between the "/watch?" and the "v=[video-id]"

### What platform are you seeing this problem on?

Windows (.py script)

### Relevant log output

```shell
There isn't a relevant output i think because the script hasn't done something because the youtube video link hasn't been identified as youtube video link
```

**Comment by Firecul** [comment]
I don't think I've ever seen that show up before tbh, still, it's an edge case that's nice if it gets caught.

**Comment by ThioJoe** [comment]
I think this is too niche to implement unless it comes up more
