### ISSUE TITLE
Filtering: "brain burner" bots

### ISSUE THREAD

**Issue by z6197** [ThioJoe/YT-Spammer-Purge#794]
### Filter Mode

Auto-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

![spam comment](https://user-images.githubusercontent.com/103390778/162643152-a262f311-17f2-40a0-9792-bee893031b0d.PNG)

![spam comment 2](https://user-images.githubusercontent.com/103390778/162643207-aeafa36d-0b76-49f7-bd25-9aad8a114171.PNG)

### Video / Post Link

https://www.youtube.com/watch?v=2NFDajQyliU&t=852s

### (Optional) Additional Info / Context

there seem to be bots that now claim youtubers are on "brain burner" and link to other youtube videos.

**Comment by Firecul** [comment]
As the links above should be caught in the main lists now (https://github.com/ThioJoe/YT-Spam-Lists) this issue can probably be closed, if you have more URLs to submit please do that in the other repo.
