### ISSUE TITLE
Filtering: a lot of Vietnamese spammer cant be detected

### ISSUE THREAD

**Issue by tranhongs0n** [ThioJoe/YT-Spammer-Purge#797]
### Filter Mode

Auto-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

![image](https://user-images.githubusercontent.com/58134175/162851705-326cd858-1406-445f-831b-83807aaeed30.png)
(username includes a site called "timbantinhvn" or "timbantinh")

**Comment by tranhongs0n** [comment]
these username also include number like 300K, 500K,...

**Comment by Firecul** [comment]
As a non-Vietnamese speaker, I wouldn't be able to tell those comments were spam. The username and picture would be good clues though. Maybe we could add the `timbantinhvn` domain to the filter lists? and `cham` to the alternates for `dot` if they are there, I don't remember atm if those exist in this code.

**Comment by DinhHuy2010** [comment]
@Firecul , I am at Vietnam, so what?

**Comment by DinhHuy2010** [comment]
Also where is link?

**Comment by Firecul** [comment]
> Also where is link?

The link/domain is in the user's name (I advise against going there)

**Comment by Firecul** [comment]
Can you link to one of the comments, it is one of the questions when filling out the form.
![image](https://user-images.githubusercontent.com/34950371/162947718-ec2a577b-b6e6-42ff-8783-90dfc42410a3.png)

**Comment by DinhHuy2010** [comment]
nope, video URL

**Comment by Firecul** [comment]
Những bình luận này trên video nào?

**Comment by DinhHuy2010** [comment]
ok
