### ISSUE TITLE
Filtering: Undetected '18+ spam' bots

### ISSUE THREAD

**Issue by d8elessar** [ThioJoe/YT-Spammer-Purge#804]
### Filter Mode

Auto-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

User: Guy Landon (https://www.youtube.com/channel/UCldvNcO0NTf32QABcXOiR7Q)
Comment: "Son unos [PORNTINDER.Uno]() de Losy mejores ❤ Mañas no se la. ."

![image](https://user-images.githubusercontent.com/1764584/164486883-c1c3104b-5d91-4367-bdb5-50bc571c8668.png)

### Video / Post Link

https://www.youtube.com/watch?v=LDtHa9QmNyk

**Comment by Firecul** [comment]
> Channel has been banned, that's good 😁

It's a start, 1 done with thousands to go.

**Comment by Firecul** [comment]
As the links above should be caught in the main lists now (https://github.com/ThioJoe/YT-Spam-Lists) this issue can probably be closed, if you have more URLs to submit please do that in the other repo.
