### ISSUE TITLE
[Bug]: Application immediately crashes on me

### ISSUE THREAD

**Issue by LunaticBFF57** [ThioJoe/YT-Spammer-Purge#815]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Well, I was trying to open the v2.16.9 version of the spammer application but then it just crashes on me without inputting anything into the Command Prompt window. (For context, I have 5 config files that are saved inside of the install location and I don't even confirm ANY configs then it immediately crashes. (Plus one is not showing up before the traceback text happens))

### Release version

v2.16.9 (Just tried the v2.16.8 application and it seems that it doesn't seem to work as well)

### Steps to reproduce

1. Simply just open the application
(You might not be able to reproduce this bug.)

### What platform are you seeing this problem on?

Windows (.exe file)

### Relevant log output

```shell
Traceback (most recent call last):
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1674, in <module>
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 192, in main
  File "Scripts\files.py", line 482, in load_config_file
  File "Scripts\files.py", line 691, in choose_config_file
  File "Scripts\files.py", line 450, in load_config_file
  File "configparser.py", line 718, in read_file
  File "configparser.py", line 1085, in _read
configparser.MissingSectionHeaderError: File contains no section headers.
file: '<???>', line: 1
'True# ---------- Config file for YT Spammer Purge program ----------\n'
------------------------------------------------
Error Message: File contains no section headers.
file: '<???>', line: 1
'True# ---------- Config file for YT Spammer Purge program ----------\n'
```

### Screenshots

![Screenshot 2022-04-30 100214](https://user-images.githubusercontent.com/78350612/166082100-958b3083-0668-4144-a027-2948a2474415.png)

**Comment by LunaticBFF57** [comment]
If any other files need to be added, please let me know.

**Comment by Firecul** [comment]
Can you move the config files out of that folder and launch without one?
I think it might be something wrong with them (or one of them,) that's the easiest thing to check first.

**Comment by Firecul** [comment]
Presumably it'll be the one loading after LTT and GN but first things first

**Comment by Firecul** [comment]
If that works, add them back in one by one. When it crashes you'll know which is the issue. Then we can look at that one and see the problem.

**Comment by LunaticBFF57** [comment]
I just realised the issue, there was a mistyped 'True' in one of the config files. It was like:
```shell
True # ---------- Config file for YT Spammer Purge program ----------
```
Instead of:
```shell
# ---------- Config file for YT Spammer Purge program ----------
```
I must have mistyped when I was editing a config file, my bad.
