### ISSUE TITLE
Filtering: (Write a short title here)

### ISSUE THREAD

**Issue by babysho** [ThioJoe/YT-Spammer-Purge#816]
### Filter Mode

Auto-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

![image](https://user-images.githubusercontent.com/72329329/166086458-515a9e74-f0b3-4839-a419-a694154258c4.png)

### Video / Post Link

https://www.youtube.com/watch?v=_68xw5uWmYY&t=1s

**Comment by Firecul** [comment]
A direct link would be good but I've filled out the form on https://github.com/ThioJoe/YT-Spam-Lists to add this domain to the ones caught by this program.

**Comment by ThioJoe** [comment]
Yep added to the spam lists
