### ISSUE TITLE
Filter "Finally its here"

### ISSUE THREAD

**Issue by Tranberg666** [ThioJoe/YT-Spammer-Purge#817]
### Filter Mode

Auto-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### (Optional) If 'Other', Enter Very Short Description

A cookie recipy channel spams with multiple accounts, all identical replies "Finally its here" 

### Spammer Example / Sample

https://www.youtube.com/watch?v=EyaVOJF3q2Y&lc=UgyvJH7afDl-WygxczV4AaABAg.9aNPmZ_cmHU9aNQkwTnUoj

### Video / Post Link

https://www.youtube.com/watch?v=EyaVOJF3q2Y&t=125s

**Comment by Firecul** [comment]
As the links above should be caught in the main lists now (https://github.com/ThioJoe/YT-Spam-Lists) this issue can probably be closed, if you have more URLs to submit please do that in the other repo.

**Comment by ThioJoe** [comment]
Should be caught with the beta
