### ISSUE TITLE
Filtering: Non-English language filtering doesn't work

### ISSUE THREAD

**Issue by SJang1** [ThioJoe/YT-Spammer-Purge#820]
### Filter Mode

Auto-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

![image](https://user-images.githubusercontent.com/29011440/166451009-5c038428-38b7-4637-8fc8-855489547aaf.png)

Korean comments doesn't detect any spams at all.

**Comment by ethnh** [comment]
@SJang1 Do you have any specific phrases / names / URLs you'd like added to the filter list?
I'm not sure what you're 'suggesting' here, otherwise.

Related: #529 #496 #497 
It is impossible for Thio to maintain spam lists for languages he does not know without any support 😅

**Comment by SJang1** [comment]
Oh, I didn't saw those related ones. I understand. Thx
