### ISSUE TITLE
Filtering: Filter misses links

### ISSUE THREAD

**Issue by Torbaz** [ThioJoe/YT-Spammer-Purge#822]
### Filter Mode

Auto-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

Text + Link.
Example:
![image](https://user-images.githubusercontent.com/16983388/167348626-711debf5-baeb-42b0-9cdd-9f486e72ef1e.png)

### Video / Post Link

https://www.youtube.com/watch?v=x8IrgjIBRt8

**Comment by Torbaz** [comment]
Similar to issue #817

**Comment by ethnh** [comment]
wow they changed "finally it's here" to "it's here finally".. dunno, could be a real human😆

**Comment by LunaticBFF57** [comment]
Could be one of those "elusive" spammer bots, though?

**Comment by Firecul** [comment]
As the links above should be caught in the main lists now (https://github.com/ThioJoe/YT-Spam-Lists) this issue can probably be closed, if you have more URLs to submit please do that in the other repo.

**Comment by ThioJoe** [comment]
Should be caught with the beta
