### ISSUE TITLE
Filtering: Not detected spam pattern

### ISSUE THREAD

**Issue by Jefferson-tan** [ThioJoe/YT-Spammer-Purge#825]
### Filter Mode

Auto-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

![image](https://user-images.githubusercontent.com/56427943/168418803-7942fc97-f495-43ec-8f7a-02cae191add1.png)

### Video / Post Link

https://www.youtube.com/watch?v=93AxLq6NFB8

### (Optional) Additional Info / Context

Been seeing these types of comments recently on multiple different channels and they seem to always link to something irrelevant.

**Comment by Firecul** [comment]
#822 #817 #736 #680 
It has been suggested once or twice 😉
Hopefully, it's on ThioJoe's list to add

**Comment by Jefferson-tan** [comment]
Nice!

**Comment by Firecul** [comment]
The links above should be caught in the main lists now (https://github.com/ThioJoe/YT-Spam-Lists) if you have more URLs to submit please do that in the other repo.
