### ISSUE TITLE
Filtering: Filters for relig

### ISSUE THREAD

**Issue by abe-pratomo** [ThioJoe/YT-Spammer-Purge#830]
### Filter Mode

Auto-Smart Mode

### Select the Problem

False Positive

### Spammer Example / Sample

![Screenshot 2022-05-20 132330](https://user-images.githubusercontent.com/90553934/169465899-ae473771-e5f8-435b-80b1-cba5ed340566.png)

### Video / Post Link

https://www.youtube.com/watch?v=ygaxC7hLp2E

### (Optional) Additional Info / Context

Perhaps tweak the filters so that for religious channels the trigger words such as probably "Jesus" etc won't be filtered as harsh, because as you can see from the screenshot I attached, those comments are all legit (well except that one channel by the name of "God's Promise"), and some of them even mentioned the preacher by name which isn't always present in the videos' title

**Comment by Firecul** [comment]
Hmm... while your suggestion makes sense I'm not sure how to filter less on a specific set of channels. There isn't even a category for solely religious videos we could programmatically look at 
![image](https://user-images.githubusercontent.com/34950371/169538805-4367dc05-3a0d-447e-a272-96a51ac6dd5e.png)

**Comment by ThioJoe** [comment]
It would be tough to implement genre specific filters and I don't really plan on it to be honest
