### ISSUE TITLE
Filtering: Missed spam

### ISSUE THREAD

**Issue by Engstory** [ThioJoe/YT-Spammer-Purge#831]
### Filter Mode

Auto-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

![image](https://user-images.githubusercontent.com/99150304/169630907-79cfd483-720c-426c-a5aa-6df3310ff021.png)

### Video / Post Link

It is found under this video: https://youtu.be/C0Ff_ee5Jkg
Spammer channel: https://www.youtube.com/channel/UCFYQGioJ1xeeaM4fBOOjymg/featured

**Comment by Firecul** [comment]
https://github.com/ThioJoe/YT-Spammer-Purge/issues/822 https://github.com/ThioJoe/YT-Spammer-Purge/issues/817 https://github.com/ThioJoe/YT-Spammer-Purge/issues/736 https://github.com/ThioJoe/YT-Spammer-Purge/issues/680 https://github.com/ThioJoe/YT-Spammer-Purge/issues/825
Again, hopefully it's something @ThioJoe will consider adding

**Comment by Firecul** [comment]
The links above should be caught in the main lists now (https://github.com/ThioJoe/YT-Spam-Lists) if you have more URLs to submit please do that in the other repo.
