### ISSUE TITLE
Filtering: Missed Spam in Spam killer

### ISSUE THREAD

**Issue by Tsuaki456** [ThioJoe/YT-Spammer-Purge#833]
### Filter Mode

Auto-Smart Mode

### Select the Problem

Some spammers not detected

### (Optional) If 'Other', Enter Very Short Description

Spanish replied advertising spam and video link spam

### Spammer Example / Sample

![image](https://user-images.githubusercontent.com/105981614/169656711-9a97f486-3085-4548-8d31-71f610b3d191.png)
![image](https://user-images.githubusercontent.com/105981614/169656719-1a744480-1637-409c-bb09-f0b82d129cb9.png)

### Video / Post Link

https://www.youtube.com/watch?v=u-hoGPUHQps

### (Optional) Additional Info / Context

Replied in most comments

**Comment by Firecul** [comment]
https://github.com/ThioJoe/YT-Spammer-Purge/issues/822 https://github.com/ThioJoe/YT-Spammer-Purge/issues/817 https://github.com/ThioJoe/YT-Spammer-Purge/issues/736 https://github.com/ThioJoe/YT-Spammer-Purge/issues/680 https://github.com/ThioJoe/YT-Spammer-Purge/issues/825 https://github.com/ThioJoe/YT-Spammer-Purge/issues/831
Again, hopefully it's something ThioJoe will consider adding

**Comment by Firecul** [comment]
As the links above should be caught in the main lists now (https://github.com/ThioJoe/YT-Spam-Lists) this issue can probably be closed, if you have more URLs to submit please do that in the other repo.

**Comment by ThioJoe** [comment]
Should be caught with the beta
