### ISSUE TITLE
Filtering: (Write a short title here)

### ISSUE THREAD

**Issue by machtyn** [ThioJoe/YT-Spammer-Purge#834]
### Filter Mode

Auto-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

"Finally it's here
https://youtu.be/IE5U2d1shBM"

### Video / Post Link

https://www.youtube.com/watch?v=BPkIsOORURQ

### (Optional) Additional Info / Context

Posted by two users on this video: "Depp" and "don't be surprised"

**Comment by Firecul** [comment]
https://github.com/ThioJoe/YT-Spammer-Purge/issues/822 https://github.com/ThioJoe/YT-Spammer-Purge/issues/817 https://github.com/ThioJoe/YT-Spammer-Purge/issues/736 https://github.com/ThioJoe/YT-Spammer-Purge/issues/680 https://github.com/ThioJoe/YT-Spammer-Purge/issues/825 https://github.com/ThioJoe/YT-Spammer-Purge/issues/831 https://github.com/ThioJoe/YT-Spammer-Purge/issues/833
Again, hopefully it's something ThioJoe will consider adding

**Comment by LunaticBFF57** [comment]
How many reports of these are there now? A large portion of the bug reports is the "Finally it's here" comments lmao

**Comment by Firecul** [comment]
Functionality to catch this type of comment has been added. This particular video is no longer available so I can't add it to the lists (https://github.com/ThioJoe/YT-Spam-Lists) though.
This issue can probably be closed now, if you have more URLs to submit please do that in the other repo.
