### ISSUE TITLE
Filtering: "telegram" hyphenated

### ISSUE THREAD

**Issue by daneel6672** [ThioJoe/YT-Spammer-Purge#835]
### Filter Mode

Auto-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

![image](https://user-images.githubusercontent.com/20476435/169772967-a3e1dd61-aa7b-478e-a8b9-dc62f8edf071.png)

### Video / Post Link

https://youtu.be/QIJh56jWG9E

### (Optional) Additional Info / Context

The clue that it's spam was this follow-up comment "His te-le-gr am (Rodney_Trade))"

**Comment by Firecul** [comment]
Those are the best I can do, maybe the filter can be updated to catch `te-le-gr am` but that's for Thiojoe to do.

**Comment by Firecul** [comment]
> Is it possible to use some kind of regular expression that allows up to a maximum number of spaces (e.g. 3) and hyphens in the word telegram? So that would catch all variations of te-legram, teleg-ram, telegr-am etc.

It should be, regex can be magic if done right.

**Comment by ThioJoe** [comment]
Probably best caught with the spam lists
