### ISSUE TITLE
Filtering: (Finally it's here)

### ISSUE THREAD

**Issue by leberschnitzel** [ThioJoe/YT-Spammer-Purge#836]
### Filter Mode

Auto-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

https://www.youtube.com/watch?v=Yrnou0SBndI&lc=Ugz-4GTLXaLBF8Y4wTx4AaABAg.9bPAVUFZLG09bPAe8QM7Ij
https://www.youtube.com/watch?v=Yrnou0SBndI&lc=UgxjqARNdSk4vM9OZAp4AaABAg.9bPCE_afJBN9bPMD4k6fm9
https://www.youtube.com/watch?v=Yrnou0SBndI&lc=UgxL8sHHGLRZS6dhP7V4AaABAg.9bPHx_Y_AOJ9bPMGMIGQue
https://www.youtube.com/watch?v=Yrnou0SBndI&lc=Ugzu9trXLNmPEvZquM94AaABAg.9bPCevqz5QF9bPMFTiqlIm

### Video / Post Link

https://www.youtube.com/watch?v=Yrnou0SBndI

**Comment by KendallDoesCoding** [comment]
> #822 #817 #736 #680 #825 #831 #833 #834 Again, hopefully, it's something ThioJoe will consider adding

You should close all these issues @ThioJoe

**Comment by KendallDoesCoding** [comment]
Only keep 1

**Comment by Firecul** [comment]
Maybe pin one of them so people **might** See it and not create a new one.

**Comment by KendallDoesCoding** [comment]
> Maybe pin one of them so people **might** See it and not create a new one.

Yup, that works too

**Comment by Firecul** [comment]
As the links above should be caught in the main lists now (https://github.com/ThioJoe/YT-Spam-Lists) this issue can probably be closed, if you have more URLs to submit please do that in the other repo.

**Comment by ThioJoe** [comment]
The comments aren't there anymore, but assuming it was a "finally its here" comment, they should be caught now with the new beta filtering
