### ISSUE TITLE
List of false negative 

### ISSUE THREAD

**Issue by caam0000** [ThioJoe/YT-Spammer-Purge#840]
### Filter Mode

Auto-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

#usernames with copied comments
eioshen boboi
foopyu nooui
mijuo roui
Soinas Doyi
gtoss chddy
koiun dwrru
bilij pdan
sannio komi
chding zuure
Deto Qcney 
dueeh nyyu

#links to channels with copied comments
https://www.youtube.com/channel/UCTDSeYsO_6Bvr0OMBjVBGpg

#usernames with not copied comments
cantika-sk
Venia.. 💗
uti🙏
Pikachu

#comments
I'd love to be Yourlover.Store  is my idol. Hes the person I aspire to be, hes my light of day.
*18+ Content* Cloveer.Monster  mejores 😘 siempre en mi corazón mañas no se la.💟 Son unos de los mejores conciertos
The legend of Barbie.Monster  snowquen's is my idol. Hes the person I aspire to be, hes my light of day..

#picture of copied comment
![billede](https://user-images.githubusercontent.com/99831815/170882810-dd449f29-3277-491f-bc80-94210c0d4b8f.png)

### Video / Post Link

https://www.youtube.com/watch?v=Sol5LwS6Ifs for copyed comment

### (Optional) Additional Info / Context

The version 2.16.9 isn't catching a type of comment copied. The channel name is typical som random letters. There is also some few comments there are not copyed, there aren't being catched.

**Comment by Firecul** [comment]
![chrome_foopyu_nooui_-_YouTube_-_Google_Chrome](https://user-images.githubusercontent.com/34950371/170891596-71f94558-a791-4359-b890-69ad816ecaeb.png)
Looks like it is to me

**Comment by Firecul** [comment]
Also `Yourlover.Store` is a spam website. so your examples don't really make sense to me tbh

**Comment by caam0000** [comment]
It is spam, and that is the "problem". The program isn't finding the things on the list.

**Comment by Firecul** [comment]
But you made a topic saying these were false negatives?

Do you have a direct link to the spam comments, preferably the ones with the websites and I'll make the issue to add the domains?

**Comment by Firecul** [comment]
As the links above should be caught in the main lists now (https://github.com/ThioJoe/YT-Spam-Lists) this issue can probably be closed, if you have more URLs to submit please do that in the other repo.
