### ISSUE TITLE
Filtering: Spanish Spam

### ISSUE THREAD

**Issue by Terryble2** [ThioJoe/YT-Spammer-Purge#841]
### Filter Mode

Auto-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

![Spam](https://user-images.githubusercontent.com/20852955/170895480-ac16723c-da46-42ee-a6c8-dbb9fba94bf6.png)

### Video / Post Link

https://www.youtube.com/watch?v=-oVhr-Hd4MI

**Comment by ThioJoe** [comment]
better caught with the spam lists repo
