### ISSUE TITLE
Has this issue been resolved yet? I also am having the issue of being unable to use variables in my `tokenUrl`

### ISSUE THREAD

**Issue by Lcote71** [ThioJoe/YT-Spammer-Purge#843]
Has this issue been resolved yet? I also am having the issue of being unable to use variables in my `tokenUrl`

__Originally posted by @dchicchon in https://github.com/OAI/OpenAPI-Specification/issues/551#issuecomment-1126425406__

**Comment by Firecul** [comment]
Sorry, I'm going to need context, has this issue (on another repo) been solved? No idea
How does the linked issue (on another repo) relate to this one, is there a bug somewhere that needs to be fixed on ~~our~~ Thio's side?

**Comment by TechStudent11** [comment]
Probably a mistake.

**Comment by KendallDoesCoding** [comment]
Please close this issue @Lcote71
