### ISSUE TITLE
Filtering: (Write a short title here)

### ISSUE THREAD

**Issue by magus1992** [ThioJoe/YT-Spammer-Purge#844]
### Filter Mode

Auto-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

https://www.youtube.com/watch?v=5xpIKud8LOM&lc=UgwvamTeAkVf2WSzSCt4AaABAg

**Comment by Firecul** [comment]
I'm going to assume the comment has been deleted already since that URL doesn't link to any particular one and I don't see anything immediately spammy.
Without any info, there isn't anything we can do sorry.
