### ISSUE TITLE
Filtering: Subbing to everyone that subs not being picked up by filter. Also, verified bot not being picked up either

### ISSUE THREAD

**Issue by ORIOLESFan02** [ThioJoe/YT-Spammer-Purge#846]
### Filter Mode

Auto-Smart Mode

### Select the Problem

Some spammers not detected

### Spammer Example / Sample

![firefox_bT9zkJTN8V](https://user-images.githubusercontent.com/48143202/171292105-30e4fd3e-2c06-4ef5-b1d3-c467591f6d89.png)
![Notepad_qcxrpKuU7g](https://user-images.githubusercontent.com/48143202/171292108-8d78cd3b-1c87-482c-875b-3b21f2c0a8c5.png)

The ones that are highlighted are the bots.

### Video / Post Link

Video: https://www.youtube.com/watch?v=uNP5o8dLja4 | Comment: https://www.youtube.com/watch?v=uNP5o8dLja4&lc=Ugw-ahXpdjdUr3CbmWp4AaABAg.9bh7C7S5vzt9bh7Lb7NCMo

### (Optional) Additional Info / Context

So, this has nothing to do with the report itself, but I accidentally submitted an unfinished report, so I hope you understand.

**Comment by ORIOLESFan02** [comment]
Similar to #845 (still uploaded by me), but that one was a mistake, so I re-uploaded this to make it better. Yes, I could've just edited the first one, but I'd rather do it this way instead.

**Comment by ThioJoe** [comment]
Should be caught next commit
