### ISSUE TITLE
Filtering: Whatsapp with an apostrophe

### ISSUE THREAD

**Issue by daneel6672** [ThioJoe/YT-Spammer-Purge#850]
### Filter Mode

Auto-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

![2022-06-05_09-53](https://user-images.githubusercontent.com/20476435/172043142-4e51c8d3-a401-4c22-b876-b94e39cdbe24.png)
![2022-06-05_09-57](https://user-images.githubusercontent.com/20476435/172043184-e49df5be-06b8-4618-86c6-3b01b0ba6382.png)

### (Optional) Additional Info / Context

The two clues in this comment is Telegram with lots of non-Latin alphabet substitutions and Whatsapp with an apostrophe

"<You can reach Shirley on ͲeIєɠɾαmyt👉Shirleybagshaw, <Orr What'sapp✙12134001320….."

**Comment by Firecul** [comment]
Do you have a link for the comment by chance?

**Comment by daneel6672** [comment]
I deleted it I'm afraid, but if you want to test the filter the offending string is in the comment above (I thought I'd preserve it for just that reason!)

**Comment by Firecul** [comment]
I was going to make an issue to add the spammer name to the lists so they can be caught. I'll do it anyway and just link back to here.

**Comment by ThioJoe** [comment]
Thought it should catch these now but let me know if new ones get through
