### ISSUE TITLE
Filtering: Comment copy bots without obvious spam profile names "click about to see more!"

### ISSUE THREAD

**Issue by Propheticus** [ThioJoe/YT-Spammer-Purge#853]
### Filter Mode

Auto-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

![image](https://user-images.githubusercontent.com/6628064/172649148-1f9cf2cd-07c5-498b-a3f7-68501c35982f.png)
![image](https://user-images.githubusercontent.com/6628064/172648950-cbed32ef-06db-48cf-977c-973e386b48cf.png)

https://www.youtube.com/watch?v=qIUb3bjh42Y&lc=UgyNXzeRX-8ova7eKvp4AaABAg
https://www.youtube.com/watch?v=qIUb3bjh42Y&lc=UgwBKthArRpKj7SkE6F4AaABAg

https://www.youtube.com/watch?v=qIUb3bjh42Y&lc=Ugy5Yip-gB_PX7fEdNR4AaABAg

https://www.youtube.com/watch?v=qIUb3bjh42Y&lc=UgxZowZluxz_ZHClO9R4AaABAg

### Video / Post Link

https://www.youtube.com/watch?v=qIUb3bjh42Y

### (Optional) Additional Info / Context

These all have pretty random profile names, without the obvious emoji's or obfuscated words. Their profile banner is a picture inviting you to check their about pages that contain links to their albums.

Scan log attached:
[Spam_Log_2022-06-08_16-25-49.txt](https://github.com/ThioJoe/YT-Spammer-Purge/files/8862895/Spam_Log_2022-06-08_16-25-49.txt)

**Comment by Firecul** [comment]
Assuming the comments aren't picked up on the normal filters I'm not sure how these could be caught. Basically, the tool would have to dl the profile pictures of every commenter and run it past an OCR program, as far as I know, that wouldn't be practical.

**Comment by Propheticus** [comment]
Of course, they are still copies of other comments so you can find them by looking at duplicates. But then the next challenge is finding the original. (timestamps available to find the first occurrence?)

**Comment by Firecul** [comment]
Oh ok, sorry that wasn't clear to me the first time. 

All of your linked examples are picked up when I scanned that video
![WindowsTerminal_Windows_PowerShell (46)](https://user-images.githubusercontent.com/34950371/173255629-cc93e915-ae93-4bd1-a536-403b29810acf.png)

**Comment by Firecul** [comment]
Are the repost filters turned on in your config file?
![notepad](https://user-images.githubusercontent.com/34950371/173255712-6d2da2ac-d22f-45b5-94fd-6a41dd98e7ab.png)

**Comment by Firecul** [comment]
Actually, that'll be it, on line 199 I added AutoSmart to the check modes, but by default that check is only in sensitive mode.
`stolen_comments_check_modes = AutoSmart, SensitiveSmart`

**Comment by Propheticus** [comment]
I was using the app fully default (no config ini file), apart from my own API credentials of course. 
Ah, so we're now tweaking the autosmart to be a bit more like sensitivesmart.
I'm configuring a copy of the ini now and will use this next time. 
Thanks!

(Allowing configs to change what a default mode does or doesn't include makes it kind of hard to troubleshoot though.
When users report they used the Auto-Smart mode that could then still mean anything... and is hard to reproduce when your config is different.)

**Comment by ThioJoe** [comment]
Unfortunately missed this old thread so not sure if these types of comments are still active, if so feel free to leave a new issue with updated comments.
