### ISSUE TITLE
Bug?: Channel ID and/or name doesn't match

### ISSUE THREAD

**Issue by mews-se** [ThioJoe/YT-Spammer-Purge#854]
For some reason when I try a channel name it reverts to another. Even when locating the actual channel ID it still seems like something goes awry. Is it something I have missed?

For example: Cleetus McFarland: https://www.youtube.com/c/SPOCARVideos or channel ID UCRMxzggINzTySZCadb0Ll6g

Result: 
![image](https://user-images.githubusercontent.com/58894405/173101271-b3ba8438-62d5-4a54-8d01-bc8284fe602f.png)

With channel ID: the name is correct, but the channel is obviously wrong:
![image](https://user-images.githubusercontent.com/58894405/173101480-27cf178d-187e-42ca-a630-5612b4835bde.png)

**Comment by Firecul** [comment]
Yeah that has came up before

> A couple things to add that I've found. The YouTube API offers absolutely zero way to do a direct query to retrieve the channel ID if the /c/ channel URL is given, for some reason. It does however, offer a way to directly get the channel ID if it's a legacy username, so for "youtube.com/whatever", you can query for just "whatever". (Except apparently not always? See example below)
> 
> The problem with that is, sometimes the /c/ name is different from the legacy name. So if I were to add a thing to query the username "mkbhd" for example, it actually returns this channel id: UCmf_VrB73I-eJ3fq0adaOkg, which is not MKBHD's main channel: https://www.youtube.com/channel/UCmf_VrB73I-eJ3fq0adaOkg
> 
> In fact, it's not even the same channel that comes up if you type in youtube.com/mkbhd. (I think at some point, YouTube started using the /c/whatever URL if someone typed in just youtube.com/whatever. So unless they're the same, it might not give the same result) So there's not really any perfect solution.

From https://github.com/ThioJoe/YT-Spammer-Purge/issues/624

and https://github.com/ThioJoe/YT-Spammer-Purge/issues/455 also had similar problems and explanations.

**Comment by ThioJoe** [comment]
This should be improved in the latest beta. Turns out there is a way to filter the API search results to only be channels, whereas before it would search videos and channels, which would often return bad results for small channels.

Now it should be a lot less likely to return false channel results. And if the API doesn't return it at all for some reason, which it still might do for small channels, the result should be empty and at least tell the user that.

Your specific example is fixed now
