### ISSUE TITLE
Filtering: (Write a short title here)

### ISSUE THREAD

**Issue by PirieBoy** [ThioJoe/YT-Spammer-Purge#856]
### Filter Mode

Auto-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### (Optional) If 'Other', Enter Very Short Description

Seeing this a lot vor.monster and Kayantanii.UNO and  Kimmy-jka.Monster

### Spammer Example / Sample

![image](https://user-images.githubusercontent.com/107310868/173190500-0e01242e-5c95-4ce1-95ab-181825136b98.png)

### Video / Post Link

https://www.youtube.com/watch?v=_X0CrfALPak

**Comment by Firecul** [comment]
I'll make the issue on the spam lists when I get back to my pc

**Comment by Firecul** [comment]
As the links above should be caught in the main lists now (https://github.com/ThioJoe/YT-Spam-Lists) this issue can probably be closed, if you have more URLs to submit please do that in the other repo.
