### ISSUE TITLE
Filtering: subs challenge channels

### ISSUE THREAD

**Issue by Neeeap** [ThioJoe/YT-Spammer-Purge#857]
### Filter Mode

Auto-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

![Screenshot (1)](https://user-images.githubusercontent.com/96753996/173226013-de142885-f184-4b18-b982-19e78fb828ba.png)

### Video / Post Link

https://user-images.githubusercontent.com/96753996/173227516-308eb6cb-4c2a-465b-9581-eaaffa73229d.mp4

### (Optional) Additional Info / Context

been seeing these for a while

**Comment by Firecul** [comment]
Odd that it doesn't catch those already 🤔
`https://www.youtube.com/watch?v=82Jqqvk7nWw` < link to the video for anyone that needs it so they don't have to type it out also.

**Comment by Neeeap** [comment]
I even tried to use the sensitive filter mode but it doesn't work as well.
![Screenshot (5)](https://user-images.githubusercontent.com/96753996/173718240-c43a8890-ddb4-424e-8f32-ebdd12236faf.png)
https://www.youtube.com/watch?v=-39rBvkSL4M video link

**Comment by Propheticus** [comment]
It's an optional filter in the config at line 158.  According to the comment that accompanies it, because some don't see this as spam... perhaps the owners of those accounts?

```
155    # In Auto-Smart and Sensitive-Smart modes, sets whether to flag comments by users with usernames such as "100k subs without any videos"
156    # These accounts usually just spam and are typically against YouTube's guidelines, but some apparently don't consider it spam
157    # Default = False  --  Possible: True | False
158  detect_sub_challenge_spam = True
```

**Comment by ThioJoe** [comment]
Old issue but should be caught with next commit
