### ISSUE TITLE
Error 400 - ProcessingFailure

### ISSUE THREAD

**Issue by ThioJoe** [ThioJoe/YT-Spammer-Purge#860]
I've been getting a `processingFailure` error when trying to scan using any method. Not sure if I'm the only one so let me know if anyone else has this issue to. Usually this error is from the server side.

**Update:** It seems YouTube is having a site-wide issue with comments, as I can't even see comments on any video.

**Comment by Firecul** [comment]
For videos, I'm getting that error too. It was working fine about 15 hours ago.
![WindowsTerminal_Windows_PowerShell (47)](https://user-images.githubusercontent.com/34950371/173640413-adf55863-7f10-4ba0-b046-2449eadf2651.png)

Community post scanning still "works" though it can't pick up any comments on the posts
![image](https://user-images.githubusercontent.com/34950371/173640841-a8a91e81-6fe3-43c9-98f7-26626a25b564.png)

**Comment by ThioJoe** [comment]
It seems like the outage might be for comments in general across the whole site. Comments don't seem to be appearing under any videos.

**Comment by Firecul** [comment]
Seems to be back atm
![image](https://user-images.githubusercontent.com/34950371/173678266-24ae0f04-61d5-4d27-b59c-6138f428965b.png)

**Comment by prettybadatcoding** [comment]
Yes, I cleared all my cookies trying to fix the issue, then realized it was a site-wide outage. I'm logged out of most of my accounts and am getting back in to them. :/

**Comment by ThioJoe** [comment]
Yea it appears fixed now
