### ISSUE TITLE
Filtering: 7 out of a total of 8 comments being spam that's impressive

### ISSUE THREAD

**Issue by WORMSS** [ThioJoe/YT-Spammer-Purge#868]
### Filter Mode

Auto-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

![image](https://user-images.githubusercontent.com/1384537/174506409-fde8ee92-98df-4f15-a11c-d0e69d7b44f7.png)

### Video / Post Link

https://www.youtube.com/watch?v=jxSh-RZTCws

### (Optional) Additional Info / Context

I see these within the first hour or so of [Matt Pocock](https://www.youtube.com/channel/UCswG6FSbgZjbWtdf_hMLaow) channel. Not really seen them anywhere else yet.

**Comment by Firecul** [comment]
7 out of a total of 8 comments being spam that's impressive

**Comment by Firecul** [comment]
https://github.com/ThioJoe/YT-Spam-Lists/issues/115
https://github.com/ThioJoe/YT-Spam-Lists/issues/116
would catch some of these, I'll make a request with the rest now

**Comment by WORMSS** [comment]
New Spam lists found only 2 of the 4 left on this video.
https://www.youtube.com/watch?v=6l3Q9DjbQ7A


![image](https://user-images.githubusercontent.com/1384537/174865129-7cd7a8ca-bb4b-41af-b809-3a06a5730e44.png)

![image](https://user-images.githubusercontent.com/1384537/174865146-f641cbad-cfda-42c1-8022-03ec99576c3c.png)

Is this expected?

**Comment by Firecul** [comment]
> Is this expected?

Yes, as those aren't in the domains that have been submitted.

**Comment by WORMSS** [comment]
because Uno and Monster are uppercased vs lowercase?

**Comment by Firecul** [comment]
no, those are top-level domains. The script blocks each domain as it's added, it's not taking a heavy-handed approach by blocking all of those sites that use `.uno` and `.monster`

**Comment by Firecul** [comment]
Short answer, yes.
You can also change a little of the code (I won't say where, but it is mentioned on here somewhere by ThioJoe I think) and it'll allow you to use any of the modes even if it's not on your own channel. That way you can search for those text strings manually. That's a lot easier than adding the detection into the code. 
![image](https://user-images.githubusercontent.com/34950371/174911005-d8d531b2-fd96-4eb3-af05-237ceea41e78.png)

**Comment by WORMSS** [comment]
I was just looking into 
```py
spamListExpressionsList.append(confusable_regex(domain.upper().replace(".", "⚫"), include_character_padding=False).replace("(?:⚫)", "(?:[^a-zA-Z0-9 ]{1,2})"))
```
a little funky, but I get the gist of what this was.
