### ISSUE TITLE
Filtering: weird nsfw link bot not caught

### ISSUE THREAD

**Issue by 200msEthan** [ThioJoe/YT-Spammer-Purge#872]
### Filter Mode

Sensitive-Smart Mode

### Select the Problem

Some spammers not detected

### Spammer Example / Sample

![image](https://user-images.githubusercontent.com/73640357/176820799-4bf4de90-a45e-4b0d-8bbf-2164887ef711.png)

### Video / Post Link

https://www.youtube.com/watch?v=gNQm3qPDtwE

### (Optional) Additional Info / Context

the link connects to some 18+ website

**Comment by KendallDoesCoding** [comment]
I got this comment on my video too a while ago, very annoying.

**Comment by ThioJoe** [comment]
Has been added
