### ISSUE TITLE
Filtering suggestion: more nsfw bots

### ISSUE THREAD

**Issue by FurblandChannel** [ThioJoe/YT-Spammer-Purge#873]
On this video (https://youtu.be/R7ghDhpCLKM) if you sort the comments by newest first and scroll down to comments from 1 month ago, you will see several spam comments from the user “stupidwh*re” (searching won’t work, as the name has special characters). Thanks!

**Comment by Firecul** [comment]
While you are correct, at least they aren't actually spamming websites or scam comments

https://www.youtube.com/watch?v=R7ghDhpCLKM&lc=UgwbO3IY22fb45OWUNx4AaABAg
https://www.youtube.com/watch?v=R7ghDhpCLKM&lc=UgyX4o4nLXDJoJBZ4Sp4AaABAg
(I'm not screenshotting those to put on here)
`‎ ‎ ‎ ‎ ‎ ˢᵗᵘᵖⁱᵈʷʰᵒʳᵉ` Is the name characters

**Comment by FurblandChannel** [comment]
(Issue closed, added to list)
