### ISSUE TITLE
Filtering: “technoblade is dead” bots

### ISSUE THREAD

**Issue by FurblandChannel** [ThioJoe/YT-Spammer-Purge#874]
![Screenshot 2022-07-02 at 6 18 33 PM](https://user-images.githubusercontent.com/78236024/177020768-881bfac2-56c5-4f7d-89e5-1e5895d38815.png)

**Comment by Firecul** [comment]
Too much effort to fill in the form that would allow you to link comments etc?

**Comment by FurblandChannel** [comment]
Wait, there’s a form for that? My apologies!

**Comment by KendallDoesCoding** [comment]
Yes, no worries! There is another repo for that tho.

**Comment by Firecul** [comment]
> Yes, no worries! There is another repo for that tho.

It doesn't really fit into those categories though so I think it'd be best for it to be here, more of a type of spammer not detected.

**Comment by KendallDoesCoding** [comment]
> > Yes, no worries! There is another repo for that tho.
> 
> It doesn't really fit into those categories though so I think it'd be best for it to be here, more of a type of spammer not detected.

Ok cool!

**Comment by Are-You-a-Person** [comment]
Yes this should be blocked, but these comments mainly have words like “I make better content” which should be blocked first which would remove a lot of these technoblade comments looking for views.

**Comment by custrtrs** [comment]
I see too much of this where bots are like, "brOOO My coNtEnTs BetTer ThAn tHiS PeRsOn's CoNtEnt" when they literally upload 1 video or don't even make anything and use other bots for content. Out of all of them, "Instagram User" is the most infamous.

**Comment by ThioJoe** [comment]
Not sure this spam is still active
