### ISSUE TITLE
Filtering: (Write a short title here)

### ISSUE THREAD

**Issue by YaHa12** [ThioJoe/YT-Spammer-Purge#877]
### Filter Mode

Auto-Smart Mode

### Select the Problem

Some spammers not detected

### Spammer Example / Sample

![Screenshot 2022-07-05 222702](https://user-images.githubusercontent.com/107270323/177410568-9eec886b-b1a7-41bd-9f40-8db1877fc60e.png)

### Video / Post Link

https://www.youtube.com/watch?v=8nxxdFGuMF4

**Comment by ThioJoe** [comment]
Has been added
