### ISSUE TITLE
[ModuleNotFoundError]: No module named 'tkinter'

### ISSUE THREAD

**Issue by ShadowStorm0** [ThioJoe/YT-Spammer-Purge#881]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [X] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

I am running Python3 version 3.9.4 and I get ModuleNotFoundError: No module named 'tkinter'.

Python3-tk is already installed.
 (python3-tk is already the newest version (3.10.4-0ubuntu1)

I tried to run the program on 3.10 but I get the same error for Regex.

### Release version

2.16.9 Latest Source

### Steps to reproduce

1) Use Python version 3.9.4
2) Run program 
3) Get "ModuleNotFoundError/' error

### What platform are you seeing this problem on?

Linux (can also be ChromeOS)

### Relevant log output

```shell
python3 YTSpammerPurge.py

Importing Script Modules...
Traceback (most recent call last):
  File "/home/REDACTED/Desktop/YT-Spammer-Purge/YTSpammerPurge.py", line 51, in <module>
    import Scripts.prepare_modes as modes
  File "/home/REDACTED/Desktop/YT-Spammer-Purge/Scripts/prepare_modes.py", line 4, in <module>
    from Scripts.gui import *
  File "/home/REDACTED/Desktop/YT-Spammer-Purge/Scripts/gui.py", line 14, in <module>
    from tkinter import Menu, TclError, Tk, Canvas, Entry, Text, Button, PhotoImage
ModuleNotFoundError: No module named 'tkinter'
```

**Comment by ShadowStorm0** [comment]
Not sure why but it works on Python version 3.9.7

**Comment by ThioJoe** [comment]
Hm not sure, but if it works maybe the other one didn't install tkinter correctly. Since it's fixed i'll close this
