### ISSUE TITLE
Filtering: Enhancement: Ensure comment language matches channel language, or certain specified languages.

### ISSUE THREAD

**Issue by rcmaehl** [ThioJoe/YT-Spammer-Purge#887]
### Filter Mode

Regex Search

### Select the Problem

Other (add details below)

### (Optional) If 'Other', Enter Very Short Description

Ensure comment language matches the channel language

### Spammer Example / Sample

Mishan 🅥
7 days ago
Don't translate😡
ເຈົ້າຖືກສາບແຊ່ງເພາະວ່າມັນຖືກແປຖ້າເຈົ້າບໍ່ທໍາລາຍຄໍາສາບແຊ່ງ, ເຈົ້າຈະຕາຍວິທີດຽວທີ່ຈະທໍາລາຍຄໍາສາບແຊ່ງແມ່ນເພື່ອຈອງຊ່ອງທາງຂອງຂ້ອຍລົງ​ທະ​ບຽນ​ດຽວ​ນີ້

[Direct Link](https://www.youtube.com/watch?v=cmCZ27U_-wg&lc=Ugz1IDZYRDEPEZCCRQZ4AaABAg.9dE0wgbuZvG9dE1pEFjaJT)

### Video / Post Link

https://www.youtube.com/watch?v=cmCZ27U_-wg

### (Optional) Additional Info / Context

I know the discussion of _translate each comment to make sure it's not spam_ has been brought up several times and really isn't feasible for a VAST number of reasons.

**_However_**, it would be feasible to check if a comment is, or is one of, English, Spanish, <insert language(s) of choice>

This will be a less strict, but more advanced, filter than ASCII-Only. This would allow channel creators to ensure the comments match the languages they want for the channel. The most appropriate language for the channel or video can be pulled from the youtube data API under `<object>.defaultLanguage`, `<object>.defaultAudioLanguage` (videos only), and `<object>.Localizations`.

Additionally, half of our work is done for us thanks to [Mimino666/langdetect](https://github.com/Mimino666/langdetect)

**Comment by rcmaehl** [comment]
> How would you be able to tell what the language is without sending it for translation?

https://github.com/Mimino666/langdetect

https://en.wikipedia.org/wiki/Wikipedia:Language_recognition_chart

**Comment by Firecul** [comment]
> > How would you be able to tell what the language is without sending it for translation?
> 
> Code wise: https://github.com/Mimino666/langdetect
> 
> Specifics: https://en.wikipedia.org/wiki/Wikipedia:Language_recognition_chart

Hmm... interesting

**Comment by ThioJoe** [comment]
Probably not going to implement this, especially with YouTube pushing for multi-language audio for videos, it is possible there will be more international comments
