### ISSUE TITLE
Filtering: Missing Spam Comment

### ISSUE THREAD

**Issue by Engstory** [ThioJoe/YT-Spammer-Purge#892]
### Filter Mode

Auto-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

![image](https://user-images.githubusercontent.com/99150304/180631978-b20328c0-a84c-4e92-bfb8-fb27edb67cb7.png)

### Video / Post Link

https://youtu.be/C1bZ5CjRpJI

**Comment by Firecul** [comment]
As the links above should be caught in the main lists now (https://github.com/ThioJoe/YT-Spam-Lists) this issue can probably be closed, if you have more URLs to submit please do that in the other repo.
