### ISSUE TITLE
Filtering: (Write a short title here)

### ISSUE THREAD

**Issue by custrtrs** [ThioJoe/YT-Spammer-Purge#894]
### Filter Mode

Auto-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

![💎 Tutorial Fortnite Skin Changer Pro Swapper FREE 💎 - YouTube - Google Chrome 7_25_2022 12_06_30 AM](https://user-images.githubusercontent.com/107527174/180697012-c98bac5e-8ccd-45d7-b778-1923d56ad1f2.png)

### Video / Post Link

https://youtu.be/Wz5KEVYeUcQ

**Comment by Firecul** [comment]
I'll add this one to the lists tonight

**Comment by raghunandhanvr** [comment]
Youtube basic scanner will block this activity after a while
