### ISSUE TITLE
Missed Sub4Sub Spam Comment

### ISSUE THREAD

**Issue by Lightning11wins** [ThioJoe/YT-Spammer-Purge#895]
### Filter Mode

Auto-Smart Mode

### Select the Problem

Some spammers not detected

### Spammer Example / Sample

This Sub4Sub spam comment was not detected:
![Spam comment](https://user-images.githubusercontent.com/42805582/181641888-0fd5d254-cc1f-4952-b9ff-db50abbd016b.png)

### Video / Post Link

https://www.youtube.com/watch?v=yi5uXFzZaCc&lc=UgwDKv_-_oK4b7-KToF4AaABAg

**Comment by Firecul** [comment]
I have actually seen quite a few videos with comments like that, impossible to tell if it's bots or legit comments though, I've seen both. 
But yes the name is a good one to filter for here.

**Comment by ThioJoe** [comment]
should be caught with next commit
