### ISSUE TITLE
Filtering: Telegram bot slipping through the filters

### ISSUE THREAD

**Issue by Firecul** [ThioJoe/YT-Spammer-Purge#896]
### Filter Mode

Auto-Smart Mode

### Select the Problem

Some spammers not detected

### Spammer Example / Sample

![image](https://user-images.githubusercontent.com/34950371/181653426-05e6478a-cc9a-4176-8619-b4b48f33b507.png)

### Video / Post Link

https://www.youtube.com/watch?v=Ov0O92m-iwk&lc=Ugwa6eQp3XPACWbL2EB4AaABAg.9de6f6IrU8g9dg7frk0UWT

### (Optional) Additional Info / Context

This spammer is caught by the similar comment detection but not by the main filters, probably using characters that aren't in the filter lists yet would be my guess. 

`ᴛᵉˡᵉᵍʳᵃᵐ ᵐᵉOfficialshortcircuit1`

**Comment by raghunandhanvr** [comment]
> 

Are there a lot of Spam messages from this kind of comment?

If yes, need to find which font category this font belongs to and add in the filter

**Comment by raghunandhanvr** [comment]
This looks like he uses text to power some other text.
Like,

2^2

Good Approach. Needs to add a new filtering approach for this kind of spam comments.

**Comment by raghunandhanvr** [comment]
This looks like he uses text to power some other text.
Like,

2^2

Good Approach.

**Comment by ThioJoe** [comment]
I've added those characters to the confusables mapping with https://github.com/ThioJoe/YT-Spammer-Purge/commit/ee4842a63ebe6da974e65ed1454e94e0348d9fa6
