### ISSUE TITLE
Filtering: (Write a short title here)

### ISSUE THREAD

**Issue by Michael-Lemons** [ThioJoe/YT-Spammer-Purge#901]
### Filter Mode

Auto-Smart Mode

### Select the Problem

Some spammers not detected

### Spammer Example / Sample

https://www.youtube.com/watch?v=RC-_fFq1mQA&lc=UgyPUiktHheIVLi36Gh4AaABAg
https://www.youtube.com/watch?v=FxaDVhnNABY&lc=Ugw56nfdZhQ_Ti0AytB4AaABAg
![Spam Kate](https://user-images.githubusercontent.com/102477612/182839777-f0576e6d-2821-4d51-a162-13f317d9b11b.jpg)
![Spam ken Hull](https://user-images.githubusercontent.com/102477612/182839792-725a9a1e-5b07-4a1a-8771-65dbe9558ff2.jpg)

### (Optional) Additional Info / Context

The top level spam comment begins with "The FED has lost it" Then there are multiple replies discussing investing and trading.

**Comment by ThioJoe** [comment]
Would need to be caught by the spam thread filter or one of the spam lists: https://github.com/ThioJoe/YT-Spam-Lists
