### ISSUE TITLE
Missing Import Validation Leading to Crash

### ISSUE THREAD

**Issue by Lightning11wins** [ThioJoe/YT-Spammer-Purge#908]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

I found an input validation bug while scanning someone else's channel:
I selected option 2 (scan a channel) and said to scan 50 videos. It handled that, but then I told it that wasn't right and it asked me for another number. This second request does not have the correct input validation, so entering a string crashes the program.

Obviously, this isn't a major issue, but I still thought I should let you know. Thank you for the amazing program!

### Release version

2.16.9

### Steps to reproduce

1. Select 2 ("Scan recent videos for a channel")
2. Enter a valid channel name.
3. Enter a valid number of videos. (eg. 1)
4. When asked "Is everything correct? (y/n):", enter "n".
5. You are asked for another "Number of Recent Videos:", entering a non-number crashes the program.

### What platform are you seeing this problem on?

Windows (.exe file)

### Relevant log output

```shell
> At any prompt, enter 'X' to return here
> Enter 'Q' now to quit


-------------------------------- Scanning Options --------------------------------
      1. Scan specific videos
      2. Scan recent videos for a channel
      3. Scan recent comments across your Entire Channel
      4. Scan a specific community post (Experimental)
      5. Scan recent community posts for a channel (Experimental)

--------------------------------- Other Options ----------------------------------
      6. Create your own config file(s) to run the program with pre-set settings
      7. Remove comments using a pre-existing list or log file
      8. Recover deleted comments using log file
      9. Check & Download Updates

Choice (1-9): 2

Enter a channel ID or Link to scan recent videos from
   > If scanning your own channel, just hit Enter

Enter Here: https://www.youtube.com/c/AdamEschborn

Chosen Channel: Adam Eschborn

Enter the number most recent videos to scan back-to-back:

Number of Recent Videos: 1



Recent Videos To Be Scanned:
  1. 5 Minute Timer - 80's Style
NOTE: These aren't your videos. Enabling 'Not Your Channel Mode'. You can report spam comments, but not delete them.

Total number of comments to scan: 5

Is everything correct? (y/n): n

Enter the number most recent videos to scan back-to-back:

Number of Recent Videos: Number of Recent Videos:

Error: Entry must be a whole number greater than zero.
Traceback (most recent call last):
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1674, in <module>
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1651, in main
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 650, in primaryInstance
TypeError: '>=' not supported between instances of 'str' and 'int'
------------------------------------------------
Unknown Error - Code: X-5 occurred. This is probably my fault,
please a bug report on the GitHub issues page, and include the above error info.
Short Link: TJoe.io/bug-report

 Press Enter to Exit...
```

### Screenshots

![Crash](https://user-images.githubusercontent.com/42805582/184729741-6f3f40ae-0564-41eb-bcb3-46c59f87fde8.png)

**Comment by ThioJoe** [comment]
Should be fixed in the next release
