### ISSUE TITLE
Filtering: False Negative in Sensitive-Smart & Auto-Smart Mode!!

### ISSUE THREAD

**Issue by Lightning11wins** [ThioJoe/YT-Spammer-Purge#909]
### Filter Mode

Sensitive-Smart Mode

### Select the Problem

Some spammers not detected

### Spammer Example / Sample

This comment was undetected by the Auto-Smart Mode and the Sensitive-Smart Mode scans:

![Avoided detection](https://user-images.githubusercontent.com/42805582/185245403-fca46d48-132e-404a-abe0-5ab2664642eb.png)

I also copied their comment and pasted the raw text here:

[⛔️TAP MY PROFILE TO MEET ME AND MORE⛔️](https://www.youtube.com/channel/UCmT-rxzUqiBK1GDH6OUSQIA)
⛔️TAP MY PROFILE TO MEET ME AND MORE⛔️
[1 hour ago](https://www.youtube.com/watch?v=gD5YMKtKGxA&lc=UgyUhnwq9vEejZu3bKp4AaABAg)
[39:23](https://www.youtube.com/watch?v=gD5YMKtKGxA&t=2363s)
I'm honestly impressed by the time and effort you put into these videos, Keep it up!
😄

### Video / Post Link

https://youtu.be/gD5YMKtKGxA

### (Optional) Additional Info / Context

I am using version 2.16.9, which is currently the latest version according to the program.

**Comment by Firecul** [comment]
Huh, I'd have thought that would have got caught.

**Comment by ThioJoe** [comment]
It should catch these now, can't check because comments are gone
