### ISSUE TITLE
[Bug]: (Unable to Select Another Channel from Same Account)

### ISSUE THREAD

**Issue by ghpk** [ThioJoe/YT-Spammer-Purge#912]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Well, I was trying to analyze a channel which is under same account I authenticated, To be very clear I've another email ID which has editor access to 2 channels, one with 33k subs and another with 130k subs and one being the default but blank channel of this account when I run script allow the access from browser,  ... but then ...some how its picking only the 3rd channel from list which has 33k subs and I see no option to make this tool to look and select  another channel.
Another point worth your notice is, the channel its searching also has editor access but the tool works fine. 

### Release version

2.16.9

### Steps to reproduce

1. have an email ID with more than one channel they can have editor access from those channel owners
2.  run the tool, it looks at one channel only, ignoring the other channel available under that authorized email ID on this app.
3. you suggest

### What platform are you seeing this problem on?

Windows (.exe file)

**Comment by TheMorpheus407** [comment]
I can confirm this.

**Comment by ThioJoe** [comment]
When you choose a Google account to log into, if you have multiple channels on it, there should be a second page where the Google login asks you which channel within that Google account to select. On that second page of the login, you'll have to select the individual channel you want to use with the script. Do you mean that when you select the channel (on the second page), not all your channels are showing? Or it doesn't even show you the second page at all?

**Comment by TheMorpheus407** [comment]
If I select the main channel, Google shows me an internal error without further information.

**Comment by ghpk** [comment]
> If I select the main channel, Google shows me an internal error without further information.

Just Tested, No Such Error in my case

**Comment by ghpk** [comment]
@ThioJoe 
` On that second page of the login, you'll have to select the individual channel you want to use with the script.`
No, Google asks you to select the Gmail Account to which you want to give Authorization. So if my browser has 3 accounts logged in, I'll select the account I want to scan, but the selected account has multiple channels with "Editor Access"
which this script doesn't select.

If you want I can make a video on what I am trying to do and send over email.

**Comment by ThioJoe** [comment]
> @ThioJoe ` On that second page of the login, you'll have to select the individual channel you want to use with the script.` No, Google asks you to select the Gmail Account to which you want to give Authorization. So if my browser has 3 accounts logged in, I'll select the account I want to scan, but the selected account has multiple channels with "Editor Access" which this script doesn't select.
> 
> If you want I can make a video on what I am trying to do and send over email.

Ok I think I'm getting what you mean, let me see if I have it right. So as far as the Google login sequence goes, you're logging into your own channel. Your channel is granted permission as an Editor in YouTube studio for another channel which you want to scan. 

And from my understanding the problem is that when you run the script, it tells you "you're logged in as [whatever] channel", which is one of the channels you're authorized to edit, but not the one you want?

**Comment by ghpk** [comment]
Replying from email, hope this works,
Yes, you understood precisely, A Authorized email account can have multiple
channels,
To make your script work for a larger community, it needs to list all the
available channel's under one account.

As people who work for a growing Youtubers, gets, editor access mostly 👍

Your script work can generate employment opportunities for people who know,
how to use and earn a few dollars and I hope they come forward for
supporting your efforts 🙏🙏.

Love from India 🙏🙏

**Comment by TheMorpheus407** [comment]
Then mine is actually a separate request, if I understand you correctly.
It asks me to select an account or brand account. All my channels are listed. If I choose a youtube channel/brand account, it works perfectly. However, when choosing the main channel which is the Account itself, Google says
"A Bug has occured. Please try again."
Going forward I get

"400. That’s an error.

The server cannot process the request because it is malformed. It should not be retried. That’s all we know."

Is that the same as yours @ghpk or should I create a new Issue?

**Comment by ThioJoe** [comment]
> Then mine is actually a separate request, if I understand you correctly. It asks me to select an account or brand account. All my channels are listed. If I choose a youtube channel/brand account, it works perfectly. However, when choosing the main channel which is the Account itself, Google says "A Bug has occured. Please try again." Going forward I get
> 
> "400. That’s an error.
> 
> The server cannot process the request because it is malformed. It should not be retried. That’s all we know."
> 
> Is that the same as yours @ghpk or should I create a new Issue?

That sounds like an issue on Google's side. You might try clearing all your cookies

**Comment by TheMorpheus407** [comment]
Seemed to have been an issue form Google, you're correct. Fixed from my side. Thanks for your help
