### ISSUE TITLE
Filtering: 2 missing spam comments

### ISSUE THREAD

**Issue by Engstory** [ThioJoe/YT-Spammer-Purge#918]
### Filter Mode

Auto-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

![image](https://user-images.githubusercontent.com/99150304/188338071-6b9ef88f-fb7d-4b2b-b9b6-100f9c706d25.png)
![image](https://user-images.githubusercontent.com/99150304/188338079-53653b13-c277-4c5e-a0d6-3c9122cbfaec.png)

### Video / Post Link

https://youtu.be/y47f4VOkJ1k

### (Optional) Additional Info / Context

These are new types of spam comments I have never seen before. Below are the links to the two spam channels:
https://www.youtube.com/channel/UCJ4GhC-GJrpABaBtHasri3Q
https://www.youtube.com/channel/UCp4VIdwYLu3Ei9yVGPb5xCw

**Comment by Firecul** [comment]
```
warmthhh.Online
gedangsiemm.ONLINE
```
Thank you, I'll add these to the filter lists tomorrow

**Comment by Engstory** [comment]
I would like to add another one to the list if that's possible: 
![image](https://user-images.githubusercontent.com/99150304/188384332-634d7b18-4630-405b-9fd9-db4be045ee90.png)
These spammers are getting crazy with the links 😂

**Comment by Engstory** [comment]
I don't want to open another ticket since they are the same type of spammers, but here are TWO more spam comments with similar structure but different links:
![image](https://user-images.githubusercontent.com/99150304/188407459-822be365-972e-4d9f-b6a8-753cc83ada5a.png)
![image](https://user-images.githubusercontent.com/99150304/188407496-1d6af507-1b9f-47fb-b7d3-3766f1a9611d.png)

Here is the YouTube video link: https://youtu.be/KHNTi_zb5yc

**Comment by Firecul** [comment]
All added. 
For any further URLs please submit them to the https://github.com/ThioJoe/YT-Spam-Lists repo as I can deal with them directly there. When you are ready this issue can be closed.
