### ISSUE TITLE
[Bug]: Unknown Error - Code: X-5

### ISSUE THREAD

**Issue by Rohith0009** [ThioJoe/YT-Spammer-Purge#924]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

I Was trying to scan my channel comments using The Second Scan option "Scan recent videos for a channel". My Channel Has 3 Videos and 1 Live Stream Once I Selected The Channel. I Entered Videos To Scan As 5 even though total videos+live streams is 4. Then a Error "Unknown Error - Code: X-5 occurred." appeared.

### Release version

2.17.0-Beta2

### Steps to reproduce

1. Scan Your Own Channel using option 2
2. Enter More amount Of Recent Videos To Scan than Your Channel Has
3. You Can see this error

### What platform are you seeing this problem on?

Windows (.exe file)

### Relevant log output

```shell
Traceback (most recent call last):
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1705, in <module>
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 1682, in main
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YTSpammerPurge.py", line 705, in primaryInstance
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
------------------------------------------------
Unknown Error - Code: X-5 occurred. This is probably my fault,
please a bug report on the GitHub issues page, and include the above error info.
Short Link: TJoe.io/bug-report
```

### Screenshots

![Screenshot 2022-09-24 210620](https://user-images.githubusercontent.com/87482502/192106941-27ad6bc5-b77c-437b-900e-2c21f3c19025.png)

**Comment by Firecul** [comment]
I'm not getting the error with the latest version of the 2.17-beta, I am using the .py version though. 

![WindowsTerminal_Windows_PowerShell (65)](https://user-images.githubusercontent.com/34950371/192119519-b8740771-3707-4d3c-be26-3880576bba67.png)

Could you possibly try the [v2.16.10 exe](https://github.com/ThioJoe/YT-Spammer-Purge/releases/tag/v2.16.10) and see if you still get the error? There are a few commits in that one that aren't in the beta2 exe you are using atm.

**Comment by Rohith0009** [comment]
Ok i will Try v2.16.10

**Comment by Rohith0009** [comment]
The Stable Release Is Working Completely Fine. Still The Beta Is Not Working Even tough I gave the same modes and channels

**Comment by Firecul** [comment]
As I said there are some commits there that weren't in the beta 2 release. Beta 3 if it comes would have those fixes in it. 

![image](https://user-images.githubusercontent.com/34950371/192165875-0aa5725a-b1b0-482d-b726-4db35c3f6ace.png)

I'm sure ThioJoe will still want to see it but at least we know that it's already fixed with these.

**Comment by ThioJoe** [comment]
Hm I'll have to check to see what could be causing it to happen in the beta branch but not the main one

**Comment by ThioJoe** [comment]
Ok I'm not fully sure what caused the video validation check to come back as invalid, but now it should treat that as if the video had no comments and skip it also. It'll be in whenever I release beta3
