### ISSUE TITLE
[Bug]: Cant Create a new config file

### ISSUE THREAD

**Issue by Rohith0009** [ThioJoe/YT-Spammer-Purge#930]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

First I created a config file then I created another config file with option 1 ( Reset main config (SpamPurgeConfig.ini) to fresh default config) Then I got an error. This happens on 2.17 Beta 3 .Py file and the latest release

### Release version

2.17.0-Beta-3 and 2.16.10

### Steps to reproduce

1. Create a config file
2. again create a config file with option 1
3. The issue will appear

### What platform are you seeing this problem on?

Windows (.exe file)

### Relevant log output

```shell
Traceback (most recent call last):
  File "Scripts\files.py", line 909, in create_config_file
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'SpamPurgeConfig.ini'
Error Code F-1: Problem deleting existing existing file! Check if it's gone. The info above may help if it's a bug.
If this keeps happening, you may want to report the issue here: https://github.com/ThioJoe/YT-Spammer-Purge/issues
Press enter to Exit...
```

### Screenshots

![Screenshot 2022-09-26 164103](https://user-images.githubusercontent.com/87482502/192263846-f8d2716e-4553-4d24-bb18-b6dd8e196f95.png)

**Comment by ThioJoe** [comment]
I'm thinking something went wrong when it was initially creating the first config. Because the main error is that it didn't find the 'info' section. Has this error ever happened again since this occurrence?

**Comment by Rohith0009** [comment]
It used to happened but then i reinstalled the stable release and since the it was fixed
