### ISSUE TITLE
Porno Spam Bots with Innocuous Names

### ISSUE THREAD

**Issue by blahguy88** [ThioJoe/YT-Spammer-Purge#933]
### Filter Mode

Auto-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### (Optional) If 'Other', Enter Very Short Description

Some of the porno spam bots going around that steal other people's comments have innocuous names but still lead to malware/phishing sites and host pornographic content to lure people there.

### Spammer Example / Sample

https://www.youtube.com/watch?v=rAwgxqk7qU4&lc=UgzRG2kNyrugTuq_ROB4AaABAg
https://www.youtube.com/watch?v=rAwgxqk7qU4&lc=UgzMeLW15QMMHRPnDbl4AaABAg
https://www.youtube.com/watch?v=gHzuabZUd6c&lc=UgwBppbSC18TP3TzkeB4AaABAg

### (Optional) Additional Info / Context

Here are the links to these specific porno channels and the channels they're associated with:

- https://www.youtube.com/channel/UC1gxLAxWeJBpNXMWXT-ZWEA
- https://www.youtube.com/channel/UCl81u7kixg-ixQvGAHxMzdQ
- https://www.youtube.com/channel/UCmEMGUvM5V8zIGOCrxEP2qQ
- https://www.youtube.com/channel/UCsS2V_pbGxzZbnHm451xV3A
- https://www.youtube.com/channel/UCJLAWDfkR_dIoxQ1tQBJ2lA
- https://www.youtube.com/channel/UC6QYJ5Y4FGD-q6L441VxErw

**Comment by Firecul** [comment]
Most of those comments can be caught by changing your config file 
https://github.com/ThioJoe/YT-Spammer-Purge/blob/main/assets/default_config.ini#L200
```diff
	# Default = SensitiveSmart  --  Possible Values:  None | ID | Username | Text | NameAndText | AutoASCII | AutoSmart | SensitiveSmart

-stolen_comments_check_modes = SensitiveSmart
+stolen_comments_check_modes = ID, Username, Text, NameAndText, AutoASCII, AutoSmart, SensitiveSmart
```
I've changed mine to the above to run the stolen comments check in all modes.

**Comment by Firecul** [comment]
For any that aren't stolen comments and don't have anything in their names or comments for the filters to catch it's extremely difficult to programmatically figure out which commenters are spammers or not. 
So if someone is using one of those accounts to post a regular comment I don't know how we could catch them.
