### ISSUE TITLE
[Bug]: Filter fails to find a name in the SpamThreadsList.txt file

### ISSUE THREAD

**Issue by daneel6672** [ThioJoe/YT-Spammer-Purge#934]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

The config file SpamPurge_Resources/Spam_Lists/SpamThreadsList.txt has the name "karen marie emma" but neither the Auto-Smart Mode nor the Sensitive-Smart Mode flags the thread. We've left it undeleted as a test case.

https://www.youtube.com/watch?v=3-lCBTU7f84&lc=UgxAzimHQLx3imIKNI54AaABAg

### Release version

v2.17.0-Beta2

### Steps to reproduce

1. Run the filter on the video https://youtu.be/3-lCBTU7f84
 

### What platform are you seeing this problem on?

Linux (can also be ChromeOS)

**Comment by Firecul** [comment]
That is strange, the main build doesn't catch it either.
I have to search for "karen" to pick it up.
![image](https://user-images.githubusercontent.com/34950371/192884134-3c395fb3-6cd9-4fdc-99e0-983252440370.png)

**Comment by daneel6672** [comment]
Also missing Christi Lily even though she's in the SpamThreadsList.txt file comment is here

[(https://www.youtube.com/watch?v=ARFVKC5KqLQ&lc=Ugy9c31kmPuTdofTX5d4AaABAg&ab_channel=PensionCraft)](https://www.youtube.com/watch?v=ARFVKC5KqLQ&lc=Ugy9c31kmPuTdofTX5d4AaABAg&ab_channel=PensionCraft)

The video is here if you want to test the filter on just this video:

https://youtu.be/ARFVKC5KqLQ

**Comment by daneel6672** [comment]
Also doesn't pick up "wendy helene bennett"

So this comment https://www.youtube.com/watch?v=XyltRZPqOH0&lc=UgztQ16zU2HpikzNgs14AaABAg.9gwtulkD7Ek9gwvBTYBIE2 isn't picked up

If you want to just scan one video this is the video URL with the missed comment

https://youtu.be/XyltRZPqOH0

**Comment by Firecul** [comment]
I can't get it to detect anything in the lists atm 
![image](https://user-images.githubusercontent.com/34950371/194929251-854f55ed-a045-45e9-b4b3-dab3f38e8f38.png)

**Comment by ThioJoe** [comment]
Figured it out. Turns out no replies were even being checked against the list, oops.

Should be fixed in the new Beta 3 release

**Comment by Firecul** [comment]
It's picking up more but not the comments I left myself. Is that because it's using a token from the same account?
![image](https://user-images.githubusercontent.com/34950371/194974290-80eaadc7-c93f-4e6f-b3ee-d0fd154f7117.png)
