### ISSUE TITLE
[Bug]: heldForReview flag in config does not work with delete_without_reviewing in moderator mode

### ISSUE THREAD

**Issue by Practicalbutterfly5** [ThioJoe/YT-Spammer-Purge#935]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

Edit: I have ironed out the cause of this issue. It's in the following [code](https://github.com/ThioJoe/YT-Spammer-Purge/blob/6c5f2b9adfd7d06a18d403fedac0fea7430bf1e3/YTSpammerPurge.py#L1341-L1345). Here the script checks if userisnotowner=true and sets deletion mode to report without checking if moderator mode is true.

I am trying to set up a fully automated hold for review system for another channel. I am the moderator on that channel.
But using `delete_without_reviewing = True` with `removal_type = heldForReview` does not work for me in moderator mode and instead of holding comments for review it **reports** them

```

+use_this_config = True
+your_channel_id = removed
+skip_confirm_video = True
+moderator_mode = True
+auto_close = True
+scan_mode = RecentVideos
+channel_to_scan = removed
+recent_videos_amount = 3
+filter_mode = AutoSmart
+detect_link_spam = False
+delete_without_reviewing = True
+remove_all_author_comments = False
+removal_type = heldForReview
+whitelist_excluded = False
+enable_logging = True
```

### Release version

YT-Spammer-Purge-2.17.0-Beta2

### Steps to reproduce

1. Use the config options mentioned earlier.
2. 
3. 

### What platform are you seeing this problem on?

Linux (can also be ChromeOS)

### Relevant log output

```shell
.
.
.

============================ Match Samples: One comment per matched-comment author ============================
 1.  [x53]  telegram me @geek...: Congratulations among my lucky winners ðŸŽðŸŽ..                                       




==================== (See log file for channel IDs of matched authors above) ====================

 NOTE:  Check that all comments listed above are indeed spam.
 > If you see missed spam or false positives, you can submit a filter suggestion here: TJoe.io/filter-feedback

Updating log file, please wait...
                                          
 Finishing Log File...
                               


Reporting Comments... - Progress: [0 / 53] (In Groups of 50)
Reporting Comments... - Progress: [50 / 53] (In Groups of 50)
Reporting Comments... - Progress: [53 / 53] (In Groups of 50)
Comments Reported! If no error messages were displayed, then everything was successful.

Program Complete.
Auto-close enabled in config. Exiting in 5 seconds...
```

**Comment by ThioJoe** [comment]
Got a chance to look at this and I'm not sure if I had put that there on purpose or not. But even if it was, it should still have some kind of message or warning. I'll have to review that to make sure if automated that it can only be run in certain modes. Unfortunately it might take a bit because that's the part of the program with some of the most complicated logic.

**Comment by LaloCo** [comment]
Yeah, I need this too. Forking to try @Practicalbutterfly5's cause of the issue.
