### ISSUE TITLE
Filtering: AMZT3S spam in comments

### ISSUE THREAD

**Issue by loic2665** [ThioJoe/YT-Spammer-Purge#938]
### Filter Mode

Sensitive-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

The word used is : AMZT3S

In this screenshot I used the "comment string" feature to detect them. But using the Sensitive Mode solves nothing. As a moderator we should be able to use it by default,  I could modify the program to do it, but everybody cannot do that.

https://www.youtube.com/watch?v=F5kNfTVm7KM&lc=Ugy28EUHzG75xj6nUmJ4AaABAg
https://www.youtube.com/watch?v=F5kNfTVm7KM&lc=Ugyv07dQyakE2obQR8p4AaABAg
https://www.youtube.com/watch?v=F5kNfTVm7KM&lc=Ugw0ox1FYsiTnKEcqZ94AaABAg
...

![image](https://user-images.githubusercontent.com/22454094/193265795-feee82f4-a487-435f-9c9e-b81371b6fb89.png)

### Video / Post Link

https://www.youtube.com/watch?v=F5kNfTVm7KM

### (Optional) Additional Info / Context

As a moderator I should be able to delete them, confidence to this program greatly improved and we all know that if something bad happends, this is the fault of the Administrator who granted these right, I cannot ask for Administrator privileges for obvious reasons but we shoud be able to use this kind of function.

**Comment by loic2665** [comment]
Update : I had to delete the comments fast. I have deleted them by hand. Still there is an issue.

**Comment by ThioJoe** [comment]
Ok I've added it to the spam list repo here so they should get caught now: https://github.com/ThioJoe/YT-Spam-Lists/commit/3c6b9519dfe9b0ffcf9f6f578db7afa149a658e3

**Comment by loic2665** [comment]
Hi @ThioJoe do I open a new issue for the word "AMC20TX" ? 

It seems that words with 7 characters in uppercase is used and a lot of variants exists. 

(I'm not on my computer but still in the same YouTube channel for this issue.)

I have a Cron job that run every 3 hours and of course this word is new so the bot cannot remove it. 

![Screenshot_20221009-151204_YouTube.jpg](https://user-images.githubusercontent.com/22454094/194758770-f525f4fd-3973-43c0-ac92-efe35c733b71.jpg)

**Comment by ThioJoe** [comment]
> Hi @ThioJoe do I open a new issue for the word "AMC20TX" ?

I've added it to the spam list so it should catch that now. In the future you can submit an issue in this repo for that kind of thing: https://github.com/ThioJoe/YT-Spam-Lists
