### ISSUE TITLE
Filtering: (Write a short title here)

### ISSUE THREAD

**Issue by jon-joy-1999** [ThioJoe/YT-Spammer-Purge#940]
### Filter Mode

Auto-Smart Mode

### Select the Problem

Some spammers not detected

### Spammer Example / Sample

https://www.youtube.com/watch?v=GaggPckMn0A&lc=UgyJUJLnWYKOHebqqjJ4AaABAg
https://www.youtube.com/watch?v=GaggPckMn0A&lc=Ugy7iARy5ZjcL15PH9l4AaABAg

### Video / Post Link

https://www.youtube.com/watch?v=GaggPckMn0A

**Comment by Firecul** [comment]
Added to lists, if you have any more spam URLs please submit them here https://github.com/ThioJoe/YT-Spam-Lists
