### ISSUE TITLE
Filtering: AMC466X and AMC20TX

### ISSUE THREAD

**Issue by loic2665** [ThioJoe/YT-Spammer-Purge#944]
### Filter Mode

Sensitive-Smart Mode

### Select the Problem

Some spammers not detected

### Spammer Example / Sample

https://www.youtube.com/watch?v=kptnV8SYUDI&lc=UgwP0lQRmhE0RThKlLF4AaABAg
https://www.youtube.com/watch?v=kptnV8SYUDI&lc=Ugw-iK5afH-IzUkbsOZ4AaABAg

![image](https://user-images.githubusercontent.com/22454094/194824695-ff70577f-d8d6-43a1-878f-99425a68d3bd.png)

The word **AMC466X** AND  **AMC20TX** is not detected 

### Video / Post Link

https://www.youtube.com/watch?v=kptnV8SYUDI

**Comment by ThioJoe** [comment]
Old thread so going to assume this spam isn't active anymore
