### ISSUE TITLE
[Bug]: Still not finding a name in the SpamThreadsList.txt file

### ISSUE THREAD

**Issue by daneel6672** [ThioJoe/YT-Spammer-Purge#952]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [X] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

I ran the filter and it didn't find "tracie lee paige" in this comment

https://www.youtube.com/watch?v=Idqx5ERlZcE&lc=UgycPp6pYxxQvl_dDVJ4AaABAg.9hLphJRRAa09hLqZ8K7I9W

If you want to scan a single video's comments to find the comment and reproduce the bug here's the video

https://youtu.be/Idqx5ERlZcE

Thanks,

Ramin.

### Release version

Beta 3

### Steps to reproduce

1. Scan this video's comments https://youtu.be/Idqx5ERlZcE
2. It doesn't find tracie lee paige in this comment https://www.youtube.com/watch?v=Idqx5ERlZcE&lc=UgycPp6pYxxQvl_dDVJ4AaABAg.9hLphJRRAa09hLqZ8K7I9W

### What platform are you seeing this problem on?

Linux (can also be ChromeOS)

### Screenshots

![2022-10-20_11-32](https://user-images.githubusercontent.com/20476435/196925770-7cfc7afe-bf4b-4e98-9a19-55fcc70da17f.png)

**Comment by daneel6672** [comment]
This name is also being missed: "wendy helene bennett" on this comment https://www.youtube.com/watch?v=PEfy-mRFYrM&lc=UgxmPWIGSbO7nGw8AT54AaABAg.9hZGlhRrT2v9hZHNXXmR2U

**Comment by ThioJoe** [comment]
Ok this should be fixed with the latest commit, and will be in the next release Beta 4 which I'll release today

**Comment by daneel6672** [comment]
Nice! Thanks for that. I can't tell you the joy it gave me to run the filter on 5000 comments this morning and weed out the 24 matches that previously eluded me.
