### ISSUE TITLE
A Porno Spam Bot Eludes Detection

### ISSUE THREAD

**Issue by blahguy88** [ThioJoe/YT-Spammer-Purge#955]
### Filter Mode

Sensitive-Smart Mode

### Select the Problem

Some spammers not detected

### Spammer Example / Sample

- https://www.youtube.com/watch?v=kqJuzLbIt4g&lc=UgxaVWTWxmjcYEjx_pF4AaABAg.9hQ9fTqLKtU9hQCeoyr2Y_
- https://www.youtube.com/watch?v=kqJuzLbIt4g&lc=UgxxtiOQNz48d6KF6D94AaABAg.9hQAGbsNYtX9hQCgO9gchO
- https://www.youtube.com/watch?v=kqJuzLbIt4g&lc=UgyVqZ5f8u27sw2-KUJ4AaABAg.9hQ9gGsphca9hQCdw374X9
- https://www.youtube.com/watch?v=kqJuzLbIt4g&lc=Ugxy9ATVvbPaJrcm6KZ4AaABAg.9hQAKxJzehc9hQCfVQXjxL

### Video / Post Link

https://www.youtube.com/watch?v=kqJuzLbIt4g

**Comment by Firecul** [comment]
`🍓 𝐌𝐘 𝐇𝐎𝐓 𝐕𝐈𝐃𝐄𝐎 - SĘÉ NÓW !` <- Username of bot
