### ISSUE TITLE
More "sub 4 sub" bots

### ISSUE THREAD

**Issue by blahguy88** [ThioJoe/YT-Spammer-Purge#957]
### Filter Mode

Auto-Smart Mode

### Select the Problem

Some spammers not detected

### Spammer Example / Sample

https://www.youtube.com/watch?v=S_CUEOBZ0P4
- https://www.youtube.com/watch?v=S_CUEOBZ0P4&lc=Ugyl2hMzSu6hSHKeq6d4AaABAg.9hSvAuq3V9n9hT47uHi70p
- https://www.youtube.com/watch?v=S_CUEOBZ0P4&lc=UgxI_arpafcqIUXv5794AaABAg.9hSn7SKR3oA9hSw4ZYK67e
- https://www.youtube.com/watch?v=S_CUEOBZ0P4&lc=UgxymKsXioFJnQraOSF4AaABAg.9hT5PhZPm_d9hTH03FlKk2

https://www.youtube.com/watch?v=kqJuzLbIt4g
- https://www.youtube.com/watch?v=kqJuzLbIt4g&lc=UgytxXaCAP3ECcfV1ox4AaABAg.9hQ9Ngf_UI89hQ9WUpENvs
- https://www.youtube.com/watch?v=kqJuzLbIt4g&lc=UgytxXaCAP3ECcfV1ox4AaABAg.9hQ9Ngf_UI89hQAIJJKO8T
- https://www.youtube.com/watch?v=kqJuzLbIt4g&lc=UgytxXaCAP3ECcfV1ox4AaABAg.9hQ9Ngf_UI89hQBJ74m7Fo
- https://www.youtube.com/watch?v=kqJuzLbIt4g&lc=UgxxtiOQNz48d6KF6D94AaABAg.9hQAGbsNYtX9hQDkxuntO0
- https://www.youtube.com/watch?v=kqJuzLbIt4g&lc=UgxaVWTWxmjcYEjx_pF4AaABAg.9hQ9fTqLKtU9hQAK_THjLY
- https://www.youtube.com/watch?v=kqJuzLbIt4g&lc=UgxaVWTWxmjcYEjx_pF4AaABAg.9hQ9fTqLKtU9hQDkKuFX5H
- https://www.youtube.com/watch?v=kqJuzLbIt4g&lc=UgyVqZ5f8u27sw2-KUJ4AaABAg.9hQ9gGsphca9hQAK2JvWmn
- https://www.youtube.com/watch?v=kqJuzLbIt4g&lc=UgyVqZ5f8u27sw2-KUJ4AaABAg.9hQ9gGsphca9hQAk1UIaQh

### (Optional) Additional Info / Context

Sensitive Smart Mode doesn't catch these bots either.

**Comment by ThioJoe** [comment]
Probably best caught with dupe filter
