### ISSUE TITLE
Filtering: Fuzzy Comments catching too many people on standard greetings such as Happy Birthday.

### ISSUE THREAD

**Issue by Sarah1390** [ThioJoe/YT-Spammer-Purge#959]
### Filter Mode

Auto-Smart Mode

### Select the Problem

Other (add details below)

### (Optional) If 'Other', Enter Very Short Description

excluding certain greetings such as Happy Birthday, Merry Christmas etc. for fuzzy comment detection only

### Spammer Example / Sample

![Screenshot 2022-10-26 145218](https://user-images.githubusercontent.com/97075311/198113539-c2d5f6cb-1d48-49ea-b8a5-51d03d34c5f9.png)

![](https://user-images.githubusercontent.com/34950371/198161991-7ba83ef1-5aed-409b-9e00-20831e6c4220.png)

![](https://user-images.githubusercontent.com/34950371/198161998-604c1815-9788-49c1-b76b-138e81b6848e.png)

### Video / Post Link

https://www.youtube.com/watch?v=iXR1b8kPu-Q

### (Optional) Additional Info / Context

I find that the Fuzzy comment detection on this specific video is going to be an issue for fully automated setups on reporting and banning. I know the workaround is to temporarily turn off fuzzy comments in the config for scanning of this particular video and I'm having to exclude about 200+ comments manually because the fuzzy comment detection really helps but how many ways can you uniquely say something like Happy Birthday on a video that is talking about a Birthday. I do not find wishing someone a Happy Birthday as stealing a comment because you can say it so many ways uniquely. Now I would pull a commenter if they kept spamming the same post but one from each commenter should be excluded by choice in config file if possible.

**Comment by Sarah1390** [comment]
I'll get a screenshot of the program tomorrow. I'm already exceeded my quota for today and I didn't think of getting a shot today

**Comment by Firecul** [comment]
> I'll get a screenshot of the program tomorrow. I'm already exceeded my quota for today and I didn't think of getting a shot today

![WindowsTerminal_Windows_PowerShell (76)](https://user-images.githubusercontent.com/34950371/198161991-7ba83ef1-5aed-409b-9e00-20831e6c4220.png)
![WindowsTerminal_Windows_PowerShell (77)](https://user-images.githubusercontent.com/34950371/198161998-604c1815-9788-49c1-b76b-138e81b6848e.png)

**Comment by Sarah1390** [comment]
Thank You.

**Comment by ThioJoe** [comment]
This is one that probably can't be avoided. In a fully automated setup it would be best to not use the stolen comment mode at all. In fact by default, the stolen comment checker is only enabled in Sensitive Smart mode, not Auto Smart mode. So I'll just mark this as working as intended.
