### ISSUE TITLE
More subscriber beggar bots

### ISSUE THREAD

**Issue by blahguy88** [ThioJoe/YT-Spammer-Purge#964]
### Filter Mode

Sensitive-Smart Mode

### Select the Problem

Some spammers not detected

### Spammer Example / Sample

- https://www.youtube.com/watch?v=iogcY_4xGjo&lc=UgyyaZ0AGaWr7u2Wen14AaABAg
- https://www.youtube.com/watch?v=iogcY_4xGjo&lc=UgyjIjhhCcaO2qhrBVx4AaABAg.9hWSrMfHYjL9hX09Deyq5H
- https://www.youtube.com/watch?v=iogcY_4xGjo&lc=UgxlJrA5Le6oowDzB694AaABAg.9hV_Fr44hdL9hWIwdEw1c6
- https://www.youtube.com/watch?v=iogcY_4xGjo&lc=UgxlJrA5Le6oowDzB694AaABAg.9hV_Fr44hdL9hWNK5RmhWQ
- https://www.youtube.com/watch?v=iogcY_4xGjo&lc=Ugx9l7Q0pWuOagLQCkd4AaABAg.9hW4e9dLkoL9hWIVZZhib6
- https://www.youtube.com/watch?v=iogcY_4xGjo&lc=Ugz7o-CWSyxiOui7_0h4AaABAg
- https://www.youtube.com/watch?v=iogcY_4xGjo&lc=UgyC8NOXdtCk9ywmM2h4AaABAg

### Video / Post Link

https://www.youtube.com/watch?v=iogcY_4xGjo

**Comment by blahguy88** [comment]
One of the aforementioned bots still isn't getting caught.

- https://www.youtube.com/watch?v=wpuFGImc_8E&lc=UgwTKmLZCnKWkLkufcp4AaABAg.9hvIFHI0Zuv9hxh8jehwB7
- https://www.youtube.com/watch?v=wpuFGImc_8E&lc=UgxISFowvPv3jnNYpJZ4AaABAg.9hyEAvAdgtO9hyF3GIXjQ5
- https://www.youtube.com/watch?v=wpuFGImc_8E&lc=Ugw2bi-sPNL73UPRwKd4AaABAg.9hxbBligeWg9hyEzVf9WOq
- https://www.youtube.com/watch?v=wpuFGImc_8E&lc=UgxF_7cOCO7t6EzfLs54AaABAg.9hxAGpwyJ-b9hxm3I1FPPd
- https://www.youtube.com/watch?v=wpuFGImc_8E&lc=UgyaqxO0lBlz2qKN2i94AaABAg.9hxhGtPnFF69hy2BwOxZAn
- https://www.youtube.com/watch?v=wpuFGImc_8E&lc=UgydVHSseEXjn3OmAgR4AaABAg.9hxcV_Umz8w9hxm6wehbv6
- https://www.youtube.com/watch?v=wpuFGImc_8E&lc=UgwVXmyUtCEaPpc5kzl4AaABAg.9hxhg8U9EOS9hyF66HRHxK
- https://www.youtube.com/watch?v=wpuFGImc_8E&lc=UgwEOx8Pu1Gin06w_Tl4AaABAg.9hxyX9VcGy89hyF0xm4xpV

This is its channel ID: https://www.youtube.com/channel/UC4KNaxI_BPZM0exdYHnrY7Q

...and this is another video where I found it in action: https://www.youtube.com/watch?v=wpuFGImc_8E

**Comment by ThioJoe** [comment]
The guy seems to change it up with every comment so it's probably best to be caught by the duplicate filter
