### ISSUE TITLE
Savetion the Pedophile Spam Bot Host

### ISSUE THREAD

**Issue by blahguy88** [ThioJoe/YT-Spammer-Purge#966]
### Filter Mode

Sensitive-Smart Mode

### Select the Problem

Some spammers not detected

### (Optional) If 'Other', Enter Very Short Description

Some of that pedophile Savetion's spam bots still aren't getting caught.

### Spammer Example / Sample

- https://www.youtube.com/watch?v=LHt9dPVE-EU&lc=Ugy9v50HmwcV6v2KEip4AaABAg.9hzCQD76YyM9hzEmn7qWMG
- https://www.youtube.com/watch?v=LHt9dPVE-EU&lc=UgwsCMxzb5O70BIyU_R4AaABAg.9hzC4dMxw_U9hzCGdcB26v
- https://www.youtube.com/watch?v=LHt9dPVE-EU&lc=UgwdsrSNckaTU_Jl9594AaABAg.9hzBgRqoy5o9hzBvXA9b1c

### Video / Post Link

https://www.youtube.com/watch?v=LHt9dPVE-EU

### (Optional) Additional Info / Context

This video shows proof of Savetion's pedophilia and racism: https://www.youtube.com/watch?v=ptJuF_dHB28

**Comment by Firecul** [comment]
> still aren't getting caught

Hard to catch them if we didn't know about them.

**Comment by blahguy88** [comment]
> Hard to catch them if we didn't know about them.

Disregard this thread. It does catch repeated comments that the bots make.
