### ISSUE TITLE
"Subbing to everyone who subs to me", "go to my homepage for a sub", etc.

### ISSUE THREAD

**Issue by blahguy88** [ThioJoe/YT-Spammer-Purge#967]
### Filter Mode

Sensitive-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### (Optional) If 'Other', Enter Very Short Description

Still more "sub 4 sub" bots elude detection.

### Spammer Example / Sample

https://www.youtube.com/watch?v=TBT0hPcpIEg

- https://www.youtube.com/watch?v=TBT0hPcpIEg&lc=UgysqIVifKHwoWSbn7B4AaABAg.9gbPLWPEvul9gbQMpOhpiu

https://www.youtube.com/watch?v=HR1ig6u9-6A

- https://www.youtube.com/watch?v=HR1ig6u9-6A&lc=UgyiTX1D9-syM8KPvzh4AaABAg

https://www.youtube.com/watch?v=YXXlSG-du7c

- https://www.youtube.com/watch?v=YXXlSG-du7c&lc=UgzxqSrwQQvINUXDlop4AaABAg
- https://www.youtube.com/watch?v=YXXlSG-du7c&lc=UgzxqSrwQQvINUXDlop4AaABAg.9i2k2HdsII59i2kDaUN1U-

**Comment by blahguy88** [comment]
These bots still aren't getting caught. Here are more examples.

- https://www.youtube.com/watch?v=qDeeJukyuXY&lc=UgxrKFZjStRy4qKbbIZ4AaABAg
- https://www.youtube.com/watch?v=qDeeJukyuXY&lc=UgyYlymd8nhtTuxrAJ54AaABAg

**Comment by ThioJoe** [comment]
I was too slow to check this old issue so the comments are already gone by now, so I can't check them
