### ISSUE TITLE
[Bug-Minor]: Inconsistent Number of Line Breaks when Scanning Multiple Videos

### ISSUE THREAD

**Issue by Lightning11wins** [ThioJoe/YT-Spammer-Purge#971]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**
- [ ] There are **existing posts relating to my problem, but the solution given, doesn't work for me.**

### What happened?

When scanning multiple videos on a channel using option 2, there are sometimes inconsistent amounts of line breaks between the video entries. I'm not sure why there is more than one line break in the first place, but the number of line breaks seems to vary a lot for some reason. This is a very minor issue, but I thought I should let you know.

### Release version

2.17.0-Beta4

### Steps to reproduce

1. Open the program.
2. Select option 2.
3. Enter a channel and begin the scan.

### What platform are you seeing this problem on?

Windows (.exe file)

### Screenshots

![Inconsistent Lines](https://user-images.githubusercontent.com/42805582/201566082-e044eaa9-c307-4dda-b989-d2f53739f3c9.png)

**Comment by ThioJoe** [comment]
Yea this is an issue that has always existed. I tried recently to figure out why, but it seems it's pretty closely tied to how the program updates the current progress at the bottom. I couldn't figure out how to fix it so for the foreseeable future it's just gonna be a cosmetic issue unfortunately. So I'm just gonna close this.
