### ISSUE TITLE
"Link to the clip", "Finally it's here", etc.

### ISSUE THREAD

**Issue by blahguy88** [ThioJoe/YT-Spammer-Purge#972]
### Filter Mode

Sensitive-Smart Mode

### Select the Problem

Some spammers not detected

### Spammer Example / Sample

- https://www.youtube.com/watch?v=-C1CrG9RzgY&lc=UgxNs6oNGNwxF18LW_V4AaABAg.9iLJk25vZP-9iLKGWJwxdZ
- https://www.youtube.com/watch?v=-C1CrG9RzgY&lc=UgzT1IrqqGs__5wQ9Ht4AaABAg.9iLKFzZKetr9iLKWZbHxYp
- https://www.youtube.com/watch?v=-C1CrG9RzgY&lc=UgzdxdUjKHb2zUqDgmt4AaABAg.9iLK4tJqdvO9iLKQFv2Vf3
- https://www.youtube.com/watch?v=iYJr9pZxSPM&lc=Ugyq4hXPVUHTqUdrQzl4AaABAg.9iL7jr0esj29iL888yrmWX
- https://www.youtube.com/watch?v=iYJr9pZxSPM&lc=UgwIn_6igZUnTXAUiPl4AaABAg.9iKzfM-PRxc9iL2NzXRQt0
- https://www.youtube.com/watch?v=iYJr9pZxSPM&lc=Ugw5o_wAHvAe6g7Ygah4AaABAg.9iL523mydcf9iL85u-D1Lo

**Comment by A802526** [comment]
![FB_IMG_1668504956089](https://user-images.githubusercontent.com/118306163/202011285-bc0c99a7-4e1e-473c-bc8d-6341f2d52bed.jpg)

**Comment by QuentinMcCarthy** [comment]
To add to this; the filters are showing them as possible false-positives, which is incorrect.

**Comment by ThioJoe** [comment]
I hadn't gotten to this old issue fast enough, so unless they're still using this phrasing I'll just close this for now
