### ISSUE TITLE
Filtering: New Telegram variant for the confusables filter

### ISSUE THREAD

**Issue by Firecul** [ThioJoe/YT-Spammer-Purge#980]
### Filter Mode

Auto-Smart Mode

### Select the Problem

Some spammers not detected

### (Optional) If 'Other', Enter Very Short Description

Another Telegram variant to swat

### Spammer Example / Sample

![WindowsTerminal_Windows_PowerShell (78)](https://user-images.githubusercontent.com/34950371/204174588-c303b79c-b120-47ba-bb1e-4959c82c836b.png)

### Video / Post Link

https://www.youtube.com/watch?v=Hnc5g74xLLM&lc=UgwCR2J5aL7kMRlapsR4AaABAg.9iNmXJpodP09im8ApUnVp0

**Comment by ThioJoe** [comment]
Should be detected with current filters

**Comment by Firecul** [comment]
User has now changed their name so unable to test however their new name *does* get caught.

![chrome_No_Wonder_No-one_Wants_To_Do_This_Work!!__Terminat](https://user-images.githubusercontent.com/34950371/224520905-49d4bc57-165d-4fab-9e9d-56fae3f4515c.png)
![WindowsTerminal_YT-Spammer-Purge (4)](https://user-images.githubusercontent.com/34950371/224520911-0d905716-1c40-484a-b132-a6bd29319364.png)
