### ISSUE TITLE
Filtering: New Telegram spam not detected

### ISSUE THREAD

**Issue by Xilver266** [ThioJoe/YT-Spammer-Purge#981]
### Filter Mode

Auto-Smart Mode

### Select the Problem

Some spammers not detected

### Spammer Example / Sample

![Notepad_7xUso1UzfX](https://user-images.githubusercontent.com/3458743/204407005-aad35e74-3d21-4ec7-845f-726e9b49e75d.png)

![Notepad_i3uqDHRThd](https://user-images.githubusercontent.com/3458743/204407067-32c24e3c-5c5d-42ff-9c8f-73edc3226d6a.png)

### Video / Post Link

https://www.youtube.com/watch?v=S5PofRQAGLc&lc=UgwwHLLK1-gQk38s-R94AaABAg.9izr6OQ1joZ9j--2GeJCWQ
https://www.youtube.com/watch?v=S5PofRQAGLc&lc=UgyCIb7MTczSpOIUm6t4AaABAg.9ikb83wfDsO9j-0opJhWS6

**Comment by ThioJoe** [comment]
These should be detected with the current filters
