### ISSUE TITLE
Add handles (suggestion)

### ISSUE THREAD

**Issue by domonkos11** [ThioJoe/YT-Spammer-Purge#984]
Please allow the use of handles instead of channel links/IDs when scanning videos on a specific channel.

**Comment by Lightning11wins** [comment]
This suggestion is a duplicate of issue #974, where the program rejects URLs with handles unless suggestions aren't able to be duplicates of issues.

**Comment by ThioJoe** [comment]
Dupe of #974 also the latest beta should work with handles now
