### ISSUE TITLE
Filtering: Undetected Spammer

### ISSUE THREAD

**Issue by Carter-M-II** [ThioJoe/YT-Spammer-Purge#986]
### Filter Mode

Auto-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

![funnywarcraft3b](https://user-images.githubusercontent.com/43128546/206906424-299d552a-9597-4c1f-9b07-cbb85fa6239a.PNG)
![funnywarcraft3](https://user-images.githubusercontent.com/43128546/206906425-ca22e1ae-a98f-4eb5-8aef-25d06a6a4a4f.PNG)

### Video / Post Link

https://www.youtube.com/watch?v=qLTJwXMOawY&lc=UgzKLha85tqlkogVD354AaABAg.9jPKD-DuKfp9jV839guO16

### (Optional) Additional Info / Context

FunnyWarcraft3 isn't being monitored by anti-spam filters

**Comment by Firecul** [comment]
I have added this account to the [YT-Spam-Lists](https://github.com/ThioJoe/YT-Spam-Lists/) repo to catch this in the future.

**Comment by ThioJoe** [comment]
Will be fixed with next commit
