### ISSUE TITLE
Filtering: 

### ISSUE THREAD

**Issue by Lightning11wins** [ThioJoe/YT-Spammer-Purge#992]
### Filter Mode: "1 Million comments" Spammer

Auto-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

![image](https://user-images.githubusercontent.com/42805582/207474046-bc16999a-1ccf-4ccd-87fa-2e113c857ff3.png)

### Video / Post Link

https://www.youtube.com/watch?v=s3Zps67zpYg

**Comment by ThioJoe** [comment]
This seems to be an individual person and not really a common type of spammer, so not much point in adding a filter for it. If i'm wrong let me know though
