### ISSUE TITLE
Filtering: the n word

### ISSUE THREAD

**Issue by Freako76** [ThioJoe/YT-Spammer-Purge#996]
### Filter Mode

Auto-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

<img width="194" alt="image" src="https://user-images.githubusercontent.com/95104389/209726922-c3d491a8-272a-4125-832b-32a5e29d4c65.png">
do I need to say anything if you see this image of a person with terrible humor?

### Video / Post Link

https://www.youtube.com/watch?v=thYAuBxWRLY

**Comment by ThioJoe** [comment]
See my comment in #997
