### ISSUE TITLE
Filtering: (N-word spam not detected, Auto-Smart & Sensitive-Smart modes)

### ISSUE THREAD

**Issue by urielceniceros918** [ThioJoe/YT-Spammer-Purge#997]
### Filter Mode

Auto-Smart Mode

### Select the Problem

A type of spammer is not detected at all

### Spammer Example / Sample

![image](https://user-images.githubusercontent.com/104616169/209775123-45fb4c22-342a-4c8f-a220-3fe59f5a4f92.png)

### Video / Post Link

https://www.youtube.com/watch?v=Sj3Ou2JLRDw

**Comment by ThioJoe** [comment]
In this case it would be better to just use a custom string search. The "fours05" user would be caught by the duplicate checker, and the other people saying a bad word once is not really spam.
